### ISSUE TITLE
List of attendees is not scrolling till the end if it exceeds the end of the page ( always the last user is cut)

### ISSUE THREAD

**Issue by tutoroom** [bigbluebutton/bigbluebutton#10022]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Actual behavior**

**Screenshots**

**BBB version (optional):**
BigBlueButton continually evolves. Providing the version/build helps us to pinpoint when an issue was introduced.
Example:
$ sudo bbb-conf --check | grep BigBlueButton
BigBlueButton Server 2.2.2 (1816)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows, Mac]
 - Browser [e.g. Chrome, Safari]

**Smartphone (please complete the following information):**
 - Browser [e.g. stock browser, Safari]

**Additional context**

**Comment by matiasilva** [comment]
Hi, please edit the bug template with the relevant information.

**Comment by cepster** [comment]
I'm seeing this issue as well.  Here's our filled in bug report:

**Describe the bug**
The users droplist gets cut off on the bottom when there is a banner present at the top (either a custom banner defined on meeting create or the meeting timer)

**To Reproduce**
Steps to reproduce the behavior:
1. Start a meeting with a custom banner
2. Add enough attendees to completely fill the white space in the users list
3. Attempt to scroll to the bottom of the user's list

**Expected behavior**
Scroll area of users area will go down to the bottom of the last user on the list

**Actual behavior**
The last user in the list gets cut off halfway

**Screenshots**
![image](https://user-images.githubusercontent.com/3458747/91902374-3d276500-ec67-11ea-95ce-45b52b0c5a98.png)


**BBB version (optional):**
2.2.17

**Desktop (please complete the following information):**

OS: All
Browser: All tested
