### ISSUE TITLE
bigbluebutton screen sharing closes unexpectedly

### ISSUE THREAD

**Issue by UnderFenex** [bigbluebutton/bigbluebutton#10191]
**Describe the bug**
Bigbluebutton screen sharing closes unexpectedly during a presentacion, teacher using chrome

**To Reproduce**
1. Start session
2. Begin sharing screen
3. Unexpectedly screen sharing closes.

**Expected behavior**
Screensharing should not close unexpectedly

**BBB version
bbb-html5                             1:2.2.0-960                                     amd64        The HTML5 components for BigBlueButton

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome 84 and also in Firefox

**Comment by UnderFenex** [comment]
In the browser I see this error: 

Websocket connection to SFU closed unexpectedly screenshare/listen only will drop.

Then it says:

WebSocket is already in CLOSING or CLOSED state.

Can this be due to bad internet? The teacher is connecting using Wifi, can this be due to it's internet/router or is a BBB isue?

**Comment by sreegithck** [comment]
We used to experience the same while connecting from low bandwidth, I think it is mainly due to the low bandwidth, as per BBB design, it is accommodating the connection by closing the high bandwidth-consuming option like Screen sharing.

We used to encounter this problem when teachers use mobile hotspot based internet and when call receives over the mobile / or when some good size video download happens over WhatsApp etc. So I strongly feel it is internet bandwidth related trouble
