### ISSUE TITLE
Remove Mute All functions from breakout room moderator menu

### ISSUE THREAD

**Issue by ffdixon** [bigbluebutton/bigbluebutton#10210]
**Describe the bug**
Students can mute each other in breakout rooms

**To Reproduce**
1. Create a breakout room
2. Click on the gear icon
3. You can mute all other users

**Expected behavior**
Students in breakout rooms shouldn't be able to mute each other.  For K12, this is especially problematic.

**Screenshots**
![image](https://user-images.githubusercontent.com/290351/89573488-ae0a6700-d7f8-11ea-8481-d0a34bbcea72.png)

**Comment by harika1258** [comment]
Hi @ffdixon
I'm using BBB-2.2.36
When I create a Break out room as a moderator don't hear in the groups students voice. If I want to hear the voice in the special group  I have to leave audio and join to it. For next group, again leave audio and join.
Is There any good solution?

**Comment by harika1258** [comment]
Hi @ffdixon 
My microphone's sometimes muted when I join a breakout room As a moderator. Why is this/How to fix?
Actually, It happens when I'm jumping between breakout rooms.  Once there, I'm able to unmute the mic; it's more the inconvenience that comes from starting to speak to students and not realizing I'm muted until one of them alerts me to it.

Thanks.

**Comment by ffdixon** [comment]
Can you post your questions to our bigbluebutton-dev mailing list (not to closed issues).  Please provide information on the version of BigBlueButton you are using -- and let us know if you can reproduce the issue on https://demo.bigbluebutton.org/.
