### ISSUE TITLE
bbb-conf should not touch/damage any config files unless --set* is given

### ISSUE THREAD

**Issue by jelmd** [bigbluebutton/bigbluebutton#10239]
Running `bbb-conf --restart` modifies/damages several configuration files for no reason.

That's an absolute no-go. Actually __NONE__ of the *configuration* and *administration* options except `--setip ...` and `--setsecret ...` should allow bbb-conf to mess around with config files. Right now the only workaround for restarting a properly configured instance is to reboot the related zone/container/box =8-((( .

env:
BIGBLUEBUTTON_RELEASE=2.2.21, Ubuntu xenial

**Comment by matiasilva** [comment]
I can restart my instance fine with no configuration loss. Can you please provide some examples?

**Comment by jelmd** [comment]
```
+ bbb-conf --setip my.do.main
Assigning my.do.main for testing for firewall in /var/www/bigbluebutton/client/conf/config.xml
Assigning my.do.main for rtmp:// in /var/www/bigbluebutton/client/conf/config.xml
Assigning my.do.main for servername in /etc/nginx/sites-available/bigbluebutton
Assigning my.do.main for http[s]:// in /var/www/bigbluebutton/client/conf/config.xml
Assigning my.do.main for publishURI in /var/www/bigbluebutton/client/conf/config.xml
Assigning my.do.main for web application URL in /usr/share/bbb-web/WEB-INF/classes/bigbluebutton.properties
Assigning my.do.main for web application URL in /usr/share/bbb-apps-akka/conf/application.conf
Assigning my.do.main for record and playback in /usr/local/bigbluebutton/core/scripts/bigbluebutton.yml
Assigning my.do.main for playback of recordings: ...
Restarting the BigBlueButton 2.2.21 ...
Stopping BigBlueButton

Starting BigBlueButton
```

And on restart it resets it:
```
+ bbb-conf --restart
Assigning my for testing for firewall in /var/www/bigbluebutton/client/conf/config.xml
Assigning my for rtmp:// in /var/www/bigbluebutton/client/conf/config.xml
Assigning my for servername in /etc/nginx/sites-available/bigbluebutton
Assigning my for http[s]:// in /var/www/bigbluebutton/client/conf/config.xml
Assigning my for publishURI in /var/www/bigbluebutton/client/conf/config.xml
Assigning my for web application URL in /usr/share/bbb-web/WEB-INF/classes/bigbluebutton.properties
Assigning my for web application URL in /usr/share/bbb-apps-akka/conf/application.conf
Assigning my for record and playback in /usr/local/bigbluebutton/core/scripts/bigbluebutton.yml
Assigning my for playback of recordings: ...
Restarting the BigBlueButton 2.2.21 ...
Stopping BigBlueButton

Starting BigBlueButton
.....
```

**Comment by matiasilva** [comment]
I have never experienced this myself, so I'll wait for others to chip in..

**Comment by jelmd** [comment]
Well, IMHO it doesn't do what is expected and it is actually not relevant, how many people get hurt by it. However, skimming over it suggests rewriting it anyway (and get it right this time) ;-).

**Comment by matiasilva** [comment]
If you have any improvements feel free to open a pull request.

**Comment by ebner** [comment]
I'm also experiencing problems when bbb is updated through the Ubuntu repo. Upgrades break the echo test (and possibly other things). Restarting the instance does not help, my workaround is to run `bbb-conf --setip insert-fqdn-here` after upgrading BBB through `apt upgrade`.

**Comment by jelmd** [comment]
@matiasilva will do, but probably for 2.3, only (haven't had the time yet to look at it). Perhaps I even fork and build proper packages to get rid off all the "pseudo-intelligent" behavior/"update - destroy config madness" ;-)

**Comment by matiasilva** [comment]
> I'm also experiencing problems when BBB is updated through the Ubuntu repo. Upgrades break the echo test (and possibly other things). Restarting the instance does not help, my workaround is to run `bbb-conf --setip insert-fqdn-here` after upgrading BBB through `apt upgrade`.

This is not a workaround. This is how you update bigbluebutton. Make sure to read the documentation on upgrading your server.

**Comment by matiasilva** [comment]
I'm 

> @matiasilva will do, but probably for 2.3, only (haven't had the time yet to look at it). Perhaps I even fork and build proper packages to get rid off all the "pseudo-intelligent" behavior/"update - destroy config madness" ;-)

Any chance you could further elaborate on the madness you refer to? I for one have not had this problem and restarting does not change my setup at all. Packaging has been discussed in the past and if you manage to make improvements or want to suggest any, please do so!!

**Comment by jelmd** [comment]
@matiasilva wrt. madness: could probably write a paper about it. However, to keep it short: BBB should start to follow these golden rules of SW engineering: 1) "Use reasonable defaults/fallbacks." 2) the principle of least surprise.

**Comment by matiasilva** [comment]
@jelmd Would you mind further elaborating? You've mentioned issues that in your opinion are critical and others might find them to be as well. If you can report them, then they can get fixed for everyone.

**Comment by lonesomewalker** [comment]
I am also curious for more details, because we run more than 10k servers, and we NEVER had this issue.
So, maybe you fumbled around a bit in your server?
In general, "bbb-conf -restart" does just a restart of the services, but never touching existing configs.
And we have several servers with several versions of BBB in 2.2...

**Comment by ebner** [comment]
> > I'm also experiencing problems when BBB is updated through the Ubuntu repo. Upgrades break the echo test (and possibly other things). Restarting the instance does not help, my workaround is to run `bbb-conf --setip insert-fqdn-here` after upgrading BBB through `apt upgrade`.
> 
> This is not a workaround. This is how you update bigbluebutton. Make sure to read the documentation on upgrading your server.

I'm simply upgrading using `apt update` followed by `apt full-upgrade`, which, if there is a new version of `bbb-web` etc, breaks (at least) the echo service. Since such minor upgrades can easily be performed using `unattended-upgrades`, I consider it highly problematic that such an automated action would involve a manual intervention such as executing `bbb-conf`.

I am not aware of any other software that requires to fix the configuration after being upgraded using the operating systems standard package management. It seems as if this issue could be easily solved with a postinst script in the Debian package.

**Comment by lonesomewalker** [comment]
@ebner : maybe you should stick to bbb-install.sh then.
And maybe "you" are not aware of such software, but there is PLENTY.
Also BBB is not only ONE software, there are several components. And if you replace parts of them, they have to get reloaded/restarted.

@jelmd : i was thinking about your problem, because we never had these issues.
Did you edit /etc/bigbluebutton/bbb-conf/apply-lib.sh?

**Comment by ebner** [comment]
> @ebner : maybe you should stick to bbb-install.sh then.

So to summarize, your recommendation is to remove `/etc/apt/sources.list.d/bigbluebutton.list` after successfully running `bbb-install.sh`. This way a BBB instance is not affected by `apt update && apt full-upgrade`. Upgrades (even bugfix releases) should be carried out using `bbb-install.sh`.

Correct?

**Comment by lonesomewalker** [comment]
No. :-)

You should setup your server with bbb-install.sh from the beginning.
This takes care of update/upgrade and other things.
(and to be honest, we never tried such a wild upgrade-mix between apt and bbb-install.sh :-D )

I don't know your personal setup, but if you want to have a system with minimal configuration issues this might the way to go for you.
In the beginning (several years ago) most of our machines were set up the classic way.
But now we have our own mirror and modified the bbb-install.sh to use this repo and some other small tweaks (which might not be relevant for you).
In general i agree with you that the classic system package manager should be able to handle these issues.
But as written BBB is not only ONE software. Things can go crazy :-)

Since we maintain over 10k servers with various configurations and modifications, we needed at least an automatization step which is reliable. And as you've written, you want a stable system :-P

bbb-install.sh saved locally, own repository (which is ALWAYS available and saves traffic), and an apply-lib.sh which starts a custom bash script on each server if available. Single servers rarely fail after this update/upgrade process, bigger scenarios are built with Ansible.

**Comment by matiasilva** [comment]
> 
> 
> > > I'm also experiencing problems when BBB is updated through the Ubuntu repo. Upgrades break the echo test (and possibly other things). Restarting the instance does not help, my workaround is to run `bbb-conf --setip insert-fqdn-here` after upgrading BBB through `apt upgrade`.
> > 
> > 
> > This is not a workaround. This is how you update bigbluebutton. Make sure to read the documentation on upgrading your server.
> 
> I'm simply upgrading using `apt update` followed by `apt full-upgrade`, which, if there is a new version of `bbb-web` etc, breaks (at least) the echo service. Since such minor upgrades can easily be performed using `unattended-upgrades`, I consider it highly problematic that such an automated action involves a manual intervention such as executing `bbb-conf`.
> 
> I am not aware of any other software that requires to fix the configuration after being upgraded using the operating system's standard package management. It seems as if this issue could be easily solved with a postinst script in the Debian package.

https://docs.bigbluebutton.org/2.2/install.html#upgrading-from-bigbluebutton-22 for reference. But you bring up a good point I have seen elsewhere! I'm sure there is a good reason this is the way it is that I don't know about.

**Comment by ebner** [comment]
> (and to be honest, we never tried such a wild upgrade-mix between apt and bbb-install.sh :-D )

I actually did not deviate from the official installation instructions. I just double-checked `https://ubuntu.bigbluebutton.org/bbb-install.sh` and on line 513 it adds a repository to `/etc/apt/sources.list.d/`. This causes the mix between apt and bbb-install.sh on subsequent upgrades. If there are new versions of packages at `https://ubuntu.bigbluebutton.org/` they will be upgraded when using apt/apt-get, even without explicitly running bbb-install.sh.

So from a sysadmin perspective is it necessary to be very careful about which packages are about to be upgraded when executing `apt full-upgrade`. If `unattended-upgrades` is configured to upgrade any packages (and not only security related ones as configured by default), it will break BBB, because the sysadmin does not know that (parts of) BBB were upgraded and therefore bbb-conf is not run manually.

Do I understand correctly that you are not using apt to keep the packages on your hosts up to date? Because I have difficulties to understand why you haven't ended up in the same situation as I have.

**Comment by lonesomewalker** [comment]
Okay... from start...

Please use bbb-install.sh with the neccessary flags for your desired options.
Keep update if something changes. Before running an upgrade by using the same setup string as before please read the changelog.
If you run the bbb-install.sh the script will handle all needed steps to get your server to the latest stable version.
Then you can run your bash script which re-applies your needed/wanted modifications.
You also could run this after an unattended upgrade. The result should be the same.

But we NEVER had the issue that after an upgrade configurations got broken or as in the case of @jelmd also set a totally different hostname. Sure, some configs get overwritten by defaults, but these are functional and your own values can be re-applied if you use apply-lib.sh.

**Comment by jelmd** [comment]
@lonesomewalker Please note, that this issue is not about install or upgrade but about misbehaving `bbb-conf` script. That it causes trouble on install and upgrade is another indicator, that it does severely strange, __unexpected__ things. Again, a script, which should start or stop an instance should never ever touch/change any config (and BTW: an upgrade should never ever overwrite or change a config as well). All the dozen of complaints about XY is not working anymore after upgrade already proofed, that the current packaging (postinstall scripts) are severely broken and do unexpected, completely wrong things.

bbb-conf is furthermore broken, because a proper webRTC requires SSL/TLS, and this implies the use of FQDNs. However, it obviously prefers or is lazy coded to use the unqualified hostname - the opposite of a reasonable default.

Not sure, what else it does, but a quick look on it shows, that it is a unmaintainable monolithic mess and definitely needs a rewrite. Having a proper script would make it a 5min job to fix the mentioned issues. However, I guess, because it is in such a bad state, maintainers prefer to discuss and argue like 'never touch a "running" system' instead of counting the facts and fixing it ...

**Comment by lonesomewalker** [comment]
@jelmd sorry, but i have never read such a rubbish like yours before.
bbb-conf is working pretty well, maybe your machine/setup is a mess.

We maintain several servers, and the issues you complain never showed up.
The code itself is pretty self-explaining and understandable:
https://github.com/bigbluebutton/bigbluebutton/blob/develop/bigbluebutton-config/bin/bbb-conf

So please stop writing such a nonsense.

**Comment by ffdixon** [comment]
I'm the product manager for BigBlueButton.  I am also the author of the build system for BigBlueButton, bbb-conf, and bbb-install.sh.

The internal packaging system is a bit of a rube Goldberg machine, and has grown over the years.  It is my intent to have the packaging system rewritten to be more standards for Debian.  However, Covid-19 hit and myself and all of the BigBlueButton developers have focused on accelerating improvements to 2.2 while in parallel working on 2.3.  

I created [bbb-install.sh](https://github.com/bigbluebutton/bbb-install) to give a (near) automated install of BigBlueButton.  Still, it's my intent to improve the packaging, which will probably come in 2.4.

**Comment by iSamof** [comment]
@ffdixon - and you and the team have done/are doing a fantastic job. The accelerated efforts have been noticed and very much appreciated. For every person who expresses gratitude and appreciation, there are a thousand who also appreciate, quietly.

**Comment by ffdixon** [comment]
We love our community.  We don't mind people being critical -- as long as they do it professionally.  Don't worry that the criticism will have any negative effect on our determination.  Some of us have been working on BigBlueButton for 10+ years now, and we are more committed than ever to make it the best web conferencing system for online learning.

**Comment by iSamof** [comment]
I think a challenge for some colleagues is that English is not their first language. (And the worldwide spread of BBB usage is a testament to the value BBB is bringing to the world). Consequently, in some cases, the colleagues may not be fully aware of how their words/phrases/statements sound to English speakers. Sometimes, when they say "X shouldn't/mustn't ..." what they are actually trying to say is behaviour X isn't as helpful as behaviour Y.

**Comment by antobinary** [comment]
Update:
After merging https://github.com/bigbluebutton/bigbluebutton/pull/15010 the only remaining step that performs touch/damage on --restart is `apply-config.sh`

**Comment by antobinary** [comment]
I believe the original comment has been fully resolved. Please comment below if it's still an issue (with some info).

There are quite a few microtopics in this thread though -- bbb-install improvements, packaging, etc. They all have progressed since the time of opening of the issue. If you still have concerns about a specific topic (different than "
bbb-conf should not touch/damage any config files unless --set* is given"), please start a new thread
