### ISSUE TITLE
Stuck at Echo Test after update to 2.2.21 and 2.2.22

### ISSUE THREAD

**Issue by testprepturkey** [bigbluebutton/bigbluebutton#10251]
After the update, the connection to echo test takes too much time. 

Solution: Reinstall using the sh installer.

**Comment by develth** [comment]
Got the same error when updating through apt-upgrade, running bbb-install.sh fixed it.

Seems that on Echo-Test the UpVote / DownVote buttons are Missing, because i got a echo.

**Comment by pedrobmarin** [comment]
`sudo bbb-conf --setip <host>`

**Comment by debdolph** [comment]
> `sudo bbb-conf --setip <host>`

Does this command do anything magical? I think its the solution for all problems with BigBlueButton. Why not just fix (or debug and document(!)) the root of these problems instead saying „bbb-conf --setip fixes everything!“

**Comment by pedrobmarin** [comment]
> > `sudo bbb-conf --setip <host>`
> 
> Does this command do anything magical? I think its the solution for all problems with BigBlueButton. Why not just fix (or debug and document(!)) the root of these problems instead saying „bbb-conf --setip fixes everything!“

Nothing special, just reconfigure the FS configuration files you need to solve a stuck in echo problem just like this one.

In one of the latest packages we added a security fix for the audio websocket connection and, since not everybody checks the docs about upgrading a server, we had to respond this over and over again.

Sorry for trying to save you some time of searching all other issues we responded (with the proper answer you deserve) just like this one.

**Comment by matiasilva** [comment]
Solution found! Read the docs and be nice :-)
