### ISSUE TITLE
Restart BigBlueButton  all meetings are deleted

### ISSUE THREAD

**Issue by alireza5014** [bigbluebutton/bigbluebutton#10338]
Hi I'm new to bigbluebutton
When I restart the big blue button, all meetings are deleted.(sudo bbb-conf --restart)
I use this service through api
Is This   normal?

**Comment by matiasilva** [comment]
Yes, that's expected behavior from a restart. Similar to how you reboot your computer, you expect things to stop. Also, the only way to use BigBlueButton is through the API, that's what it is. For future questions like this, please use the users mailing list: https://groups.google.com/forum/#!forum/bigbluebutton-users
