### ISSUE TITLE
Refactor LayoutManager to store inputs and outputs

### ISSUE THREAD

**Issue by TiagoJacobs** [bigbluebutton/bigbluebutton#10395]
Hello @vitormateusalmeida .

Based on comments from @KDSBrowne about the fact that Layout Manager is still relying on browser events in some situations, I would like to propose you a cleaner approach.

In LayoutManager, we could have different inputs ( the browser, the video dock, the chat, etc ) and different outputs ( the video dock, the chat, etc ).

Said that, the components would report to LayoutManager about their properties whenever they change. If a camera is added to VideoDock, it will let LayoutManager know. Once that happens, layout manager will calculate the state again generating different outputs.

Those outputs could be scoped on the target audience, so if something is calculated for chat it could produce a `chat` property containing  all the relevant information for chat.

This could potentially help us to understand the data model and also reduce the number of re-rendes, as the properties will be scoped ( so the chat component can look only at the `chat_panel` property.

```
"state":{
   "inputs":{
      "browser":{
         "width":300,
         "height":500
      },
      "video_dock":{
         "num_cameras":8
      }
   },
   "output":{
      "video_dock":{
         "width":200,
         "height":300
      }, 
      "chat_panel":{
         "width":200,
         "height":300
      }
   }
}
```

Now that you already know all the things that layout manager takes into account for its math, i would propose to first do a modeling of inputs/outputs and collect feedback ( before starting another cycle of refactor ).

**Comment by vitormateusalmeida** [comment]
Here goes the first draft for the specification. We're going to prototype this to validate the concepts.
![LM Use cases](https://user-images.githubusercontent.com/9675166/93238393-c191e180-f757-11ea-81c8-5de60c562c24.jpg)

**Comment by iSamof** [comment]
This is great, thank you @vitormateusalmeida and the rest of the team.

I have a couple of questions:

1- Are the above layouts "presets" or are they samples of what can be created from the commands on the right?

2- The commands all have "bool" to switch various elements on and off. Am I correct in thinking that the commands set the **initial start-up** condition of the HTML5 client? If so, a user can switch on the element that started as off?

Ability to 'disable' some elements (instead of hide at session start) would open BBB and HTML5 client to wider applications. Example: some specialist applications may not need/want the presentation and private chat.

Many thanks in advance

**Comment by vitormateusalmeida** [comment]
Refactor concluded in 2.4, as we can see in context state in https://github.com/bigbluebutton/bigbluebutton/blob/v2.4.x-release/bigbluebutton-html5/imports/ui/components/layout/initState.js

**Comment by antobinary** [comment]
The default values can be found in https://github.com/bigbluebutton/bigbluebutton/blob/v2.4.x-release/bigbluebutton-html5/imports/ui/components/layout/defaultValues.js
