### ISSUE TITLE
video and audio in the presentation

### ISSUE THREAD

**Issue by ansomkrd** [bigbluebutton/bigbluebutton#10403]
Good afternoon. It is often necessary to insert video and audio into presentations in addition to text and graphics, this is more convenient than using third-party videos, since the teacher often uses a lot of small tracks during the lesson, now it has to be done through a screen demonstration, which is not convenient(

We could not find any ready-made solutions and we are afraid that when ordering development, we will not be able to update the BBB later.

Are you going to make a similar opportunity?
Can you suggest ready-made solutions that don't interfere with the BBB core?

If this appeal should not be in the branch, then could you write in a personal message Your advice on how best to proceed and explain in a few words how the presentation is working now.

Thank you very much for your time and this product!

**Comment by mk-hs** [comment]
If you are talking about small videos, BBB is able to play mp4 files, so you can upload them somewhere - an internal server, or something like dropbox - and play them just fine via the share video function.

**Comment by hex-m** [comment]
Related: [HTML presentations](https://github.com/bigbluebutton/bigbluebutton/issues/9235), [PowerPoint animation](https://github.com/bigbluebutton/bigbluebutton/issues/9734)

**Comment by aguerson** [comment]
To play video with you own server:

https://github.com/aau-zid/BigBlueButton-liveStreaming/issues/83

Regards,
Aurélien.

**Comment by hex-m** [comment]
@aguerson This issue is about playing media files that are embedded in a (presumably PowerPoint?) presentation. Your link seems unrelated.

**Comment by ansomkrd** [comment]
@hex-m ,
Yes, you are right. But not even necessarily so, the problem is that there is no way to add video and audio to the Board for the lesson. The link to the video that is there is not the same, and showing the screen is also not the same.
Maybe you can advise how to be, tried to find someone who will finish for money, but also unsuccessfully, or expensive, or failed...
As I understand it, not only we need it, but if we can unite and make a donation to the project, will you implement it?

**Comment by hex-m** [comment]
> the problem is that there is no way to add video and audio to the Board for the lesson. The link to the video that is there is not the same, and showing the screen is also not the same.

If it's okay for you to upload the media files directly (not using media embedded in presentations), check out [this issue](https://github.com/bigbluebutton/bigbluebutton/issues/8276). There is also a [draft PR](https://github.com/bigbluebutton/bigbluebutton/pull/8753).

> Maybe you can advise how to be, tried to find someone who will finish for money

Contact the companies that offer [commercial support](https://bigbluebutton.org/commercial-support/).

**Comment by ansomkrd** [comment]
@hex-m  Thanks. #8753 When it will be in v2.3? Or there is no such information yet?

**Comment by hiroshisuga** [comment]
#8753 would not be merged soon. The development team follows its relatively conservative principle. Especially a security issue would prevent it to be merged. However, you can merge it locally. Hints are there in the conversation. Good luck!

**Comment by basisbit** [comment]
Zoom implemented this by actually running licensed MS PowerPoint Viewer on very expensive graphics-card-accelerated AWS servers and then video-streaming this to the users. However, the BigBlueButton project can't do this for various reasons. Not even using LibreOffice, because of the missing video/3D hardware acceleration on typical servers where bbb is supposed to run on. The same result however can already be achieved by having the presenter screen-share from their computer to BBB.

There exist other issues for animated presentation support (by creating a couple of slides with in-between-steps of the animation) and html-presentations, so I don't think there is anything left to do in this issue here. There also already exist feature request issues for being able to use the whiteboard drawing feature on top of a screen-share video. 
-> Closing this here issue as wont-fix.

If anyone comes up with another good solution for this, please comment here and we'll gladly reopen this issue.
