### ISSUE TITLE
Implementing automatic reconnection/recovery or fail-over on restarted or failed servers

### ISSUE THREAD

**Issue by bigbluemeeting** [bigbluebutton/bigbluebutton#10558]
**Is your feature request related to a problem? Please describe.**
Occasionally, or often enough, BBB servers have to restarted on a live server which has live users. These users are not given a proper error message as to what they should do now, instead the system shows reconnecting. 

**Describe the solution you'd like**
It's easy enough for the server to communicate to the client that the server is restarting and then perhaps save the state in a text file or redis or MongoDB so when the server restarts it's able to recover state if necessary. Alternatively, the server should at least give a proper error to the user  in this server has been restarted, please rejoin the session by going back to your application. 

Alternatively, we should add a new parameter to the API which tells the client to redirect back to that URL in case of failure. That URL can either display a message, provide a link to return to the meeting, or automatically redirect users to a new server where a new meeting with the same ID is created. The application at the URL (perhaps the application or the proxy) is responsible for saving the state of the meeting and recreating a new meeting with the same meeting id and redirecting all users who return to it via the unique URL to a new meeting. This would then lead to a much smoother experience for users who are dealing with a failed server. It should reduce re-connection time to less than a minute rather than 5-10.

**Additional context**
The proxy or the application can save state of the meeting and modify the create meeting parameters to communicate that information to the server. The server then gives that information to the client which holds it there, waiting for an unreachable server and automatically redirects the user after a certain number of seconds of failed re-connection to the server.

**Comment by iSamof** [comment]
This is a great idea which adds a huge amount of extra credibility to BBB. The second option of failing over to a different server is preferred due to the rapid resumption of the session. 

However, those with just one server ought to be catered for by way of the first option (server recovery) being the fall-back for the first option when there is only one server available. 

Bear in mind, the upcoming enhancements will increase server capacity and therefore clustering will become a  later event in the user journey. This increased capacity also means a greater number of users will be affected when a server fails, especially on a single server installation.

**Comment by GhaziTriki** [comment]
Relate to this for the server apps https://doc.akka.io/docs/akka/2.5.32/general/supervision.html
