### ISSUE TITLE
block microphone had unpleasant behavior

### ISSUE THREAD

**Issue by mojtaba82** [bigbluebutton/bigbluebutton#10552]
**Describe the bug**
When moderator is blocked user microphones, if a new user come to session not see options for choose between microphone and only listener and come to session in listener mode. after while if moderator unblock microphone still this new user can not enable microphone and speak.

**To Reproduce**
1. Moderator block microphone
2. after that a new user come to session
3. new user not see option to choose between microphone mode and only listener mode and listener mode choosed automatically
4. after moderator unblock microphone, new user not able to enable microphone

**Expected behavior**
After moderator unblock microphone, new user be able to enable microphone

**Desktop (please complete the following information):**
 - OS: all
 - Browser all
 - Version all

**Smartphone (please complete the following information):**
 - Device: all
 - OS: all
 - Browser all
 - Version all

**Comment by ffdixon** [comment]
After the moderator removes the lock on microphones, users can rejoin audio (click the phone icon twice) and receive the prompt to join with microphone.

**Comment by mojtaba82** [comment]
You are right, New user can rejoin audio and get microphone but without rejoin this is impossible and this is unpleasant.

**Comment by mailalaki** [comment]
hi @ffdixon , I strongly agree with @mojtaba82. This process is very unpleasant. It is best to perform a user echo test when entering the session, even if it is locked. Then, when the presenter removes his/her limit, he/she can use the microphone in the meeting and answer without delay. 
please provide a solution for it.

**Comment by pdunk** [comment]
I see the same issue, but manifests even worse.
In my BBB instance I configure to skip the menu, where you can select between listen and join with mic, but rather go directly to EchoTest.

When I lock as moderator the users mic, the users go straight to Echotest, which starts, and you can hear the echo working, but the menu to press thumbs up and down is gone right away and you are basically stuck and cant fully join the meeting.

Expected behavior: I could imagine, that the echo test is allowed and then the users is just put in a frozen mute, till moderator unlocks.
But maybe the simpler option, is to skip the echo test, in case mics are locked, and move folks to listen user type.
