### ISSUE TITLE
Problem in installing bbb on VM

### ISSUE THREAD

**Issue by solmaz990** [bigbluebutton/bigbluebutton#10568]
Hi everyone
I was installing bbb on VM by following line 
wget -qO- https://ubuntu.bigbluebutton.org/bbb-install.sh | bash -s -- -v xenial-22 -s bbb.solmaz.com -e info@esolmaz.com -w
After 9 hours I decided to increase cpu core to make the installation process faster.
So, I power off vm and increase cpu core to 4.  now I want to install bbb again but it doesnt work
![image](https://user-images.githubusercontent.com/16305850/94719338-eabd8f00-035f-11eb-8895-c0a148df98c2.png)
Would you help me how can I install bbb agian
Thanks in advance
Solmaz

**Comment by matiasilva** [comment]
It should not take 9 hours to install. Also, make sure to read the minimum requirements, 4 CPU cores should be the default. Please make sure you follow the guidelines for getting help https://docs.bigbluebutton.org/2.2/getting-help.html as this issue tracker is reserved exclusively for bug reports and feature requests. Thanks.

**Comment by solmaz990** [comment]
Thanks for your response
I'm new in ubuntu and It's first time working with linux. I have installed VM and ubuntu after that I wanted to install bbb through bbb-install.sh . 
My VM setting:
CPU core: 6
Ram: 7 G
Hard: 40 G
and I have not installed apache or any thing. I have not Installed SSL.
Do I need to install anything special before starting to install bbb?
Would you help me please ?
Sorry for my bad English
Thanks in advance
Solmaz

**Comment by matiasilva** [comment]
Everything about installation requirements is in the documentation: https://docs.bigbluebutton.org/2.2/install.html#before-you-install. Please make sure you read that before going forward. Since it's your first time with Linux, I also suggest familiarizing yourself with the OS more, perhaps read some Digital Ocean guides, they're great. Running BigBlueButton requires technical knowledge of different software like nginx, STUN/TURN servers, networking and so on. It's not to say you can do it as a beginner, but make sure you're ready for many mistakes ;-) I suggest taking this further in the mailing lists: https://groups.google.com/forum/#!forum/bigbluebutton-setup

**Comment by solmaz990** [comment]
I have seen this link before and since my time is limited, I wanted to ask my main questions here
thanks anyway

**Comment by matiasilva** [comment]
The same amount of time is needed to post in both places.

**Comment by solmaz990** [comment]
Any advise or guidance would be greatly appreciated..

**Comment by matiasilva** [comment]
@solmaz990 I appreciate your plight, but please, there are folks in that mailing list that will be happy to help! This is just not the right place unfortunately.
