### ISSUE TITLE
Create LTS version of BBB

### ISSUE THREAD

**Issue by bigbluemeeting** [bigbluebutton/bigbluebutton#10571]
**Is your feature request related to a problem? Please describe.**
Server upgrades routinely break BBB servers as releases are buggy with new features or updated libraries which are not fully understood by developers therefore they make mistakes in configuring them, or configuration files are changed with new parameters which are not clearly documented in the release.

**Describe the solution you'd like**
An LTS version and release cycle that is at least 1 year long:
- Adds no new features.
- Upgrades no core software like Freeswitch unless for security or stability, and even then only if it does not change any of its APIs that BBB uses to communicate with it.
- Only upgrades libraries for security purposes.
- Makes no changes to configuration files and does not override any of the existing configuration files. Adds no new parameters to them that are necessary for correct functioning.
- Has only necessary fixes that improve stability and security backported for the normal release versions.

**Describe alternatives you've considered**
Leave the state of things as they are with breaking changes with new releases, as well as new features... and user perception that this is not production ready software to be used by hundreds or thousands of users.

**Comment by matiasilva** [comment]
Such an idea was already brought up in the developer group. I don't know if this is necessary given that BigBlueButton is *already* production-ready software being used by hundreds and thousands of users.

**Comment by bigbluemeeting** [comment]
> Such an idea was already brought up in the developer group. I don't know if this is necessary given that BigBlueButton is _already_ production-ready software being used by hundreds and thousands of users.

I take it you have not had to support thousands of users using BBB with an upgrade cycle against head to be holding such strong opinions. Considering competitors run multi-million dollar companies providing similar services, BBB has a ways to go in making a dent in that market in which it competes. This would go a long way to forwarding that goal.

**Comment by matiasilva** [comment]
I personally have not supported so many users and am not operating on a large scale. Sure, it would be a "nice-to-have" but imo there are other more pressing features I would like to see first. Would I rather this or some of the things in 2.3? Definitely the latter. Perhaps this might be something to think about once 2.3 is released and stable but taking away time from development of that to lay out a roadmap on how to do this is non-ideal (again, imo).

**Comment by GhaziTriki** [comment]
Hi @bigbluemeeting 

I think there is something wrong with this issue, making the difference between an open source product as-is and making it ready for commercial production use are two different paths.

The problem you are describing is not related to BigBlueButton only, but most of the open source products I know using have that type of issues at different levels just because of their open source nature, this is why the BigBlueButton community remains one the master pillars of this project. If you need to install BigBlueButton at large-scale you surely need an internal DevOps discipline.

However, I don't think it is the right place to discuss about this, I am closing this issue in favour of a thread I created in the forums that you welcome to enrich : https://groups.google.com/g/bigbluebutton-setup/c/ONdwNczaLqI
