### ISSUE TITLE
On Iphone 11 getting error - Media could not reach the server (error 1020)

### ISSUE THREAD

**Issue by ultimateakash** [bigbluebutton/bigbluebutton#10636]
Bigbluebutton version - 2.2.26

Hello, I have installed bbb on my linux server. everything works fine on windows, android. but on iphone i am getting error on video call.
audio call working but when i am trying to use video i am getting error media could not reach the server. please help me.
thanks

**Comment by sdharmacse** [comment]
We are also facing issues while connecting from the mac safari browser while starting web cam getting  media server  1020 and audio is working. We are using our own turn server

**Comment by ultimateakash** [comment]
@sdharmacse  Is the issue fixed by using own turn server. actually, I also tried but still my error not resolved. please guide me.

**Comment by BenSjoberg** [comment]
We had a similar issue, and it seemed to be a combination of two unrelated problems:

* Coturn (the open source TURN server recommended by BBB) seems to have a bug where it will stop responding to allocation requests after some time. With verbose logging enabled, it outputs the message "allocation watchdog determined stale session state". It seems that the only way to get our of this state is to restart coturn. (After a few hours of trial and error I wasn't able to determine how to trigger this state. Possibly a race condition somewhere?) This appears to have been encountered by other users, see [here](https://github.com/coturn/coturn/issues/634)

* Safari (both iOS and Mac) will hang when setting up a connection to Kurento if it can't reach a configured TURN server, even if it doesn't actually need to use TURN to connect. This means when Coturn gets into this state, it becomes impossible to use Safari with BBB video.

We "resolved" this by adding a third-party TURN server provided by Twilio. This isn't great, because they charge 40 cents per GB (!!). To reduce costs we still include our own TURN server (so it can be used when it's actually working) but we use user-agent sniffing to exclude our own TURN server when the user is using Safari. Very hacky setup, but it works until Coturn is patched.

**Comment by jlabonte24** [comment]
please how configure turn twillio server with bigbluebutton

**Comment by prlanzarin** [comment]
Merging into https://github.com/bigbluebutton/bigbluebutton/issues/10746
