### ISSUE TITLE
echo test not working with Firefox version 79 and newer when using VPN tun device (linux)

### ISSUE THREAD

**Issue by ArminXG** [bigbluebutton/bigbluebutton#10686]
We have a BigBlueButton installation inside our network to be connected via VPN (tun device using OpenVPN).

When using Firefox after Version 78, the echo test results in ICE error 1007.
Without VPN (no tun device) it works. Chrome/Chromium does not have this error.

A wireshark trace shows that Firefox does not try to check the tun device. Maybe Firefox does not "see" that device or ignores it.
I am not sure if this is BigBlueButton / HMTL5 issue.

**Comment by matiasilva** [comment]
We spotted this a few days ago, but it's not a BigBlueButton issue. Firefox 81 fails almost all tests on test.webrtc.org.

**Comment by iam-TJ** [comment]
With Firefox 81.0.2 on Ubuntu 20.04 we found most tests pass. Network tests failed initially due to the page being unable to connect to networktraversal.googleapis.com - but that was due to having that host blocked in the uMatrix add-on.

With that enabled the UDP/TCP network tests passed.

The remaining failures were:

* Reflexive connectivity
* Video Throughput ([ FAILED ] Frame rate mean is 0, cannot test bandwidth without a working camera)

Camera tests had all succeeded earlier.

**Comment by ArminXG** [comment]
Thanks for the responses. Using this info we tested a bit more and it is really a firefox issue. Our tests showed this problem with Linux only (Windows Firefox does not have this problem) and with firefox versions starting 79.
I will close the issue here.
