### ISSUE TITLE
Default TURN Server not Working with Safari

### ISSUE THREAD

**Issue by MariusE** [bigbluebutton/bigbluebutton#10764]
**Describe the bug**
The default STUN/TURN Server *stun.freeswitch.org* seems to be incompatible with current iOS/Mac Safari.
Webcam-Sharing fails.

An additional indicator for that problem is, that Safari prompts to allow the usage of microphon even when you click und "only listening".

Changing the Server (eg. http://stun.l.google.com:19302/) solves the problem.

**Installation type**
Installed with bbb-install script?

**Firewall and IP address type**
Server uses default Firewall Config of BBB, no other FW.
Server got dedicated IPv4 Adress.

**Additional context**
There are many Issues open that mention Problems with iOS14/Safari in the last time, in the comments you find some information, which advice to use other or additional TURN Server.

**I open this as a new issue, because there is nowhere clearly mentioned that this is an issue kind of caused by the BBB default installation.**

Additionally this type of Issue can not be reproduced with the test.bigbluebutton.org instance, because this server uses a different STUN/TURN Server.

**Comment by DDQW** [comment]
i still have the problem even with the google stun so it sadly is not the solution.

But the google stund does work faster that is a benefit

**Comment by prlanzarin** [comment]
You're not supposed to use the default STUN server that comes with BBB; I'm not even in favor of BBB serving a default, hardcoded STUN server for starters, but that's another topic.

Don't rely on third party STUN and/or TURN servers if you want to know what's up with them. Setup your own coturn instances, preferably. DNS round robin them for increased reliability.

There are docs for setting coturn instances up. And there are docs to check whether STUN server X or Y is working (so you could come up with a watchdog, for instance).

**Comment by DDQW** [comment]
i have my own turn server does not help

**Comment by prlanzarin** [comment]
@DDQW 
> i have my own turn server does not help

Sorry to hear that; this issue is, however, about the default STUN server not working with ie Safari. So I don't see how your use case is related to my response.

I can help you debug this if you post more info on issue 10746 (which you've written into); but please do not start posting in multiple issues.

**Comment by MariusE** [comment]
> You're not supposed to use the default STUN server that comes with BBB; I'm not even in favor of BBB serving a default, hardcoded STUN server for starters, but that's another topic.
> 
> Don't rely on third party STUN and/or TURN servers if you want to know what's up with them. Setup your own coturn instances, preferably. DNS round robin them for increased reliability.
> 
> There are docs for setting coturn instances up. And there are docs to check whether STUN server X or Y is working (so you could come up with a watchdog, for instance).

Yes, I know there are solutions and did get it running.
So even if i'm not supposed to use the default, there is a default and many will use it, cause it works/worked. 

So I think it should be noted, that the default installation comes with some problems.
----
Also it's clear, that the fundamental technical problem is not part of BBB, but the freeswitch.org STUN server.

**Comment by greenycat** [comment]
Does it work?
stun.freeswitch.org does not even pass test with [stun test client](http://manpages.ubuntu.com/manpages/bionic/man1/stun.1.html)

```
root@srv:~# stun stun.freeswitch.org
STUN client version 0.97
Primary: Blocked or could not reach STUN server
Return value is 0x00001c
```

And 

```
root@srv:~# stun stun.freeswitch.org -p 19302
STUN client version 0.97
Primary: Blocked or could not reach STUN server
Return value is 0x00001c
root@srv:~#
```

**Comment by ffdixon** [comment]
We are removing the stun.freeswitch.org from the defaults.  Recommend you [setup your own TURN server](https://docs.bigbluebutton.org/2.2/setup-turn-server.html) (which also functions as a STUN server), or use Google's stun server at `stun.l.google.com:19302`.

**Comment by MariusE** [comment]
> We are removing the stun.freeswitch.org from the defaults. 

Maybe a good solution to avoid those problems. But I wanna through in some question from a user perspective:

What would be the impact for the standard installation, when you do so? 
Would the bbb-install script still setup a completely working and usable BBB?
Could the STUN server Address be a parameter for the install script, like e-mail or hostname?

If not: Needs the configuration redone after every update? (not very convenient) 

Also if you remove this config: would that be a breaking change for existing installations? -> should not be done in minor Version release like 2.3

**Comment by ikanashov** [comment]
@DDQW

I have the same problem with new apple safari clients.

stun google servers, don't work for me too.

I test it with `stun stun.l.google.com
STUN client version 0.97
Primary: Blocked or could not reach STUN server
Return value is 0x00001c
`
I found serves that works.
stun.xten.com
stun.voipbuster.com
stun.ekiga.net

I change  /usr/share/bbb-web/WEB-INF/classes/spring/turn-stun-servers.xml 

`   <bean id="stun0" class="org.bigbluebutton.web.services.turn.StunServer">
        <constructor-arg index="0" value="stun:stun.xten.com"/>
    </bean>

    <bean id="stun1" class="org.bigbluebutton.web.services.turn.StunServer">
        <constructor-arg index="0" value="stun:stun.ekiga.net"/>
    </bean>

    <bean id="stun2" class="org.bigbluebutton.web.services.turn.StunServer">
        <constructor-arg index="0" value="stun:stun.voipbuster.com"/>
    </bean>

    

    
`
restart bbb servers, and safari clients now works.

**Comment by MariusE** [comment]
@ikanashov thanks for your help to others. :) 

But please respect, that this Issue is about a different Topic!

**Comment by mariohock** [comment]
@MariusE actually, BBB works when no STUN server is configured (at least if BBB is not behind a NAT itself). In our case it even works better than with the default stun.freeswitch.org, since this server seems to be down. Moreover, setting a correct/working STUN server may even make the situation worse, as discussed in https://github.com/bigbluebutton/bigbluebutton/issues/8824.

**Comment by mariohock** [comment]
I would suggest: Either change the connection procedure, make the client connect first. In this case STUN is not needed at all and it would probably fix the issue that connecting audio often takes very long (https://github.com/bigbluebutton/bigbluebutton/issues/8824). Or install coturn within the bbb-install script. Since, as I pointed out in https://github.com/bigbluebutton/bigbluebutton/issues/8824, STUN without TURN can make that some users (at least me) can no longer connect at all.

**Comment by prlanzarin** [comment]
> BBB works when no STUN server is configured (at least if BBB is not behind a NAT itself) [...] Moreover, setting a correct/working STUN server may even make the situation worse, as discussed in #8824.

You're assuming this for very specific scenarios. BBB works without STUN in specific scenarios, and work best that way AS LONG as you have at least a TURN server setup. But that's a restricted scenario nonetheless. As it is, using a functional STUN server and a functional TURN server is the way to guarantee everything will work whenever possible, no mater which are the server and client environments and no matter the connection times. Any other further optimizations are environment specific, per case basis.

**Comment by mariohock** [comment]
@ prlanzarin I agree, see my suggestion about installing coturn as part of the install script. But the question I was referring was to is: "What would be the impact for the standard installation, when you do so [disable STUN in the default config]?". And my experience is, it is not worse than the status quo.

**Comment by prlanzarin** [comment]
> it is not worse than the status quo.

Agreed. But that doesn't solve the conundrum we have in this issue:
  - The current default STUN server doesn't work, so we just can't use it.
  - The 2.2 development branch got the hardcoded STUN changed to stun.l.google.com. That should be good enough for the majority of setups. This would be surely better than the status quo, reliability wise. The problematic here: will still not work reliably for audio, mainly, with funky Address-Restricted Cone NATs (like yours, I saw your analysis in the other issue). This will surely not work with Port-Restricted or Symmetric-Symmetric setups. Those, I expect, are the minority of cases, for which:
    * We have docs on how to setup a TURN instance. And we advise to do so. And bbb-install has a helper command to set up a coturn instance (if I'm not mistaken).  Environment specific.
    * Reversing the ICE controlling roles and the negotiation roles could reverse the hole punching schematic to make Address-Restricted NATs more reliable. That would be, however, not guaranteed. UDP binding requests are race-y. Also, that reversal of negotiation roles **is far from trivial** to implement.
    * Using only a TURN server and no STUN if your environment is proper. Environment specific.

The reason I'm not a fan of a default  hardcoded STUN (and in that we agree, but for different reasons)  is privacy related:
  - do administrators know they're installing an open source software that hard codes a STUN server from Google (or any other 3rd party) in the default setup? 
  - is it explicit to them that it is so and that they should set up their own coturn instance (or properly let their users know that they using a 3rd party STUN)?

It's possible that I'm being overzealous with those privacy items, though. And I agree with @MariusE that we can't just stop shipping a default STUN server in 2.2 because that would be kind of a breaking change (apart from the current STUN being flaky lately; but I suspect it did work well a couple of months ago).

**Comment by mariohock** [comment]
> do administrators know they're installing an open source software that hard codes a STUN server from Google (or any other 3rd party) in the default setup?
No, they don't. I speak from experience. And if they did, it would be easy for them to just configure one, if needed.

> is it explicit to them that it is so and that they should set up their own coturn instance (or properly let their users know that they using a 3rd party STUN)?
No. And if it was, it would be easy to do so it in the first place. This means, if it were explicit, no default would be needed.

Yes, it would be a breaking change. But not it's broken, as well. What I'm saying: In the current situation: Either your BBB still works, then it keeps working, when you remove the default STUN entry. Or your BBB does not work anymore or is _extremely_ unreliable. In this case, the breaking change would break something that's already broken.

If you assume that servers usually are accessible from the Internet, installing coturn on the same machine would solve the issue. However, this does not help, of course when your server's connection is the problem. But: You have one server, where you have to do the NAT thing right. But you have (e.g.) 1000 users all with different setups.

**Comment by prlanzarin** [comment]
> No, they don't. I speak from experience.

That would be reason enough for me to ship with no default STUN server configured.

**Comment by mariohock** [comment]
> That would be reason enough for me to ship with no default STUN server configured.

I agree. Actually, I was little bit shocked when I noticed that a third party STUN server was used. Of course, I could have read the docs more carefully. But, often you stop reading as soon as everything is working.

And regarding trouble shooting: When I know that I have configured a third party STUN server, I know to check it, if something breaks. In this case, I needed wireshark to figure this out. Especially since it did not break entirely with the faulty STUN server, it just took longer than usual.

**Comment by mariohock** [comment]
> Reversing the ICE controlling roles and the negotiation roles could reverse the hole punching schematic to make Address-Restricted NATs more reliable. That would be, however, not guaranteed. UDP binding requests are race-y. Also, that reversal of negotiation roles is far from trivial to implement.

As pointed out above, you have one server where you have to get it right, but potentially a large number of users with different and varying setups. Often servers are not NATed. In this case, without any STUN, the client sends one UDP packet, the server answers, connection is up in <<1s. A TURN server will also make it work, but will not fix the connect delays. And if the server is actually is behind a NAT, it's still not worse than now with NATed clients.

I have no idea how hard this is to implement. Maybe this is a good opportunity to say "thank you", either way.

**Comment by MariusE** [comment]
>  And my experience is, it is not worse than the status quo.

I disagree here. The status quo is a BBB 2.x that is supposed to work with NATed clients out of the box. As a solution there is a default STUN server configured. Currently this status is broken, because the server is not working. 
To go back to the defined status quo, which is set by the versioning, there needs to be a new, working default. 
If you define the broken default as the new status quo, you get a breaking change. This would lead to a very bad admin and user experience. Because everything looks the same after a simple update, but some clients are still unable to connect. In fact after an update i would expect the exact opposite, a working/fixed system. 
I did all that debugging before i opened this issue and it's very complex stuff.
As mentioned above my solution also was the google STUN server, cause i needed it to work quickly and a STUN server requires to setup a complete new (v-)server to be setup.

In the current situation, i guess there are many "click and run" installations out there, so you should be careful with breaking changes.

I agree with the point, that an admin does not know about the 3rd party STUN server (i found it while debugging and was kind of surprised). 
This fact could be mentioned in the terminal after installation, in the bbb-conf dialogue and in the docs section, where the bbb-install command is explained. Those places should be the most read once.

Also in the docs is just a description to setup your own STUN server, but not how to use a existing 3rd party server. This fact also is confusing and makes you think there is no default server set up.

---------

## So in summery there is more than one point in this context:

1. Fix the main problem with a new default STUN server
2. Notice for admins, that there is a default 3rd-party server
3. defining a way to ship without a default in a new major version and optimizing the docs for this topic

**Comment by mariohock** [comment]
@MariusE I mostly agree with what you say.

But maybe one point to consider with respect to breaking changes for "click and run" installations: We set-up our server and everyone could connect (since the STUN server was broken, but the _server_ is not behind a NAT). Then, all of a sudden, I could no longer connect for some time but then without doing anything it worked again. In retrospect: Because the default STUN server did work again for a brief period of time.

We stumbled upon the broken STUN server, fixed it. But then everything was broken (only for me, but I was the one testing the fix). So, if we didn't do this just now, the update you're talking about would have done just this for me: We make an update and I could no longer connect. But yes, I agree. A stateful firewall that breaks NAT hole punching seems to be a rare case.

This means my dream scenario would be: Do just what you suggested but also make connections always work (be it with or without STUN) if the server is not behind NAT/firewall. Conceptually this is very straight forward, however, as stated above actually implementing this might be harder.

**Comment by basisbit** [comment]
An actual solution to this problem here would be to go the same route like Jitsi did go early this year: have the install script also install stun + turn on the bbb server - this will require Ubuntu 18.04 (because of coturn of Ubuntu 16.04 being utterly broken/buggy) and thus should be implemented in 2.3.x.
Imho, no time on this issue should be wasted on a temporary hack like using google stun for 2.3, because that would just slow down development of bbb 2.3 and probably cause a media outcry in Europe again when people just apt install update and suddenly without the admins knowing, they violate GDPR by using Google STUN servers.

For bbb 2.2:  please change the bbb documentation to suggest turn+stun server configuration and configuration of it in various bbb configs just as done on test.bigbluebutton.org, as that seems to work well for most cases.

This change would instantly resolve and reduce a huge chunk of the reoccurring support issues.

**Comment by mariohock** [comment]
@basisbit I agree, installing STUN and TURN by default would help, already. Of course, this only works if the server is publicly accessible (not behind NAT or restrictive firewall). But for servers this is a valid use case (I would even argue: the default use case). So let's stay in this use case for a minute:

If you actually have a publicly accessible server there should be no need for STUN and TURN, at all. For Jitsi, this is a different thing, since Jitsi usually sets up peer-to-peer connections. But BBB is always client-server.

What's not fixed in the setup you propose is the 5s ICE timeout that happens when a client has "non-usable candidate addresses" (e.g., is connected over LAN and Wifi at the same time).

Both situations would be resolved if the connection procedure would be reworked so that the client connects to the server, not the other way round (as it is at the moment). But, as mentioned above, this seems to be a lot of work.

**Comment by prlanzarin** [comment]
>  What's not fixed in the setup you propose is the 5s ICE timeout that happens when a client has "non-usable candidate addresses" (e.g., is connected over LAN and Wifi at the same time). 
Both situations would be resolved if the connection procedure would be reworked so that the client connects to the server, not the other way round (as it is at the moment). But, as mentioned above, this seems to be a lot of work.

The connection establishment process is bidirectional by all means, so swapping controlling agent roles may improve this but it won't fix our inherent timing problem which is brought up by **not** trickling ICE.

FreeSWITCH does not trickle, SIP.js does not trickle, so we can't trickle nor half trickle. So clients with nifs enough ends with increased negotiation times because the gathering process turns itself into a gamble.

Fixing this requires adding support in **both** ends, client and server, to accept at least half trickling (ie freeswitch doing a vanilla gathering, because it's a server and its network config is predictable, and the client trickling its candidates).
Once the thing is trickled, prflx candidates are found faster. Everything is faster.

Trickling right now implies either implementing trickle in FS and SIP.js or finding another media server that does it and swap it in. You can imagine that this is a cumbersome endeavor. But don't get me wrong: the thing that would make me the most happy about BBB is managing to trickle audio, so I sure hope we end up shipping it somehow, someday.

I do believe discussion about connection times, trickle and whatnots is not what this issue is about, though. This is better suited in the other issue you've been commenting in (and that I still haven't had the time to look at your detailed analysis, sorry; but I'll sure do by the end of the week @mariohock).

**Comment by mariohock** [comment]
Sorry for mixing up these two issues. But can you explain one thing to me: If the server is reachable under a known fixed address (which has to be the case for what @basisbit suggests), why can't the client just send a "client hello" directly to this address to establish the connection? No STUN, no ICE, no trickling, no TURN.

There could even be fixed UDP-Port on the server side (only client side random), this way one could easily setup port-forwarding/open up _one_ port on the firewall, if the server actually is behind a NAT/firewall.

Maybe this is just not how FreeSwitch works. In this case I'm sorry for bringing this up. And please do not get me wrong, I really love what you're doing here and I honestly didn't mean "seems to be a lot of work" in any way offensive. I'm just fighting for our university not to ditch BBB in favor for zoom, that's why I'm so eager to get this whole connection setup thing fixed.

**Comment by basisbit** [comment]
> why can't the client just send a "client hello" directly to this address to establish the connection? No STUN, no ICE, no trickling, no TURN.
Because we want to use "standard"/existing software like freeswitch and kurento and also use UDP for better quality + timing.

The main use case for needing turn server is that your users can't use outbound udp. That won't be fixed by knowing the servers IPv4/v6 address.

**Comment by MariusE** [comment]
> An actual solution to this problem here would be to go the same route like Jitsi did go early this year: have the install script also install stun + turn on the bbb server - this will require Ubuntu 18.04 (because of coturn of Ubuntu 16.04 being utterly broken/buggy) and thus should be implemented in 2.3.x.
> Imho, no time on this issue should be wasted on a temporary hack like using google stun for 2.3, because that would just slow down development of bbb 2.3 and probably cause a media outcry in Europe again when people just apt install update and suddenly without the admins knowing, they violate GDPR, CCPA and LGPD by using Google STUN servers without having this mentioned in their data protection statement.
> 
> For bbb 2.2: please change the bbb documentation to suggest turn+stun server configuration and configuration of it in various bbb configs just as done on test.bigbluebutton.org, as that seems to work well for most cases.
> 
> This change would instantly resolve and reduce a huge chunk of the reoccurring support issues.

I agree with every point here!  
this approach would provide a suitable solution for all acute Problems in this context. :)

**Comment by iam-TJ** [comment]
What kind of load does/would a globally available TURN/COTURN server need to support?

I'm wondering if we could sponsor the infrastructure for BBB to provide its own service, thus being able to ensure quality of service AND privacy for the default installation.

**Comment by basisbit** [comment]
@iam-TJ such a service would be a data privacy nightmare as well as a quality of service nightmare and would cause many people to not use bbb servers any more. For a proper solution please see https://github.com/bigbluebutton/bigbluebutton/issues/10764#issuecomment-724362897

**Comment by uka-support** [comment]
@iam-TJ @basisbit STUN might be doable with reduced logging, but TURN is a completely different category because of the potential for high traffic, right?

**Comment by basisbit** [comment]
@uka-support this is not just about logging + not storing private stuff on the server, but instead about legal requirements: In such a case every company that does business in EU and which provides a BBB service would have to do a legally binding contract with whoever operates that STUN / TURN service. The paperwork handing overhead as well as storing that paperwork and lawyer/consultants costs would require some money, and in the end you would actually not have solved the problem. Anyhow, whoever operates that TURN server would have access to not encrypted voice / video traffic of all those who use it, so please please stop posting anything more regarding this idea  it is off-topic anyways.

**Comment by uka-support** [comment]
@basisbit Thanks for the clarification. You're right.
