### ISSUE TITLE
Ublock Origin/Privacy Badger combo returns a 1004 error when accessing the echo test on bigbluebutton (BBB)

### ISSUE THREAD

**Issue by lelibreauquotidien** [bigbluebutton/bigbluebutton#10777]
Hello.
The Ublock Origin/Privacy Badger combo returns a 1004 error when accessing the echo test on bigbluebutton (BBB).
I'm sure it's the fault of these 2 extensions, all my other extensions were disabled.
Deactivating one but leaving the other activated doesn't change anything.
I would like to specify that disabling tracing in the extensions menu is not enough, you have to disable the extension to have an effect.
My OS is Manjaro Linux and my browser is Firefox 82.0.2.
Also published on [Privacy Badger Repo](https://github.com/EFForg/privacybadger/issues/2711) and [Ublock Origin Repo](https://github.com/uBlockOrigin/uBlock-issues/issues/1327)

**Comment by matiasilva** [comment]
Hi, I'm not sure this is a bug really. This has popped up before but like the people in the issues you linked above have said, those configs stop video conferencing services from working...

**Comment by ghostwords** [comment]
Privacy Badger sets WebRTC IP handling policy to [Mode 3](https://tools.ietf.org/id/draft-ietf-rtcweb-ip-handling-12.html#rfc.section.5.2) when WebRTC local IP protection is enabled. This doesn't break all video conferencing apps, just some. This makes me think that you may be able to handle this scenario. As in instead of everything being broken, your app works but with reduced performance or perhaps functionality.

**Comment by prlanzarin** [comment]
As far as I know, BigBlueButton works with both Privacy Badger's and uBlock's WebRTC local IP handling policies activated, concurrently or not, when the server is properly setup. I use both of those options **on**, daily, always.

The only reason why it'd churn out a 1004 is if your server has a non functional STUN/TURN configuration pair (ie no STUN nor TURN at all, both of them faulty, just one of them but it's faulty, ...). What this will cause is a SDP being sent with **no** candidates, which generates a 1004. Since audio in BBB does not trickle and mDNS candidates are filtered client-side, it fails without even trying to generate prflx candidates (which would be the last resort).

So I'd consider this a setup matter, not an actual issue.

If you want to confirm what I'm saying, test.bigbluebutton.org is your friend.

**Comment by ghostwords** [comment]
So then is this a setup bug with the "echo test on bigbluebutton", as per the original reporter?

**Comment by prlanzarin** [comment]
> So then is this a setup bug with the "echo test on bigbluebutton", as per the original reporter?

I'd consider this a _setup_ _issue_ with the reporter's BigBlueButton _server_. Nothing to do with BBB, Privacy Badger and/or uBlock _code_.

@lelibreauquotidien has to try and reproduce the issue in test.bigbluebutton.org. If it isn't reproducible there, then we're 100% sure this isn't an actual issue (and help to properly configure a BBB server is usually given in one of the mailing lists, bigbluebutton-setup)

**Comment by ghostwords** [comment]
OK, got it, thank you!

**Comment by lelibreauquotidien** [comment]
Hello !
Solved by disabling webrtc filtering options in ublock origin and privacy badger.
