### ISSUE TITLE
Waiting room: communication option

### ISSUE THREAD

**Issue by iznakurnozh** [bigbluebutton/bigbluebutton#10789]
label:"User Interface (UI)"
label:"User Experience (UX)"

**Is your feature request related to a problem? Please describe.**
related to  #10786

Some moderators who uses BBB romms for appointments would like to let people in the waiting room know how long would it take until the next turn. 

**Describe the solution you'd like**
A chat option in the waiting room or an input field option of approx. time people have to wait would be helpful.

**Comment by franzgratzer** [comment]
In our experience this would be an ideal option contact waiting people. (We had people calling our office because of delays. They thought there was a technical problem for them and that they should already be in the room.) In addition it would be great to have the ability to style this page more appealing than just having a single line of text on a blank white page.
