### ISSUE TITLE
how to edit mongodb ip

### ISSUE THREAD

**Issue by liuhetongzi** [bigbluebutton/bigbluebutton#10809]
My bbb version is 2.2.23。I want to edit mongodb ip，I don't what to use the local mongodb, where is the config file，I can not find it。Please help me。Thanks..

**Comment by basisbit** [comment]
For support requests, please use the [forum / mailing list](https://groups.google.com/forum/#!forum/bigbluebutton-setup). This issue tracker here is only for BBB development related issues. Sorry.

Also, please update your BigBlueButton version to the latest release because it contains a bunch of very critical security bugfixes which allow an attacker to get full access to your server. As a service operator, you should try to always run current versions of your software for security reasons.
