### ISSUE TITLE
Note Cookie cant be placed 

### ISSUE THREAD

**Issue by hahaxd35** [bigbluebutton/bigbluebutton#10821]
**Describe the bug**
We are running BBB on multible Domains. By some users apears this error. How can we remove this error? 
BBB is working on multible domains but in newer Vrsion this error comes.

To not confuse customer it would be better to hide the Errors in UI.

reportErrorsInUI | false is default 

**Expected behavior**
maybe some changes in configuratioon needed to place cookie from comming domain? 

**Actual behavior**
cookie set is 

**Screenshots**
![bbb-cookie-fehler](https://user-images.githubusercontent.com/48324739/99061262-9550e080-25a1-11eb-92a7-3232f9e0a282.png)

**BBB version (optional):**
$ bbb-conf --check | grep BigBlueButton
BigBlueButton Server 2.2.29 (2244)

**Desktop (please complete the following information):**
 - OS: [Windows]
 - Browser [Firefox]

**Comment by hahaxd35** [comment]
i thought this issue wsa only a temporay error but user get this error often mybe note problem?

**Comment by basisbit** [comment]
@hahaxd35 BigBlueButton uses etherpad for the shared notes. There seems to be something wrong with your etherpad installation. Could you please check your etherpad/nginx logs to figure out what caused this problem?

**Comment by basisbit** [comment]
might be related to https://github.com/ether/etherpad-lite/issues/3405

**Comment by pedrobmarin** [comment]
I had some experiences with people having this issue because of proxies dropping connection headers so you might need to verify if your Etherpad's cookies are being set as secure (**express_sid**). Last time I checked express.js was only able to set it's cookie as secure if it was possible to read the connection header.

If that's the case, I would say the first alternative should be trying to fix your proxy configuration as @basisbit suggested. If that's impossible right now you can:
 - set Etherpad to use `Lax` instead of `None` as `SameSite` policy by disabling `forceSameSiteNone` at `/usr/share/etherpad-lite/settings.json`; or
 - use nginx to set `proxy_cookie_path / "/; secure; HttpOnly; SameSite=none"` to override the cookie policy
