### ISSUE TITLE
Persian translation mistake in poll result

### ISSUE THREAD

**Issue by mhajim** [bigbluebutton/bigbluebutton#10842]
Hi,
1. Start a room.
2. add a poll and Select an option "Yes/No" to start your poll.
3. Ask attender to change its language to Persian and  select "بله" (in Persian means Yes) as vote
4. Publish a pooling result.
5. You see the result shows No as a vote. It should be Yes. 
It means that in 'pooling result' translation label for Persian should (yes/no) be correct!
Yes=بله
No=خیر

 sudo bbb-conf --check | grep BigBlueButton
BigBlueButton Server 2.2.23 (2106)

**Comment by basisbit** [comment]
Please test this again after updating your bbb server to a current version. If I remember correctly, this problem was already fixed (or at least there exists an issue for that already here in the issue tracker). I'll close this issue for now. If you still encounter this problem even after updating to the newest bbb version and also can't find the other similar duplicate issue, please write a comment here and we will reopen this issue.

Also, you are using an insecure old bbb version, in the future, please make sure you install BigBlueButton updates which contain very critical security updates within a short timeframe after release to protect your users privacy.

**Comment by mhajim** [comment]
I update to BigBlueButton Server 2.2.29 (2244) but still have a problem!

**Comment by mjdtjm** [comment]
I confirm the same bug in Persian translation.

**Comment by GhaziTriki** [comment]
Dear @mhajim, can you please submit your updates to the transifex project https://www.transifex.com/bigbluebutton/bigbluebutton-v22-html5-client/ ?
Then once done plese confirm us and we will pull the updates.

Thanks

**Comment by mhajim** [comment]
Ok. TNX but I checked the translation ... it seems that translation is OK!. One of my friend told me the same problem for custom poll.(poll result shows correct for moderator but vice versa for other attender!!) 
Isn't it a logical bug in pool code?!

TNX,

**Comment by antobinary** [comment]
If there are other issues in the translation please open an issue (or have the string in Transifex reviewed)
