### ISSUE TITLE
Improve installation process for BigBlueButton

### ISSUE THREAD

**Issue by quantenschaum** [bigbluebutton/bigbluebutton#10875]
**Describe the bug**
Following the [official install guide](https://docs.bigbluebutton.org/2.2/install.html) is a PITA (sorry to say) and does not work.

**Installation type**
Neither the manual nor the provided script way works.

**Additional context**
- https://github.com/bigbluebutton/bbb-install/issues/298
- The guide is overly complicated and lengthy. It lists many instruction about what to do. If you list instructions in prose, you could write them as code and then simply execute them. No need to read several pages of instruction, that need to be executed manually which is super error prone. - Yes, there is the installer script, but it does not work.
- Why is this tied to Ubuntu (Xenial)?
- It would be an immense help if you provided prebuilt docker images on the docker hub and a `docker-compose.yml` (with `.env` file). Users could simply download the `docker-compose.yml`, edit the `.env` and do `docker-compose up`. That's it! Up and running. (https://github.com/jitsi/docker-jitsi-meet)

**Comment by hostbbb** [comment]
A fresh 16.04 that meets minimum specs, and the single bbb-install command works... 15minutes or your money back.

If you have issues... run the script and post your issues in google group. (bigluebutton-setup) there are a bunch of people that will gladly assist in helping you get it installed.

And if there is an error in install docs, help up improve with specific

This is a complex video conferencing platform.   So you will need to invest time.

**Comment by uka-support** [comment]
@quantenschaum freel free to create such a docker image. 

Please also have a look at the [installation documentation of the docker-jitsi-meet project](https://jitsi.github.io/handbook/docs/devops-guide/devops-guide-docker) - that's pretty far from "sers could simply download the `docker-compose.yml,` edit the `.env` and do `docker-compose up`." There's a lot to be done afterwards to get a useable system.

If you need any help, please refer to the [getting help section ](https://docs.bigbluebutton.org/2.2/getting-help.html#help-installing-or-running-bigbluebutton )of the documentation.

**Comment by prlanzarin** [comment]
[By the way.](https://github.com/alangecker/bigbluebutton-docker)

**Comment by quantenschaum** [comment]
Well, yes and no. The installer may work if certain conditions are fulfilled (certains commands/utils available). It checks for some packages and installs them if required, but not all (`sudo` for instance).  The installer does not stop if a command is not found, even though there is `#!/bin/bash -ex` in the shebang. Why? Because you write in the readme `wget -qO- https://... | bash ...`. Piping into bash does not read the shebang. So what I get is https://github.com/bigbluebutton/bbb-install/issues/298

Of course this is a complex system and this is where docker comes into play. It's superb for hiding this complexity away using prebuilt and correctly setup images. 

This is what the Jitsi folks did. Following the Jitsi docker guide, which is relatively short, all it takes to get a Jitsi instance up (the TL;DR version so to say, this is what the quick start guide says) is

```
git clone https://github.com/jitsi/docker-jitsi-meet.git
cd docker-jitsi-meet/
cp env.example .env && ./gen-passwords.sh
docker-compose up
```

Then you can start fine tuning, customizing, changing the config and read all the details in the docs. And many options can be set in the `.env`, which is pretty self explaining due to the comments.

So, the point of this (rather unpleasant, I know) issue is, that the installation procedure and the docs could use some simplicity and user friendliness.

(Another example of a pretty complex system that is very easy to install using docker is GitLab, thanks to the provided docker images und [instructions](https://docs.gitlab.com/omnibus/docker/). Essentially it's a one-liner.)

**Comment by basisbit** [comment]
I'd suggest closing this issue. Reasons:
- Any further discussion here will not actually result in improvements, but instead only waste developers free time.
- There already exist various issues or open tasks for improving the packaging and build system, for publishing the build instructions.
- The bbb 2.3.x branch already supports more current ubuntu.
- Only supporting Ubuntu was a design decision to reduce maintenance overhead with all the various dependencies and their dependency-worlds.
- Issues for improving the documentation should go to the [docs repo](https://github.com/bigbluebutton/bigbluebutton.github.io) where you can also participate if you have some spare free time.
- There already exists work-in-progress to dockerize bbb as you can see in various other issues and in the [bbb-docker repo](https://github.com/bigbluebutton/docker).
- For such generic discussions, please use the bbb-dev [mailing list](https://groups.google.com/g/bigbluebutton-dev)

**Comment by MagicFab** [comment]
This issue is very useful, I found it quickly and now I know the developers don't care about ease of installation.
I was looking for a way to contribute to the installation docs as there are even typos but ended up here.
Going forward, perhaps some project contributors could take this opportunity to link other install and configuration issues to this one and make it clear how other people that care can contribute (specially when they take the time to report in detail).

**Comment by basisbit** [comment]
@MagicFab please read my comment above. It mentions and links to the git repository containing the bbb documentation. The BBB community welcomes any improvements. However, an issue which just says `Installation=PITA` does not help in solving any of the mentioned problems.

For some guideline on how to get started with contributing to BigBlueButton, please see https://docs.bigbluebutton.org/support/faq.html#how-can-i-contribute
The TLDR is: The code, documentation, bbb-install script and similar stuff all can be found at https://github.com/bigbluebutton/ and as usual for most community driven free/libre open source software projects, anyone may create pull requests to suggest changes (improvements or bug fixes) and then whenever a main contributor has some spare free time, they might work on answering issue reports, checking+reviewing+testing pull requests, fixing bugs, and so on. For some of those code repositories, signing a contributor license agreement might be needed for legal reasons.

**Comment by MagicFab** [comment]
@basisbit thanks for your quick reply. I read your post just before, that's why I am here. 

I wish all that was in the documentation and I'd normally file a report and fix it... Do you see the problem ? That's why we're all wasting time here. Even contributing to BBB = PITA, unusual even in commercially driven Free software projects.

**Comment by ffdixon** [comment]
Hi everyone -- appreciate the feedback.  

I am project manager of BigBlueButton, the maintainer of the packaging, the author of [bbb-install.sh](https://github.com/bigbluebutton/bbb-install), and contributor to the documentation.  I've also worked on the docker images as well (it's still WIP).

You'll see some improvements coming in 20201 all areas you pointed out in future versions.  Right now, due to Covid-19 hitting us in March 2020, the majority of our resources went into improving the security, stability, and usability of the current 2.2 release through multiple and rapid iterations. 

Going forward, our strategy is to make BigBlueButton 2.2 as solid as possible, then move all our resources to [2.3-dev](https://docs.bigbluebutton.org/dev/dev23.html).  All the work we're doing in 2.2 is being ported to 2.3, and we're looking forward to getting a 2.3-alpha3 out soon.

We also welcome any pull requests on improving the documentation.

**Comment by matiasilva** [comment]
I agree with everything @basisbit has said. I do want to say that this project is something that many (hundreds!) people have contributed to and put their time and effort in and to call that a "pain in the asshole" is in quite poor taste. It's unfair to say that things don't work -- they do. That's why countless numbers of administrators have been running BigBlueButton successfully, especially over the past few months. Nobody really deploys BigBlueButton on each server manually, that's where the bbb-install and Ansible scripts come in. The points you've raised have been raised in this issue tracker and in the mailing lists countless times, and good answers have been given there, so give those a read if you're interested. I understand the motivation for this issue (complaining and ranting is always easier than taking action) but if we want anything good to come out of this, please propose some clear and actionable points so that even if you (or whoever else) can't, someone else can improve the installation experience and documentation. I think it's also unfair to carelessly say that people don't care about the ease of the installation process, people do! That's why this issue (and many other related ones) are getting attention.

**Comment by MagicFab** [comment]
Thank you @ffdixon, I'll be following progress in 2.3 for sure.
@matiasilva PITA is not literal, it's an expression for something that's very annoying - so I agree, it has not place in a report, sorry for that. I can't rename the subject though.
