### ISSUE TITLE
Make playback URL PRIVATE!

### ISSUE THREAD

**Issue by HomayGH** [bigbluebutton/bigbluebutton#10895]
Playback URL is public, if one shares it, others can see the recording. The suggestion is to make a hash in requesting server and check the validity on BBB server. I, myself, made a cookie (named "rid"=recordingid) on requesting server (TOP Domain) and check its validity with javascript in playback.html. however this method is not perfect.
`var c=document.cookie.match('(^|;)\\s*rid\\s*=\\s*([^;]+)');
if(c==null || c[2]!= window.location.href.substr(-54)) {window.location.href="https://example.com";}`

**Comment by aguerson** [comment]
Better than https://github.com/ichdasich/bbb-rec-perm ?

**Comment by HomayGH** [comment]
> Better than https://github.com/ichdasich/bbb-rec-perm ?

Absolutely not, Server side authentication (Python) is much better than client side (Javascript). but I am using Moodle, not Greenlight. I also added this line to moodle bbb_view.php: `setcookie("rid",,$rid);`

**Comment by aguerson** [comment]
Maybe I am wrong ( because I do not use yet bbb-rec-perm ), but it based on a scalelite infra. In my case I have Moodle too.
I have a scalelite in front of greenlight and an other one in front of Moodle. So I have two different backend ( postgre ) to each one. I could try to adapt the code. In the two case, I use a SSO with the same login. I think I could find an issue to adapt bbb-rec-perm to Moodle if necessary.
I will update this PR ;)

**Comment by ichdasich** [comment]
Added a ticket for this to bbb-rec-perm; Might be better to move the implementation discussion there. :-)
