### ISSUE TITLE
Preventing prevoius session recording processing while new meeting is started

### ISSUE THREAD

**Issue by HomayGH** [bigbluebutton/bigbluebutton#10894]
Building a recording uses too much CPU (for us about 50% on a 4core 2GHz CPU). at this moment starting a new meeting cause noisy voice and participants can not understand the lecturer voice. The suggestion is to execute `kill -STOP pid` when a new meeting is starting and previous recording is in process, and while the session is finished again execute `kill -CONT pid` automatically.

**Comment by manishkatyan** [comment]
You can change the timing for processing by stopping recordings process before beginning of classes and restarting it after ending of classes.

Add the following cron jobs on your BBB server. Choose time as appropriate in your case. 

`crontab -e

# Add the following entries
# Stop recording at 7 AM during week days
0 7 * * 1-5 systemctl stop bbb-rap-process-worker.service bbb-record-core.timer
# Start recording at 6 PM during week days; bbb-record-core will automatically launch all workers required for processing
0 18 * * 1-5 systemctl start bbb-record-core.timer`

**Comment by basisbit** [comment]
@manishkatyan thank you for posting a good solution for this problem! An alternative solution would be to get more CPU cores for the BigBlueButton server. The [suggested minimum](https://docs.bigbluebutton.org/2.2/install.html#minimum-server-requirements) for a BBB server is 8 cores (or 6 cores if you don't use the recording feature, because processing recording will use two threads by default).

On a typical BBB server, there will always be a couple of meetings in progress except for during night time. Thus, the server operator has to decide to either allow processing while other meetings are happening or only during typical server-low load hours. I think that this issue thus can be closed as there is nothing else to do, except for maybe adding the recording processing timer instructions to the [documentation](https://github.com/bigbluebutton/bigbluebutton.github.io).
