### ISSUE TITLE
WebSocket closed unexpectedly

### ISSUE THREAD

**Issue by reweb87** [bigbluebutton/bigbluebutton#10985]
**Describe the bug**
In our office we're behind a proxy and restrictive firewall. The BigBlueButton server is outside of our network and is not behind a NAT. We installed a TURN server to allow users to connect to BigBlueButton from inside and outside.

Everything work fine for users outside of our network. Users inside our network get the following console message exactly after 30 minutes: _**WebSocket closed unexpectedly sip.js:9598:25**_

If the user is successfully reconnected, everything's just fine. If the reconnection failed, the audio connection is terminated and the user has to restart the browser.

**Screenshots**

![bbb](https://user-images.githubusercontent.com/5424487/101371167-b9ef5e00-38aa-11eb-823c-122a0acf7810.PNG)

![bbb1](https://user-images.githubusercontent.com/5424487/101371193-bf4ca880-38aa-11eb-8ec8-a6d137b9ecf6.PNG)

![bbb3](https://user-images.githubusercontent.com/5424487/101371200-c2e02f80-38aa-11eb-95af-68155cccb5fb.PNG)

**BBB version:**
BigBlueButton Server 2.2.30 (2264)

**Desktop:**
 - OS: Windows
 - Browser: Firefox
 - Version: 78.5.0esr

**Additional context**
What can we do to ensure that BigBlueButton is working stable for hours? Is it a problem with our server, with BigBlueButton or with the our proxy/firewall?

**Comment by mariogasparoni** [comment]
It is hard to say where connection is failing. But i would take a closer look on firewall. Audio's websocket runs separately and firewall could treat it differently for some reason.

WebSocket's disconnection could be also happening due to inactivity (we only use it to start/stop audio session). If so, we could also add some sort of optional keepAlive in html5 (something we discussed internally a bit). I would like to reproduce it, does it happen when you access https://test.bigbluebutton.org or https://demo.bigbluebutton.org ? (from your restrictive network)

**Comment by reweb87** [comment]
Thanks for your quick response and support!

I can reproduce this issue on https://test.bigbluebutton.org as well. WebSocket connection is closed every exact 30 minutes. Sometimes the reconnect works, sometimes it doesn't. If reconnecting failed, the the camera and presentation continues to work, only the audio connection is lost. Most of the time the user has to restart the entire browser, otherwise no new WebSocket connections can be established.

bbb-webrtc-sfu-WebSocket is not interrupted, just the "normal" ws-WebSocket.

Is there a workaround for this?

**Comment by mariogasparoni** [comment]
No problem.
I noticed this happens on my FF, also. Websocket gets disconnected (and reconnect) every 10 minutes.
I tested a keep alive on websocket, to avoid connection dropping due to inactivity. Seems to be working.
Would you like to test it on my server to see if this works for you also ?

If so, email me: mariogasparoni at gmail

Thanks in advance.

**Comment by reweb87** [comment]
I tested it on our server and everything worked fine. No more disconnections. Many Thanks!
