### ISSUE TITLE
bbb-conf --secret is always printing out the same secret

### ISSUE THREAD

**Issue by zem** [bigbluebutton/bigbluebutton#11002]
bbb-conf --secret is always printing out the same secret this essentially means that I can connect one application, or the secret is no longer a secret. 

In other words: 

If two organizations share one bbb instance, both may want their own greenlight/nextcloud/moodle applications. All of those applications share the same token, which makes it very difficult to handle situations like: 

One Org has lost its token.
One Org leaves. 

**It should be possible to create multiple application specific tokens one for each application connected so that access can be controlled properly.**

**Comment by ffdixon** [comment]
At the oment, BigBlueButton does not implement a multi-tenant solution with multiple shared secrets for accounts.

**Comment by erisd** [comment]
we build a scalelite replacement with that feature - when its well tested, i can inform you...

**Comment by basisbit** [comment]
we (senfcall) also started writing a bbb API proxy for multitenancy and data privacy. Maybe we could work together on that or share results?

**Comment by zem** [comment]
I am glad to hear about any updates! I can also do some testing on my own if i get some hints how to install the code. :)

**Comment by basisbit** [comment]
In my opinion multi-tenancy should be implemented using some frontend or "middle man"/adapter which handles it transparently, so that the BBB API does not have to be adjusted and no additional complexity is introduced into BBB. It would be nice to see BBB as a kind of self-contained system which does not have to handle all the complex details of such specific requirements.
Maybe the bbb development mailing list would be a better place to discuss any details of a multi-tenancy-adapter for BBB?

**Comment by ffdixon** [comment]
This is better implemented in a front-end, not in BigBlueButton itself.
