### ISSUE TITLE
bbb2.3-dev Installation failed 

### ISSUE THREAD

**Issue by Bharat-vyas** [bigbluebutton/bigbluebutton#11016]
**Describe the bug**
We are using bbb2.3-dev version, which was installed properly some days before, but recently we have tried to install bbb2.3-dev version and now it is throwing us error in certbot SSL creation step.
For confirmation we have tried to install it in different cloud providers with different domain names (For SSL) but we have encountered the same error for all the servers.

**Installation type**
We are using "bbb-install" script for installation

**Firewall and IP address type**
For installation purposes we have allowed all ports from everywhere as well as no NAT has been used so far.

**Console output**
We have attached full Installations logs for reference.

**Additional context**
We were using the same command "bbb-install script" to set up bbb 10 days before which was working as expected.

[bbb01_installation_errors.log](https://github.com/bigbluebutton/bigbluebutton/files/5688053/bbb01_installation_errors.log)

**Comment by TrovisTV** [comment]
I think I had the same problem as you, and this is what I did to fix it.

After running bbb-install script and after it throws an error, edit **/etc/nginx/sites-available/bigbluebutton** and change **server_name** to your domain instead of local ip.

This will fix the SSL error.

In your installation log I saw another error and to fix it you need to install bundler.
Go to this location **/usr/local/bigbluebutton/core/** and run this command:

 **gem install bundler -v "$(grep -A 1 "BUNDLED WITH" Gemfile.lock | tail -n 1)"**
This will install bundler version which is defined in Gemfile.lock from location above.
(command is from this source: https://bundler.io/blog/2019/05/14/solutions-for-cant-find-gem-bundler-with-executable-bundle.html )


Now you can run bbb-install script again and hopefully without any errors.

**Comment by Bharat-vyas** [comment]
Thanks...It worked.

But do we have to execute these steps every time while installing bbb, as earlier we were installing 2.3-dev version and it was working fine without any additional steps (gem installation or nginx configuration file changes).
Is there any kind of recent changes in bbb-2.3 which are causing these issues ?

**Comment by nderambure** [comment]
Same problem here, from the last 2.3-dev from today, installing via the [automated install script](https://github.com/bigbluebutton/bbb-install).
After the install script failed with first error regarding ruby bundler version as described by @TrovisTV, I did the command he suggest to install bundler manually.
Then relaunched the bbb-install script again and everything seems OK.

Some warning to note (seems to be relative to the install script) : 

```
# Potential problems described below
dpkg-query: no packages found matching libreoffice
# Not running:  LibreOffice
..
# Warning: You have this server defined for https, but in
#
#   /etc/bigbluebutton/nginx/sip.nginx
#
#  did not find the use of https in definition for proxy_pass
#
#            proxy_pass http://135.181.143.55:5066;
#

# Warning: You have this server defined for https, but in
#
#   /etc/bigbluebutton/nginx/sip.nginx
#
#  did not find the use of port 7443 in definition for proxy_pass
#
#            proxy_pass http://135.181.143.55:5066;
```

**Comment by erichrueger** [comment]
I ran into the same problems during the installation. However, neither editing /etc/nginx/sites-available/bigbluebutton (my domain name had already been filled in) nor calling 'gem install bundler -v "$(grep -A 1 "BUNDLED WITH" Gemfile.lock | tail -n 1)"' made any difference. The process is interrupted and certbot fails. The subdomain ist definitely working. Can anybody help?

**Comment by antobinary** [comment]
Was this resolved in https://github.com/bigbluebutton/bbb-install/issues/319 ?

**Comment by erichrueger** [comment]
Yes, it worked for me.

Am Do., 20. Mai 2021 um 17:16 Uhr schrieb Anton Georgiev <
***@***.***>:
