### ISSUE TITLE
Error 1002 in Behind-Nat implementation on version 2.2.31

### ISSUE THREAD

**Issue by BenTornado** [bigbluebutton/bigbluebutton#11070]
First, thanks to the BigBlueButton wonderful team for developing such great product.

After the release of BBB 2.2.31, it is recommended in the [documentations](https://docs.bigbluebutton.org/2.2/install.html) to write a BASH script and change the **"ws-binding"** parameter to "%EXTERNAL IP%:5066" in "/opt/freeswitch/conf/sip_profiles/external.xml", however setting this in our behind-NAT server creates error 1002, and after comparing it to older versions I gathered that if I change both "ws-binding" and "wss-binding" to their respective ports ":5066" and ":7443", the problem would be solved.

Changing the https to http in "/etc/bigbluebutton/nginx/sip.nginx" and using HackViaWS is great yet changing the "ws-binding" might be problematic and somehow unnecessary. Just wanted to share this experience with you guys and ask for your comments.

Regards

**Comment by basisbit** [comment]
please see #9667

**Comment by BenTornado** [comment]
Dear basisbit, I reviewed thread #9667, and it wasn't relatable. Please read my issue again.

**Comment by ffdixon** [comment]
The 1002 error comes when FreeSWITCH is not accepting websocket connections.  That can occur when a firewall is blocking the attempt (in your case) or FreeSWITCH randomly (and rarely, but still a pain) stops accepting wss connections for a period of time (which is what #9667 refers to).  This is a bug in FreeSWITCH that we couldn't reliability reproduce, so it was stalking us for months.

The settings in `external.xml` tell FreeeSWITCH what external IPV4 address to listen for incoming connections.  If you server is behind NAT, then you need to use the external IP address of you firewall; otherwise, FreeSWITCH won't match any incoming web socket (WSS or WS) request on that IP address (and the BigBlueButton client will throw an 1002 error).

Before the hack, the client's WSS connection (coming from the external IP address of the firewall) was routed by nginx to FreeWITCH and matched on port 7443 for FreeSWITCH.  After the hack, nginx routed the incoming WSS connection as WS to FreeSWITCH, which matched on port 5066.  Nothing changed externally to the client -- it was still making an encrypted connection for the websocket connection, but we found that the WSS -> WS conversion on nginx no longer triggered the bug in FreeSWITCH.

While it is a hack, it solved the issue and made FreeSWITH, and thus BigBlueButton, more stable.

**Comment by BenTornado** [comment]
You're just brilliant Fred. Thanks for the thorough explanation and your devotion to bringing a great experience and also the incredible support which is just brilliant.
