### ISSUE TITLE
html5client not starting (Development environment)

### ISSUE THREAD

**Issue by anandsvg** [bigbluebutton/bigbluebutton#11079]
I have followed official documentation to setup bigbluebutton development environment but html5 client not starting , throwing following error. tried with  different server but same error. v2.2.31

` if (oldPresenter?.userId !== currentPresenterId) {
W20201227-04:07:46.391(0)? (STDERR)                      ^
W20201227-04:07:46.392(0)? (STDERR)
W20201227-04:07:46.392(0)? (STDERR) SyntaxError: Unexpected token .
W20201227-04:07:46.392(0)? (STDERR)     at createScript (vm.js:80:10)
W20201227-04:07:46.393(0)? (STDERR)     at Object.runInThisContext (vm.js:139:10)
W20201227-04:07:46.393(0)? (STDERR)     at /home/ubuntu/dev/bigbluebutton/bigbluebutton-html5/.meteor/local/build/programs/server/boot.js:393:30
W20201227-04:07:46.393(0)? (STDERR)     at Array.forEach (<anonymous>)
W20201227-04:07:46.394(0)? (STDERR)     at /home/ubuntu/dev/bigbluebutton/bigbluebutton-html5/.meteor/local/build/programs/server/boot.js:220:19
W20201227-04:07:46.394(0)? (STDERR)     at /home/ubuntu/dev/bigbluebutton/bigbluebutton-html5/.meteor/local/build/programs/server/boot.js:471:5
W20201227-04:07:46.394(0)? (STDERR)     at Function.run (/home/ubuntu/dev/bigbluebutton/bigbluebutton-html5/.meteor/local/build/programs/server/profile.js:510:12)
W20201227-04:07:46.395(0)? (STDERR)     at /home/ubuntu/dev/bigbluebutton/bigbluebutton-html5/.meteor/local/build/programs/server/boot.js:470:11
`
Exited with code: 1
=> Your application is crashing. Waiting for file change.

npm start failed . i didn't change any file

**Comment by rmallah** [comment]
```
-  if (auth?.connectionId !== connectionId) {
+  if ( auth && auth.connectionId !== connectionId) {

```

above kind of changes needs to be done in 
```
        modified:   imports/api/users/server/handlers/presenterAssigned.js
        modified:   imports/api/users/server/methods/userLeaving.js
        modified:   imports/startup/server/ClientConnections.js
```

**Comment by mesuttalebi** [comment]
will be any problem if Updating nodejs to its latest version?

**Comment by mesuttalebi** [comment]
I found that this problem is because we are in dev branch, checkout to 2.2.x-release branch and this errors disappear,

**Comment by mariogasparoni** [comment]
@anandsvg 
This happens when you are using old/different versions of needed dependencies.

I had the same problem when setting development environment for bigbbluetton 2.3-alpha+ versions (current develop branch). The problem happened because i mixed up 2.2 and 2.3 environments. 
To fix it,  i created a new fresh container (i use LXC), and followed the docs for [setting up development environment for 2.3](https://docs.bigbluebutton.org/dev/dev23.html#setup-development-environment)

Here are some basic instructions for setting up a development environment:

- For setting up a development environment for **2.2 release**, make sure you checkout your code to `v2.2.x-release` branch while following the [docs for 2.2-release ](https://docs.bigbluebutton.org/2.2/dev.html#setup-a-development-environment)


- For setting up a development environment for **2.3 version**, make sure you checkout your code to `develop` branch while following the [docs for 2.3-dev (currently alpha-7 version)](https://docs.bigbluebutton.org/2.2/dev.html#setup-a-development-environment)

**Comment by antobinary** [comment]
Thanks for the explanation and the suggested steps!
