### ISSUE TITLE
Handwriting on Virtual Whiteboard is Impaired by Palm and Finger Artifacts

### ISSUE THREAD

**Issue by steffen-moser** [bigbluebutton/bigbluebutton#11084]
**Describe the bug**
We use BigBlueButton's HTML5 client since its early beta stages in order to enable handwriting sessions on the virtual whiteboard (by providing empty or checkered slides), especially in mathematics and engineering subjects of our courses. Giving our students (most of them have tablet computers like iPads) the ability to do handwriting using their tablet computers remarkably improved the outcome in our distance-teaching courses. 

While this feature is widely accepted, the user experience is still impaired due to artifacts produced whenever a not-so-trained user touches the whiteboard with his or her palm. Of course, this more often happens to our students because most of our teachers know that they should not let their palms rest on the virtual whiteboard while writing or while explaining in writing breaks.
Almost all modern tablet computers and web browsers are able to distinguish between finger input, mouse input, and pencil input. Unfortunately, BigBlueButton does not seem to evaluate this piece of information. All kinds of pointer events are treated equally and can possibly produce annoying and unwanted drawings. 

It is not uncommon that untrained users try to remove the erroneously produced artifact by clicking the reverse arrow symbol. While doing so, they might also remove their intentionally written pieces - sometimes even worse: they might also press the trash bin symbol and delete everything...

Such a great feature (like a distributed virtual whiteboard) should not come with this kind of usability impairment.

**To Reproduce**
1. Start BigBlueButton's HTML5 client on a tablet computer, e.g. an iPad Pro
2. Open an empty slide
3. Activate the pencil function
4. Write to the virtual whiteboard by using, for example, an Apple Pencil 2. While doing so, let your palm or parts of your hand rest on the tablet.
5. Sooner or later you'll see artifacts produced by the pencil jumping to the position where your palm has touched the tablet, especially when lifting the pencil.

**Expected behavior**
When being in pencil mode and writing with a real pencil device, other inputs should be ignored, at least on a user's demand.

**Actual behavior**
All input devices contribute to the drawing/writing on the whiteboard, also unintentionally.

**Screenshots**
You'll find a screenshot attached.

**BBB version (optional):**
BigBlueButton Server 2.2.31 (2310)

**Tablet, desktop, or smartphone client (please complete the following information):**
 - Device: e.g. iPad Pro 11-inch, Model number: MTXN2FD/A
 - OS: e.g. Apple iPadOS 14.3
 - Browser: (Mobile) Safari
 - Version: 14.0.2

**Additional context**
I am fully aware that it is hard for BigBlueButton to decide upon itself and automatically which kinds of input devices should be ignored in which situation. For this reason, I would propose to make it possible that a user is able to toggle between two modes: a) accepting all kinds of pointer events and b) accepting only pencil events. 

A student of mine is working on a solution for his.

**Attachment**
![Screenshot_2020-12-28_11-53-33](https://user-images.githubusercontent.com/4097996/103209738-153dca80-4904-11eb-80ca-b8984113840b.png)

**Comment by ffdixon** [comment]
Hi Steffen,

Thanks for your feature request -- it was very well written.  We're know there are improvements we want to do to the pen and whiteboard.  At the moment we're focused on getting to a production release of 2.3, which does have some whiteboard improvements (but not in the area you described).

> A student of mine is working on a solution for his.

If your student can make headway, or needs any help, please have them post to bigbluebutton-dev, we're interested to work with them.

**Comment by jonathansch1** [comment]
Hi Fred,

Steffen already mentioned the basic concept of our solution. We want to add the functionality that a user is able to toggle between the modes: a) accepting all kinds of pointer events and b) accepting only pencil events.

Therefore I outlined the following steps:

* We have to add a new button to the whiteboard toolbar to switch between the palm rejection modes.
  * That button needs a new icon, that have to become integrated into the BBB Font.
    * We already designed an icon and can submit it to the BBB Font repository.
  * The button also needs a message, so we have to adapt the locales/en.

* The state of the palm rejection mode have to be saved.
  * The state is only needed in the session, so we can use the session storage.

* We need event handlers that can distinguish hand touch, pencil touch and mouse input.
  * The event handlers in use can't do that, so we have to add new ones. The new handlers are based on the existing event handlers and adapt them to use pointer events. Re-using the "old" handlers and adapting them have the benefit that we can replace them and there is no need to modify any interfaces.
  * The handlers are written to accept hand input only if palm rejection is disabled (finger touch input is allowed).
  * We need pointer event handlers only for *pencil-* and *shape-listener*

* Finally we have to add browser sniffing.
  * Most browsers can handle pointer events, but it's possible to use BBB with browsers that can't.
  * Due to browser sniffing BBB provides palm rejection only, if the browser has implemented pointer events.
  * If a browser hasn't implemented pointer events, there is a fallback to the existing event handlers. And the button new button for palm rejection isn't visible.

**Known Issue:**

We already implemented these steps for BBB v2.2.x and so we could do a proof of concept and test that approach.

That was very successfully and that feature was tested on Windows, MacOS, Linux, iOS and Android. For the Browsers Chrome, Firefox, Edge, Opera, Yandex, Safari.

The tests were done by a test protocol. So we tried to cover the use cases manually.

There is only one issue in Windows with Firefox. It's necessary to set *dom.w3c_pointer_events.dispatch_by_pointer_messages = true* in the Firefox config. By default that parameter is *false*. That is a known bug in Firefox (https://bugzilla.mozilla.org/show_bug.cgi?id=1487509). If that isn't set *true* all touch events are handled as finger touch and so it isn't possible to write with a pencil, if palm rejection is enabled.

Actually we didn't fix that, because it is to Mozilla to fix that. But maybe we have to think about a solution (possibly another browser sniffing), because it isn't expectable that a normal user can change that parameter in the firefox config.
