### ISSUE TITLE
Publishing survey results when a presentation is hidden - 2.3 alpha4

### ISSUE THREAD

**Issue by Jossef-767** [bigbluebutton/bigbluebutton#11097]
Publishing a survey results on a presentation appears in a huge font size, and overlapping lines

1. Start a meeting with 1 student and 1 teacher
2. minimize  presentation on student
3. Start a poll and publish results 
4. on student maximize presentation
5.  this is what you get (tested on https://test23.bigbluebutton.org)
![image](https://user-images.githubusercontent.com/2356928/103419073-20118d00-4b9a-11eb-8b71-eabb076f539b.png)

**Expected behavior**
In publishing results on a presentation there are also other unsolved problems mainly in RTL languages.
  In fact, in my opinion, it is possible to give up publishing the results on the presentation And leave only on the chat.

**Comment by burakguder** [comment]
++ In addition

Version : 2.3a4
camera position fails after uploading survey results on whiteboard

I added a video to repeat the error
https://user-images.githubusercontent.com/560147/103531628-cc08f000-4e9a-11eb-9c9d-3fede9ddce1c.mp4

**Comment by burakguder** [comment]
I did another test. After conducting the survey, the page is broken when the camera location changes. You don't need to publish the survey. Just do the survey

**Comment by KDSBrowne** [comment]
An attempt to address this issue was made in https://github.com/bigbluebutton/bigbluebutton/pull/11098. As mentioned in that PR, we can not get the correct values for `keySizes`, `voteSizes`, and `percSizes` because `getBBox` always returns `0` when the element is not rendered. These values are needed to calculate the correct size for the poll annotation.

https://github.com/bigbluebutton/bigbluebutton/pull/11098 Tries to restore the presentation area when the polling options mount (if swapped). I think it creates a situation where even though the presentation was forced open, a user can simply minimize again before the poll is publish and the same problem will occur.

**Comment by antobinary** [comment]
There are three possible solutions that we see.
A ) force the display of the slide when a poll result is published (similar to `userdata-bbb_force_restore_presentation_on_new_events=true` ) -- I do not really like the idea of forcing the layout swap, especially since in some setups the presentation is hidden by default
B ) For users who have the presentation minimized, skip the publishing of poll results as an annotation on the slide. Only display the results on the public chat
C ) render annotations on server side, so if the user sees the presentation later on, it will have the annotation poll result included - this is a long term direction but we are not targeting 2.3

@KDSBrowne implemented B) in #11417
