### ISSUE TITLE
Color emoji is not converted from pptx

### ISSUE THREAD

**Issue by hiroshisuga** [bigbluebutton/bigbluebutton#11096]
**Describe the bug**
Color emoji is not correctly converted from a pptx file.

**To Reproduce**
1. Start a meeting
2. Upload a pptx presentation with color emojis.
3. Emojis do not show up

Used pptx file:
[emoji.pptx](https://github.com/bigbluebutton/bigbluebutton/files/5752874/emoji.pptx)

**Expected behavior**
Emojis show up.

**Actual behavior**
White rectangles (tofu) or monochrome emojis appear.

**Screenshots**
![名称未設定 1](https://user-images.githubusercontent.com/45039819/103327089-83b29200-4a96-11eb-8d90-e34db4c11c5a.jpg)

**Additional context**
Installing fonts-noto-color-emoji according to #11089 did not help. Likely a Libreoffice version problem.

**Comment by hiroshisuga** [comment]
This problem still persists on test24 server.

![1 0](https://user-images.githubusercontent.com/45039819/151683020-92802a03-f458-4d6d-a0c9-546ff2997595.jpg)

**Comment by hiroshisuga** [comment]
@antobinary , I will try to look more. I posted it quite a long time ago...

**Comment by gustavotrott** [comment]
Hello, it seems to be a known Libreoffice problem https://bugs.documentfoundation.org/show_bug.cgi?id=129523
I can reproduce a similar behavior, although for me the Emoijis are being removed instead of replaced by that wrong chars.

Using Libreoffice Desktop (on Ubuntu) I exported to PDF:
![image](https://user-images.githubusercontent.com/5660191/193058506-d46f60e5-b7d9-42ee-84ca-ec39db1501ff.png)

Result:
![image](https://user-images.githubusercontent.com/5660191/193061537-695578f2-fe8d-4799-a8b9-694ddc804523.png)

And in BBB I have the same result:
![image](https://user-images.githubusercontent.com/5660191/193061722-dadd2246-4323-41e7-a2cf-9baa03406fbb.png)

**Comment by gustavotrott** [comment]
It is also visible when exporting Shared Notes or moving it to Whiteboard:

![image](https://user-images.githubusercontent.com/5660191/193063143-f22bf47c-47c6-4730-b9c6-b81dedc18bef.png)

**Comment by gustavotrott** [comment]
Libreoffice will not release a fix in next days..
As a workaround, not perfect, but better than before:

We can remove the font `fonts-noto-color-emoji` that comes with Debian, and install this one as replacement https://github.com/adobe-fonts/noto-emoji-svg

```
sudo apt remove fonts-noto-color-emoji

wget https://github.com/adobe-fonts/noto-emoji-svg/releases/download/2.100/NotoColorEmoji-SVG.otf
wget https://github.com/adobe-fonts/noto-emoji-svg/releases/download/2.100/NotoEmoji.otf

sudo mv NotoColorEmoji-SVG.otf /usr/share/fonts/
sudo mv NotoEmoji.otf /usr/share/fonts/

fc-cache -v
```

Results after that:
![image](https://user-images.githubusercontent.com/5660191/193065495-25002d86-4a97-4e77-9dda-3e76ec20f1a6.png)

emoji.pptx:
![image](https://user-images.githubusercontent.com/5660191/193065633-245fba81-e235-41b4-9db2-159d783bc13f.png)

**Comment by gustavotrott** [comment]
Currently BBB is using `LibreOffice 7.3.7.2 30(Build:2)  (Alpine 3.17.2)`.
I did a test using `LibreOffice 7.5.1.1 50(Build:1) (Alpine 3.18_alpha20230208)`.
It seems to be a little better but doesn't solve the problem yet.

emoji.pptx:
![image](https://user-images.githubusercontent.com/5660191/220354669-09474c66-f7cd-405b-a1db-3076da922501.png)

`adobe-fonts/noto-emoji-svg` is still the best strategy to mitigate the issue so far.

**Comment by gustavotrott** [comment]
Further testing has revealed specifics about the issue at hand. The problem arises during the process of converting a PDF to a PNG image.

Here's a breakdown of the issue:

1. **Generation of PDF with LibreOffice:** The initial PDF is created using LibreOffice, where emojis are correctly displayed in color.

   ![PDF with colored emojis](https://github.com/bigbluebutton/bigbluebutton/assets/5660191/d835e51b-729e-447e-94e8-b9c406a7147c)

2. **Conversion of PDF to PNG with `pdftocairo`:** The problem occurs when the `pdftocairo` tool is used to convert the PDF into a PNG image. The command used is as follows:

`pdftocairo -r 300 -png -singlefile -scale-to-x 2048 -scale-to-y -1 -q -f 1 -l 1 /tmp/test.pdf /tmp/testc`

This command results in emojis being rendered in grayscale, not in color.

![PNG with grayscale emojis](https://github.com/bigbluebutton/bigbluebutton/assets/5660191/eb721031-6f8d-43f4-ae08-c74e2d036341)

3. **Testing Conversion with `pdftoppm`:** To isolate the issue, the same PDF file was converted using `pdftoppm` using the following command:

`pdftoppm -png /tmp/test.pdf /tmp/testp.png`

The `pdftoppm` tool successfully preserved the color of the emojis, confirming that the issue lies specifically with `pdftocairo`.

![PNG with colored emojis](https://github.com/bigbluebutton/bigbluebutton/assets/5660191/f3d7333d-c905-4fa0-8a63-66f335c5f0c5)

This detailed analysis indicates that the color loss issue during the conversion process is linked specifically to the use of `pdftocairo`. Alternative tools like `pdftoppm` do not exhibit this problem, suggesting an inherent issue with `pdftocairo`'s rendering.

**Comment by gustavotrott** [comment]
Further testing has revealed specifics about the issue at hand. The problem arises during the process of converting a PDF to a PNG image.

Here's a breakdown of the issue:

1. **Generation of PDF with LibreOffice:** The initial PDF is created using LibreOffice, where emojis are correctly displayed in color.

   ![PDF with colored emojis](https://github.com/bigbluebutton/bigbluebutton/assets/5660191/d835e51b-729e-447e-94e8-b9c406a7147c)

2. **Conversion of PDF to PNG with `pdftocairo`:** The problem occurs when the `pdftocairo` tool is used to convert the PDF into a PNG image. The command used is as follows:

`pdftocairo -r 300 -png -singlefile -scale-to-x 2048 -scale-to-y -1 -q -f 1 -l 1 /tmp/test.pdf /tmp/testc`

This command results in emojis being rendered in grayscale, not in color.

![PNG with grayscale emojis](https://github.com/bigbluebutton/bigbluebutton/assets/5660191/eb721031-6f8d-43f4-ae08-c74e2d036341)

3. **Testing Conversion with `pdftoppm`:** To isolate the issue, the same PDF file was converted using `pdftoppm` using the following command:

`pdftoppm -png /tmp/test.pdf /tmp/testp.png`

The `pdftoppm` tool successfully preserved the color of the emojis, confirming that the issue lies specifically with `pdftocairo`.

![PNG with colored emojis](https://github.com/bigbluebutton/bigbluebutton/assets/5660191/f3d7333d-c905-4fa0-8a63-66f335c5f0c5)

This detailed analysis indicates that the color loss issue during the conversion process is linked specifically to the use of `pdftocairo`. Alternative tools like `pdftoppm` do not exhibit this problem, suggesting an inherent issue with `pdftocairo`'s rendering.
