### ISSUE TITLE
Unable to share screen with one application only.

### ISSUE THREAD

**Issue by Gillian-Delvigne** [bigbluebutton/bigbluebutton#11109]
Hi everone,

I have a curious problem. 
In the context of training for an accounting software, our trainers have to use BigBlueButton (on Moodle) to train students on [this application](https://www.sage.com/fr-be/produits/sage-bob/).
However, it is not possible to share the screen with this application only. It displays a black screen when selected and the sharing does not start.
General screen sharing works fine and particular sharing with all other applications work as well. 
The problematic application works fine on other video conferencing systems. It can be shared singularly without any problem.
I don't know if the problem comes from the application in question, from BBB or from the hosting.

We tested on Chrome and Edge (last versions) on Windows 10. 

![image003](https://user-images.githubusercontent.com/46646593/103752996-c03c3b80-500a-11eb-9415-8f9625a7f33c.jpg)

Thank you for your help!

**Comment by ffdixon** [comment]
> However, it is not possible to share the screen with this application only. It displays a black screen when selected and the sharing does not start.

BigBlueButton asks the browser to share the screen using the browser's built-in WebRTC libraries.  The browser is doing the capture and transmit the screen.

We suspect that this application does something non-standard for writing into is window.  

You could try both FireFox and Chrome (and latest version of Edge) to see if there is any difference. If not, the sharing the window will depend on future updates to the application and/or the web browsers.

**Comment by basisbit** [comment]
Use [OBS](https://obsproject.com/) to try recording the application. Then in the record application settings, switch between BitBlt and Windows Graphics Capture as recording method. I'd bet that the application can not be recorded using Windows Graphics Capture because it returns a window size of 0x0 pixels to the webbrowser. This usually is caused by a bug in the drawing / UI library which the application (the one you want to record) uses. the Chromium project as well as Firefox could try to implement a workaround for this by detecting the 0x0 pixel window size and then falling back to using BitBlt instead.

This is neither a bug in BigBlueButton, nor something this project can fix or work around.
