### ISSUE TITLE
UI freeze on Android

### ISSUE THREAD

**Issue by siavash79** [bigbluebutton/bigbluebutton#11126]
**Describe the bug**
When using bbb on chrome on android, the client freezes when you click on the buttons

**To Reproduce**
1. Join a session on chrome on android
2. Click on (for example) camera button
3. You'll see that the UI is frozen
4. Go to recent apps and then return to chrome, everything starts working again

**BBB version (optional):**
BigBlueButton Server 2.2.31 (2307) installed using bbb_install

**Smartphone (please complete the following information):**
 - Device: Pixel 4 XL
 - OS: Android 11 RQ1A.201205.008
 - Browser Chrome
 - version 87.0.4280.101
 
**Additional context**
Apparently, (because it will restore correct behavior if you force it render again by switching out/in the app) it's the browser that freezes during the session. However, testing on a high end device and updated software, such behavior is not expected

**Comment by ffdixon** [comment]
Can you test against https://test.bigbluebutton.org/ and let us know if you get the same results.

**Comment by siavash79** [comment]
No I couldn't reproduce it on the test website (I tested it for about 5
minutes)

Is it different from the latest stable version? How can I get it?

**Comment by basisbit** [comment]
The test server currently runs on bbb 2.2.31, so this problem is related to your setup. Could it be that your server was under high load when this problem happened? (NodeJS > 90% usage of one cpu core?). Anyways, for further support, please use the [forum / mailing list](https://groups.google.com/forum/#!forum/bigbluebutton-setup). This issue tracker here is only for BBB development related issues.
