### ISSUE TITLE
How to Install version bionic-230 alpha2 of BigBlueButton?

### ISSUE THREAD

**Issue by ehsangerayli** [bigbluebutton/bigbluebutton#11133]
I find the following script to install bbb 2.3

wget -qO- https://ubuntu.bigbluebutton.org/bbb-install.sh | bash -s -- -v bionic-230-dev -s bbb.example.com -e notice@example.com  -a -w

but this is just for version `bionic-230-dev` and I need to install version `2.3 Alpha 2`.
Where i can find the list of all available versions?

Thank you

**Comment by ffdixon** [comment]
We would recommend running 2.3-alpha4 as have been merging in all the updates from 2.2 during development, which includes a number of important security fixes.

**Comment by ehsangerayli** [comment]
Actually my problem is that we did a lot's of edits on version alpha 2 and now it's not compatible with alpha 4.
Now we want to create a pool of servers and just replace our customized HTML5 client there, but it's not possible with bbb-install.sh
Is there any way to achieve this ?

**Comment by ffdixon** [comment]
Sorry, but you have to update your edits for alpha4.  We know it's a pain, but 2.3-dev is under very active development and you'll want to keep pace with the latest builds to ensure you have all the security updates.

**Comment by basisbit** [comment]
Closing this issue because of not supported setup. Sorry. Please bear in mind that the alpha versions of BBB 2.3 should definitely not be used in production and if you still use it, we can't support that. The developers free time in most free/libre open source software projects is very limited, and there are a lot of important changes that lots of people wait for, so we can't support every corner case.
