### ISSUE TITLE
"Set explicitly Niceness and CPUSchedulingPolicy in /usr/lib/systemd/system/bbb-html5.service as discussed in #10739" is not compatible with LXC containers

### ISSUE THREAD

**Issue by InfoFractal** [bigbluebutton/bigbluebutton#11137]
After installing 2.2.31 in a LXC container, you have to edit bbb-html5.service and remove the cpu scheduling policy for it to start correctly.

**Comment by ffdixon** [comment]
Thanks for the report.  For now, we have this documented as a workaround

  https://docs.bigbluebutton.org/2.2/troubleshooting.html#bbb-html5-fails-to-start-with-a-setscheduler-error

**Comment by basisbit** [comment]
We strongly recommend running BigBlueButton on a bare metal system or a system with dedicated computing ressources. When using LXC or docker, you'll have to use features of those environments to achieve similar process prioritization or your system will not work well under higher load. It makes a huge difference and because the BBB deployment setup mostly targets bare metal setup, we ask you to follow the above linked workaround for systems which don't support such common systemd features.

I'll close this issue for now because it is not a problem of BigBlueButton itself, but instead rather the limitation of the environment which you chose to use. If anyone has a good suggestion for how to improve this, please create a pull request or post your suggested improvement here in this issue, then we will reopen the issue as enhancement type.
