### ISSUE TITLE
Memory utilization difference

### ISSUE THREAD

**Issue by myOmikron** [bigbluebutton/bigbluebutton#11152]
I am running a total of 6 BBB VMs Load balanced with a scalelite instance. 

**Describe the bug**
On some of the servers we have a high memory utilization (mostly cached) on others we haven't this utilization at all.

VM Specs:
24 Cores
42 GB RAM
120 GB SSD Storage
1TB SSD Storage for recordings

I'm running 2 VMs on each physical server.

**Screenshots**
High utilization
![image](https://user-images.githubusercontent.com/39948112/104605255-8ad4c500-567e-11eb-8960-4632882dad1d.png)

High utilization - 7 days
![image](https://user-images.githubusercontent.com/39948112/104606525-20bd1f80-5680-11eb-9569-37260aee2949.png)

Low utilization
![image](https://user-images.githubusercontent.com/39948112/104605916-64635980-567f-11eb-963e-6664db97c15d.png)

Low utilization - 7 days
![image](https://user-images.githubusercontent.com/39948112/104606392-fff4ca00-567f-11eb-96f4-f2671f6e973c.png)

**Comment by basisbit** [comment]
Please use your favorite search engine for reading basics of linux file access caching.
We recommend each VM of BBB should have 16 GB or RAM. For many use cases, 12 GB is also enough. Bear in mind that recording processing, amount of concurrent users, features the users use, and especially concurrent processing of uploaded presentation/ image files might take up more amounts of memory.
Cached memory if not `used up` memory, but instead the system only makes use of the otherwise not used memory by caching files that it did already read since last system boot.
