### ISSUE TITLE
Improvements for education

### ISSUE THREAD

**Issue by alombia** [bigbluebutton/bigbluebutton#11225]
I think BBB is an amazing piece of work. I use it to teach online due to school closures. I would like to make some suggestions which I believe will greatly enhance user experience, especially from an educator's perspective. 
1. There should be easier access to mute/unmute users. The current method of manage users and mute seems overly unnecessary. A dedicated button at the bottom of the user panel would suffice. This button should also prevent users from unmuting themselves unless instructor does so.
2. Currently the only way now to prevent users unmuting themselves is to lock users from sharing mic; however, this does not allow instructor to allow individuals to share mic
3. There should be a waiting room feature so that students cannot leave and join as they please. It makes the task of working out who is in the session or not difficult
4. There should be some attendance/register functionality which shows users present and most crucially, **amount of time spent in session**. As teachers we need tp take register. Current method of 'saving usernames' only shows names of users present at time of clicking 'save username' button. But it would greatly help if the information included all users present with join/exit times as well, most importantly, time spent. Teachers can use the time spent figure to determine if students really have been present.
5. Unlocking of the user panel during screen share to allow instructor to see attendees. When screen sharing and talking its not possible to know who is present or has left
6. Hover effect over names of users to see full name. Some students have very long names which is cut off. Only way to see full name is to click on user
7. Removed users should be moved to a 'Removed panel' where they can be re-instated. For teachers this is very useful to allow some time-out for misbehavior
8. Some way to get rid of the picture-in-picture problem when screen sharing. This may be avoided if point 5 is implemented

These are my observations from a teacher's perspective.

**Comment by basisbit** [comment]
Sorry, but this issue tracker here is only for issues directly related to BigBlueButton development, but not for collections of change requests or user discussions. Could you please instead use the [forum / mailing list](https://groups.google.com/forum/#!forum/bigbluebutton-users)? Also, regarding the waiting room feature: that is already supported for a long time - please ask your server administrator if they can improve the configuration.
Regarding point 4, this is already somewhat possible depending on which learning tool you use - please ask your BigBlueButton server admin/support for details.
Regarding point 2, you can unlock individual users and then they are able to use their microphone.
Regarding point 6, good suggestion, please create a new feature request - select the type "Feature request" and then please fill in the template instead of just deleting that.
Regarding point 7, you can already do that using the guest room feature - although this might need some discussion in the forum I mentioned above.

Regarding adding various new buttons: those would make it more difficult to use BigBlueButton on mobile devices /devices with small screens, and might also impact usability for impaired users.
