### ISSUE TITLE
Alerts allow locked users to obtain participant names

### ISSUE THREAD

**Issue by hex-m** [bigbluebutton/bigbluebutton#11252]
**Describe the bug**
In a meeting that was created with `lockSettingsHideUserList=true`  or where "See other viewers in the Users list" was locked manually, users can still enable "Audio Alerts for User Join" or "Popup Alerts for User Join" and get information about other users in the meeting.

**Expected behavior**
The setting should keep users from knowing who else is in the meeting. It should not be possible to get this information by activating alerts.

**BBB version (optional):**
BigBlueButton Server 2.2.31 (2307)

**Comment by antobinary** [comment]
Related to https://github.com/bigbluebutton/bigbluebutton/pull/7909#pullrequestreview-275665449

We only hide the userlist via that parameter and it does the job correctly. It does not prevent one user from 'obtaining' the names of other meeting participants who have willfully provided their names and are willfully participating in the audio (thus revealing their usernames). If you are looking for anonymizing the usernames of other participants, the current implementations (as of Jan 2021) are not enough. I have seen some meetings where users were joining with numbers instead of names, were not sharing webcams, etc. which may be enough for the job. I still do not understand why you would be trying to hide the identities of users engaged in a conversation but would still need them to type their real names to join...

I am closing this issue as the `lockSettingsHideUserList=true` parameter does its job correctly. If you are requesting support for full anonymity (if that is possible) in a meeting you would want to open a new issue, title it accordingly and go from there.

**Comment by hex-m** [comment]
Thanks for the clarification.

>participants who have willfully provided their names and are willfully participating in the audio (thus revealing their usernames)

A user reported this to me because it was unexpected to him. I understand why a user would assume that other attendees (of the university lecture in our case) would not know if he/she was in the room as long as he/she doesn't participate via chat, voice or video. But there is also a notification for "XXX joined the session".
