### ISSUE TITLE
Banning system is not good

### ISSUE THREAD

**Issue by MathisBurger** [bigbluebutton/bigbluebutton#11250]
If you are banned from a conference, you only have to delete an cookie to rejoin.
This is not a acceptable solution for banning other people, because it is easy to trick

**Comment by basisbit** [comment]
For more advanced "banning", you'll have to handle this in your frontend. Also, when creating issues, please fill in the issue template, so that you provide the minimal amount of information needed. Issues where users only "complain" without suggesting solutions get closed because developers can't really make any use of them.
