### ISSUE TITLE
Set number of bbb-html5 nodejs processes to 2

### ISSUE THREAD

**Issue by antobinary** [bigbluebutton/bigbluebutton#11288]
Enable 2 parallel  nodejs processes for `bbb-html5` by default (current default is 1)

@basisbit, @pedrobmarin or others please feel free to comment (if there are cases where this is undesirable)

**Comment by basisbit** [comment]
Could this be made dependent on CPU threads count? Maybe like this?
| CPU Thread Count | NodeJS process count |
|------------------|----------------------|
| <=4              | 1                    |
| 5-12             | 2                    |
| 13+              | 4                    |

Assumptions: 
- A system with many CPU threads is more likely to be rather slow in single-threading but also more likely to have enough RAM
- More than 4 NodeJS Threads would not help because of various other bottlenecks being hit already before that
- Setups on `small` systems should not eat up too much RAM
- NodeJS memory usage grows and shrinks depending on currently active users and events on the system
- Admins should still be able to overwrite this behaviour

**Comment by pedrobmarin** [comment]
Is this new configuration already in a public documentation?

I'm not a big fan of self-modifying configurations (if I understood correctly what @basisbit suggested). In my opinion these points he shared are important and should be part of performance improvement documentation.

Since bigbluebutton suggests as minimum requirement 8-core servers, makes sense to set the default as 2.

**Comment by basisbit** [comment]
(just my two cents)
Automatically choosing sane defaults depending on environment as "automatic mode" is a best practice to reduce support tickets and simplify installation. One of the problems of current setup of BBB is that there are so many adjustment that almost everyone who installs BBB on their server has to do. Good tools would try to automate as much as possible but still allow for manual override so people can fine-tune their setup.
New BBB admins usually aren't experts at BBB and thus usually don't know what settings fit well for their environment. Requiring every new admin to read and understand 30 pages of documentation does not work in the real world (see various complaints from users on social media, usually just being caused by not properly configured BBB setups).

**Comment by pedrobmarin** [comment]
For that I believe it would be better to have a `bbb-conf` routine to suggest/apply those kind of changes and new admins could do it in a single line of command. Regarding documentation, it isn't the case about if everyone will read or not. It's important to maintain the project.

**Comment by antobinary** [comment]
@basisbit Thanks for the suggestion!
Would it then make sense to also automatically decide on a threshold for `--max-old-space-size=` ( from #11183 ) (1.5M being the default if we don't override afaik)

```PORT=3000 /usr/share/$NODE_VERSION/bin/node --max-old-space-size=4096 --max_semi_space_size=128 main.js```

**Comment by basisbit** [comment]
(I'll reply in the other issue 11183 regarding the memory limit.)

**Comment by antobinary** [comment]
In https://github.com/bigbluebutton/bigbluebutton/pull/11439 I removed the apply-config procedure for setting the number of instances.
Also 2.3-alpha7 shipped with default configuration of 2 frontends and 2 backends, editable as described in https://github.com/bigbluebutton/bigbluebutton/pull/11439 I just wanted to have 'enabled' the multi-instance for both frontend and backend. This was to include and enable the work in #10349 and #11317

I have not yet heard any feedback on whether this setup is sufficient or not for most use cases or most configurations. 

Any discussion on the recommended numbers, or actual code which checks resources and calculates ideal counts, is still open.

**Comment by rasos** [comment]
I have set this new setting to 3 frontend and 3 backend instances on a mediocre machine with 8 cores and 32 GB RAM and it works fine. This should avoid in peak load situation that users are not able to join anymore or chat (which we have seen again today on a BBB 2.2 machine). Even when freeswitch usually consumes most CPU when serving many users (up to 400% in top), some context switching of freeswitch would not really harm the overall conference experience, compared to totally overbooked node processes.

**Comment by antobinary** [comment]
I have not heard of issues with the current defaults (2 frontends and 2 backends). I will be closing this issue but if it needs to be reopened later due to discussion forming up, we can certainly do that. Thanks everyone!
