### ISSUE TITLE
Warning if you forgot that your hand is raised

### ISSUE THREAD

**Issue by elvinceffm** [bigbluebutton/bigbluebutton#11296]
**Is your feature request related to a problem? Please describe.**
There is a feature if you want to signal participation to change your status to a raised hand. Oftentimes people forget to reset their status afterwards and then are asked to speak again.

**Describe the solution you'd like**
A reminder that your hand is raised atm.

**Describe alternatives you've considered**
A dedicated "raise-your-hand"-button that allows an easy reset of your status

**Additional context**
none

**Comment by robske110** [comment]
I think this issue is related to https://github.com/bigbluebutton/bigbluebutton/issues/9394
On another note, if anyone works on this: Making a hand raise more visible to the moderators would be greatly appreciated. It is at the moment very hard for them to notice a raised hand. A popup and a audio notification would be really nice to see. This is also described here https://github.com/bigbluebutton/bigbluebutton/issues/9396, but it appears no work has been done on that yet.

**Comment by PhMemmel** [comment]
Both audio and popup notification when users are raising their hands are already implemented in 2.3.
