### ISSUE TITLE
Conference link and other cannot be copied out of chat window

### ISSUE THREAD

**Issue by glxnet** [bigbluebutton/bigbluebutton#11409]
**Describe the bug**
It is not possible to copy text out of the welcome message in the public chat.

**To Reproduce**
1. Open/Enter a conference
2. Select the public chat
3. Try to copy any text from the welcome message

Note: the cursor image *does* change from the pointer to the insert bar.

The problem seems to stem from continuous events arriving at <div class="messageListWrapper...>

**Expected behavior**
Text can be selected and copied

**Actual behavior**
Text cannot be selected

**Screenshots**
-

**BBB version (optional):**
BigBlueButton Server 2.3.0-alpha6 (1573)

**Desktop (please complete the following information):**
 - OS: Debian GNU/Linux 10, XFCE4 Desktop
 - Browser Firefox (but also observed with Chrome)
 - Version 78.6.1esr (64-Bit)

**Smartphone (please complete the following information):**
-

**Additional context**

**Comment by daminebenq** [comment]
Hi @glxnet 
I don't think that this issue is still reproducible
to be able to copy and paste the invite link from public chat box, you should be first able to see it.
As Moderator, I tried it in demo server, and it worked as expected. I believe you're using an outdated bbb server.


https://user-images.githubusercontent.com/5144311/109532797-410e3580-7a98-11eb-9cf6-d56af9964e3f.mp4

**Comment by antobinary** [comment]
Thank you for reporting. I am also not able to reproduce on [what is going to be] 2.3-alpha8.
