### ISSUE TITLE
[2.3] setNumberOfHTML5Processes: command not found

### ISSUE THREAD

**Issue by lonesomewalker** [bigbluebutton/bigbluebutton#11479]
After upgrading we ran in the same issue as here: #11442 

When restarting BBB, we get an:
```/etc/bigbluebutton/bbb-conf/apply-config.sh: line 17: setNumberOfHTML5Processes: command not found```

Is this function deleted now?

**Comment by antobinary** [comment]
Hi @lonesomewalker 

Yes, I removed the function https://github.com/bigbluebutton/bigbluebutton/pull/11439 in 2.3-alpha7
I don't think it's coming back. Only people who has 2.3-alpha 5 or 6 on their server (and had enabled it in apply-config) would notice its absence

**Comment by lonesomewalker** [comment]
Any reason why?
Does this affect stability/smaller/bigger groups?

Thx

**Comment by antobinary** [comment]
> Any reason why?

Yes, as explained in the description of #11439 I think it would be better, more reliable if the changes are made by the operator straight in the config file, rather than using apply-config with additional layer of logic. There is work underway to allow operators to overwrite settings in /etc/bigbluebutton/* and I hope in the future to allow these values to be exposed there too.
