### ISSUE TITLE
isMeetingRunning always returning false (0.63)

### ISSUE THREAD

**Issue by bigbluebutton-issue-import** [bigbluebutton/bigbluebutton#1153]
Originally reported on Google Code with ID 398

```
What steps will reproduce the problem?
1. Just use isMeetingRunning() with ONLY a meetingToken


What is the expected output? What do you see instead?
Expect to see 'true' returned when at least one person is in the room.
Especially the moderator.


What version of the product are you using? On what operating system?
0.63


Please provide any additional information below.
I'm using a meetingID = name with the create api however, since my
meetingID doesn't fit the format of an extension for askterisk, I'm also
supplying the undocumented voiceBridge parameter on the query string to the
create api. This seems to work fine and fixes the strangeness created with
red5 (which by default will use the meetingID as the extension) and askterisk.

Other than that, I'm NOT supplying the meetingID (even though I defined it
in the create api) to isMeetingRunning(). The documentation clearly says
only meetingID OR meetingToken is required. I do the same thing on the join
api and it's working fine.

Ike
```

Reported by `goikeman` on 2010-03-09 21:42:55

**Comment by ss-shubham** [comment]
Just use isMeetingRunning() with all parameters like meetingID and checksum and my meeting is currently ongoing but  the response is still false

**Comment by ffdixon** [comment]
We just did a quick test with the excellent [API Mate](http://docs.bigbluebutton.org/dev/api.html#testing-api-calls) and it looks like the `isMeetingRunning()` is working correctly.  You need to have a user join the meeting before the BigBlueButton server will return `true` for `isMeetingRunning()`.

![ismeetingrunning](https://user-images.githubusercontent.com/290351/47083460-a79f9b00-d1de-11e8-8966-6c4a49965d0c.gif)

**Comment by ss-shubham** [comment]
Yes I did that , but the problem is API is showing meetingID is not found in getMeetingInfo()

**Comment by ffdixon** [comment]
What version of BigBlueButton server are you running.  Can you post some sample code?

**Comment by ss-shubham** [comment]
version 2.0
https://live.scholarspace.org/bigbluebutton/api/getMeetingInfo?meetingID=shu-zwd-pnj&password=shubham01&checksum=369920f330bad954662d7c2dd4a12a1526485120

**Comment by ffdixon** [comment]
Can you share what version of BigBlueButton you are running.  Also, did you do the `getMeetingInfo` **after** you had joined it with a user?

**Comment by ss-shubham** [comment]
BigBlueButton Server 2.0.0-RC6 (1600) Kernel version: 4.4.0-1067-aws Distribution: Ubuntu 16.04.5 LTS (64-bit) Yes , I had joined it with a user and after that i tried getMeetingInfo  ---- On Mon, 22 Oct 2018 19:07:05 +0530 Fred Dixon <notifications@github.com> wrote ---- Can you share what version of BigBlueButton you are running. Also, did you do the getMeetingInfo after you had joined it with a user? — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by capilkey** [comment]
The three API calls that are needed to test are create, join, and getMeetingInfo. Without the ability to call create and join it's impossible for us to test your server. I'm going to guess that you're not joining a user before trying to get the meeting info.

The API calls for the test-install server are:
create - http://test-install.blindsidenetworks.com/bigbluebutton/api/create?allowStartStopRecording=true&attendeePW=ap&autoStartRecording=false&meetingID=shu-zwd-pnj&moderatorPW=mp&name=shu-zwd-pnj&record=false&voiceBridge=72793&welcome=%3Cbr%3EWelcome+to+%3Cb%3E%25%25CONFNAME%25%25%3C%2Fb%3E%21&checksum=938ad48d24d3523b698c77b9405047e7c0ba6ca3

join - http://test-install.blindsidenetworks.com/bigbluebutton/api/join?fullName=shubham01&meetingID=shu-zwd-pnj&password=mp&redirect=true&checksum=866f0deaa79928b137e7d8b368f7b08edb1a0a64

getMeetingInfo - http://test-install.blindsidenetworks.com/bigbluebutton/api/getMeetingInfo?meetingID=shu-zwd-pnj&password=mp&checksum=1d75ddf2d8bdf4ff1641d309a1b77a2c78647c77

isMeetingRunning - http://test-install.blindsidenetworks.com/bigbluebutton/api/isMeetingRunning?meetingID=shu-zwd-pnj&checksum=c74a058b6202bbd88ab5f3786013ef562a7c43ff

Try plugging your own server credentials into API Mate (https://mconf.github.io/api-mate/) and then try the calls.

**Comment by ss-shubham** [comment]
Hey , I tested both API's "https://live.scholarspace.org/bigbluebutton/api/getMeetingInfo?meetingID=shu-zwd-pnj&password=shubham01&checksum=369920f330bad954662d7c2dd4a12a1526485120"  AND  http://test-install.blindsidenetworks.com/bigbluebutton/api/getMeetingInfo?meetingID=shu-zwd-pnj&password=mp&checksum=1d75ddf2d8bdf4ff1641d309a1b77a2c78647c77 Still the response is "<message>We could not find a meeting with that meeting ID</message>" Please find the attachment below of that will confirm you that the meeting is running and a user also joined it  We manually created the meeting and joined with a user and then trying to hit getMeetingInfo API ---- On Tue, 23 Oct 2018 01:37:35 +0530 Chad Pilkey <notifications@github.com> wrote ---- The three API calls that are needed to test are create, join, and getMeetingInfo. Without the ability to call create and join it's impossible for us to test your server. I'm going to guess that you're not joining a user before trying to get the meeting info. The API calls for the test-install server are: create - http://test-install.blindsidenetworks.com/bigbluebutton/api/create?allowStartStopRecording=true&attendeePW=ap&autoStartRecording=false&meetingID=shu-zwd-pnj&moderatorPW=mp&name=shu-zwd-pnj&record=false&voiceBridge=72793&welcome=%3Cbr%3EWelcome+to+%3Cb%3E%25%25CONFNAME%25%25%3C%2Fb%3E%21&checksum=938ad48d24d3523b698c77b9405047e7c0ba6ca3 join - http://test-install.blindsidenetworks.com/bigbluebutton/api/join?fullName=shubham01&meetingID=shu-zwd-pnj&password=mp&redirect=true&checksum=866f0deaa79928b137e7d8b368f7b08edb1a0a64 getMeetingInfo - http://test-install.blindsidenetworks.com/bigbluebutton/api/getMeetingInfo?meetingID=shu-zwd-pnj&password=mp&checksum=1d75ddf2d8bdf4ff1641d309a1b77a2c78647c77 isMeetingRunning - http://test-install.blindsidenetworks.com/bigbluebutton/api/isMeetingRunning?meetingID=shu-zwd-pnj&checksum=c74a058b6202bbd88ab5f3786013ef562a7c43ff Try plugging your own server credentials into API Mate (https://mconf.github.io/api-mate/) and then try the calls. — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by ss-shubham** [comment]
Hey , I tested both API's 
"https://live.scholarspace.org/bigbluebutton/api/getMeetingInfo?meetingID=shu-zwd-pnj&password=shubham01&checksum=369920f330bad954662d7c2dd4a12a1526485120"

  AND 

 http://test-install.blindsidenetworks.com/bigbluebutton/api/getMeetingInfo?meetingID=shu-zwd-pnj&password=mp&checksum=1d75ddf2d8bdf4ff1641d309a1b77a2c78647c77 
Still the response is  "<message>We could not find a meeting with that meeting ID</message>" 
Please find the attachment below of that will confirm you that the meeting is running and a user also joined it  
We manually created the meeting and joined with a user and then trying to hit getMeetingInfo API

**Comment by ss-shubham** [comment]
@capilkey  How to make sure that meetingID is correct?
