### ISSUE TITLE
Preupload presentation: 413 Request Entity Too Large

### ISSUE THREAD

**Issue by blu-IT** [bigbluebutton/bigbluebutton#11619]
Hello,

I am trying to **preupload** a presentation of **2,5 MB** and get the follwoing error:

"413 Request Entity Too Large"

I already checked the config like described here https://docs.bigbluebutton.org/2.2/customize.html#increase-the-file-size-for-an-uploaded-presentation and the **upload size** is already set to **30 MB**.

When I try to upload the presentation during the already started conference it works, so **it is only the preupload function** via greenlight that is affected.

I am using greenlight v. 2.7.20 with bbb 2.2.35 (2390)

Regards

**Comment by mk-hs** [comment]
Make sure to configure client_max_body_size in nginx correctly:
https://docs.bigbluebutton.org/greenlight/gl-config.html#updating-from-version-prior-to-27

The docs you mentioned are for BigBlueButton, your issue relates to greenlight. Since this issue isn't related to BBB itself, please close this issue.

**Comment by blu-IT** [comment]
OK, thanks for the hint! I did the modifications as described in the upgrade guide and it works now.

Thanks again!
