### ISSUE TITLE
Memory leaking with nodejs server app in case user exit and join again

### ISSUE THREAD

**Issue by TatChu** [bigbluebutton/bigbluebutton#11615]
**Describe the bug**
Memory is not released and increased continuously every user exit and join again.

**To Reproduce**
1. Create a meeting
2. 10 users join the meeting in 5 mins
3. 9 users exit
4. wait for about 2 mins
5. 9 users join meeting again.
6. loop step 3,4,5 several times and observe the memory

**Expected behavior**
The memory for each time users exit and re-join is the same

**Actual behavior**
The memory for each time users exit and re-join is increased.

**Screenshots**
My memory report from AWS
![image](https://user-images.githubusercontent.com/16249867/110737029-3bb2a700-825f-11eb-9630-9244932ab2d1.png)

**Additional context**
- This happened in both case allowDuplicateExtUserid equals to True and False
- NodeJs is the most process that consumes the memory
- Version: 2.2.25

**Comment by basisbit** [comment]
What does the graph show - is that some statistics from within NodeJS or overall memory used by that BigBlueButton server? How much memory does the server have / which instance size did you order?

**Comment by TatChu** [comment]
> What does the graph show - is that some statistics from within NodeJS or overall memory used by that BigBlueButton server? How much memory does the server have / which instance size did you order?

it's overall memory used. I used c5.xlarge with 4CPU and 8GB. also that chart is the result with the test case almost 200 users and it is the same as the test case with 10 users

**Comment by basisbit** [comment]
Thank you for the quick response! Those numbers are absolutely normal and to be expected. 2.2.32 included a bunch of performance improvements, including optimizations for the NodeJS garbage collector and memory options. NodeJS now will use up to 4GB of RAM and optimize itself so that garbage collection has to run as rarely as feasible in order to not block the main thread.
The recommended minimum amount of memory for BBB is 16GB or RAM. However, it works fine with 12 GB of RAM and works okay for some use cases with 8GB of RAM.

If upgrading your VMs is not an option, you might want to change the maximum amount of RAM that NodeJS may use (which will reduce the amounts of concurrent users that your server supports), by changing the number 4096 to for example 2048 in the last line of `/usr/share/meteor/bundle/systemd_start.sh`.

Closing this issue as this is not an issue.

**Comment by basisbit** [comment]
For more details on this change and the discussion, please see https://github.com/bigbluebutton/bigbluebutton/issues/11183
