### ISSUE TITLE
Return from breakouts - full audio rejoins with wrong audio output

### ISSUE THREAD

**Issue by antobinary** [bigbluebutton/bigbluebutton#11663]
**Describe the bug**
When returning from a breakout room to the main room, audio is re-joined with incorrect settings.

**To Reproduce**
1. Join a room with audio in full audio mode with non-default audio output
2. Accept to join a breakout (main room audio will drop)
3. Upon exiting the breakout (breakout ended) you will be back at the main room and your audio will automatically re-join

**Expected behavior**
Since you last used full audio, you will re-connect into full audio with the exact same audio input and output devices

**Actual behavior**
Likely the default input and output audio devices are used
 - [ ] check which devices we save
 - [ ] try connecting with 2 mics and 2 sets of outputs and try combinations to ensure correct behaviour

**BBB version (optional):**
BigBlueButton 2.3-alpha8

**Comment by mlncn** [comment]
By 'session' do we only mean breakout rooms?  Other issues for remembering audio have been closed in favor of this one, but until we're remembering audio settings for the same device returning to a meeting room or a BBB server (so cookies not login, as settings are tied to a device not a user account), then #10127 should be re-opened or another issue opened?

**Comment by mariogasparoni** [comment]
Yes, #10127 was closed because it was requested when we didn't have some of the audio features we have now and before audio mechanism changed. The current version covered most of the complaining we had related to device remembering, mute-state and switching between main/breakout rooms, so that issue kinda got staled (we didn't have stale bot by then)

And yes, i have no problem reopening #10127.
