### ISSUE TITLE
Chat error

### ISSUE THREAD

**Issue by GyR4uk** [bigbluebutton/bigbluebutton#11704]
** Error description**
When sending a message in a private chat to another user and quickly switching to a public chat, an error occurs that causes html5 to crash.

Sequence of actions:
1) Connect to the conference
2) Send a message in a private chat
3) Quickly go to a public chat

The error occurs when a message in a private chat was sent but has not yet been displayed, the user immediately went to the public chat.

![image](https://user-images.githubusercontent.com/35705596/111922226-bbcfdc80-8aa9-11eb-9d12-48b3ea30e11f.png)

**Comment by antobinary** [comment]
Likely duplicate of https://github.com/bigbluebutton/bigbluebutton/issues/11677 but we'll let @Tainan404 confirm.

Thank you for reporting it @GyR4uk ! And this looks like 2.3-alpha8

**Comment by Tainan404** [comment]
Hi @antobinary, this issue report is the same of the issues #11677 and #11528

**Comment by daminebenq** [comment]
Confirming, the error below reported in #11528 was already fixed in #11676..
![image](https://user-images.githubusercontent.com/5144311/111985804-de82e500-8aeb-11eb-80dd-f4460e581bd2.png)

while the other was also already reported in #11677.. so to avoid duplication, would @GyR4uk please close this issue ?

**Comment by GyR4uk** [comment]
Ok
