### ISSUE TITLE
Poll results: Spacing issue for RTL languages

### ISSUE THREAD

**Issue by antobinary** [bigbluebutton/bigbluebutton#11768]
When you switch from LTR language to RTL one after receiving the poll results
![image](https://user-images.githubusercontent.com/5144311/112637227-b1507280-8e1c-11eb-8cfd-e2ab88a123a9.png)

_Originally posted by @daminebenq in https://github.com/bigbluebutton/bigbluebutton/pull/11127#issuecomment-808208507_

Version:
BigBlueButton 2.3-beta-1

**Comment by antobinary** [comment]
@daminebenq please help describe the exact steps to reproduce

**Comment by daminebenq** [comment]
To reproduce:
1. Start a poll in RTL language and share the results
2. Switch from RTL language to and LTR one
3. See the wrong behavior

Expected behavior:
![image](https://user-images.githubusercontent.com/5144311/112690409-7a994d00-8e5a-11eb-80a0-1b4af378afb6.png)

Current behavior:
![image](https://user-images.githubusercontent.com/5144311/112690279-47ef5480-8e5a-11eb-9d23-276d1bb1b652.png)

**Comment by antobinary** [comment]
Similar to https://github.com/bigbluebutton/bigbluebutton/issues/11097

**Comment by antobinary** [comment]
Can't reproduce on 2.4.0.
