### ISSUE TITLE
Presentation upload configuration

### ISSUE THREAD

**Issue by pedrobmarin** [bigbluebutton/bigbluebutton#11830]
https://github.com/bigbluebutton/bigbluebutton/blob/6695f7a1196c56e67c00f93cde4f5b4804e455c4/bigbluebutton-html5/private/config/settings.yml#L459-L460

Two questions here:
 - why do we need to have `uploadSizeMin` at the settings file?
 - why do we set the top cap to 50 MB if all back-end caps to 30 MB?

**Comment by jfsiebel** [comment]
The `uploadSizeMax` is used by the [react-dropzone](https://react-dropzone.js.org/#src) component in https://github.com/bigbluebutton/bigbluebutton/blob/develop/bigbluebutton-html5/imports/ui/components/presentation/presentation-uploader/component.jsx#L820 to separate valid and invalid files, but this config is almost useless, because we ignore the file size if the file extension is a valid one (https://github.com/bigbluebutton/bigbluebutton/blob/develop/bigbluebutton-html5/imports/ui/components/presentation/presentation-uploader/component.jsx#L294-L297). 

About the value I don't know why this value was chosen.

**Comment by antobinary** [comment]
@jfsiebel will be removing these lines (and the ones that use them in the code) since he is reworking how we handle files that are too large. @gustavotrott will be sending a bbb-web PR where bbb-web provided feedback if the file is too large. Currently we have no feedback and the `uploadSizeMax` was (afaik) meant to be kept up to date (via packaging?) to the value we have in bigbluebutton.properties. But it never was kept up to date.

**Comment by pedrobmarin** [comment]
I believe bbb-web also caps the number of pages: https://github.com/bigbluebutton/bigbluebutton/blob/44a5eb8b263404a5153bf09f787795d3c24768c0/bigbluebutton-web/grails-app/conf/bigbluebutton.properties#L69-L75
Maybe we could include a textual description on these thresholds at the presentation's upload modal.

**Comment by antobinary** [comment]
About the maxNumPages, issue https://github.com/bigbluebutton/bigbluebutton/issues/7202 is included in the rework that @jfsiebel is doing
