### ISSUE TITLE
Incorrect ownership of /dev/shm/core.db leading to high FS CPU

### ISSUE THREAD

**Issue by antobinary** [bigbluebutton/bigbluebutton#11887]
**Describe the bug**
(copied from https://groups.google.com/g/bigbluebutton-dev/c/KfygeyPnCuw/m/hZw1i69ZBwAJ )
@oliver-74
After the installation with bbb-install.sh was done, I did not immediately check if everything was ok and by the time I did, I saw that the freeswitch process was using 200% cpu load without any meetings running. When I checked the freeswitch log directory it already had several GBs of error logs in it after just 60 minutes since the install. They were full with this:

BEGIN EXCLUSIVE
2021-04-03 10:49:38.379102 [CRIT] switch_core_sqldb.c:2171 ERROR [attempt to write a readonly database], [db="/dev/shm/core.db",type="core_db"]
2021-04-03 10:49:38.379102 [ERR] switch_core_sqldb.c:732 [db="/dev/shm/core.db",type="core_db"] NATIVE SQL ERR [cannot commit - no transaction is active]
COMMIT

Permissions for the mentioned file were:

root:/dev/shm# ls -l
total 344
-rw-r--r-- 1 meteor daemon 352256 Apr  3 09:34 core.db

After checking with my old BBB2.2 server I saw this file should be owned by freeswitch and not by meteor. After changing the owner and restarting BBB2.3-beta2 everything now works fine as far as I can tell.

**Installation type**
bbb-install script. Upgrade from 2.3-alphaX straight to 2.3-beta-2

Related to https://github.com/bigbluebutton/bigbluebutton/issues/11752

**Comment by znerol** [comment]
From a FreeSWITCH [release notes](https://signalwire.com/blogs/product/signalwire-stack-release-20-19-7):

> ## New Features
> * [FS-11827](https://freeswitch.org/jira/browse/FS-11827) - Add feature allowing FreeSWITCH to store CORE DB (SQLite) fully in memory

The relevant commit is [signalwire/freeswitch@20295c53](https://github.com/signalwire/freeswitch/commit/20295c53efcda037cb67703c36fc3fc62656cc2d#diff-0941b2df48f11a5b4e55631f2869f4056cafc803eed16e9565f59d0e08bca351R461-R467). And the relevant docs for sqlite are [here](https://www.sqlite.org/inmemorydb.html).

Still took me some fiddling around, but the following `value` for `core-db-dsn` param in `autoload_configs/switch.conf.xml` does the trick:

```xml
<configuration name="switch.conf" description="Core Configuration">
  <settings>
    <param name="core-db-dsn" value="sqlite://memory://file:core?mode=memory&cache=shared"/>
  </settings>
</configuration>
```

Explanation for the weird DSN format:

* `sqlite://`: use the sqlite driver
* `memory://`: use FreeSWITCH function `switch_core_db_open_in_memory` instead of `switch_core_db_open_file`.
* `file:core?mode=memory&cache=shared`: sqlite file URL passed directly into `sqlite3_open_v2`. Shared cache is important since FreeSWITCH uses multiple connections to create the schema and access the database.

The same schema can be used for the `dbname` param in sip profiles.

**Comment by antobinary** [comment]
@ffdixon would you be able to confirm / merge #12231 ?
