### ISSUE TITLE
[2.3] Unable to share camera/The very first Audio connection try fails with 1004 Error code

### ISSUE THREAD

**Issue by daminebenq** [bigbluebutton/bigbluebutton#11897]
To reproduce:
1. Use Microsoft Edge browser and connect to a 2.3 bbb server (I tried with v89 and v90)
2. Try to share webcam, audio
3. See results below

Unsupported camera profile:
![image](https://user-images.githubusercontent.com/5144311/113639215-1000c200-964f-11eb-8a18-a5ab7c18c2fe.png)

1004 Error code at the very first audio connection try:
![image](https://user-images.githubusercontent.com/5144311/113639475-a3d28e00-964f-11eb-85fb-72f957e0a46d.png)

WebRTC troubleshoot report:
![image](https://user-images.githubusercontent.com/5144311/113639279-2c9cfa00-964f-11eb-81d8-f542e16aeacf.png)

**Comment by prlanzarin** [comment]
You're missing OS (+version).

Moreover, your WebRTC troubleshooter (which attests the issue has probably little to do with BBB) says you only have relay connectivity, which stems a new question: did the server you try that on had a TURN server configured?

The third thing is that the troubleshooter itself basically says audio capture and camera capture are borked. Again, tentatively little to do with BBB. Reproducing in ie appr.tc  is a good test as well.

**Comment by daminebenq** [comment]
Windows 10, Microsoft Edge v89 and v90.

**Comment by prlanzarin** [comment]
Still missing the info about whether the test server as TURN configured or not.

I'll make a _wild guess_: you're testing in Browserstack. Can you confirm that or not?

**Comment by daminebenq** [comment]
Yes, this was on browserstack, and the server used was bbb 2.3 dev server.

**Comment by prlanzarin** [comment]
1 - Browserstack DESKTOP environments don't have cameras, hence the camera error. You have to pass the fake capture device flag (and I don't even know if that's possible there). So not an issue.

2 - That dev server doesn't have TURN enabled, so it's a non ideal setup. mDNS resolution in Browserstack actually works (which is an absolute edge case on its own), so the reason it fails the first time is due to mDNS heuristics. If there's no TURN server, host/srflx candidates won't be gathered and the SDP will go to the server empty (because mDNS candidates are filtered), rendering a 1004. If there's a TURN server (which is the _recommended_ setup), that won't happen. Subsequent attempts won't fail because host candidates will be generated.

**Comment by daminebenq** [comment]
I just found out that Browserstack doesn't have webcam plugged in or a fake webcam...
![image](https://user-images.githubusercontent.com/5144311/113713471-c56a5e80-96bd-11eb-8793-7e6893d56567.png)

**Comment by daminebenq** [comment]
Closed, after trying this on a real windows machine with a real MS Edge, i couldn't reproduce any of the WebRTC problems reported in this issue, so to conclude, Browserstacks isn't a good tool to test this 😆
