### ISSUE TITLE
Provide some way to move meeting to a different server

### ISSUE THREAD

**Issue by arthurzenika** [bigbluebutton/bigbluebutton#11944]
Follow up of #11942 

**Is your feature request related to a problem? Please describe.**

Once we've identified that the server is the bottleneck for a given setup, to keep and encourage a decentralized and diverse ecosystem, it would be nice to be able to "move a class" or "move a meeting" to another URL/server. 

**Describe the solution you'd like**

For example town.schoolexample.org/myclass could, during a meeting, move to region.schoolexample.org/myclass with either a banner or a redirect. 

**Describe alternatives you've considered**
I've seen in some cases, using the chat to indicate to all participants "hey the server is not handling the load, let's regroup in 5 minutes in URL (bigger server)"

**Comment by basisbit** [comment]
imho, this would first require separating the frontend-server from the webrtc-server/audio+video bridges. Otherwise you would have to tell every user to please change to this URL (through the load-balancer) and then completely rejoin the new session including audio setup and so on.

Here again, I think the much easier and probably much better solution is to actually monitor your servers and services, make the load balancer aware of the different limitations and then have the load-balancer avoid overloaded servers in the first place.

**Comment by basisbit** [comment]
I'll bump this once, in hope for some more discussion on the topic of improved load balancing, especially regarding dealing with long running sessions that unexpectedly got lots of participants.

**Comment by ffdixon** [comment]
It would be a good feature to have, especially for load balancing.  However, fundamentally, BigBlueButton is not designed to support this type of dynamic moving from one server to another.  It would take a significant rework of the architecture.  The best way to approach this is to add this capability to components of BigBlueButton over time as they get refactored.  

However, there isn't any priority at the moment for this.  Nonetheless, we'll keep this issue open.
