### ISSUE TITLE
Provide some way to display server load problems to end users

### ISSUE THREAD

**Issue by arthurzenika** [bigbluebutton/bigbluebutton#11943]
First of kudos to all to people that made BBB possible, I use it in personal and professional use cases and it's great !

**Is your feature request related to a problem? Please describe.**

Yes. On some BBB instances where the specifications and size of server is not public or where usage may vary, the quality of a conference with the same number of participants (which same network conditions) may vary. Many issues and forum posts talk about the potential limitations of running a BBB server on limited hardware and the impact it has on users when they are in conferences or when number of participants reach more than X people, which is technically fully understandable.

**Describe the solution you'd like**

It would be really nice to have (maybe an optional) way of displaying to the end users a warning about the state of the server load when it might have an impact on their performance. For example I would imagine a low-end server that one would use for 20 participant classes or small meetings which works fine and then when 50 people are on it and it is too loaded that it would suggest in the browser for the users to maybe move to a bigger server (which could be indicated by the admin of the instance).

In a lot of cases varying experience on the same server causes the users to think they are having problems with their client, their ISP, etc. This type of feature would help them identify the problem.

**Describe alternatives you've considered**

Maybe there could be a setting to automatically disable some features such as video with a warning such as "server overload disabling some features" ?

**Comment by basisbit** [comment]
One more note: with current versions of BBB on decent hardware and with a supported setup, the server should work well even quite far above its capacity limit, thanks to linux cpu scheduling and process priorities. You'll see video fail first long before the server gets unusable for all users.

This however does not work for some of the ways how people use BBB in LXC or in Docker, because these setup scripts often don't handle configuring the containers for decent task scheduling.

@arthurlogilab could you maybe describe your reasons why you created these issues here in the first place? Which version of BBB are you using, what hardware is it running on, dedicated network bandwidth and what uplink peerings does the data center use?
