### ISSUE TITLE
Integration of external whiteboards like miro

### ISSUE THREAD

**Issue by glu000** [bigbluebutton/bigbluebutton#11958]
**Is your feature request related to a problem? Please describe.**
Whiteboard is a key-feature for trainings and workshops. The integrated whiteboard only supports basic functionality

**Describe the solution you'd like**
Integration of miro like it is implemented by https://butter.us

**Comment by basisbit** [comment]
Closing this issue for now because this completely breaks the main use case of BigBlueButton and its UI/UX workflows. This will not be a feature in BBB for quite some time.

For a majority of use cases, integrating a third party whiteboard would also violate data privacy laws like GDPR or CCPA. Instead, I'd suggest working on improving the whiteboard feature in BigBlueButton - there already have been done lots of improvements in the 2.3.x version which you can test by running the current 2.3-beta version.

Alternatively, it might be worth it to integrate another whiteboard library which offers all the desired features - however keep licensing compatibility as well as usability requirements in mind when implementing this.
