### ISSUE TITLE
[2.3] A problem with returning from Breakoutroom about audio automatic reconnection

### ISSUE THREAD

**Issue by daminebenq** [bigbluebutton/bigbluebutton#12006]
A problem with returning from Breakoutroom about audio automatic reconnection 

https://user-images.githubusercontent.com/5144311/114433980-d96bff80-9b98-11eb-8c65-247fd59e00db.mp4

Also, sometimes there is a problem with the presenter role gets lost.

_Originally posted by @daminebenq in https://github.com/bigbluebutton/bigbluebutton/issues/11964#issuecomment-817981179_

**Comment by mariogasparoni** [comment]
Hey, @daminebenq , thanks for reporting and the video. 

Could you please complete the template form ?
I had to watch it three times to find where the possible problems are (and i am not really sure if i found the same problem as you did, sorry). With the complete description we can go straight to the point.
Specially for the **steps to reproduce** , **current** and **expected behaviors** fields.

This is what i have found so far (please, correct me if this is wrong) :

#### Steps to reproduce
1. Join meeting
2. Create breakouts
3. Join breakout room
4. In breakout room, the full audio will automatically start  (first problem? : user didn't have audio active in main room - this strongly related to #11662 and can be treated there)
5. At the upper right corner,  click on the three dots "⋮"  -> Leave Meeting. Breakout window will be closed.
6. Back to the main room microphone won't connect automatically (second problem).

#### Expected behavior
In step `4` user **should not** connect to full audio automatically.
In step `6` user **should** connect to full audio automatically.

#### Current behavior
In step `4` user connects to full audio automatically (even if he/she was using listen-only, which may results in a server overload).
In step `6` user doesn't connect to full audio automatically.

**Comment by daminebenq** [comment]
**Steps to reproduce:**
1 - join meeting with full audio
2 - create breakouts
3 - join breakout (audio will connect automatically)
4 - leave breakout by clicking the close tab or the "Leave meeting" in Settings menu (the three dots)
5 - back to the main room, audio should connect automatically

At step (5), the **expected behavior** is:
Audio connects automatically in the main room
But the **current behavior** is:
audio is not connecting automatically, it only reconnects automatically to main room when **End all breakout rooms** is clicked.

**Comment by mariogasparoni** [comment]
Thanks @daminebenq ! :) :)

**Comment by ludm-dev** [comment]
>  In step `6` user doesn't connect to full audio automatically.

We have a similar problem,it connects in listen only mode and trying to activate the mic with the button does not work.
