### ISSUE TITLE
make fs_clibbb usable for scripting, tiny fix

### ISSUE THREAD

**Issue by thifranc** [bigbluebutton/bigbluebutton#12009]
**Is your feature request related to a problem? Please describe.**
actual fs_clibbb does not allow to make automated API call through '-x' option e.g. : fs_clibbb -s 'show calls'

**Describe the solution you'd like**
I'd like to have a fs_clibbb that I can use as fs_cli. Thanks to this, I'll be able to use it to collect data or do some monitoring.

**Describe alternatives you've considered**
I could just rewrite the srcript myself, but I think it's still an improvement that others could benefit from, fs_clibbb will become more intuitive to use.

Code proposed :
fs_clibbb
```
#!/bin/bash

/opt/freeswitch/bin/fs_cli -p $(xmlstarlet sel -t -m 'configuration/settings/param[@name="password"]' -v @value /opt/freeswitch/etc/freeswitch/autoload_configs/event_socket.conf.xml) "$@"
```

I did not found how to directly PR bbb-freeswitch-core as I could not get its source code.

**Comment by znerol** [comment]
I recomend to simply not rely on `fs_clibbb` at all for scripting. Better just use `/opt/freeswitch/bin/fs_cli` directly, so you can be sure that updates to the `fs_clibbb` wrapper script will not break your code. In order to disable the password prompt, just add a file into `/root/.fs_cli_conf` with the following content:

```
[default]
password => yourfreeswitchpassword
```

**Comment by thifranc** [comment]
You're right, Closing the issue as a better solution already exist :)
