### ISSUE TITLE
[2.3 Beta 3+] Broken layout after open+close shared notes multiple times

### ISSUE THREAD

**Issue by schrd** [bigbluebutton/bigbluebutton#12050]
**Describe the bug**
Opening/closing shared notes breaks layout (see screenshot)

**To Reproduce**

1. Join a BBB conference. 
2. Open some cameras (we had 3). Do not change camera/slide size, so that autolayout is active
2. open shared notes
3. close shared notes by clicking on "shared notes" again (neither shared notes nor chat are visible)
4. open shared notes again
5. layout is broken

I know that there were some fixes after 2.3 Beta3, so I tested this on commit (8cd827a379). If you resize the slides, everything is fine again and this bug cannot be triggered anymore.

**Screenshots**
![Bildschirmfoto von 2021-04-16 09-09-37](https://user-images.githubusercontent.com/179952/114994245-dfb1f280-9e9c-11eb-9593-aae72da407c5.png)

**BBB version (optional):**

BBB 2.3 Beta, commit 8cd827a379

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser: Firefox
 - Version 78.9.0esr

**Comment by schrd** [comment]
reproducable on Beta4 as well

**Comment by schrd** [comment]
tried this on beta 5 and discovered something else:

* when the slides are in 4:3 aspect ratio, it works perfectly
* when the slides are in 16:9, layout is broken as described above

**Comment by waesien** [comment]
#11980

**Comment by daminebenq** [comment]
This is now reproducible on opening closing polling panel on 2.3 RC2

**To reproduce:**
1. Share webcam
2. Open polling panel
3. Click on polling button in userslist to hide it
4. See result on opening and closing polling panel

**Current behavior:**

https://user-images.githubusercontent.com/5144311/116339499-ebae8600-a7b3-11eb-83b6-628761950795.mp4

**Expected behavior:**
Presentation should not get any overlaps on clicking on any element (for this case; panels as polling, shared notes, chat... etc)
