### ISSUE TITLE
bbb-conf --setip fails to rewrite some metadata.xml links when migrating recordings.

### ISSUE THREAD

**Issue by hostbbb** [bigbluebutton/bigbluebutton#12051]
Move recordings to new server and use bbb-conf --setip to rewrite all the metadata.xml links, thumbnails fails to convert all of them,

need to check for this, and run
find . -name 'metadata.xml' -exec sed -i 's/old.link/new.link/g' {} +to fix the missed ones.

Next time it happens i will collect the metadata.xmls that the script missed so we can debug.

**Comment by ali-alhaidary** [comment]
I had to rename the file so that it can be uploaded. Each bbb.the5stars.org should have been made almajlis.the5stars.org after running bbb-conf --setip command, however, it did not. I still have 4GB of such files in backups.
I had to rectify the issue using the above command.
[metadata.xml.log](https://github.com/bigbluebutton/bigbluebutton/files/6325359/metadata.xml.log)

**Comment by antobinary** [comment]
Merging into https://github.com/bigbluebutton/bigbluebutton/issues/12628
Please let me know if this merge is incorrect
