### ISSUE TITLE
Make custom quick poll

### ISSUE THREAD

**Issue by thifranc** [bigbluebutton/bigbluebutton#12055]
**Is your feature request related to a problem? Please describe.**
We find ourselves limitated with the current default quick poll options. We, for example, often have to create poll that ranks from 1 to 10, and we'd like to have it as a quick poll button

**Describe the solution you'd like**
I would love to have the possibility to edit custom quick poll, for example in /usr/share/meteor/bundle/programs/server/assets/app/config/settings.yml or a file there

**Describe alternatives you've considered**
We use custom poll so far

**Additional context**
I've seen that the description of the default quick poll are in : bigbluebutton-html5/imports/ui/components/poll/service.js, making the link with the file bigbluebutton-html5/imports/ui/components/poll/component.jsx.
One drawback could be that we'll lose 'default', that is to say by adding default quick poll options, we would have to add translations in /usr/share/meteor/bundle/programs/server/assets/app/locales/ files.

I don't know if there's already work on that, I'd love to come up with a PR for that, and maybe can do the work from BBB dev if you would be into merging a PR like that.

thanks for all the work and effort you've put into this project, it's awesome !

cheers,

**Comment by hiroshisuga** [comment]
If increasing the number of options to 6, instead of 5, improves your situation, just a small change in this line:
https://github.com/bigbluebutton/bigbluebutton/blob/7fa9f97c74d1eca2cdb20873b03e48155afcc128/bigbluebutton-html5/imports/ui/components/actions-bar/quick-poll-dropdown/component.jsx#L87
might help.
`1: 'A', 2: 'B', 3: 'C', 4: 'D', 5: 'E', 6: 'F',`
Increasing it to more than 6 will require more changes, but possible. You may be interested in #10854 , which shows question texts in the poll.
