### ISSUE TITLE
Connection status indicator unexpected behavior

### ISSUE THREAD

**Issue by basisbit** [bigbluebutton/bigbluebutton#12060]
**Describe the bug**
The HTML5 client contains a component for displaying the "connection status". Currently the implementation only measures roundtrip time for a server-function-call, which does not necessarily result in usable data for indicating good or bad connection quality between the webclient and the nodejs/meteor server.

The code can be found starting here:
https://github.com/bigbluebutton/bigbluebutton/blob/7fa9f97c74d1eca2cdb20873b03e48155afcc128/bigbluebutton-html5/imports/ui/components/connection-status/service.js#L121

**Expected behavior**
I wold suggest a connection quality check should only complain about connection quality issues when there is high jitter (high average difference between multiple probes) or high packet loss (not just a one time short burst of few lost packets because the user is using wireless network connection).
When the server reached its capacity limit (monitor this within NodeJS) or the client has a low frames per second user interface redraw speed (too much client cpu load), then the server as well as the client should handle those situation differently (either show a different warning message or reduce load by switching into a low-power mode).

**Actual behavior**
People reported that the widget complained about horrible connection quality, although audio+video transmission and event response was fine/good. For long distance links or slightly lossy connections, it always reports connection quality problems for them, although there is no problem is participating in the class.

**BBB version (optional):**
Current BBB 2.3/develop master.

**Comment by pedrobmarin** [comment]
If you take a closer look, it also does this https://github.com/bigbluebutton/bigbluebutton/blob/develop/bigbluebutton-html5/imports/utils/stats.js.

**Comment by prlanzarin** [comment]
To add to what @pedrobmarin said: https://github.com/bigbluebutton/bigbluebutton/blob/7fa9f97c74d1eca2cdb20873b03e48155afcc128/bigbluebutton-html5/private/config/settings.yml#L429-L451

A lot of that stuff is heavily configurable.

**Comment by pedrobmarin** [comment]
Not sure how to follow up this issue.

Monitoring RTT has been a valuable addition to this feedback status. It's a good and simple alternative for capturing client and server load that affects directly the UI responsiveness.

From the **expected behavior** section, jitter and packet loss are already there for the audio connection (both microphone and listen only). We could reason about including it for each video stream too but I wouldn't expect much improvement on the connectivity feedback from that.

As @prlanzarin mentioned, you can configure the thresholds at the client's settings file. The base RTT for our servers is something near 200 ms. You can adapt that to provide a better experience for your customers.
