### ISSUE TITLE
Get more chars and rows for input-field in text-poll

### ISSUE THREAD

**Issue by makabar** [bigbluebutton/bigbluebutton#12108]
Our teachers are heavy poll users. Currently they are using Adobe Connect which allows editing and storing polls before the beginning of a conference. 
I´ve seen there is a option to allow drag and drop for custom polls in bbb2.2. Hopefully this feature is coming soon in 2.3 beta.
This would help to increase bbb acceptance.

The real reason for this request. you can do polls with free text input area. But the available character range is too small for more complex answers. The users can input their answers only in a single row and only in 45 charakters.
It would be great if you can implement an option in polls to enlarge the text input area and allow more than 45 chars in
`bigbluebutton-html5/imports/ui/components/poll/component.jsx`

thanks

**Comment by antobinary** [comment]
Hi @makabar 

>option to allow drag and drop for custom polls
You may want to enable https://github.com/bigbluebutton/bigbluebutton/blob/v2.3-beta-5/bigbluebutton-html5/private/config/settings.yml#L353 in your server, check https://github.com/bigbluebutton/bigbluebutton/pull/11336

> Implement an option in polls to enlarge the text input area and allow more than 45 chars
That will require some re-thinking of how we do things. We had to limit the length to 45 chars because otherwise the poll result on the slide would be too small to read. (Both live session and recording).
Would your use case be fine with just public chat summary (results) of the poll, with nothing on the slide?

**Comment by makabar** [comment]
Hello Anton,
thanx for Your very fast reply. I´m really deeply impressed of Your performance. (not kidding)

I forgot to click on A/B/C/D. My fault. Drag`n Drop works of course in 2.3 beta. But it fills the possible answers only.
A solution as [suggested here](https://github.com/bigbluebutton/bigbluebutton/issues/11457) would be awsome.

to Your question. I understand Your objection very well!! It could be an solution if the teacher/moderator/presentor  gets the results in his preview window before publishing in public chat. in some cases it also could be more sensitive to the students if the teacher could anonymize the results before publishing.

additionally to this it should be possible to get anonymized results in any multiple choice poll. as a kind of secret vote. it´s also needed here in our meetings. i know - thats an different issue/ feature request.
