### ISSUE TITLE
Sharer webcam can get into an inconsistent state on disconnections

### ISSUE THREAD

**Issue by GyR4uk** [bigbluebutton/bigbluebutton#12122]
This bug is very often observed in users who have a weak and unstable Internet.

It looks like this:
1) The user joined the meeting
2) Turned on the camera (other users can see it)
3) Due to a bad Internet connection, the camera reconnects
4) Now users don't see his camera, but the user sees his camera and other participants.

Reconnecting the camera does not help, the problem is solved only by reloading the page.

This problem is observed on all versions of bbb 2.3

**Comment by prlanzarin** [comment]
I'm renaming this issue to be about the client side state inconsistency (**local** camera dropped, but still on the UI even though it's not technically shared).

There is _no_ reconnection for outbound (_sharer_) webcams right now, nor there will be in the shortest term. This is a state inconsistency problem that I confirm happens and for which I have a fix that I forgot to lift into 2.3.

The expected behavior is that the shared camera just disconnects and the UI state reflects that.

**Comment by prlanzarin** [comment]
Should be fixed by https://github.com/bigbluebutton/bbb-webrtc-sfu/pull/89

**Comment by GyR4uk** [comment]
@prlanzarin Thank you for the clarification

**Comment by prlanzarin** [comment]
Tagged in https://github.com/bigbluebutton/bbb-webrtc-sfu/releases/tag/v2.5.0-alpha.6, will land in the next BBB tag.
