### ISSUE TITLE
bbb 2.3-rc1 Not all of the switch status letters in the settings are placed on the switch.

### ISSUE THREAD

**Issue by nikkei00** [bigbluebutton/bigbluebutton#12146]
**Describe the bug**
Not all of the switch status letters in the settings are placed on the switch.
**Не все буквы состояния переключателя активности в настройках помещаются на выключателе**

**To Reproduce**
1. Начать конференцию на test23.bigbluebutton.org
2. Зайти в настройки
3. Смотреть, как на русском языке вместо "**ВЫКЛ**" отображается только "**ВЫК**"
![image](https://user-images.githubusercontent.com/64165027/115990934-0c6db480-a5d7-11eb-8c1d-5642a7f813da.png)

**Я нашел, что при увеличении width у класса .react-toggle-track с 3.5 до 4.5 - все буквы начинают помещаться.**
![image](https://user-images.githubusercontent.com/64165027/115990958-1c859400-a5d7-11eb-900b-7729017c5d76.png)
![image](https://user-images.githubusercontent.com/64165027/115991016-5b1b4e80-a5d7-11eb-932a-527674bccf05.png)

![image](https://user-images.githubusercontent.com/64165027/115990974-33c48180-a5d7-11eb-97ca-698da68eecaf.png)

**Однако, в случае, если примут моё предложение, нужно будет доработать положение кружочка на выключателе. У меня не хватает знаний для этого**

**Desktop:**
 - OS: Windows 10
 - Browser Chrome

**Comment by antobinary** [comment]
Thanks for reporting this @nikkei00 !

I just checked with @tylercopeland and looks like we are leaning towards bringing the ON / OFF text (in any language) outside off the switch, similar to how we have it on the Lock Settings modal:

![screen_shot_2021-04-29_at_11 26 51_am](https://user-images.githubusercontent.com/6312397/116583416-53fc8500-a8e4-11eb-979d-1cbb38308f96.png)

With the desired approach clarified, I think we can move to implementing this change so that long strings are displayed in full.

Please comment if you have any questions / concerns / recommendations...

**Comment by nikkei00** [comment]
**Thanks for the answer!
Yes, it will be a good option.

There is a question not on the topic: Why are there two Russian languages in transifex (ru) and (ru_RU) ? I did a full check and correction of grammatical errors, but I have to duplicate everything in the second language.**
![image](https://user-images.githubusercontent.com/64165027/116650419-181ff900-a992-11eb-8868-b889a1232f07.png)

**Comment by antobinary** [comment]
>Why are there two Russian languages in transifex (ru) and (ru_RU)

The short answer is - because Transifex users requested both and did translations in both. I am typically the one who authorizes new requests to join or add a language but I am not really in position to know if there are subtle differences - ru, ru_RU, Russian from Kazakhstan, etc.. For Spanish and Arabic it looks like the different versions are justified.
We recently removed a duplicate German and Japanese locales due to them being essentially the same. If you can guarantee that ru and ru_RU 's differences are unjustified, we can remove ru_RU (more specific), so all browsers that request `ru_*` fallback to `ru`.

**Comment by antobinary** [comment]
(offtopic)
>The suggestion is this: Make the "settings" window also modal, and not full-screen. Similar to the presentation management window. Too much white space is obtained

This was a design decision made some time ago, iirc we tried both types of modals and the overall consensus was that full screen modal looked better. It also ties in with the fact that in the presentation modal you need to do a few operations and then hit the confirm or cancel options. If the modal was not full screen, clicking outside the modal would be interpreted as 'cancel' and all your operations would be lost. Full screen modal avoids that scenario.

**Comment by nikkei00** [comment]
> (не по теме)
> 
> > Почему в transifex (ru) и (ru_RU) два русских языка
> 
> Краткий ответ - потому что пользователи Transifex запрашивали и переводили оба. Я обычно являюсь тем, кто разрешает новые запросы на присоединение или добавление языка, но на самом деле я не могу знать, есть ли тонкие различия - ru, ru_RU, русский из Казахстана и т. Д. Для испанского и арабского языков это похоже на разные версии обоснованы.
> Недавно мы удалили повторяющиеся немецкие и японские языковые стандарты, поскольку они по сути совпадают. Если вы можете гарантировать, что различия ru и ru_RU необоснованны, мы можем удалить ru_RU (более конкретно), чтобы все браузеры, запрашивающие `ru_*`переход на `ru`.

Как я могу гарантировать что переводы идентичны? Русско-казахстанского языка не бывает. Русский язык один. Внутри нашей много национальной страны есть другие языки, но они не связаны с русским (например, татарский), боюсь для них нужно открывать отдельный язык. Но татары в любом случае знают русский.

**Comment by antobinary** [comment]
@nikkei00 , I moved this conversatoin to #12226 Let's continue there, please

**Comment by mrkeksi** [comment]
I think that it is not the right way to divide all states of the switches. Is this for accessibility or for easy understanding? Why isn't the label done the way Apple does it? There it is an I for the on state and an O for the off state. I think this is sufficient for all visually impaired people. For screen reading devices it is also invisibly feasible. Have you ever looked at it on a mobile device? Does it look really nice when each word of a sentence has its own line?
