### ISSUE TITLE
[html5] question regarding default numbers of nodejs processes

### ISSUE THREAD

**Issue by BrutalBirdie** [bigbluebutton/bigbluebutton#12232]
https://github.com/bigbluebutton/bigbluebutton/blob/a2c17ad0699421d9cf4942b557798121051cd2ce/bigbluebutton-html5/deploy_to_usr_share.sh#L47-L54

Comments say:
```
# Default = 1; Min = 1; Max = 4 
```
and
```
 # Default = 1; Min = 0; Max = 8 
```
But both are set to `2`.
Which one is the 'real' default? `1` or `2`?
Asking because of templating and defaults in the ansible role.
https://github.com/ebbba-org/ansible-role-bigbluebutton

https://github.com/BrutalBirdie/ansible-role-bigbluebutton/blob/bbb/2.3/templates/bbb-html5/bbb-html5-with-roles.conf#L2-L9

**Comment by laserrapt0r** [comment]
It would also be interesting what the downsides are when setting it to a higher value.

**Comment by antobinary** [comment]
Hi @BrutalBirdie thanks for pointing this out!
I forgot to change the comments when I changed the defaults to `2`.

I think 2 of each (backend and frontend) is a good default because you take advantage of the spread of the load while the setup also works on what we regard as 'minimum requirements for a BBB server.

I will proceed to update the comments in the BBB code and bbb-html5 package and will then mark this issue as resolved. I will make sure to document this in the release notes so `github.com/ebbba-org/ansible-role-bigbluebutton` and other repos can pick up the change.
