### ISSUE TITLE
Whiteboard annotation ordering fails

### ISSUE THREAD

**Issue by hiroshisuga** [bigbluebutton/bigbluebutton#12245]
**Describe the bug**
In some edge cases, the order of SVG element from a pen drawing is not correct. 

**To Reproduce**
1. open two sessions
2. the moderator draws a pen drawing
3. the viewer draws a pen drawing
4. the moderator draws two rectangles (or something that is not a pen drawing)
5. the viewer draws a pen drawing over the rectangles
6. the last pen drawing by the viewer is hidden under one rectangle

**Expected behavior**
the latest drawing should always be drawn over the previous ones.

**Actual behavior**
Pen drawing is sometimes drawn under the previous one. 

**Screenshots**
![annotation2](https://user-images.githubusercontent.com/45039819/116842609-0485c400-ac18-11eb-96f2-8a884b7df76f.gif)

**Additional context**
Confirmed on 2.3. Some discussion in #11018. I will post an idea to fix this problem.

**Comment by mk-hs** [comment]
Could this be related to the following?

Steps to reproduce:
1. Presenter activates multi-user whiteboard
2. Viewers draw something
3. Presenter stops multi-user whiteboard, draws something
4. Presenter uses the back button to remove something previously drawn

Expected behaviour: Only recently drawn lines by the presenter are getting removed
Actual behaviour: Lines drawn by the viewers are getting removed instead

**Comment by hiroshisuga** [comment]
I have never seen that before. You'd better post it as a different issue.

**Comment by hiroshisuga** [comment]
Hi @hostbbb , thanks for the comment. I have missed it.
Right now I installed the latest version 2.4b7 without any modification, and the problem still happens. No error in run.sh.
I will try to investigate the problem.

**Comment by hiroshisuga** [comment]
The problem persists in 2.4rc7.
