### ISSUE TITLE
Move palm recognition icon on desktop into settings

### ISSUE THREAD

**Issue by mrkeksi** [bigbluebutton/bigbluebutton#12243]
**Is your feature request related to a problem? Please describe.**
Since the function has no recognizable function on the desktop, it would be good to hide it. Or am I not recognizing the benefit correctly?

**NEW IDEA Describe the solution you'd like**
Move the Setting from the tool bar to the user settings section. 

**OLD IDEA Describe the solution you'd like**
```
.parentdiv_palmdetection {display:none;}

@media (pointer: coarse) and (any-pointer: fine) {
     .parentdiv_palmdetection {display:block;}
}
```

**Comment by laserrapt0r** [comment]
You can have a tablet with or touchscreen laptop with Windows 10. I don't know if the feature works here though?

**Comment by mrkeksi** [comment]
Hey @laserrapt0r I don't have such a device. Would by nice if you could test it for us with the Chrome dev tools? Do you know how to do that?

**Comment by MaximilianJacobs** [comment]
If you have an expensive wacom tablet with touch, or even an integrated screen, you would very likely want this feature.

**Comment by mrkeksi** [comment]
I only have a cheap wacom without screen. I think that few have such an expensive device. how about optional hidden in the settings for desktop devices?

**Comment by antobinary** [comment]
We should include this in https://github.com/bigbluebutton/bigbluebutton/blob/develop/bigbluebutton-html5/private/config/settings.yml#L582 but that would be a per-server setting, so it does not really address the original request.

We don't really know when this feature is applicable to the presenter...
As a side note, do you custom remove other tools currently?

**Comment by mrkeksi** [comment]
I have never removed tools, why should I? I don't want to remove this palm recognition completely for everyone, as it is certainly helpful for some.

**Comment by mrkeksi** [comment]
Or move this palm recognition into the settings section. It would surely be well placed there.

**Comment by aogilvie** [comment]
+1 for making this a server setting enable true/false. This is such a niche feature, it just confuses users.

**Comment by MaximilianJacobs** [comment]
A serverside switch is a horribe solution for this. It should be up to the individual user to decide if they need it, not some server admin with no idea what the users hardware looks like.
Either it should be a togglable feature in the client settings or we should preemptively look for touch based input devices being present on the system and only show the icon if there is one.

**Comment by aogilvie** [comment]
If I have to explain to a user what it is, it's badly designed feature.
That aside 99% of client features have server flags - which are treated as an override if necessary dependant on project use case.
My request is in conjunction with OP. I didn't think it warranted an extra ticket.

**Comment by MaximilianJacobs** [comment]
I think there should be 3 determining factors that should be used in order to determine if the button should be displayed:

1. A touch input device is detected
2. User override in the client settings
3. Server override in the config

This is one of those features where disabling it for all users makes no sense. 
But at the same time enabling it for all users also makes no sense.
Palm rejection is nice but it's entirely useless for people who dont have a touch input.
That is why I think users should be given full agency over the feature, but I agree that having this be a button on the sidebar is a weird design choice, it should be in the options.

**Comment by antobinary** [comment]
Looks like there is a way to detect whether device has touch capabilities - thanks for the link @maxjacobs283 

```
function isTouchDevice() {
  return (('ontouchstart' in window) ||
     (navigator.maxTouchPoints > 0) ||
     (navigator.msMaxTouchPoints > 0));
}
```
That would handle `1.` frorm the list above.


> I think there should be 3 determining factors that should be used in order to determine if the button should be displayed:
> 1. A touch input device is detected
> 2. User override in the client settings
> 3. Server override in the config

I am still not super sure I understand 2)  ...
I assume the default would be no toggle button, since it's a niche capability, especially among presenters...
But then would the presenter be supposed to go to Settings -> Allow palm recognition for whiteboard annotation ?

I am not super thrilled on hiding the setting if the device is not considered touch .. There's USB drawing pads, there's laptops with touch screen, I don't think we can correctly detect the environment for all cases. And even for a touch device, very few of them support stylus, so the palm would have no business on the screen...
