### ISSUE TITLE
Generic Embed/Support for ViMP

### ISSUE THREAD

**Issue by MaximilianJacobs** [bigbluebutton/bigbluebutton#12312]
I am working with a client who is using ViMP Video CMS. 
We're trying to embed videos from ViMP into BBB and unfortunately they are unsupported.
It's not an option to embed the mp4 download link because of licensing issues. 

It would be really helpful if BBB could either add support for ViMP Video CMS or for generic embed tags.

The client's BBB Installation is also currently running on 2.2 with Ubuntu Advantage so a backport to 2.2 would be great if this feature was implemented.

**Comment by basisbit** [comment]
For sharing video files, see https://github.com/bigbluebutton/bigbluebutton/issues/8276 .
For sharing / embedding an external website, see https://github.com/bigbluebutton/bigbluebutton/issues/9785 .
There also exists this issue for sharing videos from other online video hosting services: https://github.com/bigbluebutton/bigbluebutton/issues/10861

Regarding 2.2: there will be only security patches for 2.2, no more additional feature will be released for it.

I'll close this issue here because there already exist many issues about mostly the same feature (sharing videos from third-party posting services). Of course pull requests are always welcome.
