### ISSUE TITLE
Poll results not translated upon playback

### ISSUE THREAD

**Issue by hiroshisuga** [bigbluebutton/bigbluebutton#12626]
**Describe the bug**
On v2.3.x, the published poll results are not translated within SVG figures when played back.

**To Reproduce**
1. start a poll either yes/no/abstention or true/false
2. record the session
3. playback and see the results are not translated on the whiteboard.

**Expected behavior**
results are translated

**Actual behavior**
not translated

**Screenshots**
![名称未設定 1](https://user-images.githubusercontent.com/45039819/122632958-e36a2b80-d110-11eb-8c90-8c416cebe298.jpg)

**Additional context**
During the lecture the results are shown translated. The problem happens only when they are recorded.
The new PR of bbb-playback (https://github.com/bigbluebutton/bbb-playback/pull/109/) shows the results correctly in the chat panel. It's not the problem of bbb-playback.

**Comment by pedrobmarin** [comment]
Hi @hiroshisuga , thanks for the feedback!

I did notice that too but that one is harder to translate since it's an SVG image we just plot over the whiteboard canvas. I guess it would be easier to just ignore the whiteboard poll annotation and build something from scratch at the playback using the same data we now fetch from the published polling results.

**Comment by laserrapt0r** [comment]
Can the whiteboard poll annotation be disabled? Via settings.yml or anything? In the past it was not posted to chat but since it is also in chat I don't see a necessity (at least for me) to have it on the whitebaord as well. Public chat can be disabled but in general I think posting to the whiteboard is not optimal.

**Comment by hiroshisuga** [comment]
Making whiteboard annotation optional is one possibility. 
My personal opinion: I prefer the functionality not to be completely removed (it can be removed easily after shown anyway); when students are watching a lecture on smartphones they usually close the chat panel.
