### ISSUE TITLE
ExternalProcessExecutor: Store stderr in a file to debug problems (bbb-common-web)

### ISSUE THREAD

**Issue by gustavotrott** [bigbluebutton/bigbluebutton#12855]
We can't see output error logs from commands executed through `bbb-common-web / ExternalProcessExecutor`.
It would be useful to log the errors to a `tmp file` and let it be accessible to be debugged in case of process exit code different from 0.

Basically:
- It would capture the stderr in memory and;
- if process exit code is different from zero, dump it into a temp file;
- adding the temp file name in error log line.

**Comment by defnull** [comment]
ExternalProcessExecutor is only used by some of the steps. Others use `NuProcessBuilder`, which seems to be a backport (or inspiration) of the standard ProcessBuilder available since Java 7. I also see a lot of repetition and copy&paste in that codebase. Perhaps the whole `org.bigbluebutton.presentation.imp` module could use some attention and should be refactored.
