### ISSUE TITLE
systemd and encrypted /var/bigbluebutton

### ISSUE THREAD

**Issue by M-Stenzel** [bigbluebutton/bigbluebutton#12857]
Hi team,

this is more like a feature request, although supposedly not a brain teaser... 

Since bbb stores recordings in /var/bigbluebutton this directory ideally should be encrypted.
Now I wonder how to implement correctly.
Before the first bbb related process gets started the directory should be available. This means that these processes should not get started beforehand. Mounting the encrypted directory depends on a password, which again relies on sshd.

So the order of systemd should be sth. like this.

1. network
2. sshd
3. truecrypt/bestcrypt/ecryptfs/... software
4. bigbluebutten.

Step 4 must not take place before step 3 and step 3 must not start before step 2

Any help regarding my ideas greatly appreciated.

Martin.

**Comment by basisbit** [comment]
Imho this is not something BigBlueButton specific. Encryption is best done by using full disk encryption instead of only partial encryption, so that an attacker doesn't just have to tamper with the OS and wait for the next time you open the encrypted container. You could for example use [luks](https://www.thegeeksearch.com/beginners-guide-to-luks-disk-encryption-in-linux/) for this.
