### ISSUE TITLE
Fresh install BBB 2.3.9 - 04.08.2021 - bbb-install.sh - docker - ssl

### ISSUE THREAD

**Issue by aguerson** [bigbluebutton/bigbluebutton#12913]
Hi BBB devs,
How are you ?
Just a feedback from the french guy ;)

I Installed a fresh BBB 2.3.9 and I need to give you my feedback. Maybe you don't care, but maybe you could improve some parts.

1) In the script bbb-install.sh ( my big problem ), I didn't find the option to say where to use its own certs. And all the part about he https, the creation of the dhp.pem file, the modification of all the files to take the https weren'n not apply. it resulted that BBB didn't work correctly... Could you imagine in the bbb-install.sh to ask for the 2 mandatory certs ( ssl_certificate and ssl_certificate_key ) and to use the "install_ssl()" func / module. ? Without this mandatory function, BBB can't work correctly. Many companies have their owns certs.

2) I noticed you change the way to use the docker instance with bbb-libreoffice, but I didn't find any doc about this change. In a previous 2.3.x release, the docker instance were launched by a systemd sevice. Now the docker instances are only used to convert the files when it is asked for. May be it is reduce the perf ( I don't known ? ). But some doc about this change could be cool ;), and maybe some feedback about the troubleshoot if it exists ( to update the instance, to unloc some situation / case ).Thanks in adavance for all

3) a last point, I noticed a bad traduction in BBB 2.3.9 in french. I could not change it by myselft because of the compiled js. The bad trad is for the network situation. It is writen "satus de connexion". It could be "status de connexion".

It is always a really good product ;)

A question : Did you plan to integration the background image of the cam in the 2.3.x release ? Or it just for the 2.4.x release ?

Regards,
Aurélien.

**Comment by antobinary** [comment]
This issue is tricky to handle as it contains three very different topics...

> 1. In the script bbb-install.sh ( my big problem ), I didn't find the option to say where to use its own certs. ...

This is a question which is for the bigbluebutton/bbb-install repository ... But the short answer is that there is a `-d` parameter which skips the LetsEncrypt cert creation so you can use your own certs.

> 2. bbb-libreoffice documentation

The information from this pull request might help - https://github.com/bigbluebutton/bigbluebutton/pull/11717 
Feel free to open a new thread in the dev forum https://groups.google.com/g/bigbluebutton-dev if there's specific information you'd [still] like clarified.


> 3. bad traduction in BBB 2.3.9 in french

BigBlueButton pulls its translations from Transifex.com -- any change would have to be done there. Currently the French team translating BigBlueButton there consists of 38 translators and 3 reviewers. We welcome feedback / translation help but essentially rely on the reviewers to make the call on which variation of a translation should be used.
