### ISSUE TITLE
bbb-lti wrong URL (ip instead hostname)

### ISSUE THREAD

**Issue by lonesomewalker** [bigbluebutton/bigbluebutton#12951]
**Describe the bug**
Since BBB 2.3 bbb-lti shows the IP instead the URL of the host

**To Reproduce**
Install bbb-lti, fetch URL.

**Expected behavior**
It should use the hostname, hence SSL issues.

**Actual behavior**
It shows the IP, since somebody decided to also write this to /usr/share/bbb-web/WEB-INF/classes/bigbluebutton.properties and overwrite that later with /etc/bigbluebutton/bbb-web.properties

**Solution**
Either also let the overwrite file take care of the URL for LTI or just writing it also to /usr/share/bbb-web/WEB-INF/classes/bigbluebutton.properties and /usr/share/bbb-lti/WEB-INF/classes/lti-config.properties...

**Comment by lonesomewalker** [comment]
I just realize, this goes much deeper...

/usr/share/bbb-apps-akka/conf/application.conf:
services {
  bbbWebAPI="http://xxx.xxx.xxx/bigbluebutton/api"
Instead the hostname

Seems there is an issue with bbb-conf --setip?
Server is installed by bbb-install.sh

**Comment by PhMemmel** [comment]
Can confirm the akka-apps config "problem", this URL definitely doesn't work (not even on the server itself), especially because "http" is being used instead of "https". On my machine in a NAT environment being set up by `bbb-install.sh` it even shows the local IP of the machine. The server is running fine though as the override file contains the correct URL.

As already stated by @lonesomewalker there also is a wrong entry in `/usr/share/bbb-web/WEB-INF/classes/bigbluebutton.properties which is overriden correctly by `/etc/bigbluebutton/bbb-web.properties`:
`https://xxx.xxx.xxx.xxx` where `xxx.xxx.xxx.xxx` is the local IP.
Note that here `https` is being used, not `http` like in akka-apps conf.

**Comment by lonesomewalker** [comment]
bump.

still open...

**Comment by zhem0004** [comment]
It seems to work normally in 2.6.
When you initially pull bbb-lti and run command "bbb-conf --lti" returns: 
       URL: https://172.17.0.2/lti/tool
  Customer: bbb
    Secret: <secret>

  Icon URL: https://172.17.0.2/lti/images/icon.ico

After you set the value of ltiEndPoint in "/usr/share/bbb-lti/WEB-INF/classes/lti-config.properties" to your host as described in "https://docs.bigbluebutton.org/admin/lti.html" command "bbb-conf --lti" returns:
       URL: https://<host>/lti/tool
  Customer: bbb
    Secret: <secret>

  Icon URL: https://bohdan.bbb-dev/lti/images/icon.ico

**Comment by antobinary** [comment]
@zhem0004 do you think https://github.com/bigbluebutton/bbb-lti/pull/13 has any effect on this?

**Comment by antobinary** [comment]
bbb-lti has been archived. Long live bbb-lti-broker https://github.com/bigbluebutton/bbb-lti-broker
