### ISSUE TITLE
Recordings of rallies have video and audio out of sync 

### ISSUE THREAD

**Issue by IamLuksha** [bigbluebutton/bigbluebutton#13055]
**Describe the bug**
Recordings of rallies have video and audio out of sync.
Are there any ways to solve the problem or minimize the desynchronization?

**To Reproduce**
Record a meeting using a webcam and microphone

**Expected behavior**
No or minimal out of sync in video and sound.

**Actual behavior**
Video and audio desynchronization 1-10 seconds

**Additional context**
server: ubuntu 16.04 (bbb 2.2 latest) and 18.04  (bbb 2.3 latest) 32cpu, 50ram, ssd

**Comment by hostbbb** [comment]
Should move this to bigbluebutton-setup,  large delays of more than a 1sec is a server configuration or upstream bandwidth issue.  Are you using coturn and relaying media.... dropped packets in turn add delay since retransmision occurs of packet.   Submit your server specs, concurrent user and cpu graphs.  Others can assist with helping you debug.

**Comment by IamLuksha** [comment]
Hey
Thanks for the answer

During the rally itself, there is no lag in sound or video.
Lagging sound or video is present only on the recording.
That is, the presence or absence of a turn server does not affect.

I can only tomorrow ..
`Submit your server specs, concurrent user and cpu graphs`
