### ISSUE TITLE
Allow moderator to change the Display name of phone callers

### ISSUE THREAD

**Issue by kaystrobach** [bigbluebutton/bigbluebutton#13065]
**Is your feature request related to a problem? Please describe.**

As a moderator i want to be able to change the name of a caller (via phone) to be able to identify people properly.

**Describe the solution you'd like**

Add option to change name of user via context menu for people using the phone line

**Describe alternatives you've considered**

have no idea.

**Additional context**

We had several meetings with more than 10 people on the phone line, so that it was hard to identify users.

**Long Term goal**

A long termin goal could be to have seperate join codes per user to be able to map users to people joining via the web ui to the ones using the phone to join the session.

**Comment by PhMemmel** [comment]
Related to #12115, might be handled by #12259

**Comment by kaystrobach** [comment]
@PhMemmel what do you think about the long term goal?

**Comment by PhMemmel** [comment]
I could imagine the following:

When joining via HTML5 client the audio modal shows an "external userID specific" phonenumber or access code. If a phone user then calls in with this number/code this phone user can be assigned the `fullName` of the HTML5 client user this specific code has been shown to.

As far as I can tell from looking at the HTML5 client code this shouldn't be too hard to realize. However, I cannot say anything about the part with the specific phone number/access code, because I don't have any clue of freeswitch and `bbb-fsesl-client` :-)

For some edge cases in this scenario feature #12259 probably still would be nice to have.

**Comment by PhMemmel** [comment]
Updated #12259: It's now possible for moderators to rename dial-in users. Feel free to test.
