### ISSUE TITLE
Enable use of Shared notes externally 

### ISSUE THREAD

**Issue by gorlapraveen** [bigbluebutton/bigbluebutton#13165]
**Is your feature request related to a problem? Please describe.**

Enabling shared notes accessibility externally. 

**Describe the solution you'd like**
As BBB uses etherpad for shared notes, enabling external use of shared notes can persist the document. For this enabling the persist option and generating shared link should be considered.

**Describe alternatives you've considered**

**Additional context**

**Comment by ffdixon** [comment]
Currently, there isn't any content in a BigBlueButton session that persists after the session is over.  

This is by design as in a multi-server environment (such as when using Scalelite), the success meetings may launch on multiple servers, and such servers may be added and deleted (once all meetings have ended) at random times.

As such, we don't have any plans to persist the etherpad session beyond the length of the BigBlueButton session.
