### ISSUE TITLE
Recordings quality and size is not predictable

### ISSUE THREAD

**Issue by mikhailnov** [bigbluebutton/bigbluebutton#13408]
BigBlueButton runs ffmpeg to create webcams.webm with the following params:

-deadline realtime
-cpu-used 8

According to https://trac.ffmpeg.org/wiki/Encode/VP9 , it means that the resulting quality and size of webcams.webm will depend from:

* number of threads ($COUNT) set for bbb-rap-resque-worker.service
* server load at a random moment (e.g. number of other meeting running)
* per-CPU core performance of hardware (?)

It is bad because:
* disk usage by recordings will be not well predictable
* the more threads are enabled in bbb-rap-resque-worker.service, the worse quality and the larger size of recordings will be

Recordings processing does not require realtimeness, I suggest to change "realtime" to "good" or "best" and better make it configurable. "-cpu-used" should also be configurable. For example, I run recordings processing on a separate server where webinars are not hold and would prefer to spend more machine time on processing but get better quality and less size of the video to use disk space more efficiently.

"-preset veryfast" for H264 (webcams.mp4) could also be configurable.

**Comment by abautu** [comment]
This would partially undo https://github.com/bigbluebutton/bigbluebutton/issues/2483

The choice for realtime instead of good/best was made because libvpx-vp9 was dead-slow with good/best (more than 6x slower if I recall corectly). The setting only affects the filesize (i.e. changing the speed you will get lower files), becasue the quality is controlled by -crf, which value was selected after a few empirical tests to maintain the video quality around 99%. The same is valid for the MP4 preset, but it's impact on speed is much less dramatic.

So if you process recordings on a separate server (ie. you have extra CPU to spare) and you care about file size (you'll get maybe 20-40% smaller files), you can safely change them to the values you want.

FYI, I disabled webm on my servers. I found it useless to process it since iOS devices don't want it, it is much slower than MP4, and has no extra benefits (i.e. files are not dramatically smaller than MP4). Doing so will save you more disk space than if you do good/best compression on them ;)

**Comment by mikhailnov** [comment]
I agree, without -deadline realtime, processing of webm became extremely slow, I will also just disable webm for now. Hope that Apple's slaves will be allowed to watch vp9 encoded videos some time soon.
