### ISSUE TITLE
Differentiate roles in recordings chat

### ISSUE THREAD

**Issue by jfsiebel** [bigbluebutton/bigbluebutton#13547]
**Describe the bug**
In recordings we don't differentiate between moderators and viewers in recording chat. (MODERATOR and VIEWER are the user's name)

**Screenshots**
![image](https://user-images.githubusercontent.com/2110278/138454341-b23decb6-c628-4d14-8b5c-e016c6dbc5e9.png)

**BBB version:**
BigBlueButton Server 2.4

**Comment by kepstin** [comment]
* The recording processing needs to be updated to include an extra flag on the processed chat xml indicating which messages are emphasised
* The bbb-playback needs to read that flag and use it to bold the appropriate messages.

**Comment by GuiLeme** [comment]
I already did a PR #14227, with my WIP, and I am almost finishing it, but I would like to propose a different and yet better approach to takle this issue.
See, the way it is, the message is only getting the emphasised tag because it has not this property in the moment that it is generated, the result is that we have to process more things and end up not being as efficient as it could. 
Therefore, what I suggest we do is to mark the message with the property `role=xxxx` through akka  and then for the recording, we wouldn't have to check the period when each user was a moderator. Then this would even correct the problem where the chat is updated whenever someone demote a user, and all the messages sent by that user keeps with the same emphasis (either bold, or not).

**Comment by TiagoJacobs** [comment]
> I already did a PR #14227, with my WIP, and I am almost finishing it, but I would like to propose a different and yet better approach to takle this issue. See, the way it is, the message is only getting the emphasised tag because it has not this property in the moment that it is generated, the result is that we have to process more things and end up not being as efficient as it could. Therefore, what I suggest we do is to mark the message with the property `role=xxxx` through akka and then for the recording, we wouldn't have to check the period when each user was a moderator. Then this would even correct the problem where the chat is updated whenever someone demote a user, and all the messages sent by that user keeps with the same emphasis (either bold, or not).

This way akka would "stamp" the message with the role that user had when the message was sent, sounds good!

**Comment by TiagoJacobs** [comment]
Closing this issue in favor of https://github.com/bigbluebutton/bigbluebutton/issues/14243
