### ISSUE TITLE
Menu is behind show hands popup

### ISSUE THREAD

**Issue by crosscodr** [bigbluebutton/bigbluebutton#13580]
**Describe the bug**
Show hands popup covers the main menu, which can prevent users from editing settings etc..

**Expected behavior**
The main menu should always be on top of any popups, since its an explicit user action to open the menu.

**Actual behavior**
The main menu is covered by Popups.

**Screenshots**
![hands_popup_over_menu](https://user-images.githubusercontent.com/20466649/139062681-f7cd6d3a-eb76-4cdd-ad0e-64388320f086.png)

**BBB version:**
BigBlueButton Server 2.3.15 (2482)

**Additional context**

**Comment by tibroc** [comment]
I agree with the before mentioned points and am happy to see that this issue is already assigned.

Additionally, I would like to mention that the current speaker is sometimes hidden behind the pop-up (as seen in the original screenshot). This happens frequently enough to be annoying and we are actually hearing complaints from users about this.

Maybe the pop-up can simply be re-positioned?

**Comment by antobinary** [comment]
@ramonlsouza You fixed this via z-index on 2.4+ via https://github.com/bigbluebutton/bigbluebutton/pull/13152 but we could not backport this to 2.3 (different file) and after a brief attempt with @zhem0004 it looked like the issue was a bit deeper.
When you get a chance could you please take a look and advise?

**Comment by ramonlsouza** [comment]
> @ramonlsouza You fixed this via z-index on 2.4+ via #13152 but we could not backport this to 2.3 (different file) and after a brief attempt with @zhem0004 it looked like the issue was a bit deeper.
> When you get a chance could you please take a look and advise?

Yes, we switched to a different component for the menus in 2.4... Changing the z-index of the [settings-dropdown component](https://github.com/bigbluebutton/bigbluebutton/blob/v2.3.x-release/bigbluebutton-html5/imports/ui/components/nav-bar/settings-dropdown/component.jsx#L287) to 9999 should give the same results in 2.3.
