### ISSUE TITLE
Recordings V0.9.0 slides cannot be played anymore

### ISSUE THREAD

**Issue by jjvanrossum** [bigbluebutton/bigbluebutton#13615]
**Describe the bug**
Discovered the bug in scalelite, so issue already described there. Not sure how this maps to the code of BBB, but it seems the bug exists here in https://github.com/bigbluebutton/bigbluebutton/blob/5189abb225247290d1954e10827853d5fc022b66/record-and-playback/presentation/playback/presentation/0.81/lib/writing.js

for further information, see issue of scalelite:
https://github.com/blindsidenetworks/scalelite/issues/721

**Comment by jfederico** [comment]
It seems to have been found with SL, but the issue is unrelated to it. The recordings are rendered as they are based on BBB playback code. Here @jjvanrossum findings

--------------------------
Additional context
I already narrowed down the issue. The slides are loaded from an SVG, and JavaScript expects the documenttype to be XML. Somehow this has changed recently to be not accepted anymore; see https://blog.yeshere.org/2010/11/xmlhttprequestresponsexml-returns-null.html

In the scalelite-nginx docker container there is the file /var/bigbluebutton/playback/presentation/0.9.0/lib/writing.js there is a line 'var xmlDoc = xmlhttp.responseXML;' wich returns null. when added 'xmlhttp.overrideMimeType('text/xml');' before 'smlhttp.send()' the issue is resolved.
This takes place on lines 245 and 834.

Would be nice if this gets fixed.

**Comment by jfederico** [comment]
@jjvanrossum you reported the issue on 0.9.0 slides and you are pointing to the problem on playback/presentation/0.81, is this affecting both?

**Comment by kepstin** [comment]
This is not a BigBlueButton bug. BigBlueButton servers correctly serve the appropriate mime types for xml and svg files. If this isn't working in scalelite, then the issue is that the nginx server in scalelite is missing some mime type configuration.

**Comment by kepstin** [comment]
Oh, wait, I misread this issue. Is the problem specifically that *SVG* files hosted with the *SVG* mime type are no longer interpreted as XML by the browser? if so this also affects BigBlueButton.

**Comment by kepstin** [comment]
This issue needs some more information. Please reproduce with a recording on a BigBlueButton server, and include information about the Browser vendor and version, and what mime type the file is served with.
