### ISSUE TITLE
When a user leaves a meeting they remain in the User list for 30 seconds

### ISSUE THREAD

**Issue by ffdixon** [bigbluebutton/bigbluebutton#13832]
**Describe the bug**
When a user leaves a meeting they remain in the User list for 30 seconds (it was about 2 seconds in 2.3).

**To Reproduce**
1. Go to demo.bigbluebutton.org (2.4-rc5)
2. Create a new meeting and join as "A"
3. Invite a second user called "B" 
Both "A" and "B" are shown in the Users list

4. Choose "Leave meeting" for "B"

**Expected behavior**
User "B" disappears from the User list in about 2 seconds (this is how long it takes in 2.3)

**Actual behavior**
User "B" will stay in User list for about 30 seconds.

**Screenshots**

https://user-images.githubusercontent.com/290351/144778289-7c4f2d67-84f5-4977-a841-36a23c3d50d1.mp4

**BBB version:**
Tested on demo.bigbluebutton.org (build 2394) and latest dev build 2.3-rc6 (2414).

**Comment by PhMemmel** [comment]
I can confirm. This is especially painful in the context of breakout rooms:

- When you want a user to change a breakout room: You tell him to leave the room and then you as the moderator as well as the the user have to wait about 30s until the moderator can assign a new breakout room to the user.
- If you just left a breakout room (as an instructor) you cannot instantly join again (maybe you forgot to tell the participants something) but have to wait 30s until you're able to rejoin which can be annonying.
- It is very irritating for the moderator, because the users seem to still be in their breakout rooms for a longer time than they actually are, so you suspect some problems. However, the users already have returned, they are just not shown as "back in the main room" according to their icon status in the user list.

**Comment by jacotec** [comment]
I can also confirm this behavior!

**Comment by Tainan404** [comment]
https://github.com/bigbluebutton/bigbluebutton/pull/13531

**Comment by ffdixon** [comment]
Hmm ... 30 seconds is a long time.  This delay is visible in breakout rooms.  

As a user, if I leave a breakout room (close the tab), then click 'Breakout Rooms' on the left-hand side to show the breakout room pane, BigBlueButton will report that I'm still in the breakout room for 30 seconds before it shows a 'join' link to rejoin the breakout rooms.

I know that 30 seconds is an arbitrary time ... is there a lesser time that would still work?

**Comment by PhMemmel** [comment]
I think BBB should differentiate between "user not respoding, maybe reconnecting, waiting 30s" and "user left, not waiting". Is there a possibility for BBB to unregister/kick a user if he actively leaves? This should be triggered when the user leaves a session/breakout room by hitting "Leave session" in the menu as well as when the browser tab is being closed.

**Comment by jacotec** [comment]
I'm not sure if BBB can detect a closed tab, but @PhMemmel is fully right. When a session is actively left (breakout room or the whole conference with "Leave conference" there is **no** reason to wait for the immediate reconnect of this user.

Once he leaves, the user should vanish from the list. If he decides to rejoin it's still possible.

**Comment by spreeni151** [comment]
> I know that 30 seconds is an arbitrary time ... is there a lesser time that would still work?

Entirely my opinion. 10 seconds would be the maximum time I would tolerate in a session.

**Comment by antobinary** [comment]
In 2.4-rc-6 this value will be decreased to 10s #13878

**Comment by antobinary** [comment]
Related https://github.com/bigbluebutton/bigbluebutton/issues/13912
