### ISSUE TITLE
Cursor should allow configuration

### ISSUE THREAD

**Issue by hiroshisuga** [bigbluebutton/bigbluebutton#13896]
**Is your feature request related to a problem? Please describe.**
Currently the size, color, and style of the cursor is hard-coded. I have been stressed when explaining something putting the cursor over a reddish object, because the cursor is hardly visible.
For color blinded people, the red cursor is not ideal. An option to change it to magenta would be useful. Similarly, for those who have weak sight, a larger cursor may be better in terms of accessibility.

**Describe the solution you'd like**
Implementing options to change the size, color, and probably style (using CSS's mix-blend-mode).

**Additional context**
We need to consider where to configure (configuration file or HTML5 UI). But for now adding options in the configuration file would be fine for letting the users to test the function and return feedbacks.

Here is a video explaining the problem.
![cursor](https://user-images.githubusercontent.com/45039819/145671942-d8c99538-58b2-46ce-b7c3-8676a9399e03.gif)

**Comment by antobinary** [comment]
I am reopening the issue. A few days ago @KDSBrowne commented that this should be addressable via tl;draw. I will leave the 2.4 PR from @hiroshisuga closed though, as it is done on the whiteboard that is now obsolete (as of BBB 2.6).

**Comment by ffdixon** [comment]
Thanks again @hiroshisuga for all your contributions -- you pushed us to improve the whiteboard, and we've got a much better whiteboard coming in 2.6 in response.

**Comment by kepstin** [comment]
Note that any implementation of this feature which allows changing cursor during the live meeting should also save the cursor configuration as recording events so the recording will match.

It should be fairly straightforwards to add static cursor configuration settings to the "video" recording format playback.

I'm not sure about how hard it would be to update the "presentation" recording format. That format currently uses a cursor which does not match the live meeting - it is opaque instead of translucent.
