### ISSUE TITLE
WebSocket connection to 'wss://[DOMAIN]/bbb-webrtc-sfu' failed: HTTP Authentication failed; no valid credentials available

### ISSUE THREAD

**Issue by digionline-gmbh** [bigbluebutton/bigbluebutton#13970]
Hi,

we use bigbluebutton for different projects on several domains. Lets say:
bbb.primary.de   (for www.primary.de)
bbb.secondary.de (for www.secondary.de)
bbb.another.de   (for www.another.de)

There is a multi-domain certificate (Let's encrypt) which covers all these domains.

To start the room, we call (from www.secondary.de, after some API calls):
https://bbb.secondary.de/html5client/join?sessionToken=j4xxommhdupwhsac

In v2.3.15 and at least 2.4-rc-4 everything is working as expected.

In v2.3.17 (don't know .16) and 2.4 (release) presentations and audio work - but screen sharing and webcam is broken.

On the error console (chromium) it shows a failed call to wss://bbb.**_primary_**.de/bbb-webrtc-sfu from the room running on bbb.**_secondary_**.de (see below).

So something went wrong in the last two weeks. :-(

Can this be fixed?

Thanks and bye,
Thomas

```
774eacd4364abb4abc676eb47d090741bc03a1e4.js?meteor_js_resource=true:375 WebSocket connection to 'wss://bbb.primary.de/bbb-webrtc-sfu?sessionToken=j4xxommhdupwhsac' failed: HTTP Authentication failed; no valid credentials available
(anonymous) @ 774eacd4364abb4abc676eb47d090741bc03a1e4.js?meteor_js_resource=true:375
openWSConnection @ 774eacd4364abb4abc676eb47d090741bc03a1e4.js?meteor_js_resource=true:375
share @ 774eacd4364abb4abc676eb47d090741bc03a1e4.js?meteor_js_resource=true:375
(anonymous) @ 774eacd4364abb4abc676eb47d090741bc03a1e4.js?meteor_js_resource=true:375
774eacd4364abb4abc676eb47d090741bc03a1e4.js?meteor_js_resource=true:133 [14:39:25:0685] ERROR: clientLogger: WebSocket connection to SFU failed WebSocket.ws.onerror (https://bbb.secondary.de/html5client/774eacd4364abb4abc676eb47d090741bc03a1e4.js?meteor_js_resource=true:375:1445633)
774eacd4364abb4abc676eb47d090741bc03a1e4.js?meteor_js_resource=true:133 [14:39:25:0685] ERROR: clientLogger: Screenshare broker failure: SIGNALLING_TRANSPORT_CONNECTION_FAILED x.handleBrokerFailure (https://bbb.secondary.de/html5client/774eacd4364abb4abc676eb47d090741bc03a1e4.js?meteor_js_resource=true:375:1501310)
774eacd4364abb4abc676eb47d090741bc03a1e4.js?meteor_js_resource=true:133 [14:39:25:0685] ERROR: clientLogger: Screenshare failed d (https://bbb.secondary.de/html5client/774eacd4364abb4abc676eb47d090741bc03a1e4.js?meteor_js_resource=true:375:347727)
774eacd4364abb4abc676eb47d090741bc03a1e4.js?meteor_js_resource=true:133 [14:39:25:0686] DEBUG: clientLogger: Stopped broker session for screenshare l.stop (https://bbb.secondary.de/html5client/774eacd4364abb4abc676eb47d090741bc03a1e4.js?meteor_js_resource=true:375:1448735)
774eacd4364abb4abc676eb47d090741bc03a1e4.js?meteor_js_resource=true:133 [14:39:25:0687] ERROR: clientLogger: Screenshare failed d (https://bbb.secondary.de/html5client/774eacd4364abb4abc676eb47d090741bc03a1e4.js?meteor_js_resource=true:375:347727)
```

**Comment by Buda9** [comment]
I don't know solution, but could it be that we have the same issue? https://groups.google.com/g/bigbluebutton-setup/c/hOMHPFV2uIw

**Comment by prlanzarin** [comment]
Output of `cat /etc/bigbluebutton/nginx/webrtc-sfu.nginx`

**Comment by prlanzarin** [comment]
Actually, now that I read the issue more carefully:
`On the error console (chromium) it shows a failed call to wss://bbb.primary.de/bbb-webrtc-sfu from the room running on bbb.secondary.de (see below).`

Why would an user in BBB server "secondary" be trying to use a webrtc-sfu instance in BBB server "primary"? Not sure I understand your setup tbh.

Just so that you know, for the WS connection to be established the user needs a valid `sessionToken` and a valid JSESSIONID cookie set for the calling domain. That is valid for both webrtc-sfu connections AND audio connections, so if the cookie is not set it wouldn't work for both. That's post RC-5/2.3.17 behavior.

**Comment by digionline-gmbh** [comment]
> Why would an user in BBB server "secondary" be trying to use a webrtc-sfu instance in BBB server "primary"? Not sure I understand your setup tbh.

There is just one server "driving" several domains. primary is the domain configured mainly. The server has a multi-domain certificate for all domains. There are several projects which launch rooms on their domain - so www.secondary.de launches rooms on bbb.secondary.de. We use this setup since over a year, starting with v2.2.

The problem seems to be, that for some reason, the HTML clients sends the user to webrtc-sfu on the primary domain instead of the current in use by the room. I don't know, if this is new or just ignored by the former versions.  But of course, all cookies would be missing then, as they are from a different domain.

> That's post RC-5/2.3.17 behavior.

Is there an option to switch this off as a quick fix?

**Comment by prlanzarin** [comment]
> The problem seems to be, that for some reason, the HTML clients sends the user to webrtc-sfu on the primary domain instead of the current in use by the room. I don't know, if this is new or just ignored by the former versions.

It's not new. The webrtc-sfu domain is set in bbb-html's settings.yml. So if primary is the "main" domain of your setup, that's the one you're probably setting, hence the problem. Audio does work, then, because WS domain is inferred rather than set through config (so it's using secondary rather than primary).

> Is there an option to switch this off as a quick fix?

From the top of my mind: not really AFAIK. That's not really a canonical setup. But I understand your pain. I'll see to it that the websocket URI in inferred in v2.4.1 (no date for that yet).

Until then, either use RC-5 or lower or just split domains/bbb servers. If I think about any other workaround, will let you know.

**Comment by liske** [comment]
To configure multiple domains on a single BBB server we use multiple `server {}` blocks in nginx for each domain. (*Sadly, splitting domains/bbb server is not an option due to scaling reasons*).

As a workaround we are using nginx's subs filter to replace the server's FQDN for the websocket and etherpad urls in the `html5client/join` request by the alternative name (i.e. replace `s://n5116.bbbconf.de` with `s://n5116.bbbconf.example.com`):

```bash
  location /html5client/join {
    # to prevent gzip compressed responses not handled by subs_filter
    proxy_set_header Accept-Encoding "";

    # from /etc/bigbluebutton/nginx/bbb-html5.nginx
    proxy_pass http://poolhtml5servers;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "Upgrade";

    # rewrite FQDN in join response with alternative name
    subs_filter 's%3A%2F%2Fn5116.bbbconf.de%2F' 's%3A%2F%2Fn5116.bbbconf.example.com%2F';
  }
```

This works for BBB 2.3.15 (is not required but doesn't break anything), 2.3.17 and 2.4.0.


A more generic solution might be to use the http `Host` header to build the urls in the settings of the join response. This would ensure that it always matches the url requested by the client.
