### ISSUE TITLE
allowModsToEjectCameras not working when set in bigbluebutton.properties

### ISSUE THREAD

**Issue by misisol** [bigbluebutton/bigbluebutton#14035]
On setting allowModsToEjectCameras in bigbluebutton.properties, closing cameras option does not appear. It only works when setting it through API on creating session.

**Comment by prlanzarin** [comment]
Fixed in https://github.com/bigbluebutton/bigbluebutton/pull/13971

Until next tag lands, workaround:
  - Add ` <property name="allowModsToEjectCameras" value="${allowModsToEjectCameras}"/>` to /usr/share/bbb-web/WEB-INF/classes/spring/resources.xml (like it was done in PR 13971), then restart bbb-web.

**Comment by misisol** [comment]
Thanks for answering. 
There's also another issue with localization of the title for this option. 'Close Cameras' doesn't get translated into other languages ( ex. fa_IR )

**Comment by prlanzarin** [comment]
Needs to be translated in Transifex then pulled into the repo. Not an "issue" in the canonical sense, it's just how the localization flow works.
