### ISSUE TITLE
(Optional) Require consent on joining recorded sessions

### ISSUE THREAD

**Issue by antobinary** [bigbluebutton/bigbluebutton#14077]
We are looking into handling a use case where the requirement is to be _extremely_ clear that the session is recorded.

This includes both collecting consent prior to fully joining (note - auto join webcam or auto join audio will need to wait for the consent)
![Screenshot from 2022-01-12 15-11-30](https://user-images.githubusercontent.com/6312397/149240369-cd8e4d4f-e632-41c6-9634-9834bf10d119.png)

Leave session acts as the three-dots-menu Leave.
Continue closes the modal and proceeds as normal. Please put an additional emphasis on not being able to close the modal without clicking Continue.

Also including a supersize recording indicator with the same intent - making it crystal clear recording is going on.
![Screenshot from 2022-01-12 15-11-39](https://user-images.githubusercontent.com/6312397/149240365-8ff0a111-b76d-4b3a-a5c2-548fd4c135bb.png)

Additional considerations:
1) Not everyone is interested in this UI, so both of these should be disabled by default.
 A `settings.yml` flag like `requireAdditionalRecordingConsentOnJoin` with default value `false` can control the modal.
A `settings.yml` flag like `displayLargeRecordingIndicator` with default value `false` can control the recording indicator.

In the case I am aware of a server-wide configuration suffices. Please comment if there's a different use case requiring per-meeting control of these two.

2) There's a difference between a session being recordable and actively recorded. I believe we need to be enabling this for recordable sessions. I.e. if you join prior to moderator starting the recording (or in between recorded chunks)

**Comment by antobinary** [comment]
Possibly @gustavo-em can help with this one?

**Comment by basisbit** [comment]
Could you please specify the reason for not keeping this outside of BBB UI? I very much like the current solution of requiring the frontend to ask for consent depending on of recording feature is enabled or not, because that makes it much easier to customize the consent process depending on the specific needs.

Asking the user after joining the session currently would be too late, because the current implementation always records if the API request explicitly told BBB to enable the recording feature - the recording is only later "cut" using the recording start/stop button press marker times.

**Comment by TiagoJacobs** [comment]
@gustavo-em please note that this popup must appear on join when the setting `requireAdditionalRecordingConsentOnJoin` is true and a meeting *can be recorded* ( not only when it's **being recorded** ). It's little different from what we understood on our initial discussion.

**Comment by gustavo-em** [comment]
@TiagoJacobs Okay

**Comment by schrd** [comment]
If the user consent for recording is collected in BBB instead of the frontends this could allow people to attend meetings even if they don't give recording consent.

If users does not give consent their microphone, camera, screenshare and public chat should be blocked for these users similar to lock settings instead of forcing a leave. They could listen though and follow the presentation and participate using BBB tools where no individual data is recorded like polls, private chat, shared notes.

If BBBs recording would be improved in a way that it only records personal data/media when the recording is active, then the user experience could be further improved. The lock settings would only have to apply as long as content is recorded. Users could change their opinion during the session and give recording consent later so the locks are released. In a lecture scenario the instructor may record the lecture but not the Q&A. People who did not give consent could still use their microphone or the public chat in the Q&A part.

**Comment by antobinary** [comment]
Update - we're iterating over the designs and the role of this modal.
I have marked the pull request as draft as we won't be merging it as-is.

In the coming days we'll try to make public the latest iteration of @tylercopeland 's design.
A key part to stress is that this is **not replacing consent collection prior to navigating to BBB**. I realize the screenshot on the issue description somewhat implies that. In the latest stage (as far as I know), the role of this modal is shifted more to be a _reminder_ that a recorded portion of the meeting commences.

**Comment by gustavo-em** [comment]
After user reloads page, the popup is appearing again, is it a desitable behavior? @antobinary

**Comment by worldthumbler** [comment]
If only the presenter/moderators were to be recorded there would be no need to ask for consent (from the other users). This would  avoid problems from contributions.

Nonetheless, the optimization proposed by @schrd to only record data when recording is set active is very important.

**Comment by basisbit** [comment]
@antobinary yes, see #9202
