### ISSUE TITLE
Recordings timeline in hours of the day

### ISSUE THREAD

**Issue by ClemRiviere** [bigbluebutton/bigbluebutton#14119]
Currently, recordings timeline is just a timer increasing from 0:00 to the duration of the meeting.

Do you think it is technically possible to have a timeline related to the time of the day ? 

Let's have an exemple : the meeting began at 12:00 and I want to watch something happened at 12:47. Currently, I need to go to "0:47" on the timeline. What I want is to go to "12:47" instead.

Maybe this is not a good idea but is it possible to modify this in the recordings creation process and / or the replayer ?

Any suggestion/idea is accepted.

**Comment by ClemRiviere** [comment]
Any ideas / remarks on this topic ?

**Comment by hostbbb** [comment]
The meeting start is in the metadata.xml...  but if you hit start/pause a few tines in the meeting.  You get one combined recording.  So implementing just in the player works be hard... since the recording segments timestamps would need ro be calculated in recording scripts.

One thought... may be easier to modify the mp4 scriptd @danielpetri1 created... and emboss the actual time in bottom right of video as overlay.    So you could advance the video and see time..  only works for single timezone
