### ISSUE TITLE
Clear raise hand after voice active

### ISSUE THREAD

**Issue by PavelZ-creator** [bigbluebutton/bigbluebutton#14204]
**Is your feature request related to a problem? Please describe.**
Participants often forget to put their hand down after they made their comment.

**Describe the solution you'd like**
Raise hand could be cleared automatically after voice input gets registered from the user.

**Describe alternatives you've considered**
Making it more obvious for the user that his hand is raised (e.g. moving the button to the center, changing it's color, add notification).

**Additional context**
- A certain threshold of minimal voice duration should probably be included. This would eliminate accidental clearing in case someone has their microphone on before he gets acknowledged. The feature as well as the threshold could be part of global config settings.
- Teams and some other conference systems have this useful functionality.

**Comment by antobinary** [comment]
Hi @PavelZ-creator ,
Thank you for this enhancement request!

> Raise hand could be cleared automatically after voice input gets registered from the user.

I am not sure if this behind-the-scenes logic would be as robust as it may sound. Often times when I have my hand raised and try to start speaking someone else interrupts me (person who did not even raise hand :sweat_smile: ) and I stop and wait for a better opportunity. If the suggestion was implemented, my raised hand would be automatically lowered and I'd be losing my spot in the sorted-by-time-of-raising-hand queue.
If we were to go that route, though, I'd recommend trying to detect a sequence like

`unmute, gap of no more than 3 seconds, speaking duration of at least a few seconds, mute`

to avoid false positives like noisy environment, interruption right at the start of asking the question, etc. I'd also say a notification to the user saying 'your hand was lowered automatically because the system detected you spoke, raise hand again if you want to ask another question' or something like it might be justified.



> Making it more obvious for the user that his hand is raised (e.g. moving the button to the center, changing it's color, add notification).

Personally, I think this approach is more promising. I'd hope to see a combination of 
- a larger/clearer visualization of the queue
- a system like suggested in https://github.com/bigbluebutton/bigbluebutton/issues/12185 where possibly a question would be typed up by the student, visible to others, and possible to upvote to increase the priority of the question
- possibly a _prompt_ asking the student after voice was used whether the raised hand can now be lowered (i.e. if the question was fully asked).

I am just not sure if detecting the speaking of active voice [ even for 4-5-6 seconds ] is reliable enough to automatically lower the hand.

**Comment by alinastolzenburg** [comment]
This is one of the problems I have most often in teaching!
I think the problem of the microphone being turned on at the same time as another person and then lowering the hand can be solved by lowering the hand only after 5 seconds of open mic.

**Comment by g550** [comment]
I agree with @alinastolzenburg. The potential problem of a person who has raised their hand but accidentally opens their mic seems to be a rather theoretical occurrence – as opposed to people forgetting to lower their hands which basically happens in every single session. Having fewer raised hands shown would also mitigate the problem of the raised hands-popup overlapping with webcams

**Comment by dreamflasher** [comment]
This is being done both at Zoom and Jitsi, so it's apparently possible (and it works reliably there). And with Jitsi there is even an open source implementation to copy.

**Comment by ffdixon** [comment]
I think there is merit in what you are suggesting for automatically lowering the raise hand.  We'll look at this for a future update to BigBlueButton.

**Comment by alinastolzenburg** [comment]
> Meiner Meinung nach hat Ihr Vorschlag, die Raise-Hand automatisch zu senken, durchaus seine Berechtigung. Wir werden uns dies für ein zukünftiges Update von BigBlueButton ansehen.

The problem has increased in version 2.7 because the button to lower the hand is more difficult to reach. Are there any plans to implement my suggestion?
