### ISSUE TITLE
Consistent design of the Share WebCam dialog 

### ISSUE THREAD

**Issue by scheff** [bigbluebutton/bigbluebutton#14206]
**Is your feature request related to a problem? Please describe.**
When sharing a WebCam for the first time, the Share WebCam dialog only shows the "Start Sharing" button. To cancel the sharing, you must click on the "X" in the upper right corner of the dialog.

But when changing the WebCam settings (selecting a different camera, resolution or virtual background), only the "Stop sharing" button is displayed in the same dialog. Now changes have to be applied via the "X" in the upper right corner of the dialog.

**Describe the solution you'd like**
A function should never have to be selected - neither positively (accept), nor negatively (cancel) - by closing a dialog:

- When sharing a WebCam for the first time, a 'Cancel' button should be displayed in the Share WebCam dialog in addition to the existing 'Start sharing' button.
- When changing the WebCam settings, two additional buttons 'Apply changes' and 'Cancel' should be displayed in addition to the existing 'Stop sharing' button.

**Describe alternatives you've considered**
There is no alternative to consistently designed dialogs. ;-)

**Additional context**
The inconsistency was noticed by a visually impaired person during a test with a screen reader.

**Comment by prlanzarin** [comment]
> But when changing the WebCam settings (selecting a different camera, resolution or virtual background), only the "Stop sharing" button is displayed in the same dialog. Now changes have to be applied via the "X" in the upper right corner of the dialog.

That's not correct. Changes are applied _on action_ (if you click to change your virtual background, the background is changed in that moment; if you click to share a new camera, the camera is shared in that moment).

The pattern is different, yes, mainly due to technical reasons.
See: https://github.com/bigbluebutton/bigbluebutton/issues/14113
https://github.com/bigbluebutton/bigbluebutton/pull/13818#issuecomment-985048994

In both places I give the rationale _and_ mention that video-preview will probably undergo a restructuring once someone provides a better spec. When that moment comes, that will be registered into an actual issue. For the moment, this is a duplicate and a wontfix, sorry.

>  The inconsistency was noticed by a visually impaired person during a test with a screen reader.

I'll bring that up internally to see if the fact that actions being applied _on click_ can be made clearer to screen readers.

**Comment by scheff** [comment]
> That's not correct. Changes are applied on action

I'm sorry, you are right. The point is that an explicit button was expected, not just the X in the top right corner.

**Comment by scheff** [comment]
if I may add: 

The fact that settings changed in the dialog in the main window of BBB have an immediate effect cannot be communicated by screen readers and is also difficult to notice for visually impaired people.
