### ISSUE TITLE
Allow user to upload own webcam virtual background

### ISSUE THREAD

**Issue by antobinary** [bigbluebutton/bigbluebutton#14249]
**Is your feature request related to a problem? Please describe.**
We have received numerous requests to add support for end users to be able to upload their own virtual background [ to be used as a background in their webcams ] during the session. 

This issue is a placeholder for those who have more specific ideas or designs.

**Describe the solution you'd like**
~~Within the webcam share preview window~~ (see @prlanzarin 's comment below) allow for upload of a background image.

**Describe alternatives you've considered**
BigBlueButton 2.4+ supports backround images provided on the server which can be managed by the server administrators (see https://github.com/bigbluebutton/bigbluebutton/issues/12937 )

**Additional context**
* Needs to respect `virtualBackgroundsDisabled=true`, see https://github.com/bigbluebutton/bigbluebutton/issues/13964
* Needs a new config to allow (or not) upload of backgrounds from end users. Could be a bbb-web property or settings.yml, suggestions are welcome. Likely good idea to keep it consistent with the other related parameters
* ~~Need to think of how to handle max file size or dimensions of the background image~~ (see @prlanzarin 's comment below)

**Comment by maxjacobs283** [comment]
Is the Image Segmentation Algorithm run serverside? If not, why not just create a link to a local file and store the settings in a cookie, so if run from the same machine, BBB tries to load that same local file and notifies the user if it doesn't exist. 
IMO There is no need to allow the users to upload anything to the server if only this one person is ever going to be served the file.
You could even consider allowing to add a custom image URL.

**Comment by prlanzarin** [comment]
> Is the Image Segmentation Algorithm run serverside? If not, why not just create a link to a local file and store the settings in a cookie, so if run from the same machine, BBB tries to load that same local file and notifies the user if it doesn't exist. IMO There is no need to allow the users to upload anything to the server if only this one person is ever going to be served the file. You could even consider allowing to add a custom image URL.

It isn't. That's why we said the "upload" is client-side only (see the addendum to the issue description + the  previous comment).

**Comment by maxjacobs283** [comment]
A local solution needs to make sure that the configuration is stored between sessions, a user does not typically want to go into settings and click on the same file over and over, especially with 1-2 hour long, back to back meetings.

It would also need to ensure that BBB does not crash if the local file is missing because it was moved or deleted.

Regarding the position of the background selection UI, using a setup similar to Teams, Google Meet or Jitsi Meet will typically be familiar to Corporate Users, but not to University Students. Discord is implementing the same Library as BBB is and places the Background selection into a dialogue similar to how it is implemented for BBB, as such this will be the first point of contact with this Feature for a lot of younger users, predominantly in the education sector.

**Comment by defnull** [comment]
To preserve custom images between meetings, the easiest way would be to store image metadata as well as the entire image (encoded as a data-URI) in localStorage.
