### ISSUE TITLE
Export Shared Notes with meaningful name

### ISSUE THREAD

**Issue by antobinary** [bigbluebutton/bigbluebutton#14342]
Right now we save the file with filename that looks like:
`[2]1f7c561e7ca5e86811bce14c69a70b8e433c.pdf` or `.txt` etc

The name does not correspond to the meeting name.

Suggested format:
<meeting name>-<YYYYMMDD-(hour minute second)-shared-notes>

**Comment by pedrobmarin** [comment]
I believe this is the same as https://github.com/alangecker/bbb-etherpad-plugin/issues/4

As far as I looked into, must be done at Etherpad.

**Comment by pedrobmarin** [comment]
> Thanks! Ooops, I did not search the closed issues... Do you expect anything to change (in this area) in the coming months?

The problem is that Etherpad does not know that it is serving a pad for a BigBlueButton meeting that has another name, etc... the file Etherpad exports is named after the pad's id.

After bbb-pads, the pad naming went to a different direction. I believe the file will now be called `notes.(txt/pdf/odt...)`. So maybe we could check if that's enough for now.
