### ISSUE TITLE
Maintain the default presentation as the current while uploading new documents via insert API.

### ISSUE THREAD

**Issue by GuiLeme** [bigbluebutton/bigbluebutton#14431]
**Describe the bug**
As mentioned [here](https://github.com/bigbluebutton/bigbluebutton/pull/14264#issuecomment-1047104457) by @sualko, it would be  great to be able to upload some new documents without changing the old one. As for now, the `current = false` is the same as if there is no `current` attribute, which is a reasonable scenario except for when all the presentations has  `current = false`, in that case, the expected behavior should be not to change the old current document.

**To Reproduce**
1. Build a payload with a bunch of documents for the `insertDocument` endpoint;
2. Set `current = false` in each of them;
3. Send the request.

**Actual behavior**
The actual behavior is that the first document will have its `current` attribute set to true, and therefore, the current presentation will change.

**Expected behavior**
As discussed above, this scenario should not change the current presentation.

**Additional context**
In this [comment](https://github.com/bigbluebutton/bigbluebutton/pull/14264#issuecomment-1047614842), it was mentioned some possible flickering problem when sending a bulk upload of documents. This could be fixed here too, since both the context and endpoint are the same.

# Edit:
**Context**

Yesterday on the 22/02/2022 at our weekly Dev call, the team discussed a little bit about this issue and somethings related to it. We came to some conclusions that are going to be specified down below. 

**New demands**
1. The `InsertDocument` endpoint is not going to have the possibility to set a presentation as current already in the payload, on the grounds that, as discussed, it would be inconvenient for the presenter to have his document changed in the middle of the presentation.
2. As it is not possible to set a document as current anymore, we talked about setting a toast to both inform the user that the presentations have been uploaded, and let the presenter to choose whether to change the current document or not.
3. And for the last but not the least: it is mandatory that the `InsertDocument` endpoint must warn/inform the presenter that the presentations are being uploaded (This is likely to be happening already, but I am noting it down, just for the record.).

**Comment by sualko** [comment]
Thanks for opening this issue. Just for the background what I mean by flickering. Imagine a scenario where students are creating some kind of presentation outside of BBB and if they are finished the click "share" to upload their presentation to BBB, so that the teacher can show different example/solutions/ and so on. With the current implementation, every time a presentation is uploaded, the presentation will change. This is probably not intended and will result in "flickering" (presentation A is shown for 2 sec, than presentation B for 1 sec, ....).

**Comment by GuiLeme** [comment]
> Thanks for opening this issue. Just for the background what I mean by flickering. Imagine a scenario where students are creating some kind of presentation outside of BBB and if they are finished the click "share"...

Ohh, now I get it, I will dig into that, for sure. Thank you for clarifying that to me.

**Comment by antobinary** [comment]
Heads up - we discussed internally, @GuiLeme updated the issue description. Writing this as a comment so @sualko is notified of the change. Thank you for bringing this up, @sualko !! :rocket: 
By us refactoring how we set 'current' and making it more intentional and end-user-driven, rather than system-driven, I think we should avoid the flickering and the undesired presentation changed. Please comment if anything else needs tweaking to make your upcoming changes easier

**Comment by TiagoJacobs** [comment]
> And for the last but not the least: it is mandatory that the InsertDocument endpoint must warn/inform the presenter that the presentations are being uploaded (This is likely to be happening already, but I am noting it down, just for the record.).

As we discussed this morning, to notify the user that "a presentation is being converted" we will need a new message in akka, while to notify that "new presentation is available" will be a simpler implementation.

Considering this, I think that for a first iteration we can just warn the presenter when the conversion is done.

- Example: "A new presentation is available: XXX.PDF"

What you guys think about it?
