### ISSUE TITLE
Dial-in users not removed from viewer's user list

### ISSUE THREAD

**Issue by zhem0004** [bigbluebutton/bigbluebutton#14464]
**Description**
Phone users are not being removed from viewer's user list when they leave

**To Reproduce**
1. Create meeting
2. Join as viewer
3. Join as dial-in user
4. Hang up as dial-in user

**Expected behavior**
Once dial-in user hangs up their name should be removed from user list

**Actual behavior**
For viewers the name of dial-in user stays in user list even after dial-in user has left. (name will be removed if youreload the page)

**Screenshots**
An example where "bohdan"  is a dial-in user who has left the meeting

![Screenshot from 2022-02-24 15-35-21](https://user-images.githubusercontent.com/80958763/155730034-a6a42569-fdc2-4405-b7a0-a8e1f6854f90.png)

**BBB version:**
2.5

**Desktop **
 - OS: Ubuntu 20.04
 - Browser: Chromium

**Comment by ramonlsouza** [comment]
Hello @zhem0004 I tried to reproduce it locally with sipp and it worked as expected (user was removed from userlist when the script finished).

https://user-images.githubusercontent.com/3728706/157261386-01652b28-308c-4fcb-8c06-c0aba4e4c327.mov

Could you please try to reproduce it again with the latest changes? We had 2 PRs with changes in userlist after the issue was reported (#14445 and #14518)... The bug might be fixed by one of them.

**Comment by antobinary** [comment]
@zhem0004 what is the current status on this?

**Comment by zhem0004** [comment]
The issue is no longer present. Dial-in user is removed from user list on hang up
