### ISSUE TITLE
Improve the control and display of toast messages

### ISSUE THREAD

**Issue by antobinary** [bigbluebutton/bigbluebutton#14493]
[details to follow, I am creating this as a placeholder]

**Comment by gustavotrott** [comment]
Currently each component that need to send notification has a different logic for it.
In general, the component tracks a Collection in `mongodb`. When something is changed it needs to compare with last version and decide if it is time to show a notification or not.

![current-toast-appoach](https://user-images.githubusercontent.com/5660191/156207141-acffa801-5507-40fc-b5c4-8cc533f9e4e8.png)


Cons:
- Each component has a different logic and use a different Collection for it
- It requires a lot of work each time a new notification is needed
- Mongo "garbage" data only for controlling the notifications
- Several components monitoring different Collections may result in performance loss

The idea is to set a new pattern for creation of Toast Messages.

**Comment by gustavotrott** [comment]
@Tainan404 said we could use Meteor's Low-Level Publications API as solution for it.
http://richsilv.github.io/meteor/meteor-low-level-publications/

If I understood well, the idea is to eliminate all the dependency on mongo. And it would result in something like this:
![new-toast-appoach](https://user-images.githubusercontent.com/5660191/156208308-92f960db-9d41-44c3-9a40-603956a1e057.png)

Pros:
- Only one generic component could handle notification instead of different components do it
- Much easier for Meteor API send notifications (once the UI part can be reused)
- Only users that are online at the moment of the publication of the notification  will receive it

**Comment by gustavotrott** [comment]
### New approach proposal

- **Akka** will be liable for sending notifications (instead of bbb-html5-backend + bbb-html5-frontend)
- **Redis** will be used as channel for notifications (instead of mongo Collections)
- **bbb-html5-frontend** will have a generic Component liable for all notifications (instead of each component manages its notifications)

![redis-toast-logic2](https://user-images.githubusercontent.com/5660191/156552868-6ae6b411-859c-4a09-9a29-29916e926b36.png)

### New msgs to be sent from Akka to bbb-html5-frontend (**from-akka-apps-frontend-redis-channel**)
#### Msg to All users
```
NotifyAllInMeeting  (meetingId, type, icon, messageId, messageValues)

e.g:
type: 'info'
icon: 'promote'
messageId: 'app.chat.breakoutDurationUpdated'
messageValues: ['20']

In en.json:
"app.chat.breakoutDurationUpdated": "Breakout time is now {0} minutes",

Final msg:
"Breakout time is now 20 minutes" (each user will see in their language)
```

#### Msg to specific user
```
NotifyUserInMeeting (meetingId, userId, type, icon, messageId, messageValues)
```

#### Msg to specific role (e.g only for Moderators)
```
NotifyRoleInMeeting (meetingId, role, type, icon, messageId, messageValues)
```

**Comment by antobinary** [comment]
@Tainan404 did a big chunk of this and sent #14579 
Let's have @ramonlsouza continue on top of the changes, please
