### ISSUE TITLE
[2.5-alpha3] Meeting crashes when trying to end

### ISSUE THREAD

**Issue by PhMemmel** [bigbluebutton/bigbluebutton#14545]
**Describe the bug**
Meeting is not ending properly but crashes.

**To Reproduce**
1. Open meeting.
2. Click on three dots menu, choose "End meeting"
3. HTML5 client crashes, see screenshot

**Screenshots**
![grafik](https://user-images.githubusercontent.com/65113153/157089802-7e209b19-00fe-4291-83da-44add0a705ae.png)

**BBB version:**
Current version of test25.bigbluebutton.org, version info shows 2.5-beta2, client build 82, but probably it's already beta3?

**Additional context**
Tested just now on test25.bigbluebutton.org

**Comment by antobinary** [comment]
Thanks for reporting! test25 server is at version 2.5-alpha-3

**Comment by PhMemmel** [comment]
> Thanks for reporting! test25 server is at version 2.5-alpha-3

Then the wrong version information is another issue :-)

**Comment by antobinary** [comment]
The fix for the endMeeting issue will be part of 2.5-alpha-4.

The different version you saw is likely a mistake on my part. After a bbb-install re-run there I see the correct version, even though bbb-html5 package was not upgraded... I upgraded test25 before the official alpha-3 release (to get some final testing), which may have been done prior to the change where we update the version...I will keep an eye out for this one.
