### ISSUE TITLE
Smart layout doesn’t fit the screen best with screensharing

### ISSUE THREAD

**Issue by einhirn** [bigbluebutton/bigbluebutton#14691]
**Describe the bug**
When a user starts screensharing, smart layout doesn’t recognize the resolution of shared window properly. The layout is always top/bottom even when the shared window is not wide. There is no change if the user hides the chat and the participant list. When the user switches to custom layout and back to smart layout the resolution of screensharing video is recognized and the layout is okay.   

**To Reproduce**
1.     Join a meeting with user A and B and set layout to smart layout
2.     User A starts screensharing with a slim window
3.     User B gets a top/bottom screen layout
4.     User B switches to custom layout and back to smart layout
5.     User B gets a left/right screen layout  

**Expected behavior**
When a user starts screensharing the smart layout fits the screen best for all users

**Actual behavior**
The shared screen is always displayed under the webcam areas 

**BBB version:**
2.4.4

**Comment by antobinary** [comment]
Thanks for reporting this!
As far as I know, if a window(or tab) is shared, rather than screen, the dimensions of the screenshare area may actually change during the sharing. I am not sure if attempting to adjust the layout during such session would be desired. I wonder if @prlanzarin or @ramonlsouza would like to comment...

**Comment by prlanzarin** [comment]
> Thanks for reporting this! As far as I know, if a window(or tab) is shared, rather than screen, the dimensions of the screenshare area may actually change during the sharing. I am not sure if attempting to adjust the layout during such session would be desired. I wonder if @prlanzarin or @ramonlsouza would like to comment...

Well, it's definitely not a bug as it arbitrarily fills the presentation area with "letterboxing" by design - so rather a feature request.

Probably could be done by hooking into the `resize` event of the HTMLMediaElement playing the screen stream and then shoving that into a tracker of sorts that outputs the element's width and height for the layout to consume.
I'm not sure it's worth the trouble. If it's guaranteed to have no performance drawbacks and doesn't make the client UI jumpy somehow, I don't think I would oppose.

**Comment by einhirn** [comment]
Thanks for your thoughts on this, of course antobinary is right that a size change could happen at any time. But that's not what I was talking about:

Usually a presenter does not change the size of the shared window during the presentation. Therefore, this probably does not have to be permanently checked and the layout adjusted. I only ask that the size of the shared screen or window is determined at the beginning of the sharing and that the layout (in Smart Layout mode) is optimised for it, as it happens when switching to a new PDF presentation.
This adjustment of the layout to the initial size of the share does not happen for us, as described above. But maybe this is also due to autoSwapLayout=true?
The fact that you get a different result when you switch from smart layout to custom layout and back is definitely a bug in my opinion.
