### ISSUE TITLE
2.5 alpha 5 post install kurento/mediasoup problem

### ISSUE THREAD

**Issue by markginter31** [bigbluebutton/bigbluebutton#14710]
**Describe the bug**
Post installation, non local media types fail, ie- a user not on the local network cannot share or see webcams
**Installation type**
Did you install manually or did you use the bbb-install script?
Bbb-install script
**Firewall and IP address type**
Is your server behind a NAT or firewall? Does your BBB server have its own IPv4 addres?
Behind a nat

**Additional context**
The installation script seems to skip two places that the external ip needs to be set.
In /usr/local/bigbluebutton/bbb-webrtc-sfu/config/default.yml there were two options for "announcedIP" both were set to my local network (I'm behind NAT) so I changed them to my public facing IP -- now it works. So it looks like (for me) the 2.5 install did fine except for setting those two announcedIP settings.

**Comment by antobinary** [comment]
These seem to be the lines currently involved in configuring `announcedIP`

https://github.com/bigbluebutton/bigbluebutton/blob/v2.5.x-release/build/packages-template/bbb-webrtc-sfu/after-install.sh#L19-L20

but the actual miconfig is likely coming from https://github.com/bigbluebutton/bigbluebutton/blob/v2.5.x-release/build/deb-helper.sh#L200-L212

@markginter31 I wonder, if you run the following (which is a copy of https://github.com/bigbluebutton/bigbluebutton/blob/v2.5.x-release/build/deb-helper.sh#L200-L212 + an echo line)

```
if [ -e "/sys/class/net/venet0:0" ]; then
    # IP detection for OpenVZ environment
    _dev="venet0:0"
else
    _dev=$(awk '$2 == 00000000 { print $1 }' /proc/net/route | head -1)
fi
_ips=$(LANG=C ip -4 -br address show dev "$_dev" | awk '{ $1=$2=""; print $0 }')
_ips=${_ips/127.0.0.1\/8/}
read -r IP _ <<< "$_ips"
IP=${IP/\/*} # strip subnet provided by ip address
if [ -z "$IP" ]; then
  read -r IP _ <<< "$(hostname -I)"
fi
echo "final IP: $IP"
```

What would be the final IP?

**Comment by prlanzarin** [comment]
> but the actual miconfig is likely coming from https://github.com/bigbluebutton/bigbluebutton/blob/v2.5.x-release/build/deb-helper.sh#L200-L212

As per the pattern since 2.4, packages only configure the local IP. Configuring the correct external IP (when there's NAT or the public IP is not on the default network interface) has been the role of bbb-install up until now.

If we are to follow the existing pattern, what's missing is an analogous of https://github.com/bigbluebutton/bbb-install/blob/dc330a7603b6eae6794b0124b69511fe3b900cea/bbb-install-2.5.sh#L635 for mediasoup in bbb-install. The value of `$IP` there is generally the correct one and it would suffice for bbb-install to set `mediasoup.webrtc.listenIps[0].announcedId $IP` and `mediasoup.plainRtp.listenIp.announcedIp $IP` in /etc/bigbluebutton/bbb-webrtc-sfu/production.yml.

If we are to change that pattern so that the packages already ship with the correct IP, then the logic in https://github.com/bigbluebutton/bbb-install/blob/dc330a7603b6eae6794b0124b69511fe3b900cea/bbb-install-2.5.sh#L381-L453 should be ported somehow to the aforementioned deb-helper script.

I'm not sure what's the preferred approach here.

**Comment by markginter31** [comment]
@antobinary - running that script --> final IP: 192.168.76.6 -- So, I can confirm that it only finds the local ip and not the public facing ip.

**Comment by antobinary** [comment]
Resolved by @prlanzarin in https://github.com/bigbluebutton/bbb-install/pull/503
