### ISSUE TITLE
BigBlueButton web version not working if 'Enhanced Security Mode' is enabled in MS Edge

### ISSUE THREAD

**Issue by htcfreek** [bigbluebutton/bigbluebutton#14717]
## System details
Operating system: Windows 10 21H2 x64 German
Browser: Microsoft Edge v98

## Problem description
The web version of the meeting software BigBlueButton isn't working anymore if I enable the 'Enhanced Security Mode' and set it to 'balanced' or higher. Then the web page is showing only a loading screen after logging in. This is happening for the instance on test.bigbluebutton.org and self hosted instances.

### Expected behavior
After entering the name the meeting space is loading/showing.

### Actual behavior
After entering the name I see only a blue page.

## Screenshot

![image](https://user-images.githubusercontent.com/61519853/161216637-713a3943-39d9-4a6d-b6a9-06d6b9369f8e.png)

## Additional notes

- I have sent a feedback containing a screenshot and an diagnostics/failure record from the feedback menu within the browser to Microsoft.
- I opened a discussion on the Microsoft Edge Insider community: https://techcommunity.microsoft.com/t5/discussions/bigbluebutton-not-working-if-enhanced-security-mode-is-enabled/m-p/3273421

**Comment by basisbit** [comment]
How did you `enable the 'Enhanced Security Mode' and set it to 'balanced' or higher? Do those settings maybe block JavaScript or block WebRTC or similar?

**Comment by basisbit** [comment]
Google did help find that setting. This is what the web developer console from the Microsoft branded Chromium reported:
![image](https://user-images.githubusercontent.com/10870269/165426585-e6aacd55-2641-41cd-bc63-a9d763589fc8.png)

The response of the join?sessionToken=x request returned code that includes `wasm-check.min.js`, which then contains a reference to `WebAssembly`. However [the documentation from Microsoft](https://docs.microsoft.com/en-us/deployedge/microsoft-edge-security-browse-safer) states this:
![image](https://user-images.githubusercontent.com/10870269/165426971-ee34189b-665b-4879-8f75-9225b209ea8e.png)

So, to resolve this issue for your own use case, add the address of your BigBlueButton service to your webbrowser's list of exceptions, as described [here](https://docs.microsoft.com/en-us/deployedge/microsoft-edge-security-browse-safer#exception-site-list). Besides that, BigBlueButton HTML client could be improved to add a detection for if WebAssembly is not defined, and if that is the case, show an error message to the user, asking them to add the current website to the above mentioned exceptions list, so that WebAssembly can be used.

WebAssembly is a standardized technology used by many websites nowadays to allow for a website to be fast / with good performance even if it does complex stuff (like handling webcam video streams or similar). Just disabling support for WebAssembly without a `This website requires WebAssembly, do you want to enable and load it?`, and thus ignoring web-standards in my opinion is not a helpful measure.

**Comment by htcfreek** [comment]
> How did you `enable the 'Enhanced Security Mode' and set it to 'balanced' or higher`? Do those settings maybe block JavaScript or block WebRTC or similar?

@basisbit 
Thank you for the provided information.

To answer your question: We configured it by using [the gpo](https://docs.microsoft.com/en-us/deployedge/microsoft-edge-policies#enhancesecuritymode) which has the same effect as configure it in the settings ux. 

The workaround we used is to add the url of the BBB instance to the bypass list. You can do that with a [GPO](https://docs.microsoft.com/en-us/deployedge/microsoft-edge-policies#enhancesecuritymodebypasslistdomains) or in the settings ux.

![image](https://user-images.githubusercontent.com/61519853/165484124-1ad7a08d-0bec-451f-85fb-8e774586a4b7.png)

**Comment by lishouxin** [comment]
> > How did you ? Do those settings maybe block JavaScript or block WebRTC or similar?`enable the 'Enhanced Security Mode' and set it to 'balanced' or higher`你是怎么做到的？是不是设置了阻止JavaScript或阻止WebRTC或类似的设置？ `enable the 'Enhanced Security Mode' and set it to 'balanced' or higher`
> 
> @basisbit Thank you for the provided information.感谢您提供的信息。
> 
> To answer your question: We configured it by using [the gpo](https://docs.microsoft.com/en-us/deployedge/microsoft-edge-policies#enhancesecuritymode) which has the same effect as configure it in the settings ux.回答你的问题：我们通过使用具有与在设置界面中配置相同效果的组策略对象进行配置。
> 
> The workaround we used is to add the url of the BBB instance to the bypass list. You can do that with a [GPO](https://docs.microsoft.com/en-us/deployedge/microsoft-edge-policies#enhancesecuritymodebypasslistdomains) or in the settings ux.我们使用的解决方法是将BBB实例的URL添加到绕过列表中。您可以通过GPO或设置界面来完成。
> 
> ![image](https://user-images.githubusercontent.com/61519853/165484124-1ad7a08d-0bec-451f-85fb-8e774586a4b7.png)

This setting is also not acceptable
