### ISSUE TITLE
Demoted user can access the shared notes editor

### ISSUE THREAD

**Issue by Tainan404** [bigbluebutton/bigbluebutton#14757]
**Describe the bug**
An user that was moderator and is demoted to viewer can access and edit in shared notes

**To Reproduce**
1. Join with two moderators
2. demote one to viewer
3. access the shared notes with the demoted user

**Expected behavior**
 the demoted should only see the static html generated by the shared notes

**Actual behavior**
the demoted user can access the shared notes editor

**Screenshots**

https://user-images.githubusercontent.com/15806883/162037171-a744c6a3-2279-444c-aa47-32347a3be1b0.mp4

**BBB version:**
BBB 2.5-dev

**Desktop (please complete the following information):**
 - OS:Ubuntu
 - Browser: Chrome
 - Version: 100.0.4896.60

**Comment by pedrobmarin** [comment]
Hi @Tainan404 , I was taking a look on this. Looks like a cookie/browser thing...

The user loses his session cookie but, since there's another user with a valid cookie sharing a browser tab, he still has access over the other user session. I believe this problem won't happen in regular usage of the feature. It should not happen on private browser tabs as well.
