### ISSUE TITLE
bbb-conf 2.5 calculation of version number from bbb* packages version numbers does not respect shortening from 2.4.0 to 2.5

### ISSUE THREAD

**Issue by christmart** [bigbluebutton/bigbluebutton#14957]
**Describe the bug**
bbb-conf calculates the version number with
`dpkg -l | grep bbb | grep -v bbb-demo | grep -v bbb-lti | sed -n '/[0-9].[0-9].[0-9]-/{s/.*[0-9].[0-9].[0-9]-//;s/;//;p}' | awk '{ sum+=$1} END {print sum}'
`
This rule was not changed from 2.4.0 to 2.5 but the versions of the packages are now without the .0 at the end.
The rule would match 
`bbb-apps-akka                          2.4.0-103`
from 2.4.0
but not
`bbb-apps-akka  2.5-20`
from 2.5

The rule matches most of the other package versions, because they have an epoch like 1: in front of the version number.

**To Reproduce**
Call `bbb-conf --version`. Then change the sed command to
`sed -n '/[0-9].[0-9]-/{s/.*[0-9].[0-9]-//;s/;//;p}'`
and compare the results.

**Expected behavior**
version number should include versions from packages like bbb-apps-akka and bbb-fsesl-akka 
**Actual behavior**
version number does not include versions from packages like bbb-apps-akka and bbb-fsesl-akka

**Comment by christmart** [comment]
BBB version 2.5.0-beta.2

**Comment by antobinary** [comment]
Hi @christmart 
I just looked into this and it seems like we only use epoch values `1` and `2` or nothing.
Based on https://github.com/jordansissel/fpm/issues/381 it looks like we could/should go with nothing but as of a new major version some day.

In terms of fixing this issue until then, it looks to me like the simplest way would be to add epoch of `1` for the two packages that lack epoch.
Alternatively, we could tweak the regex we use for calculating the "version" so that it only sums up starting from the `-`, so the epoch and the BBB version would be ignored. However, I am not super certain on this approach as it could be problematic in case we support a mix of 2.6 and 2.7 packages on the same system (as an example).

I think I'll move forward with setting default epoch of `1` to the two packages.

For the record, these two packages seem to deviate from the `fpm` build process as they use `sbt debian:packageBin` instead. Hence the difference - not taking --epoch params.
