### ISSUE TITLE
[2.6]  RTL language, "move notes to whiteboard" wrong text alignment on PDF

### ISSUE THREAD

**Issue by Jossef-767** [bigbluebutton/bigbluebutton#15261]
When writing in RTL language in Shared Notes "move notes to whiteboard" create Shared Notes.pdf  with wrong text alignment

1. Join a 2.6 server
3. use RTL language to Write in shared notes with RTL Letters and RTL text alignment
4. Click on 'Move notes to whiteboard'

**Expected behavior**
see the text in Shared Notes.pdf with text Aligned to the right of page

**Actual behavior**
 text in Shared Notes.pdf is Aligned to the left of page

**BBB version:**
BigBlueButton 2.6.0-alpha.1

**Comment by danielpetri1** [comment]
Hi @Jossef-767,
could you provide a text sample for testing?

Thanks!

**Comment by Jossef-767** [comment]
Hi danielpetri1, I did not check on 2.5. Not sure if 2.5 has this option.
for text sample for testing you can use google translate to generate rtl language text.

**Comment by danielpetri1** [comment]
Hi,
Could reproduce the issue with Arabic text copied from Google Translate but the same happens when downloading the PDF from Etherpad directly. So the problem lies with Etherpad's conversion to PDF and not the "move notes to whiteboard" feature per se.

**Comment by danielpetri1** [comment]
Hello @Jossef-767!
Here is how you can fix this issue:

1. Open Etherpad's configuration file. It is probably under `/usr/share/etherpad-lite/settings.json`.
2. Under `padOptions`, set `rtl` to `true`.
3. Under `padOptions`, set desired language code under `lang`.
4. Restart `etherpad` and `bbb-pads`: 

```
sudo service bbb-pads restart
sudo service etherpad restart
```
Etherpad should now handle file exports correctly.
Let me know if this helped so that the issue can be closed.
