### ISSUE TITLE
Users are still shown in the breakout rooms (in the users list) when the rooms are ended

### ISSUE THREAD

**Issue by mokazemi** [bigbluebutton/bigbluebutton#15396]
The rooms are finished, but users list is not updated and users are still shown in the breakout rooms. **Reloading page doesn't help.** 

**Screenshots**
![image](https://user-images.githubusercontent.com/18334056/179363557-d479369c-8162-4bbf-9132-9e619dfa2ee2.png)

**BBB version:**
BigBlueButton Server 2.5.3 (3059)

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser: Firefox 102.0.1

**Comment by rob0403** [comment]
We just reproduced this bug on 2.5.4. and I'd like to add the following additional information:
The cause of this bug seems to be the introduction of reusable breakout rooms which doesn't work properly yet. Let's consider the following scenario:
1. We have 1 moderator and 2 participants (users)
2. The moderator creates two breakout rooms and adds 1 participant per room
3. The moderator closes the breakout room and both participants rejoin the main room
4. (Bug part1) The moderator doesn't see the closed breakout rooms anymore (which is afaik part of the new feature) but he sees the breakout room number of every participant in the user list: 
![image](https://user-images.githubusercontent.com/15635417/182352395-b5797142-5ec3-42c3-a757-5d28dd96c0f6.png)


6. (Bug part2) The participants still see the breakout rooms they joined. User2 was assigned to breakout room "Raum2": 
![image](https://user-images.githubusercontent.com/15635417/182352468-68706c61-0bb7-4fd1-af51-b96f58a080bb.png)

7. (Bug part3) The moderator can create new breakout rooms and assign the participants to these rooms. The participants, however, don't get the information/join screen for the breakout rooms anymore since they are still somehow in the initially created breakout rooms. User 2 was assigned to the new "Raum2" but doesn't get a notification about this: 
![image](https://user-images.githubusercontent.com/15635417/182352763-581fbd50-457b-4567-993a-132ce27faa5a.png)

I hope this helps!

**Comment by mokazemi** [comment]
Looks to be fixed with #15099
