### ISSUE TITLE
Client not responding to actions while reconnecting

### ISSUE THREAD

**Issue by antobinary** [bigbluebutton/bigbluebutton#15448]
**Describe the bug**
I was in a call and visually all seemed fine. I was toggling myself muted/unmuted every few seconds. At some point I could no longer unmute myself even though visually there was no problem -- webcams were running, I could hear audio. My connection status was green-ish and at some point later purple. I kep hitting the unmute button and it would add a line in the browser console (expected) but would not take effect (unplanned). I am not sure how to reproduce. When I have more info I will include it in this issue.

This issue is meant as a placeholder as this has been happening to me a few times now and it's been diagnozed as "network congestion for X seconds" before. Others have also hit / debugged similar cases.

My main problem was that my client did not inform me of what was going on, and instead just acted unresposive.

**To Reproduce**
...

**Screenshots**
![Screenshot from 2022-07-26 14-41-33](https://user-images.githubusercontent.com/6312397/181087888-31995354-3b05-4ea1-bdb0-945e15115338.png)

**BBB version:**
BigBlueButton 2.6.0-alpha.2 although I have seen the same on 2.5.3

**Comment by antobinary** [comment]
at 14:39:07 this is what my connection status looked like
![Screenshot from 2022-07-26 14-51-55](https://user-images.githubusercontent.com/6312397/181088312-ac9e3bde-8592-452f-96f6-60136e4c432c.png)

and this is not a super helpful post-mortem
![Screenshot from 2022-07-26 14-53-14](https://user-images.githubusercontent.com/6312397/181088643-0189f570-4ddb-4b9e-a66b-3926a4730bf6.png)

**Comment by prlanzarin** [comment]
> I am not sure how to reproduce. When I have more info I will include it in this issue.

Trigger a network block on Meteor's signaling channel that does not immediately cause a channel shutdown.
That can be achieved by pulling the network cable/switching off Wi-Fi, switching in and out of VPNs, bringing the network interface down for a short period of time or things of the sort. Eventually the signaling channel will just reconnect, but it takes an unhealthy amount of time to do so. UI stays inconsistent in the meanwhile.

The expected behavior can be seen running a Meteor.disconnect() from the console - which immediately flags Meteor as disconnected and blocks the UI for some signaling-dependant tasks (mute, chat, etc). So yeah, detecting outages earlier would help.

**Comment by prlanzarin** [comment]
Also worth noting that this is not a regression from anything - it's been the behavior since 2.2/whatever the first HTML5 client release was. 

There's also the argument that some specific things should _not_ be signaling dependant the way they are (eg mute/unmute) - while that's correct, it's another issue entirely that should be covered separately. I believe this is already where this issue's aimed at, but just to emphasize: I suggest constricting this issue's scope to UI consistency.
