### ISSUE TITLE
Cannot create breakout room via API

### ISSUE THREAD

**Issue by JoachimLaviolette** [bigbluebutton/bigbluebutton#15707]
**Describe the bug**
In the case of breakout rooms created by the API, the ID is not known to the server. As a result, it is not possible to retrieve the detailed meeting information of the breakout room, join the breakout room through the API or terminate the breakout room through the API. The breakout room is assigned to the parent room with the meetingID and also appears there in the result of the request. For breakout rooms created by Greenlight, the API works to join the breakout room and also the meeting information. I suspect by comparing the result of the two requests in the meeting room, that possibly the internal and external ID are confused and it comes to errors in the room assignment.

**To Reproduce**
1. Creating a main room with the API
2. Creating a breakout room associated with the main room
3. Joining the breakout room or requesting detailed meeting information via the API -> Does not work.

**Expected behavior**
Breakout rooms are created neatly through the API, assigned to the parent room, and are accessible through the API.

**Actual behavior**
Breakout rooms are created via the API and assigned to the parent room. Unfortunately, however, due to the ID not being known to the server, access or calling detailed information is not possible.

**Screenshots**
Create API call : `https://myserverURL/bigbluebutton/api/create?meetingID=breakout-room-test&name=Sous-salle+de+test&welcome=Bienvenue+dans+cette+sous-salle&isBreakout=true&freeJoin=true&duration=5&parentMeetingID=c083206432c68f6bb1136b18f64095020dc95abd-1663597249830&sequence=15&checksum=d5034db000ed104ebbfc1bea937f3df953448125` 

Meeting representing the breakout room (from getMeetings API call):
![MicrosoftTeams-image](https://user-images.githubusercontent.com/29040593/191049573-f8826f3e-8a0c-4e9f-9815-6ab2b67f1183.png)

**Additional context**
Linked to #12084

**Comment by BrentBaccala** [comment]
We discussed this issue on the developer's call today.

Right now, breakout rooms are handled somewhat specially.  As you see, you provide an internal meeting ID to the create API call, while for normal meetings you pass the external meeting ID.  Also, there's a bunch of extra logic (not in the API) that takes care of assigning users to breakout rooms and presenting a set of breakout rooms in the side panel on the HTML5 GUI.

We're not entirely sure what to do with breakout rooms created with the API, as opposed to breakout rooms created via the GUI, which "know" how to use the special calling syntax.  Questions arise like, should users be invited to join them?  If so, which users should be invited to join which breakout rooms?

What are you trying to achieve with the breakout rooms created via the API?  I would personally be inclined to clean up this code to resolve the issue, but I'm not sure what the use case is.

**Comment by JoachimLaviolette** [comment]
Hi @BrentBaccala,

In the API call to create the breakout room, for the parameter `parentMeetintID`, I do pass the parent meeting's internal ID as I saw it was the case when creating a breakout room from the GUI. Indeed, the breakout rooms created by the GUI have their parentMeetingID matching the parent meeting's internal ID and not its external ID.

Just for your information, at first I tried passing the parent meeting's external ID and it did not work either.

My use case it to be able to create a breakout room from our web application's GUI (for a running meeting) without necessarily using the BBB html client.

**Comment by BrentBaccala** [comment]
> In the API call to create the breakout room, for the parameter `parentMeetintID`, I do pass the parent meeting's internal ID as I saw it was the case when creating a breakout room from the GUI. Indeed, the breakout rooms created by the GUI have their parentMeetingID matching the parent meeting's internal ID and not its external ID.
> 
> Just for your information, at first I tried passing the parent meeting's external ID and it did not work either.

That's a known bug.  I've got a fix in the pipeline.  Either an internal or external ID should be fine for the *parent* meeting ID (it currently has to be an internal ID), but the *new* meeting ID has to be an internal meeting ID in the proper format (hash, hyphen, timestamp).  But even if you do that, it still don't think it will work.

> My use case it to be able to create a breakout room from our web application's GUI (for a running meeting) without necessarily using the BBB html client.

What would you like to happen after the breakout room(s) are created?  In particular, how should users be assigned to the breakout room(s)?  We don't have anything in the API to assign users to breakout rooms, or to tell a running meeting that it should prompt the user to join the breakout room.

Right now, the HTML5 client does some extra coordination behind the scenes of the API so that the moderator can assign users to breakout rooms.  Viewers that don't get assigned to a breakout room never get any indication that breakout rooms have been created.

What would you like to see happen after your web application creates a breakout room?  Should the moderators be asked to assign users to the rooms?  Which moderator should be asked, and how?  Do you want all of the users to just see the breakout rooms become available for anyone to join?

None of this will work right now, unfortunately.  I'm trying to figure out what *should* happen.

**Comment by JoachimLaviolette** [comment]
After creating the breakout room in our app, we would like to see it displayed in the HTML5 client from the parent meeting GUI (as if we had created it directly from the HTML5 client).
Then the expected behavior should be the same as for the breakout rooms created from the HTML5 client. No particular action asked to the user. If `freeJoin=true` was passed when creating the breakout room via the API then users would be able to join it anytime, else they would not.

Thanks a lot for replying!
