### ISSUE TITLE
Draggable whiteboard toolbar for 2.6

### ISSUE THREAD

**Issue by hiroshisuga** [bigbluebutton/bigbluebutton#15739]
**Is your feature request related to a problem? Please describe.**
Testing 2.6, I am a bit frustrated that the new tldraw toolbar is not movable. It's larger than the old whiteboard toolbar and hide more space within the slide. It's more problematic when I use a laptop with a small screen.

**Describe the solution you'd like**
The whiteboard toolbar becomes movable by dragging.

**Describe alternatives you've considered**
Implementing "Hide the toolbar" function, for instance (I may have missed it... please let me know if it's already implemented).

**Comment by antobinary** [comment]
Cross-referrencing https://groups.google.com/g/bigbluebutton-dev/c/CpJNhogn4EU/m/WgHZRU4xBAAJ

**Comment by antobinary** [comment]
Hi @hiroshisuga 

We're looking into preventing the toolbars from hiding areas of the slide. Instead of moving the toolbars, though, we're considering introducing a shortcut which would toggle them both [in]visible. That would work both for single presenter and also for the multiuser whiteboard scenarios.

**Comment by hiroshisuga** [comment]
I prefer the hide/show toolbar shortcut. And when it's hidden, the pan tool should be selected, and the presenter would zoom the slide by mouse wheeling, without any other key down, the same behaviour as 2.5.

**Comment by Wladimir-N** [comment]
https://discord.com/channels/859816885297741824/1075694851028439081
I mentioned this issue in the tldraw discord community and they seem to be addressing this issue on their side as well. Probably, it is necessary to coordinate actions so that work is not done by both the bbb developers and the tldraw developers. Can one of the bbb developers contribute to the discussion of this issue in the tldraw discord community?

Я упомянул об этой проблеме в discord сообществе tldraw, и кажется они тоже решают этот вопрос на своей стороне. Наверное надо согласовать действия чтобы не выполнялась работа и со стороны разработчиков bbb и со стороны разработчиков tldraw. Может кто-то из разработчиков bbb принять участие в обсуждении этой проблемы в discord сообществе tldraw?

**Comment by hiroshisuga** [comment]
I am working on hide/show toolbar.  Would the community be interested in it? (Perhaps some core developers are already working on it...I will submit anyway)

**Comment by ffdixon** [comment]
> Would the community be interested in it? ( 

How did you implement it -- keyboard shortcut or auto-hide?

**Comment by hiroshisuga** [comment]
I made a button on the whiteboard option dropdown (three dots at the top-right corner). It's working well. The implementation is, as always, a bit dirty, using DOM. There is no other way to tweak tldraw...
The idea is not to interfere the face-to-face presentation during the hybrid style lecture.
![Animation1](https://user-images.githubusercontent.com/45039819/225169920-cde20e99-504e-4522-a88a-d666da3947be.gif)

**Comment by KDSBrowne** [comment]
Tldraw has a way to hide all of the controls using the `isFocusMode` setting property. 
tldrawAPI?.setSetting('isFocusMode', true);

**Comment by hiroshisuga** [comment]
That would simplify the code. Thanks!
We really need a complete document covering all API of tldraw..

**Comment by hiroshisuga** [comment]
There is also toggleFocusMode() API. But I cannot find an API for obtaining the current focus mode. In other word, there is setSetting, but no getSetting... any idea?

**Comment by hiroshisuga** [comment]
Sorry, I've found that just 'setting' returns all values.

**Comment by hiroshisuga** [comment]
Using the focus mode API works. But there is another problem regarding CSS. I would rather stay my original idea of tweaking the DOM.... 
![Animation1](https://user-images.githubusercontent.com/45039819/225187691-b19a7b51-6b52-4acd-9c8d-e483756f66dd.gif)

**Comment by KDSBrowne** [comment]
I would be fine with tweaking the DOM
