### ISSUE TITLE
Connection: change network causes an odd state on webcam

### ISSUE THREAD

**Issue by Tainan404** [bigbluebutton/bigbluebutton#15823]
**Describe the bug**
When an user changes the network and is sharring a webcam it causes a case where the webcam keeps black for the sharing user and the other user can't see the user webcam, user can't stop sharing his webcam to retry.

**To Reproduce**
prerequisites: should have a webcam and two different wifi networks
1. Join with an user and share his webcam (audio is optional)
2. change your wifi network 
3. Join with a seocnd user
4. See the error

**Expected behavior**
reshare the user webcam or allow user cancel it and retry by himself 

**Actual behavior**
client keeps a webcam frame and doesn't allow sue to stop the sharing and retry

**Screenshots**

https://user-images.githubusercontent.com/15806883/195166091-35f34273-c848-4655-bab7-1032864f7553.mp4

**BBB version:**
BigBlueButton Server 2.6.0-alpha.4

**Desktop (please complete the following information):**
 - OS: ubuntu
 - Browser: Chrome
 - Version: 106.0.5249.91

**Comment by prlanzarin** [comment]
I stumbled upon this when migrating to v2.5.x-release and decided to do some digging.
This looks like a widespread issue which affects the handling of stale data on most of the client-side collections. It was probably introduced by https://github.com/bigbluebutton/bigbluebutton/pull/13261 and https://github.com/bigbluebutton/bigbluebutton/pull/13574, hence why I tagged this v2.5.x-release.

The way I figure this issue plays out is that the collection mirroring thing does not clean up stale collection in all necessary scenarios. Currently, the cleanup code is only run when an [`added` event is received from the server](https://github.com/bigbluebutton/bigbluebutton/blob/9f9c5db0e8175cf401f14fea150b538dcbb35880/bigbluebutton-html5/imports/ui/services/LocalCollectionSynchronizer/LocalCollectionSynchronizer.js#L40-L52). Where that fails is in scenarios where a server-side collection turns empty _while_ an affected users is disconnected - and then reconnects. There's no `removed` (or updated) event in that scenario, so no cleanup code is run and you have stale data. ie.:

1. u1 connects
2. u1 enters Meteor.disconnect() in the console
3. u1 waits a few seconds for their camera to fail (1007, etc)
4. Server side terminates the camera connection. The server side video-streams document is accordingly removed and the collection is now empty.
5. u1 inputs Meteor.reconnect() in the console
6. u1 has a stale video-streams document in their client-side version of the collection for a camera that _doesn't_ exist anymore in the server-side (but it doesn't really know that)
6.1. Camera state is server mandated, so yeah, you can't close a camera that doesn't really exist, neither can you pause or anything of the sorts like the suggested "expected behavior" in this issue. The problem here is state inconsistency, and the state reconciliation code is broken.
6.2 The same thing happens if u1 was the one watching a camera shared by `u2` and that camera was unsharing while u1 reconnects.

This is also the reason for:
  - https://github.com/bigbluebutton/bigbluebutton/issues/15829
  - User typing indicator getting stuck in the chat after a re-connect
  - Breakout rooms getting stuck in the users panel if they're closed while the user is re-connecting
  - [...]
  
As for the solution, I was considering running the [cleanup procedure](https://github.com/bigbluebutton/bigbluebutton/blob/develop/bigbluebutton-html5/imports/ui/services/LocalCollectionSynchronizer/LocalCollectionSynchronizer.js#L40-L52) when a subscription for a collection is re-established (via a onReady trigger or something of the sorts). This should preserve the data while the client doesn't reconnect (which I believe was the original intention), but guarantee things are up to date after re-subscribing.
I need more input on this, though, since I lack experience in this particular area and I don't know if there are any possible fallouts from doing this. cc @Tainan404 since you were the original implementer of the mirroring strategy.

**Comment by prlanzarin** [comment]
@Tainan404 see the proposed solution in #15929

**Comment by antobinary** [comment]
Likely related to https://github.com/bigbluebutton/bigbluebutton/issues/16518
