### ISSUE TITLE
Leave vs End Meeting

### ISSUE THREAD

**Issue by lkiesow** [bigbluebutton/bigbluebutton#15891]
In the top right corner, moderators have access to a menu with the two options “Leave meeting” and “End meeting”. The distinction between these options is not always clear to users and it is a regular occurrence that users accidentally end the meeting for everyone if they want to leave, despite the warning being displayed when they click “End meeting”.

Part of this is likely that the less dangerous option “Leave meeting” is marked in the danger color red, while the actually more dangerous option “End meeting” is in the regular black:

![Screenshot from 2022-10-21 13-11-58](https://user-images.githubusercontent.com/1008395/197518578-0a805a36-9d0e-4182-bc84-98643fe9c895.png)

To make sure users are aware that they do something dangerous, the color should be reversed and “End meeting” should be red.

> This issue is created for the Fall 2022, mini hackathon at UOS/ELAN on November 10.
> Expect a pull request as part of that until the end of the week.
> If any of these won't get worked on, I'll remove this comment.

**Comment by davidsiecke** [comment]
Perhaps one additional way to visually communicate the higher destructivity of the "End meeting" button could be to have it switch places in the menu with the "Leave meeting" button, i.e. place it at the very bottom of the menu.

On top of that it could be considered to display this button center-aligned and on a red backdrop to further single out this button. I sketched this here:
![Bildschirm­foto 2022-10-27 um 11 36 38](https://user-images.githubusercontent.com/72148199/198249567-644a3ec4-08e0-46bf-b709-c624e1535311.png)

**Comment by lkiesow** [comment]
> On top of that it could be considered to display this button center-aligned and on a red backdrop to further single out this button. But I'm not really sure if this would be a meaningful improvement, just want to throw in the idea. I made a sketch:

While I dislike the idea to have this centered. This would be the one place in all of BigBlueButton where we have a menu which has a separate button placed within that menu (that feels weird). But I actually like the idea of having a red background to really make this stand out. We could either always show this, or just when hovering over this option. We usually have a blue background when hovering over a menu item.

Having a red background while keeping the current style would look like this:

![Screenshot from 2022-10-27 22-03-04](https://user-images.githubusercontent.com/1008395/198388059-41751a96-8163-421b-9587-6403679b09d4.png)

That said, the two open pull requests for this issue already improve the situation quite a bit.

**Comment by FreeScholar** [comment]
How about "End Meeting for All"

**Comment by ErikLtz** [comment]
Also placed last using parent.appendChild in same JS "hack":

![bild](https://user-images.githubusercontent.com/57834443/200923897-74a38765-dad5-4c30-ba46-ca8ff9c316f8.png)

(sorry for "spamming" but it is working - hope a future release include adjustments or even options but little things like these are possible _by other means_ if You don't want to wait - inquire if interested)

**Comment by alinastolzenburg** [comment]
> 

I think this is a good solution. It would be important that the button is only highlighted in red when hovering over it. If this is not the case, then the writing is displayed in red.

**Comment by ErikLtz** [comment]
@cgruber-uos Maybe the philosophy behind a "hidden leave button" is that a more visible one would disturb the learning process BBB is mainly designed for.

From a technical point of view I'm sure some JS code in a custom included file could both create a leave button outside the menu on the fly and make it work outside any official BBB source enhancement, though more customisation options in BBB would be welcome (I have used JS to hide the record button and insert "my own" connected to AddPipe screen recorder to enable full meeting recording as mp4, including shared videos and more, works quite well).

**Comment by MegaKeegMan** [comment]
What if the we did as @cgruber-uos suggests, but also provide additional prompts for both options, clarifying the meaning of each, like "Are you sure you want to end the meeting? This will end the call for all participants."

And if you want to make extra  certain, you can add another note below that can be clicked, like "Or maybe you just want to leave the call yourself?"

...For the Leave meeting button, "Are you sure you want to leave the meeting?"

**Comment by MegaKeegMan** [comment]
Oh, and potentially a different route for the "Leave meeting" button. You could also make it so that a moderator can control whether or not people have the "Leave meeting" button available free from the menu. This way you could have both, but the more accessible one would not be available while moderators deemed class to still be in session. There's still a little more room for ideas, but here is at least a little food for thought.

**Comment by mlncn** [comment]
We would love the ability to simply remove the "End meeting for all" option from everyone (agree strongly with @FreeScholar on that clearer wording).

**Comment by cgruber-uos** [comment]
I don't think we should remove the function "end meeting [for all]" entirely. In case a teacher or lecturer (or "technical" moderator) has to control a meeting and there should not be a "left alone" class without teacher or chef you have to close a meeting. But in many circumstances a lot of moderators or people with moderation rights are in meeting. Our working group teams or university administration groups meet as "moderators" so it is easy to grab the moderation rights and you do not have to wait for some tasks for "the admin". But leaving the meeting earlier than the rest can be dangerous in case you click the wrong menu icon.

**Comment by cgruber-uos** [comment]
For me it's a bit intransparent why this issue has been closed and what the "result" is. So there is no PR assiciated with the closing action or no final design showing up in this issue or linked to an other issue or design proposal.

**Comment by ffdixon** [comment]
In terms of UI changes, here's what it current looks like in 2.5

<img width="267" alt="image" src="https://user-images.githubusercontent.com/290351/204463427-bed0f2d5-1c82-44f9-aa92-47a4466d27d2.png">


and here is what it currently looks like in 2.6-dev

<img width="248" alt="image" src="https://user-images.githubusercontent.com/290351/204463404-ec6e45e3-ea1d-4942-9a89-65a5bc616e17.png">

**Comment by ErikLtz** [comment]
> [...]
> <img alt="image" width="248" src="https://user-images.githubusercontent.com/290351/204463404-ec6e45e3-ea1d-4942-9a89-65a5bc616e17.png">

Looks really good - and if I may say so really close to what I already have in my "JavaScript-modify-on-the-fly" version as shown in a previous post. Me like 😊

**Comment by MegaKeegMan** [comment]
I think the fix is reasonable, but I am curious to know whether it will fix the problem. Certainly, while red is the danger color (which is the main thing being reoriented), red is also the hang up color, as I think was already mentioned. I can imagine people opening the menu, seeing the big red button, and just going right to it. With that said, I think it is reasonable to wait and just see what happens. Maybe the issue I am describing here will not be such a big issue after all, in which case, great.

**Comment by FreeScholar** [comment]
Even with this great treatment I still hear Zoom recruits asking where is the hangup button that is red and looks like a phone receiver.

**Comment by ClemensGruber** [comment]
... and I think they are right because this is the standard to have at first UI level the opportunity to hang up.

I will forecast that the new "solution" - a red button - will not fix our problem, perhaps its get worse than before. Why? Because the people know that a big red button will end a call. So they will click on the red button. 

Please add at least the suggestion @FreeScholar made and add "for all" to the button.

**Comment by Ithanil** [comment]
I think this issue is not really solved, I still regularly get complaints about mistakenly ended meetings. But the issue goes beyond that, because such a basic functionality as leaving the meeting is hidden behind an options menu. 

My proposal is as follows:
- Leave the "End Meeting" with background red in the options menu
- Below the three dots for the options menu, add a "door" button to leave meetings
- remove "Leave Meeting" from the menu

Result:
- Easy to find and intuitive way of leaving the meeting
- No more confusion about the difference between leave and end meeting
- No more accidentally ended sessions!

Please consider this solution, because it is really requested a lot and better matches what people are used to from other applications.

**Comment by anc-tvr** [comment]
Damn, this is the dumbest feature that can't be turned off! Today, my video conference was interrupted several times due to the fact that inexperienced users used "end meeting" instead of leaving. It's terribly annoying! How can I disable this sh!t give "end meeting" function only for moders?

**Comment by antobinary** [comment]
@anc-tvr End meeting is indeed only available to moderators. Be careful who you promote to moderator.
