### ISSUE TITLE
Usability concept for presentation upload and management

### ISSUE THREAD

**Issue by lkiesow** [bigbluebutton/bigbluebutton#15954]
Presentation management in BigBlueButton is a bit cumbersome since you always have to leave the conference mode to go to the presentation management view and then come back. Some functionality, like selecting already uploaded presentations, has also made its way into the 🞤-menu. But not all the functionality is available there.

Short term, we already have a few suggestions for how to improve the usability without changing the overall concept like:
- #15893
- #15895

Mid or long term, it would be great to develop a new usability concept for the management functionality:

- Can we make the user interface for managing presentations easier to use?
- Can we prevent users from having to leave the conference mode?
- Can we manage presentations with fewer clicks?
- Can we make it that this also still works on a tablet?

A few ideas to get started with this issue (please don't hesitate to throw them out of the window if you come up with anything better):

- Add “Upload presentation” to the 🞤-menu directly
- Add additional functionality like allowing downloads to sub-menus
- Remove the manage presentations view entirely

Current views which are involved are:

![Screenshot from 2022-11-04 15-33-01](https://user-images.githubusercontent.com/1008395/200016412-9aca4fb9-3513-4cc6-9ca4-12feac92f5db.png)

![Screenshot from 2022-11-04 15-32-14](https://user-images.githubusercontent.com/1008395/200016440-3a86a375-72d5-472e-8a61-c876c3cb451d.png)

> This issue is created for the Fall 2022, mini hackathon at UOS/ELAN on November 10.
> Expect a pull request as part of that until the end of the week.
> If any of these won't get worked on, I'll remove this comment.

**Comment by alinastolzenburg** [comment]
Additionally, it would be desirable that:
    - the button "manage presentations" is always visible in the user list for presenters
    - moderators also have the rights to _add_ presentations (not the change which one is currently shown though)
    - moderators don't see "manage presentations" in their user list by default though, but only if they add it via the "+" button
    - by closing the "manage presentations" dialogue, presenters and moderators also remove it from their user list (analogue to "start a poll")
    - users can also find all currently uploaded presentations in their user list

**Comment by cgruber-uos** [comment]
See also the Usability Test Report from Osnabruck https://osnadocs.ub.uni-osnabrueck.de/bitstream/ds-202210077614/1/workingpaper_1_2022_virtUOS.pdf page 16 section 3.2.2 Presenting

The "+"-icon is not associated and too "neutral" for "presentation" a lot of test users searched the upload functionality in the share screen area or missmatched the "minimize presentation" button as "something with slides" so it seems a good idea to unifie things here **and delete the "+"-button.** 

![2022-11-10 16_23_36-Usability Report (virtUOS) - workingpaper_1_2022_virtUOS pdf – Mozilla Firefox](https://user-images.githubusercontent.com/101632236/201136709-0d89baf7-3cb3-48cf-9199-6b42dd32d51b.png)

![2022-11-10 16_24_07-Usability Report (virtUOS) - workingpaper_1_2022_virtUOS pdf – Mozilla Firefox](https://user-images.githubusercontent.com/101632236/201136745-ff5edf45-a1bc-4755-9bc7-5f25503ef349.png)

**Comment by davidsiecke** [comment]
I don't think placing the "manage presentations" dialog where otherwise the chat and shared notes are displayed would be an improvement over simply bringing it to a smaller centered dialog, as suggested in #15893. To the contrary — it would bring about problems that we would not have if we just sticked with the latter:
- Users would not be able see the chat or shared notes while uploading the slides.
- Having a "Manage presentations" button pop up in the user list tab brings changes to an UI area that is otherwise very static, and thereby contradicts what users believe to know from experience about the interface. The user list tab is not designed in a way that leads one to expect this dynamicity there. Attaching the "Manage presentations" dialog to it therefore likely contributes to users feeling insecure in using BBB, which already seems to be a problem, given that none of the ten students who participated in the usability test we conducted fully agreed with the statement "I felt very confident using the system". 3 participants selected "Agree", 3 more selected "Neutral", 1 selected "Disagree", 3 selected "Strongly disagree". (For the same two reasons we argue in issue #15811 that the polling dialog should not be attached to the user list tab.)

Looking beyond these additional problems, the chat / shared notes panel is a vertical container, which specifically suits the chat and shared notes functionalities, but not the "Manage presentations" dialog. Assuming that for teaching use cases, no more than four presentations need to be uploaded for a single session, about a third of the panel's height would be utilized at maximum. This is not space-efficient and in my opinion also questionable from an aesthetic perspective.

I described some ideas for an improved "manage presentations" dialog in issues #15810 and #15809. These proposals do not only give answers to the four questions @lkiesow raised above, but additionally
- seem to conform to users' expectations where a functionality for managing presentations would be placed,
- would make different slide decks more easily distinguishable,
- may alleviate confusion around having e.g. an external video displayed on top of a presentation,
- would relieve moderators / presenters of always having to find the user who they want to make presenter in the user list,
- could increase users' awareness of the option to upload slides (which would desirable especially considering that this is not a widespread feature in video conferencing applications), and
- support users in building a coherent mental map of the BBB UI.

See the two issues referenced above for explanations regarding all these points. The concepts would also be suited to accommodate @alinastolzenburg's proposal to allow moderators to add presentations.

**Comment by davidsiecke** [comment]
I revised my proposals slightly and conducted a poll to evaluate users’ preferences. See the comments under issues #15809 and #15810 for the updated proposals and users’ responses. For more details on the survey itself, see the paragraph at the end of this comment.

Among other things, I specifically asked participants whether they would – considering first and foremost the location, not the design – prefer to have the dialog for managing presentations displayed in the chat / shared notes panel or attached to a unified button for presentation tools (as proposed in #15809). Out of 48 participants, 45 (≈ 94 %) indicated that they would prefer the latter option.
When asked which design (regardless of location) they preferred, either a more compact version of the current dialog or something along the lines of what I describe in #15810, 44 out of 47 participants (≈ 94 %) were in favor of the latter option.
Lastly, participants should complete the statement

> “I think that my preferred [combination of design and location] is _____ user-friendly than the current “manage presentations” dialog.”

by choosing one of the options
- “much less”,
- “less”,
- “neither more nor less”,
- “more”,
- “much more”.

Out of the 37 participants who preferred both the location and the design suggested in #15810, none selected “much less” or “less”, but 34 (≈ 92 %) selected “more” or “much more”. Here is a plot of the response counts:

<img width="400" alt="plot" src="https://user-images.githubusercontent.com/72148199/217102969-bcda29cb-0ab1-40bc-85e0-1932b285eb1f.png">

### About the survey

This survey was conducted with 124 people, mostly students, who had used BBB at least once. About 99 % of participants had been using BBB for more than three months, about 84 % for more than one year. They were allocated randomly to one of two questionnaires, such that 66 users answered questionnaire 1 and 58 users answered questionnaire 2. Participants who were allocated to the questionnaire that includes the questions addressed in this comment mostly (about 81 %) had some experience in the presenter role, e.g. as tutors. The data collected in the survey as well as all pages of both questionnaires can be found here:
https://sync.academiccloud.de/index.php/s/w2cWlDCrW4jOpCY
