### ISSUE TITLE
Refactor: add a failed reason for the enter endpoint response.

### ISSUE THREAD

**Issue by Tainan404** [bigbluebutton/bigbluebutton#16037]
**Is your feature request related to a problem? Please describe.**
When the enter api returns a failed message if doesn't includes the reason of the error, would be great have a code that could include extra information about the failed.

E.G. if the user receives a message `"Access denied"` we could add a failed reason saying why it's was denied `denied because the meeting ended`, `denied because the user was banned` and etc.

it would allow the client better threat the error cases.

**Describe the solution you'd like**
add a failed code that would allow us to track the failed reason

**Comment by gustavotrott** [comment]
It was improved in #16060.

But still not fully settled.
It can still be improved in the API version 2. The current one doesn't know the error because once the meeting is ended, the API removes all informations about that including the users sessions. So it is impossible to know if the problem is related with the sessionToken or if the meeting ended.
