### ISSUE TITLE
Learning dashboard issue

### ISSUE THREAD

**Issue by ShaunWhitee** [bigbluebutton/bigbluebutton#16053]
I am trying to access Learning Dashboard after meeting is ended so I changed the value of `LearningDashboardCleanupDelayInMinutes=0` to keep the data for longer duration but I can't access the url or dashboard from a different browser even with session token.
the error I get is- `Data is no longer available`
is there any way to make the dashboard accessible from any browser after meeting is over ?
and also sometimes urls does not open even from same browser

**Comment by mathmartins2** [comment]
i am having this same problem. it seems that when the room is generated, a cookie is also created. making only the browser that created the room have access to the dashboards.

I still can't think of how to access the pages

**Comment by hostbbb** [comment]
the data is stored like,

/var/bigbluebutton/learning-dashboard/bd21c297d4802287470458700b2406e5bdede31a-1672856845828/kcbcxlss4gav/learning_dashboard_data.json

so the learning dashboard node app,  authenticates the token in cookie browser and uses it in the path for privacy issues since this data is available thru http without the token if you know the path,

we take the learning_dashboard_data.json and send to analytics database.  then you can modify the learning dashboard or write your own front end to display with your level of authentication. and aggregate data over lots of classes by student or instructor.

This warehousing of analytics can be used in a number of ways to inform instruction, but some may find intrusive to privacy.

**Comment by mohamedrelsayed2811** [comment]
i am having this same problem

> i am having this same problem. it seems that when the room is generated, a cookie is also created. making only the browser that created the room have access to the dashboards.
> 
> I still can't think of how to access the pages

**Comment by Nick64M** [comment]
Did you manage to solve the problem https://github.com/bigbluebutton/bigbluebutton/issues/16053

**Comment by Arlidi** [comment]
@Nick64M 
try #23844
