### ISSUE TITLE
Create a HTML5 Interface to BigBlueButton

### ISSUE THREAD

**Issue by bigbluebutton-issue-import** [bigbluebutton/bigbluebutton#1605]
Originally reported on Google Code with ID 850

```
This is definitely a research are at the moment as HTML5 doesn't provide a means to
access the user's microphone or webcam.

Still, with the right architectural changes in the BigBlueButton server, it should
be possible to create an HTML5 client that could view a BigBlueButton presentation
in real-time.
```

Reported by `ffdixon` on 2011-02-06 15:33:48

**Comment by kfogel** [comment]
Fred, thanks for the update.  Might be good to change this issue's title to "Create an open-source (i.e., non-Flash) browser interface to BigBlueButton", since that's the real issue, not whether it's pure HTML5 vs WebRTC.

I looked for commits in the `bigbluebutton` repository mentioning issue #1605, but didn't see anything.  Is that the right repository to be looking in, or would they be somewhere else?

Best regards,
-Karl

**Comment by antobinary** [comment]
Hey Karl,

The HTML5 client is part of the master branch, albeit still under development. You can find the code here: https://github.com/antobinary/bigbluebutton/tree/master/bigbluebutton-html5 . You use it to join Demo Meeting from here: http://demo.bigbluebutton.org/demo/demoHTML5.jsp .
Here is more info on the HTML5 client. You can also watch the video from the last summit: https://www.youtube.com/watch?v=3ioY-zyAUhQ

Regards,
Anton

**Comment by capilkey** [comment]
The link to the code should be this one, https://github.com/bigbluebutton/bigbluebutton/tree/master/bigbluebutton-html5. You linked to your personal fork Anton.

**Comment by capilkey** [comment]
Karl,
An overview of the HTML5 client in development can be found here, http://docs.bigbluebutton.org/labs/html5-overview.html. You can also follow the following link if you want to set up the development environment for the client, http://docs.bigbluebutton.org/labs/html5-dev.html.

As to the title of the issue, I think the current title is more accurate as the Flash client is already an open-source client. The difference between the two clients is Flash vs. HTML5.

**Comment by kfogel** [comment]
Thanks so much, @antobinary and @capilkey!  That's very helpful.

@capilkey: Yes, I see what you mean about the Flash client code being open source; it's just Flash itself that is not (though there's always Gnash).  The current issue title is certainly accurate from a technical perspective, and perhaps is more findable anyway.

**Comment by mschipperheyn** [comment]
I think that it is time to accept that quality and Flash don't belong in the same sentence anymore. I'm not talking about all the security issues with Flash. Flash is dead and has been for a while now. Pretty soon, Chrome will not even run it by default. 

Every second invested in building or maintaining code related to the Flash client is a lost second. Because it could have been used to create the HTML 5 client, which, in the short term, seems to have very modest design goals (no video), and progresses very very slowly. Even with it, given the lack of support for open source video codecs on Safari, will have significant limitations on the most popular mobile client: iOS. But, it's the best option. 

My suggestion in terms of focus would be: 

* Focus ALL energy on the HTML 5 client. Get the audio version our before the fall and get a beta video version out before EOY.
* Migrate as much as possible to ReactJS to minimize development time and have access to ready made libraries
* Integrate  the open source video codec
* Integrate the Apple video codec as a paid option. Try to license it so that you can use this license in a way that gives everybody an affordable option, e.g. monthly fee. 

I get regular questions from our front office these days "can't we replace BBB with something that works on a mobile client"? A year ago, I was still saying, "next year, we'll have HTML 5" (I didn't realize the open source video codec issue then), but I've stopped doing that. Now, I'm looking around.

I know critical feedback often gets received by a: what have you done for me lately, it's open source. So be it. I invested significant time and energy in our BBB infrastructure and I really hope it will get to the next level. But some changes in focus are desperately needed. Because, if not, it will just die. And that would be a real shame.

**Comment by ffdixon** [comment]
Hi Karl,

Thanks for your comments -- it clearly shows you care about the project!

We are working on moving over the entire HTML5 client to react.  You can see a recent update of our progresses here

   http://bigbluebutton.org/2016/05/03/bigbluebutton-summit-viii-ottawa-ontario-canada/

Want to follow our progress?  All this work on the HTML5 client now occurs on the master branch, and I encourage you to following the developments here

  https://github.com/bigbluebutton/bigbluebutton/commits/master

Want to see what the interface is going to look like?  Check out

      http://docs.bigbluebutton.org/html/html5-design.html


Regarding Flash, given that Microsoft recently built it into Edge and IE 11, joining Google with an integrated Flash runtime -- Flash is a platform that is going to be around for a long time.  We don't have any plans to abandon it as it "just works" (and has done so for the last seven years).

At the end of the day, an instructor going into a course just wants the web conferencing system to work -- they really don't care about the platform (we as developers care, but beyond ensuring the environment is working correctly, they don't care about the underlying technology).  

We will continue to enhance the existing web client (in Flash) with updates coming in BigBlueButton 1.1, see

  https://groups.google.com/d/msg/bigbluebutton-dev/2OLdUbi2K_w/1pzOZoppAwAJ

AND we are working hard to give you the option to have your users join via a pure HTML5 client that uses the latest web technologies (react and WebRTC).  There has been a lot of development under the hood to modify the BigBlueButton server to support both the Flash client AND HTML5 client simultaneous. 

Thanks for your feedback Marc -- hopefully the above gives you comfort that we're headed in the right direction for you.

**Comment by kfogel** [comment]
Wow -- thanks for the update, @ffdixon, and congratulations on the progress!

**Comment by mschipperheyn** [comment]
Fred, thanks for the feedback. I appreciate it. 

I don't agree on your point of view regarding Flash and I think it's a mistake. But I understand your point that right now, it's the option that offers the most coverage. 

I agree that it has to just work and on iOS, this is not the case. I hope that either Apple will start supporting open source video codecs, or open source their own, but I'm not holding my breath. So, I hope that someone will find a commercial opportunity in supporting Apple's codecs somehow to get BBB working on iOS. That's a lot of ifs and maybe's. And I'm really at a loss of how to deal with the demand for iOS tablet and iPhone access.

**Comment by aensley** [comment]
Love this project and the progress made on it as a whole. It continues to get better with every release.

Just adding a note here since no one else has yet. I'm sure most people following this issue already know. Chrome, the world's most-used browser, now disables flash by default (since version 56, February, 2017), requiring several steps to allow an exception:

* https://www.blog.google/products/chrome/flash-and-chrome/
* https://www.chromium.org/flash-roadmap
* https://blog.chromium.org/2016/12/roll-out-plan-for-html5-by-default.html

Now, Adobe is going to kill Flash in 2020:

* https://blogs.adobe.com/conversations/2017/07/adobe-flash-update.html
* https://blog.chromium.org/2017/07/so-long-and-thanks-for-all-flash.html

It will be completely dead. No support, no updates, nothing. Hoping to see more activity on making the HTML5 client the primary interface of BBB soon.

**Comment by ffdixon** [comment]
Hi there,

We did a post about this to our developer mailing list on July 25.  See

   https://groups.google.com/d/msg/bigbluebutton-dev/87zUiBqPBUY/ovj-_o5WGAAJ

As stated in the above post, we are aware of the transition and have put forward our intent to continue to improve the BigBlueButton client in Flash for our community (as you can see by the recent announcement of BigBlueButton 2.0 *and* work towards a pure HTML5 client).  

We've updated the BigBlueButton server so it supports both the Flash and HTML5 client at the same time, so we can give you a seamless transition over time to HTML5.

**Comment by aensley** [comment]
_Replying to https://github.com/bigbluebutton/bigbluebutton/issues/1605#issuecomment-329814229 by @ffdixon:_

Thanks for the link, Fred. I missed that message before. I found these two statements very encouraging:

> You can expect the first release of the BigBlueButton HTML5 client before the end of 2017.  We're targeting it as a mobile client for both Andorid and iOS.
> 
> Our goal, over time, is to make the HTML5 client feature compatible with the Flash client and provide you a smooth transition.

**Comment by ROBERT-MCDOWELL** [comment]
well, first of all, believe to everything said by adobe or google (working together) is a mistake.
last example, they stopped to support flash on linux 7 years ago, and then this year linux is supported again.
Everything decided on behalf user experience is purely speculative and political. Then, cut the grass under millions users and websites is an absolute non sense, and they know that.
For sure, in 3 years many developers will react and will certainly find a way to just make SWF files as any binary file compatible for the web. Yes, it's good to remove plugins, No, it's not good to remove an entire language like as2/as3 for the web.
so let's reinvent the wheel and reprogram everything for the same (and even worse) result at the end...
Today it's extremely risky to convert an entire complex flash platform to html5/javacrap, only one word, good luck and don't be afraid to pass years to convert it.

**Comment by ffdixon** [comment]
Great -- Adobe has been very good for the BigBlueButton project.  We've been working on this for many years and it enabled us to deliver a cross-platform solution to, well, pretty much everyone except the mobile clients.

The announcement for end of 2020 gives the project over 3 years to transition -- a lifetime in computer software.  Again, I credit Adobe for giving everyone a long horizon to make the transition.  

We'll have you transitioned over to pure HTML5 *well* before the above date and there will be more capabilities added to BigBlueButton for our community along the way.

**Comment by ffdixon** [comment]
Marking this as part of the 2.0 release (currently in beta).  Looking forward to closing this issue!

**Comment by ffdixon** [comment]
We have released a significant update to the HTML5 client with the latest release of BigBlueButton 2.0-beta.  To try out the latest build, visit
  
  https://test.bigbluebutton.org/

**Comment by ffdixon** [comment]
@mschipperheyn @kfogel @aensley We're getting very close to fully replacing BigBlueButton with an HTML5 client.  

Marking this issue as part of the upcoming 2.2 release.

**Comment by kfogel** [comment]
W00t!  That's great news, thank you!

**Comment by nadavkav** [comment]
Great news!

**Comment by ffdixon** [comment]
Closing this issue as we've implemented the features of Flash client in the HTML5 client with 2.2.

**Comment by OZhurbenko** [comment]
Yaaay! 🎉 🎉 🎉

**Comment by nadavkav** [comment]
![image](https://user-images.githubusercontent.com/231168/57979668-c17db680-7a29-11e9-9a52-039736ebc528.png)

**Comment by nadavkav** [comment]
![Yes](http://bestanimations.com/Holidays/Fireworks/fireworks/amazing-electrc-feel-fireworks-gif.gif)
