### ISSUE TITLE
Add timestamp to exported breakouts content

### ISSUE THREAD

**Issue by antobinary** [bigbluebutton/bigbluebutton#16110]
**Describe the bug**
In BBB 2.6 we are able to export the shared notes and/or whiteboard content from the breakout rooms back to the main room. However, when we pick a name for these newly created exported documents, we risk repeating the name if we do several breakout batches within the same session.

**To Reproduce**
1. Join a meeting as a moderator.
2. Create breakouts and select to export the breakouts' shared notes and whiteboard
3. End the breakouts.
4. One more time - create breakouts and select to export the breakouts' shared notes and whiteboard
5. End the breakouts.
6. Go to the main room and open the presentation upload (manage) dialog to see the entire list of what was imported from the breakouts.

**Expected behavior**
Some way of knowing which exports resulted from the first batch of breakouts vs second. For example a timestamp like '..._10:25:06.pdf'

**Actual behavior**
The file names get repeated

**Screenshots**
![Screenshot from 2022-12-09 10-20-25](https://user-images.githubusercontent.com/6312397/206735590-b5a1f9bc-feae-4cea-8cb2-4cd1583dc118.png)

**BBB version:**
BigBlueButton 2.6.0-beta.2

**Comment by gustavotrott** [comment]
Since #16421, it has a counter to diff the last presentation captured.
how does it sound?

![name_duplicates_using_parentheses](https://user-images.githubusercontent.com/5660191/213543096-53f59cc4-ac0f-47cb-bfa5-190810c7d36d.png)

The timezone idea has a problem due to timezone differences!
For example if the server is hosted in a different country, the time will be wrong for the presenter perspective.. so it could introduce confusion.
