### ISSUE TITLE
Uncaught (in Promise)

### ISSUE THREAD

**Issue by NarsimaChilkuri** [bigbluebutton/bigbluebutton#16123]
<img width="867" alt="image" src="https://user-images.githubusercontent.com/40288440/207273207-b27fd798-d18e-4e7a-a7c7-6fc069fc735e.png">

It throws an error after deploying with the script from development

**Comment by ffdixon** [comment]
When posting an issue, think about the information you need to give another developer to recreate the issue.

1. What version of BigBlueButton are you installing?
2. What steps would someone go through to reproduce this error?
3. Are you using stock BigBlueButton?
4. Have you made any changes to BigBlueButton before encountering the error?

**Comment by NarsimaChilkuri** [comment]
Sorry, for the lack of the information,
1. I am using focal-260 version.
2. I have my previous code which was working in other servers which I deployed using the script (deploy_to_usr_share.sh) inside bigbluebutton-html5
3. No I am not using Stock Bigbluebutton
4. The same code is working on my previous servers, only change I can see know is while creating a new instance the components versions of old servers and new server created is different.

**Comment by antobinary** [comment]
It's possible that we've changed client side code that you were relying on in your modifications that you deploy.
Try reproducing this issue on your local development environment where it will be easier for you to troubleshoot / spot which source code line is responsible.

If you're able to reproduce this issue in stock BigBlueButton we will be quite interested in digging deeper and resolving. If it's only present on your setup though, it will be best to close this github issue as there's little we can do without the custom code.

I'd suggest checking out a tag of the code, for example beta.2 if that's when your system worked and matching this to a matching tagged copy of the packages like `focal-260-2.6.0-beta.2` instead of the floating `focal-260`. This way you could have your setup stable and only do a bit of work to jump to rc.1 or 2.6.0 when these are published.
