### ISSUE TITLE
Autodetect public.kurento.forceRelayOnFirefox

### ISSUE THREAD

**Issue by schrd** [bigbluebutton/bigbluebutton#16164]
**Describe the bug**
`public.kurento.forceRelayOnFirefox` should be either set to true by default or even better autodetect if a turn server is configured for BBB and set it to true if a turn server is configured.

If https://github.com/bigbluebutton/bbb-install/pull/579 gets merged, BBB servers will have a turn server configured by default. Firefox still needs a configuration tweak to work correctly with mediasoup. If the operator forgets to configure the turn workaround by setting `public.kurento.forceRelayOnFirefox`  to true, firefox media behaviour will be weird as it works in some scenarios but not all of them.

**To Reproduce**
1. Install a BBB server with `bbb-install-2.6.sh` with PR 579 applied or use any other BBB setup with a turn server and no further config tweaks
2. Firefox may or may not work, depending on the setup of the client.

**Expected behavior**
All supported browsers should work out of the box.

**Actual behavior**
Firefox sometimes works, sometimes doesn't.

**BBB version:**
all versions of BBB 2.4 - 2.6 Beta 3 with mediasoup enabled are affected

**Desktop (please complete the following information):**
 - OS: Linux, Mac, Windows
 - Browser Firefox
 - Version 102

**Additional context**

**Comment by ffdixon** [comment]
> public.kurento.forceRelayOnFirefox should be either set to true by default or even better autodetect if a turn server is configured for BBB and set it to true if a turn server is configured.

Agreed.

If we enable this, does it mean that FireFox will use port 443 or 3478 for media?

**Comment by schrd** [comment]
I don't know what the preference rules are in the browser and if it is possible to influence this. I assume the first TURN service that responds will be used. Maybe @prlanzarin has some advice

**Comment by prlanzarin** [comment]
> I don't know what the preference rules are in the browser and if it is possible to influence this. I assume the first TURN service that responds will be used. Maybe @prlanzarin has some advice

This is majorly defined by candidate priority (which is calculated via a bunch of factors, some of them RFC-suggested and others implementation specific). So a bunch of things may apply when picking a TURN server (eg transport protocol, latency, IP version, ...).

> If we enable this, does it mean that FireFox will use port 443 or 3478 for media?

As for the port question: it'll use whatever is configured for the chosen candidate/TURN server.

I'm not sure I get Fred's question, but if the general intent behind it is figuring out if we can nudge Firefox towards using TURN/UDP instead of TURN/TLS to minimize TLS/TCP tradeoffs - the answer is that if one configures  TURN/UDP + TURN/TLS entries, the browser will _probably_ pick the one that works best (and I'm not 100% sure, but I'd wager TURN/UDP candidates have higher priority than TURN/TLS).

**Comment by BrentBaccala** [comment]
Any idea what settings or environment is needed for a Firefox client to fail when `forceRelayOnFirefox` is false?
