### ISSUE TITLE
Please update the docs to 2.6

### ISSUE THREAD

**Issue by Rhywden** [bigbluebutton/bigbluebutton#17530]
I just wasted several hours because 2.6 now seemingly installs its own STUN server and does not read the values from `/usr/share/bbb-web/WEB-INF/classes/spring/turn-stun-servers.xml` anymore.

I was very lucky to see the "Installing Coturn" message scrolling by when re-installing BBB to see where I went wrong.

Don't get me wrong, I'm happy that this feature is now included and seems to be working out of the box. But it needs to be documented.

Also, most of the links to documentation on the website lead to outdated versions (the link to documentation at the bottom of the mainpage, for example, _tries_ to lead to 2.3!)

**Comment by Rhywden** [comment]
Here's another example which, frankly, is a bit weird: Go to the main page ( https://bigbluebutton.org/ ), click on "Explore our new release", click on "Read About What's New In Our Blog Post" right under "Read more in our BigBlueButton 2.6 blog post" and you get:

https://bigbluebutton.org/2022/10/14/bigbluebutton-releases-version-2-5-with-features-to-assist-teachers-with-management-engagement-and-assessment-in-their-virtual-classroom/

Which, you'll note, is version 2.5

**Comment by PhilippeAccorsi** [comment]
hi @Rhywden ,
do you sure about that ? `I just wasted several hours because 2.6 now seemingly installs its own STUN server and does not read the values from /usr/share/bbb-web/WEB-INF/classes/spring/turn-stun-servers.xml anymore.`

I replace this file `turn-stun-servers.xml` with the `/etc/bigbluebutton/bbb-conf/apply-config.sh` but if what you said is true, why bbb explain to use apply-config.sh to make sure custom config are always apply and not explain about breaking change when upgrade bbb from 2.5.x to 2.6.x :( :( :(

Nothing inform user about greenlight 3 in documentation. Migration from v2 to v3 is not automatic, but when we use upgrade command between 2.5.x version of bbb, greenlight use all the time the v2. When upgrade to bbb 2.6.x, bbb install script try to install greenlight v3 and in some case, is not what we want.

I also happy by the big job you done, also in documentation, but when many breaking change appear, a good idea is to inform users (admin sys of course) about the risk of migration with this new major release. Here https://docs.bigbluebutton.org/administration/install/#upgrading-from-bigbluebutton-25 (but also in release not) we just seen: no big change.

**Comment by antobinary** [comment]
Hi @Rhywden 
We had updated https://docs.bigbluebutton.org/administration/turn-server (see the note in the very beginning)
I just made a change to also mention the inclusion of the TURN server for people using bbb-install -- https://github.com/bigbluebutton/bigbluebutton/pull/17550

About the bigbluebutton.org website -- thanks for reporting! I don't have edit access there but have passed your comments to the right person.

>and does not read the values from /usr/share/bbb-web/WEB-INF/classes/spring/turn-stun-servers.xml anymore.

You may want to try the `-c` argument for bbb-install https://github.com/bigbluebutton/bbb-install/blob/master/bbb-install-2.6.sh#L61
