### ISSUE TITLE
Annotations get smaller when exporting slides

### ISSUE THREAD

**Issue by GuiLeme** [bigbluebutton/bigbluebutton#17564]
**Describe the bug**

It seems that when exporting slides, the annotations have their size decreased when comparing to the original ones, see:

![image](https://user-images.githubusercontent.com/69865537/232073560-27e5b3af-f0a7-4b4e-b768-c80233d7df9b.png)

![image](https://user-images.githubusercontent.com/69865537/232073835-0c28bcb6-25ee-4c7c-bd77-0fb92dc6afa8.png)

**To Reproduce**
1. Annotate something in the presentation you want to export (Just for comparing the exported PDF, make sure to create a big annotation);
2. Go to the upload-presentation Modal;
3. Click the `send to chat` button for the presentation you made an annotation;
4. Wait for it to export;
5. In the chat, click the `download` Button;
6. See error.

**Expected behavior**
Annotations should keep proportions.

**Actual behavior**
Annotations get smaller in the exported PDF.

**BBB version:**
`v2.7.x-release`, it doesn't seem to be happening in `dev26`.

**Comment by danielpetri1** [comment]
Hi @GuiLeme! Around 3 weeks ago, the size of the presentation canvas was reduced - see issue #17086 and related PRs. If the canvas size of `bbb-html5` does not match `bbb-export-annotations`, such scaling and positioning issues occur.

I tried to reproduce this issue with the following steps:
- checking out the `v2.7.x-release` branch
- stopping, building, and starting`bbb-common-message`, `bbb-web`, `akka-bbb-apps`, and `bbb-html5`
- stopping `bbb-export-annotations` and manually starting it
- joining a meeting and following the procedure outlined in the issue.

Here is the result I obtained:
![Screenshot 2023-04-17 at 20 37 30](https://user-images.githubusercontent.com/33319791/232582002-63e01d9e-4268-42c6-85c9-bc05fd268b1f.png)

Is it possible that when you started up a `2.7` meeting, the packaged `2.6` version of `bbb-export-annotations` was still running in the background of your environment? This would explain why it works correctly on `dev26` but not your `2.7` branch. 

Could you try manually starting the service to see whether the problem persists? There are instructions for that [here](https://docs.bigbluebutton.org/development/guide#:~:text=Developing%20Akka%2DFSESL-,Developing%20bbb%2Dexport%2Dannotations,-Troubleshooting). If it does, please report back so that I can dig deeper into this.
Cheers!

**Comment by antobinary** [comment]
Thank you for the explanation @danielpetri1 ! Makes sense!
Thank you for being on the lookout for issues @GuiLeme !

Closing.
