### ISSUE TITLE
[2.6.0 -> 2.6.6]unknown "real_scheme" variable

### ISSUE THREAD

**Issue by Nemu-x** [bigbluebutton/bigbluebutton#17887]
Describe the bug
When updating to BBB 2.6.6. starting nginx fails

To Reproduce

    Update 2.6.0 to 2.6.6
    check nginx status for error message

Additional context
root@vc:/home/ak# systemctl status nginx.service
● nginx.service - A high performance web server and a reverse proxy server
     Loaded: loaded (/lib/systemd/system/nginx.service; enabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Sat 2023-05-13 17:02:18 MSK; 3min 32s ago
       Docs: man:nginx(8)
    Process: 12802 ExecStartPre=/usr/sbin/nginx -t -q -g daemon on; master_process on; (code=exited, status=1/FAILURE)

May 13 17:02:18 vc systemd[1]: Starting A high performance web server and a reverse proxy server...
May 13 17:02:18 vc nginx[12802]: nginx: [emerg] unknown "real_scheme" variable
May 13 17:02:18 vc nginx[12802]: nginx: configuration file /etc/nginx/nginx.conf test failed
May 13 17:02:18 vc systemd[1]: nginx.service: Control process exited, code=exited, status=1/FAILURE
May 13 17:02:18 vc systemd[1]: nginx.service: Failed with result 'exit-code'.
May 13 17:02:18 vc systemd[1]: Failed to start A high performance web server and a reverse proxy server.

**Comment by Nemu-x** [comment]
fixed by adding 

`set $real_scheme $scheme;`

to /etc/nginx/sites-available/bigbluebutton

**Comment by antobinary** [comment]
Hi!

The variable you're referring was introduced via https://github.com/bigbluebutton/bigbluebutton/pull/17732

So likely your /etc/nginx/sites-available/bigbluebutton

needs tweaking. See what's on test26:
root@test26:~# grep -rn scheme /etc/nginx/sites-available/bigbluebutton*
/etc/nginx/sites-available/bigbluebutton:48:  # This variable is used instead of $scheme by bigbluebutton nginx include
/etc/nginx/sites-available/bigbluebutton:49:  # files, so $scheme can be overridden in reverse-proxy configurations.
/etc/nginx/sites-available/bigbluebutton:50:  set $real_scheme "https";
