### ISSUE TITLE
fitToWidth is always false for non-presenter

### ISSUE THREAD

**Issue by vasylOstrovskyi** [bigbluebutton/bigbluebutton#18368]
**Describe the bug**
Just wondering why https://github.com/bigbluebutton/bigbluebutton/issues/17982 could happen, I notice that for non-presenter, the variable fitToWidth in the Whiteboard component is always false. Does not seem to be intended behaviour.

**To Reproduce**
1. In the file `bigbluebutton-html5/imports/ui/components/whiteboard/component.jsx` add line
`logger.debug({}, 'fittowidth: ' + fitToWidth)`
near line 179 or in some other place where this variable is used. Rebuild.
2. Start session for two or more users.
3. As presenter, turn on an off fit to width, change slides
5. Compare console messages for different users 

**BBB version:**
latest git v2.6.0-release

Regards,
 Vasyl

**Comment by KDSBrowne** [comment]
I'm not sure if this was intentional or not, but I don't think the `fitToWidth` property was ever set up to be transmitted through `akka`.  In that case, it would always false for non-presenter. For issue #18368 it looks like a race condition could be causing the problem. In #18153 the idea was to turn off `fitToWidth` before the presentation switches (still had some issues), I was able to move the property one component higher and was able to prevent the issue from happening.

**Comment by vasylOstrovskyi** [comment]
Thank you. You right, now I see that non-presenter does not need to know this value.
