### ISSUE TITLE
The userdata-bbb_auto_join_audio does not work 

### ISSUE THREAD

**Issue by hanazarraa** [bigbluebutton/bigbluebutton#18370]
**Describe the bug**
The audio modal appears always even userdata-bbb_auto_join_audio is set to true 

**To Reproduce**
1. Start a bbb session
2. Configure api mate adding also userdata-bbb_auto_join_audio=true
3. Join the session.

**Expected behavior**
Automatic joining the session in microphone  mode by ignoring the audio modal 

**Actual behavior**
The audio modal appears always even userdata-bbb_auto_join_audio is set to true 

BigBlueButton 2.7.0-beta.1

OS: Windows

Browser: Chrome/Edge/Firefox/opera

**Comment by ramonlsouza** [comment]
This is the expected behavior (when auto_join_audio=true, the audio modal will appear when a user joins the meeting; setting it to 'false' will prevent the modal from appearing during joining).

To achieve the desired effect, configure the following settings:

`userdata-bbb_listen_only_mode=false` (to disable listen-only mode)
`userdata-bbb_skip_check_audio=true` (to disable the echo test)
