### ISSUE TITLE
Replace modal views so the presenter can still see webcams

### ISSUE THREAD

**Issue by debuglevel** [bigbluebutton/bigbluebutton#18435]
**Is your feature request related to a problem? Please describe.**
There are a few "modal" views (e.g. upload a new presentation, create breakout rooms, settings) which consume the whole screen.
When I'm creating/configuring a breakout room (which might easily take up some minutes if I move users manually into their rooms) I do not see the webcams anymore.

It already happened that some user wanted to show my something while I created breakout rooms, which I was unable to see then.

**Describe the solution you'd like**
The modals could be placed in the presentation area. Or the could use a window widget.

**Comment by antobinary** [comment]
We used to have the modals only cover a portion of the screen but there were other types of complaints - confusion on what's going on, anger about lost changes when clicking outside of the modal etc. We decided to make the modals fullscreen and that type of feedback stopped. It's been a few years since. I personally don't look forward to reverting the design decision.
