### ISSUE TITLE
Screen sharing should be bigger on the own client

### ISSUE THREAD

**Issue by debuglevel** [bigbluebutton/bigbluebutton#18433]
**Describe the bug**

If I'm sharing my screen, I get a rather small preview / indicator that I'm currently sharing my screen. I always think "oh, why it is it so small?" until I remember "it's so small because it's me who is sharing the screen. The other users see it in normal presentation size."

**To Reproduce**
1. Share your screen.
2. Go back into your client.

**Expected behavior**
It's as big as somehow possible.

**Actual behavior**
It's quite small.

**Screenshots**
![image](https://github.com/bigbluebutton/bigbluebutton/assets/2401265/b8451620-4562-4683-8f29-0662428b6bfd)

**BBB version:**

* 2.7 beta 3

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - *on a screen with High-DPI settings! 3840x2160 with 175% magnification*

**Comment by antobinary** [comment]
We used to have it bigger and it caused a LOT of confusion for years because when the presenter was sharing screen and would [inevitably] screenshare the current client, which was screensharing the presenter screensharing (etc) and that mirroring effect was really throwing off instructors... 
See https://github.com/bigbluebutton/bigbluebutton/pull/12522

Based on what I see we no longer hear about confusion of this type...

**Comment by debuglevel** [comment]
I see. I also got some of these complaints and wondered if none of them ever saw an infinity mirror or video feedback in their lives :D.

Unfortunately I've got no real good idea how to solve both issues. The best I came up with is labeling it "You are now sharing your screen. And don't worry, it's bigger for the others."; but that feels kind of poor :)
