### ISSUE TITLE
Make Screen Wake Lock more implicit

### ISSUE THREAD

**Issue by danimo** [bigbluebutton/bigbluebutton#18431]
I am really excited about the Screen Wake Lock feature (#18164). What puzzels me is that the feature is optional. While I see why you might want to turn it off on the administrative level (it's still experimental), I do not understand the purpose of dis-/enabling it in the UI.

Maybe I am on the wrong train of thought here, but is there a use case where a user would opt out of this feature? Turning the screen off would mean the device would go to power saving mode which means going to sleep and dropping the call. This is certainly not an expected user experience.

I'd rather the user would be sent a notification about the screen being active as long as they are participating in the conference with audio. Conversely, the user on a mobile device _without_ the feature should be notified that the call will be dropped after they turn off their screen.

The ideal solution would be to allow the display to turn off, but simply not go into deep sleep, but I guess that's intentionally not available from the browser API?

**Comment by Arthurk12** [comment]
Hi @danimo ! Sorry for the late response.
> I am really excited about the Screen Wake Lock feature (https://github.com/bigbluebutton/bigbluebutton/pull/18164). What puzzels me is that the feature is optional. While I see why you might want to turn it off on the administrative level (it's still experimental), I do not understand the purpose of dis-/enabling it in the UI.
Maybe I am on the wrong train of thought here, but is there a use case where a user would opt out of this feature? Turning the screen off would mean the device would go to power saving mode which means going to sleep and dropping the call. This is certainly not an expected user experience.
I'd rather the user would be sent a notification about the screen being active as long as they are participating in the conference with audio. Conversely, the user on a mobile device without the feature should be notified that the call will be dropped after they turn off their screen.

I agree with you. There is no special/technical reason for the flow to be like the way it is currently. And the disable/enable toast is shown to the user because, at first, it seemed to give users more understanding of what is going on(they may question why the screen is not turning off, why is the battery being drained faster...) but, as you mentioned, it can be easily replaced by an informative toast, both when the feature is enabled and disabled/not supported.

> The ideal solution would be to allow the display to turn off, but simply not go into deep sleep, but I guess that's intentionally not available from the browser API?

You're right. The wake lock API does not provide independent control over the display turning off and the device going into deep sleep.

**Comment by danimo** [comment]
No worries, your response is appreciated. Would you like to give give this proposal a shot or do you want me to? I cannot promise a swift implementation through.

**Comment by Arthurk12** [comment]
Yes. I'll open a PR addressing this proposal.

**Comment by antobinary** [comment]
FYI we're activating this by default in https://github.com/bigbluebutton/bigbluebutton/pull/18472
