### ISSUE TITLE
[2.7] Recording archive fails with 0-byte sized media files from Kurento

### ISSUE THREAD

**Issue by prlanzarin** [bigbluebutton/bigbluebutton#18720]
**Describe the bug**

KMS sometimes generates 0-byte camera/screen sharing files.
The remuxing added in https://github.com/bigbluebutton/bigbluebutton/pull/18559 runs before those files are discarded by sanity and there's no explicit handling for this scenario in the archive step, so it can fail.

**To Reproduce**

Organic reproducible scenario unclear - error can be simulated.

**Expected behavior**

Archive ignores 0-byte sized files and skips through failed remux attemps.

**Actual behavior**

Archive fails.

**Additional context**

- https://github.com/bigbluebutton/bigbluebutton/pull/18559

**Comment by kepstin** [comment]
I believe that the particular case which is failing is when a user shares a webcam, but due to network issues, kurento does not receive any frames (or does not receive any keyframes) before the webcam stream is stopped. Regardless, there’s no recovery possible – the expected behaviour is that the webcam will be omitted during processing.
