### ISSUE TITLE
Some PDF files appear over black background in recordings when in firefox

### ISSUE THREAD

**Issue by JuanCasad0** [bigbluebutton/bigbluebutton#18761]
**Describe the bug**
When in firefox, some pdf show in black on the recordings (presentation). However, when testing under Google Chrome they show as they should be. (Some users are reporting they see the black background under chrome ,though). I tried to modify the pdf's, however couldn't find where the problem comes from.

**To Reproduce**
1. Start the session, upload the pdf while recording.
2. Play the presentation, and find the black background.

**Expected behavior**
The PDF should be clearly visible.

**Actual behavior**
It is not (see pic)

Bigbluebutton 2.6.12

**Desktop (please complete the following information):**
 - OS: Windows 11 & OSX
 - Browsers: latest Firefox & Chrome.

**Additional context**
![Captura de pantalla 2023-09-12 153121](https://github.com/bigbluebutton/bigbluebutton/assets/122808643/ced5a123-d454-41e4-a605-bd6c3b5a649b)
[curriculo_estudio 2022.pdf](https://github.com/bigbluebutton/bigbluebutton/files/12586947/curriculo_estudio.2022.pdf)

**Comment by JuanCasad0** [comment]
Just checked in test27, getting the same result: https://test27.bigbluebutton.org/playback/presentation/2.3/ce112bced29bfa037dec409ef367157f367faf0d-1694625730432

Is this a normal behavior? It seems odd to me that this problem is happening with some teachers in our system. Thanks for replying!

**Comment by jorgelondo** [comment]
Hello @JuanCasad0 , maybe it is related to https://github.com/bigbluebutton/bigbluebutton/issues/18550

**Comment by JuanCasad0** [comment]
Hi  @jorgelondo

Indeed, it appears to be the same problem. I was going nuts thinking it was only happening to me!

Have your tried opening in Chrome? Any workaround or improvement since August? 

Thanks for reaching out!

**Comment by JuanCasad0** [comment]
2.7.1 and the problem persists for us. As it doesn't seem to be something "usual", could this be related to the pdf files? Any idea?

thanks!

**Comment by jorgelondo** [comment]
@JuanCasad0 
I Juan, have been carrying out some tests and what I have seen is that the problem occurs due to the color profile with which the file is exported.
But the solution is to add a white background to the "canvas" id of the presentation (I will detail it later and attach images)

SRGBIEC61966-2.1 is an RGB (red, green, blue) color space standard that HP and Microsoft created collaboratively in 1996 for use in monitors, printers, and the World Wide Web.

RGB-ADOBE-1998 The Adobe RGB color space is an RGB color space developed by Adobe Systems in 1998. It was designed with the objective of reproducing as best as possible the CMYK color space, used in printing, but from a color space RGB used in computer monitors.

By using SRGBIEC61966-2.1 it allows transparency in the background, normally we would see it in white, but when uploading the pdf to bigbluebutton with this color profile, the transparency is left and the background color is kept in black.

When using RGB-ADOBE-1998, which is a profile designed to display print colors but on the screen, it keeps the background white.

Apparently a solution would be to export the documents in RGB-ADOBE-1998 profile or similar, but in reality if we see the documentation one of the correct profiles should be SRGBIEC61966-2.1 since they are designed for working with colors for monitors (for web) since they have less information therefore reducing the weight of the file.
So I think there must be some way to change the background color of the presentation in the div id="canvas" (in the CSS code) when viewing the class recording in "Presentation" format.
Error
![bbb-error-background](https://github.com/bigbluebutton/bigbluebutton/assets/672505/a6a08c61-5af6-47ac-b110-afa4a19fb9a7)
Solution
![bbb-solution-background](https://github.com/bigbluebutton/bigbluebutton/assets/672505/b4443f9d-58ad-4a8d-980b-4070646395d8)

**Comment by JuanCasad0** [comment]
@jorgelondo Thanks a lot for your well detailed explanation. It is indeed really interesting, but it is difficult to solve from the user's point of view. Once again, thank you very much for taking your time!

I don't know it this problem could have an easy fix from @ffdixon and team? Hope they can tell us something!

**Comment by JuanCasad0** [comment]
Okay. I found the issue, and it's unrelated to BigBlueButton. 

It actually resides in the user profile of Firefox itself. My solution was to create a new profile by accessing about:profiles. 

Click on 'Create a new profile' and open it in a new window. The previous profile will still exist, but the new one will be set as the default (at least that's what happened in my case). 

I recommend exporting bookmarks, saved passwords, and making a note of the installed extensions, so that the new profile can be the default without having to change it each time.

Best regards.
Juan.

**Comment by jorgelondo** [comment]
Hi @JuanCasad0, @ffdixon   I still think that the solution is to set a default "background-color:#ffffff" in the ".tl-canvas" class in the css since the problem persists in both Chrome and Firefox and in other browsers, at least in my case. Thanks

**Comment by JuanCasad0** [comment]
Agree, @jorgelondo . However, seeing that there was no other solution available, for me this was the simplest and quickest one... although it's not perfect. 

I suspect that this only happens in very rare occasions and will probably be hard to reproduce.
