### ISSUE TITLE
tldraw translations not get updated

### ISSUE THREAD

**Issue by mokazemi** [bigbluebutton/bigbluebutton#18835]
It looks tldraw translations are separated from BBB translations. I didn't find some strings on BBB strings, so I fixed them upstream on tldraw [here](https://github.com/tldraw/tldraw/tree/main/assets/translations).
Could you please update whiteboard version used in BBB? 
Or another approach is to move tldraw translations to BBB Transifex, too (like the old whiteboard).

**Comment by antobinary** [comment]
Hi @mokazemi 

I see your pull requests in tldraw. You translated in the tldraw v2 repository (v2 is still an alpha and we're looking to migrate to it in BBB 3.0 -- 

On BBB 2.6, 2.7 we use tldraw v1, https://github.com/tldraw/tldraw-v1 and we're on 1.27.0 version. There is 1.28.4 now it seems with some translations and fixes. At this point we intend to focus the resources toward migrating to v2 rather than pulling 1.28.4 in (unless someone starts hitting v1 issues solved on 1.28).

But to answer your question directly -- your translations (thank you for doing those!) will land in BBB 3.0 together with tldraw v2.
