### ISSUE TITLE
Big Blue Button rebuild on Azure VM server

### ISSUE THREAD

**Issue by sky-bear-dev** [bigbluebutton/bigbluebutton#19355]
Hello, everyone.

I have now deployed Big Blue Button server on Azure VM ubuntu server. Now, after changing the code of some components in bigbluebutton-html5/imports/ui, I want to rebuild the server so that it is reflected.

I already changed the code of some components in the home/bigbluebutton/dev/bigbluebutton/bigbluebutton-html5/ directory and tried the following command.

I can access the VM server using cli. I would appreciate any help on this.

Cheers

**Comment by Ithanil** [comment]
Hi, you can find documentation for developing and building BBB components here: https://docs.bigbluebutton.org/development/guide/

Also, please consider using for example this Google group https://groups.google.com/g/bigbluebutton-dev to ask questions instead of opening issues on GitHub.

Merry Christmas!
