### ISSUE TITLE
Chapter "Delete recordings older than N days" hidden inside code block

### ISSUE THREAD

**Issue by cmos64** [bigbluebutton/bigbluebutton#19585]
**Link to the portion of the docs**
https://docs.bigbluebutton.org/administration/customize/#delete-raw-data-from-published-recordings

This chapter contains a code block at the end of the chapter which is missing a closing code block line. The following chapter "Delete recordings older than N days" is then contained nearly completely in this code block. Also because of this the headline is not detected and therefore it's not visible in the TOC which could lead to admins not noticing this maybe important information.

**Describe what you believe the correct version should be**
Add a closing code block line here:
https://github.com/bigbluebutton/bigbluebutton/blob/d924e23069f0519e80157fb632c2e0d8138a6f6c/docs/docs/administration/customize.md?plain=1#L72-L74

**Screenshots**
![Screenshot_20240206_102501](https://github.com/bigbluebutton/bigbluebutton/assets/96437610/f628429f-f308-42ac-bf0f-a13671901c26)

**Comment by antobinary** [comment]
Thanks for reporting!
Fixed in 2.7 docs via https://github.com/bigbluebutton/bigbluebutton/pull/19588
Fixed in 3.0+ docs via https://github.com/bigbluebutton/bigbluebutton/pull/19589

![Screenshot from 2024-02-06 09-11-13](https://github.com/bigbluebutton/bigbluebutton/assets/6312397/7d26918b-c8fb-4cf6-98ff-b85f783fa9ba)
