### ISSUE TITLE
Unable to run BigBlueButton within an iFrame on Safari

### ISSUE THREAD

**Issue by bigbluebutton-issue-import** [bigbluebutton/bigbluebutton#1958]
Originally reported on Google Code with ID 1204

```
Given a sample BigBlueButton server running at 192.168.0.35, create an HTML file with
the following 


Before
<iframe name="inlineframe" src="http://192.168.0.35/" frameborder="0" scrolling="auto"
width="800" height="800" marginwidth="5" marginheight="5" ></iframe>
After

and store it on a different web server (such as 192.168.0.174) in the web root as iframe_test.html.
 Open

  http://192.168.0.174/iframe_test.html

in Safari, then try to login to the BigBlueButton server.  Safari will exit the login
process.  Enabling the Developer tools in Safari shows the following message in the
console.

Unsafe JavaScript attempt to access frame with URL http://192.168.0.174/index2.html
from frame with URL http://192.168.0.35/client/BigBlueButton.html. Domains, protocols
and ports must match.




What is the expected output? What do you see instead?


Please use labels and text to provide additional information.
```

Reported by `ffdixon` on 2012-04-07 17:18:10

**Comment by ffdixon** [comment]
Closing as this was an issue related to the Flash client (the project has moved to an HTML5 client).

**Comment by somuelle-tmt** [comment]
@ffdixon This issue was/is not related to the Flash client but to restrictions in Safari.

If you open a  https://example.com/html5client/join?sessionToken=****** url inside an iframe in Safari you get "401 forbidden" message because BBB is not allowed to set cookies before user interaction inside the iframe. According to different sources storage access via their APIs could be a solution: https://webkit.org/blog/10218/full-third-party-cookie-blocking-and-more/

Is anything here planned for BBB?
