### ISSUE TITLE
Write all userdata parameters to the join in the events.xml

### ISSUE THREAD

**Issue by ffdixon** [bigbluebutton/bigbluebutton#20316]
**Is your feature request related to a problem? Please describe.**
To enable a front-end to pass through a courseID and domain name for the user, add to parameters to the join

```
userdata-bbb_ext_course_id
userdata-bbb_ext_domain
```

**Describe the solution you'd like**
These parameters would be stored in the events.xml along with the user's join information. 

**Additional context**
This feature is to enable users to join from multiple sites to the same room and have a way to distinguish between users in later processing of the events.xml, such as when creating a customer recording format.

These should be added to the documentation [here](https://docs.bigbluebutton.org./3.0/administration/customize/#application-parameters).

**Comment by jfederico** [comment]
So probably the parameters to be passed should be

`userdata-bbb_ext_course_id
userdata-bbb_ext_domain`

**Comment by antobinary** [comment]
During the discussion phase the number of parameters increased quite a bit. The idea now is to include _all_ `userdata-*` parameters that were passed when a user was joining  to `events.xml`.

Before:

``` 
<event timestamp="40081568279" module="PARTICIPANT" eventname="ParticipantJoinEvent">
    <name>Viewer One</name>
    <role>MODERATOR</role>
    <date>2024-06-07T12:47:20.215Z</date>
    <externalUserId>w_pfqgkglpsaer</externalUserId>
    <userId>w_pfqgkglpsaer</userId>
    <timestampUTC>1717764440215</timestampUTC>
  </event>
```

After:

``` 
<event timestamp="40081568279" module="PARTICIPANT" eventname="ParticipantJoinEvent">
    <name>Viewer One</name>
    <role>MODERATOR</role>
    <date>2024-06-07T12:47:20.215Z</date>
    <externalUserId>w_pfqgkglpsaer</externalUserId>
    <userId>w_pfqgkglpsaer</userId>
    <timestampUTC>1717764440215</timestampUTC>
    <userdata
      ext_domain="some string"
      ext_course_id="123dhk"
      bbb_hide_actions_bar=true
...
    />
  </event>
```

https://github.com/bigbluebutton/bigbluebutton/blob/v2.7.x-release/akka-bbb-apps/src/main/scala/org/bigbluebutton/core/record/events/ParticipantJoinRecordEvent.scala

Steps identified so far (on BBB 2.7):
- bbb-web to get the userdata and possibly include it in the message bbb-web->akka-apps
- akka-apps to store the userdata
- akka-apps to dump the userdata into the ParticipantJoinRecordEvent

---

Steps after implementation
- document the events.xml change in 2.7 What's New docs (@antobinary )
- mention this change of events.xml in the release notes (@antobinary )

**Comment by kepstin** [comment]
Underscores not being allowed was a mistake on my part, after re-reading the linked XML doc, it turns out they're acceptable. The main things to note are that digits 0-9 are not permitted as the first character in an attribute name, and although `:` is permitted, it has special meaning regarding xml namespaces and should be avoided.

**Comment by gustavotrott** [comment]
Hey,

the name `userdata` is unclear regarding what this prop stores. While it acts as a prefix for parameters, the documentation refers to this as "Custom parameters," which is a more accurate description. In version 3.0, we have been renaming this prop to `userCustomParameter` because `userdata` is vague and can be confused with meeting metadata or other similar data within the system. 

I suggest naming this prop `customParameters` to align with the terminology used in version 3.0, thus avoiding future refactoring and inconsistencies across different projects.

<table><tr><td>

![image](https://github.com/bigbluebutton/bigbluebutton/assets/5660191/9969cc9c-14b8-4d6c-9e02-2fe3b3e4d8fd)

</td></tr></table>

**Comment by antobinary** [comment]
Renaming the xml prop to `customParameters` sounds good to me too. I would **not** rename the `userdata` prefix though (just to be clear).

**Comment by kepstin** [comment]
I recommend leaving the xml element name as `<userdata>`. Anything else would be confusing. You put `userdata-*` parameters on the join call, and they come out in the recording XML in the `<userdata>` element.

**Comment by gustavotrott** [comment]
> I recommend leaving the xml element name as `<userdata>`. Anything else would be confusing. You put `userdata-*` parameters on the join call, and they come out in the recording XML in the `<userdata>` element.

I understand your concern about the confusion caused by different names. However, do you think `userdata` is a better name than `customParameter` for storing user-specific parameters?

To address this issue without breaking current integrations, I suggest accepting both `customParameter` and `userdata` as prefixes. This approach maintains compatibility with the existing prefix while recommending the new prefix for future integrations. By doing this, we can gradually transition to using the new name throughout the system.

**Comment by kepstin** [comment]
There's no reason to change it, that's just useless churn. The name doesn't really matter that much. If anything, i'd argue that the documentation should be updated to say "userdata" paramters instead of "custom" parameters.

"userdata" is pretty short and simple - it's data for or about a specific user - and is analogous to the meta(data) parameters on the create call.

**Comment by gustavotrott** [comment]
Now, with GraphQL and plugins making integrations easier, we are particularly concerned with aligning names with 
documentation and system labels. 

If `userdata` is genuinely the best name, let's use it. But if we're keeping it just for convenience, I believe this is the right time to improve names for future integrations and new developers.

Let's choose the best option, not just the easiest one.

I defend using `customParameter` or `userCustomParameter`  because these names make it clear that the parameter was passed during the user's creation and is intended to provide customized behavior unique to this user.

**Comment by kepstin** [comment]
In general, the "userdata" parameters are a way to attach additional "data" to a specific "user" when they join the session. This may or may not be custom - up until this point, the only use was to set parameters defined by BigBlueButton itself - i.e. non-custom parameters.

It's just… user data. So `userdata` is fine.

**Comment by gustavotrott** [comment]
In this case, looks like `user-metadata` would be the best name 😅
But maybe it's not worth the change.

Alright, if `userdata` is really the best name, we should tweak documentation and I'll refactor all parts that was using `customParameter` to align with this name.
Thanks for clarifying it @kepstin !
