### ISSUE TITLE
To have the exact list of supported presentation document format

### ISSUE THREAD

**Issue by klorydryk** [bigbluebutton/bigbluebutton#20346]
Hi,
the list here https://support.bigbluebutton.org/hc/en-us/articles/1500005216321-Upload-a-presentation-enable-for-download does not contains opendocument format, when we see 2 different lists in the code:

https://github.com/bigbluebutton/bigbluebutton/blob/48df491e58216567757ebe6cd91c6d5befaf9a1e/bbb-common-web/src/main/java/org/bigbluebutton/presentation/MimeTypeUtils.java#L9

and

https://github.com/bigbluebutton/bigbluebutton/blob/develop/bigbluebutton-html5/private/config/settings.yml#L936

have different lists.

Please provide the exact and complet list of supported formats.
Thanks !

**Comment by GuiLeme** [comment]
Hey, @klorydryk, thank you for pointing that out! We are going to fix that, but summing up those two pieces of code you brought up are just validations to the front and for the back-end, so ideally, they would match, but since they are not, at the moment, consider the overlapping of them the valid presentation formats.

I am going to investigate it a little better, and send a fix for that making sure they match and it is described in the docs.

Thanks again!

Kind regards!

**Comment by GuiLeme** [comment]
Hello, @klorydryk, sorry for the late response regarding a solution for this issue. I did not touch it just yet, I will take a look on it next week, though. Thank you for being patient and please ping me if any doubts or suggestions.

**Comment by antobinary** [comment]
We'll close this when we are done backporting it to BBB 2.7.

**Comment by antobinary** [comment]
https://docs.bigbluebutton.org/development/api/#supported-document-types is the list
