### ISSUE TITLE
[3.0] Remove ja-jp locale from transifex

### ISSUE THREAD

**Issue by hiroshisuga** [bigbluebutton/bigbluebutton#20359]
I am happy to see the internationalization has started on BBB3.0.
Long time ago we decided to remove the locale ja-jp, leaving only ja. Please remove ja-jp from the BBB3.0 translation at Transifex.

**Comment by antobinary** [comment]
Hi @hiroshisuga 
I remember we spoke about this long ago and I removed (several times) ja_JP. However, this seems to go against the flow with Transifex and I also have not found a good way to remove it forever.
We now use an integration Transifex <-> GitHub which we've configured to only pull the locale if/when it is 100% translated. This means that if Transifex translator focus on ja, you should never see ja_JP in the client. The same goes for a dozen or so other locales that were requested by community members at some point but were never really translated. We have 2x Turkish, Vietnamese, German, etc.
Rather than keeping a list of these (undesirably) doubled locales and manually removing them every once in a while, my current thinking is to just let them hang around in Transifex unused. The reality is that I don't know whether there are differences in locales and accept doubles when requested by people who know the language. We have several nuances of Spanish which all seem to be used for example and there've been discussions in the past about using the second German locale as a "variation" of written forms.
Could you please confirm that aside from Transifex (as an empty locale) you don't see ja_JP anywhere else?

**Comment by hiroshisuga** [comment]
Hi @antobinary , I got it. Let's leave ja-jp as it is. 
I followed the discussion of written German variation with some interest. For sure, we do not want to be involved into a "political" (sorry to say so) issue.

**Comment by antobinary** [comment]
Thanks @hiroshisuga !
I will be closing this issue now. Don't hesitate to reopen (or open a new one) if the need arises.
