### ISSUE TITLE
Users manually removed and prevented from rejoining meeting can still rejoin 

### ISSUE THREAD

**Issue by jamesbellbn** [bigbluebutton/bigbluebutton#21207]
BigBlueButton 2.7.12

After a Moderator manually removes a user from a meeting and opts to prevent them from rejoining, the same user can rejoin meeting. 

Steps to reproduce:
- Choose a user to remove from the list of Users in any live meeting
- Select "Remove user"
- On the "Remove user" confirmation window, check the "Prevent this user from rejoining the session" box and select "Yes"
- Then as the removed-user, rejoin the same meeting with the same name, in the same browser tab, from the same IP address

Expected behavior:
That any removed-user prevented from rejoining not be allowed to rejoin

Actual behavior:
Removed users prevented from rejoining are able to rejoin

![image](https://github.com/user-attachments/assets/e29ef1b6-68cc-4904-b4bb-e008081814b7)

**Comment by antobinary** [comment]
Steps to reproduce (via api mate):
1. Join as moderator
2. set username (in api mate) to `Viewer`
3. set `userID` to `jaja`
**4. set Custom Parameters to `userdata-bbb_ask_for_feedback_on_logout=true`**
5. click on Join as attendee
6. (you joined fine)
7. Have the moderator click on the username Viewer, eject, also ban
8. Viewer should be removed from the session.
9. Go back to api mate (the values you set are still present)
10. Click one more time on Join as attendee so that a viewer with userID=jaja attemts to join

Expected result: Viewer can't join. The screen says the user was removed

Actual result: The viewer joins as if it was never banned.

Observations: In the client code we seem to handle two cases separately - 1) feedback dialog needs to be shown 2) a combination of factors including ejectedReason.
