### ISSUE TITLE
Load testing with H5P plugin

### ISSUE THREAD

**Issue by fadgan** [bigbluebutton/bigbluebutton#21388]
Dear friends,

Any tips and suggestions are highly appreciated.

We are in the process of customizing BBB and integrating H5P plugin into it. One of the features we will extensively use is the drag and drop provided by the plugin (see [here](https://www.youtube.com/watch?v=byn3cYsmoSk)). Classes will be one-to-one always.

We are now looking for ways/tools to simulate users performing these actions. In particular, tools to concurrently have several processes perform the drag and drop. 

Please, share any thoughts to assist us in simulating this type of behavior.

**Comment by otacke** [comment]
Can't you use Playwright (or puppeteer or Selenium or similar) for end-to-end testing? Please compare https://www.olivertacke.de/labs/2024/04/30/990/ and https://github.com/otacke/h5p-game-map

My current implementation is still patchwork, because I had to work around current shortcomings of the H5P CLI tool,  but it works. Don't know about running concurrent processes though.

**Comment by fadgan** [comment]
Thank you for coming back. I've been researching the tools you mentioned here. Looks like Playright can do the job. 
Highly Appreciated !!!
