### ISSUE TITLE
Create native desktop sharing binaries for Mac, Unix, and PC users

### ISSUE THREAD

**Issue by bigbluebutton-issue-import** [bigbluebutton/bigbluebutton#2183]
Originally reported on Google Code with ID 1430

```
Hello,

in recent times, Java is quite insecure for web content. Disabling / uninstalling Java
on Desktop computers is a as best practice. (*)

By that, screensharing is broken on almost any client computer - rendering BBB useless
for foreign presenters.

Please support screen-sharing if Java is not installaed - like Google Hangout does.


(*) 
http://blog.fireeye.com/research/2013/02/yaj0-yet-another-java-zero-day-2.html
https://community.rapid7.com/community/metasploit/blog/2013/02/25/java-abused-in-the-wild-one-more-time
http://www.kb.cert.org/vuls/id/625617

```

Reported by `oma@stephan.homeunix.net` on 2013-03-01 10:16:33

**Comment by ffdixon** [comment]
Implemented in BigBlueButton 1.1-beta.  

When the presenter starts desktop sharing, the browser downloads a java native launch program that triggers the download a platform specific JAR file (Windows, Mac OS X, or Linux) that has ffmpeg embedded inside.

ffmpeg is a binary application that captures the screen and transmits it to the BigBlueButton server encoded directly in screen video codec 2 (SVC2) over real-time messaging protocol (RTMP) to redt.

It's a binary application (instead of Flash) doing the capture, encoding, and transmitting of the presenters screen.
