### ISSUE TITLE
BBB 0.8 video playback

### ISSUE THREAD

**Issue by amit22285** [bigbluebutton/bigbluebutton#2784]
HI Team,

 I am using BBB 0.8 in one of our project.As per requirement we want to record a session  (contains chat,audio,desk-share,webcam).
 And as per BBB 0.8 documentation we made some changes to achieve this. (please find below steps and confirm for the same)
 
 1: edit /usr/share/red5/webapps/video/WEB-INF/red5-web.xml and set recordVideoStream to true.
 2: edit /usr/share/red5/webapps/deskshare/WEB-INF/red5-web.xml and at line 41 set the value for constructor-arg to true.
 3: while creating a new meeting pass record=true 
 
 After this change we restarted the server and tested , the recorded contents are correctly storing in corresponding paths (including .flv for video)
 
 But when we run default playback.html file its showing only chat,audio,presentation but not able to see the recorded video.
 
 Q1. So can anyone help us to achieve this requirement for BBB 0.8 ? please share the links / steps for the same.
 Q2. Also want to know whether BBB 0.8 has any feature to record the session on demand . if yes/no how do we achieve in BBB 0.8 ?

**Comment by kepstin** [comment]
The features you're asking about have already been implemented in the current release of BigBlueButton version 0.9. I recommend that you move from 0.8 to 0.9; we no longer support the 0.8 release.

http://docs.bigbluebutton.org/install/install.html has instructions for installing the current BigBlueButton version, including how to move your recordings to the new server so that they can be reprocessed with the new features available.
