### ISSUE TITLE
Save cursor position when sharing desktop

### ISSUE THREAD

**Issue by ritzalam** [bigbluebutton/bigbluebutton#2836]
In desktop sharing, we don't record the cursor's position when the meeting is recorded.

We need to record the cursor's position do be able to display it when processing the recording.

**Comment by ritzalam** [comment]
Calvin says: Note that this isn't applicable to webrtc desktop sharing; the cursor is actually encoded into the video in that case

**Comment by kepstin** [comment]
As far as I know, there is no windows API available to capture an image of the screen including the mouse cursor; this is because the mouse cursor is actually drawn over top of the screen image using special hardware built into the video card.

Most windows screen capture works by grabbing an image of the screen, getting the current cursor position and cursor image, then drawing the cursor on top of the screen image themselves before encoding.

**Comment by ritzalam** [comment]
We might be able to draw the cursor into the snapshot image after finding the cursor position. Not sure if we can determine the cursor shape (i.e. arrow or vertical bar).

**Comment by kepstin** [comment]
The other alternative - where deskshare cursor position is saved as events in events.xml is also doable; it makes the recordings scripts a bit more complicated but it shouldn't be too hard to do I think.

**Comment by ritzalam** [comment]
Drawing it on the applet before the image is sent to the server would be the easiest and least implementation changes.

**Comment by ffdixon** [comment]
Merged into https://github.com/bigbluebutton/bigbluebutton/issues/2926

(capturing desktop using Java Web Start will enable us to capture the mouse cursor)
