### ISSUE TITLE
Convert Deskstop sharing applet to JWS

### ISSUE THREAD

**Issue by ritzalam** [bigbluebutton/bigbluebutton#2926]
We need to convert the desktop sharing applet into a java web start application. 

The JWS app doesn't prompt to allow permission to run when it is signed. It only displays the certificate.

**Comment by tsalafi** [comment]
Hi Richard,

We also want to achieve the same functionality...Can you please guide me? Actually, we want to run the desktop sharing applet as a desktop application (either via jws or something else) so that we would be able to make it browser-independent...

Any response from you will be highly appreciated...

Talal Shoaib, MCTS, MBA
APPLICATION DEVELOPER, NORTH AMERICA
Gmail: talal.bsse@gmail.com
Phone:       +1.647.925.3163  x7138
Mobile:      +1.647.529.3635
www.solgenia.com
Linkedin: https://ca.linkedin.com/in/talal-shoaib-7671709 
Canada | United States | Italy | Mexico

**Comment by ffdixon** [comment]
Implemented in BigBlueButton 1.1-beta.
