### ISSUE TITLE
Kicked user auto-reconnects

### ISSUE THREAD

**Issue by ffdixon** [bigbluebutton/bigbluebutton#2957]
Immediately after kicking a user, the client's auto-reconnect code will activate.  (We've done too good a job of reconnecting :-).

A kicked user should be logged out.

**Comment by ritzalam** [comment]
When the client reconnects, is it able to join the meeting again? I think there was code there that makes the auto-reconnect fail and not be able to join again.

**Comment by ritzalam** [comment]
Ok. There's no code to remove the user's authToken when kicked out.

Just need too remove the authToken from the RegisteredUsers in https://github.com/bigbluebutton/bigbluebutton/blob/master/akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/UsersApp.scala#L155

The client would still reconnect but would fail. We can do more where the client won't attempt to reconnect by telling it that the user was kicked but that takes changes on both server and client.

**Comment by ritzalam** [comment]
Wrong line. The user can't actually join again. But the client still tries to re-join after being kicked.

Here is where we remove the user from the RegisteredUsers so that the authToken will fail on reconnect.

https://github.com/bigbluebutton/bigbluebutton/blob/master/akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/UsersApp.scala#L245
