### ISSUE TITLE
The error message when trying to use WebRTC in Chrome without HTTPS is unclear

### ISSUE THREAD

**Issue by capilkey** [bigbluebutton/bigbluebutton#2966]
The error message presented to users when they try to join audio with WebRTC while on (I think) Chrome 47 or later is just a generic message about not being able to grab their microphone. The bridge code should be expanded to check for HTTPS when on Chrome 47+ before even attempting to grab the user's microphone and present the user with an error message that more accurately describes the issue. Something like "Your version of Chrome requires the page to be HTTPS for WebRTC to work. Would you like to fall back to Flash?"

**Comment by ffdixon** [comment]
This is a good suggest -- the first time I saw this message when testing Chrome 47 beta it took me a moment to figure out it was an error due to permissions.

On the other hand, the error message is really for the administrator of the BigBlueButton server.  The solution is to setup HTTPS/SSL on the BigBlueButton server as soon as possible (see [steps](http://docs.bigbluebutton.org/install/install.html#configuring-https-on-bigbluebutton)).

**Comment by ffdixon** [comment]
We added a warning message in BigBlueButton 2.0 that will prevent the user from sharing their microphone if (a) the client detects the user is on Chrome, (b) the client is not loaded via SSL, and (c) the user attempts to join via WebRTC audio.

![image](https://user-images.githubusercontent.com/290351/41502669-65e41e4a-718d-11e8-9a2c-abcacc568862.png)

Any BigBlueButton server running in production should be configured to use SSL.  See

  https://github.com/bigbluebutton/bbb-install

**Comment by ZockerBoysHD** [comment]
i too have echo-tst problems in chromee. every other browser works only chrome doesnt
the error i get in my f12 console in chrome
https://screens.egopvp.com/files/2022/02/02/7vl7q.png

**Comment by hostbbb** [comment]
you need 2.2.36 or 2.3 2.4 for this error to disappear.   What version of bbb are you using? google forums bigbluebutton-setup bet place for help.
