### ISSUE TITLE
Last slide not appearing on recording

### ISSUE THREAD

**Issue by ffdixon** [bigbluebutton/bigbluebutton#3021]
To reproduce,

Install the latest build of BigBlueButton 1.0-beta.  Create a recorded meeting, such as using

  http://demo.bigbluebutton.org/demo/demo10.jsp

Start recording and advance the slides, taking note of the last slide.  Exit the session by closing the browser tab.

The last slide will not be recorded.  Here's a test recording to demonstrate

  http://demo.bigbluebutton.org/playback/presentation/0.9.0/playback.html?meetingId=6e35e3b2778883f5db637d7a5dba0a427f692e91-1456085320469&t=6s

First reported in bigbluebutton-dev

  https://groups.google.com/d/msg/bigbluebutton-dev/9zwKmBN_Zio/QPzMhQTCEwAJ

**Comment by kepstin** [comment]
Update on investigation:

The recording processing scripts generated the `shapes.svg` file for this recording with the `<image>` tag for the slide having attributes `in="11.0"  out="0.0"`. Since the out time is before the in time, the slide is never shown.

In addition, the `<g>` tag with `id="canvas5"` is not output to the shapes.svg file at all.

The bug is almost certainly in the presentation format "publish" script, where the shapes.svg file is generated; the playback JavaScript code appears to be operating correctly.
