### ISSUE TITLE
Client Bandwidth Control Options

### ISSUE THREAD

**Issue by mkpelletier** [bigbluebutton/bigbluebutton#3024]
Greetings BBB Team,
This is not an issue as such, but more of an enhancement or suggestion.  At present the html5 version of BBB provides us with a brilliant option for users who wish to conserve data consumption, since webcam feeds do not go through the html5 client.  I do not know if this is by design or if the webcam is just not available in html5 yet.  If the latter is the case, I would suggest that once html5 does accommodate webcams, you allow the user some means of turning off webcam feeds in their view for the sake of low speed connections or mobile where the data is expensive or limited.  This may also be useful in the flash version.

**Comment by capilkey** [comment]
The lack of video in HTML5 is a technical limitation not a design decision. The webcams go through red5 right now and red5 can't act as a WebRTC endpoint. Currently the WebRTC video stream that we get back would actually have less fine grained control than the Flash client gives us because the WebRTC video mixes all of the streams together and red5 gives us individual streams.

Every webcam in the Flash client has a close button in the top right corner.

**Comment by ffdixon** [comment]
The HTML5 client in BigBlueButton 2.2-beta allows users to turn off video streams via Settings menu (upper right-hand corner) and choosing the Data Savings option.
