### ISSUE TITLE
bbb-check not checking WebRTC when server is setup with SSL

### ISSUE THREAD

**Issue by ffdixon** [bigbluebutton/bigbluebutton#3084]
To reproduce, open

  https://demo.bigbluebutton.org/check/

 and the WebRTC checks currently will not resolve as the server is configured to use HTTPS

![image](https://cloud.githubusercontent.com/assets/290351/14515341/364c80a6-01c7-11e6-8da3-e733eaa8d032.png)

Need to update bbb-conf check to work with a server setup with HTTPS links.

**Comment by ReimarBauer** [comment]
Hi Fred

seems you solved it on your server, what was the needed change ?

**Comment by ffdixon** [comment]
We haven't changed anything in demo and it still has issues with https://demo.bigbluebutton.org/check

![image](https://cloud.githubusercontent.com/assets/290351/14741649/7183a478-085d-11e6-9dcc-24a263b20de4.png)

**Comment by jsalatas** [comment]
I believe the problem is that FreeSwitch is using self-signed certificates. I have solved it in my own server by creating the certificates for FreeSwitrch using properly signed certificates. In my case I used LetsEncrypt CA (https://letsencrypt.org/) and merged the various certificates (private key, ca and chain) into one as required by FreeSwitch using the following commands 
cd /opt/freeswitch/certs
cp dtls-srtp.pem ~/dtls-srtp.pem.backup
cp wss.pem ~/wss.pem.backup
cat /etc/letsencrypt/live/XXXXXXXXXX/privkey.pem /etc/letsencrypt/live/XXXXXXXXXX/fullchain.pem > dtls-srtp.pem 
cat /etc/letsencrypt/live/XXXXXXXXXX/privkey.pem /etc/letsencrypt/live/XXXXXXXXXX/fullchain.pem > wss.pem 

Of course you need to replace XXXXXXXXXX with your domain name

After restarting bbb

bbb-conf --restart

it worked ok as you can see in screenshot 


![bbb](https://cloud.githubusercontent.com/assets/1066320/14933218/4f03ec2a-0e3c-11e6-89f9-9334a8b99d2f.png)

**Comment by ffdixon** [comment]
Fixed in BigBlueButton 1.1-beta -- we needed to update some JavaScript libraries in bbb-check to use the same libraries as in BigBlueButton client (see https://github.com/bigbluebutton/bigbluebutton/pull/3540)
