### ISSUE TITLE
API checksum error response is different between getDefaultConfigXML and the other methods

### ISSUE THREAD

**Issue by GhaziTriki** [bigbluebutton/bigbluebutton#3148]
When calling any API method with an invalid checksum, as example calling `getMeetings` using this URL http://test-install.blindsidenetworks.com/bigbluebutton/api/getMeetings?checksum=d23fef405937517be465ffccae12d5c1103a5e0 we get the following answer:

``` xml
<response>
    <returncode>FAILED</returncode>
    <messageKey>checksumError</messageKey>
    <message>You did not pass the checksum security check</message>
</response>
```

However when calling `getDefaultConfigXML` using this URL http://test-install.blindsidenetworks.com/bigbluebutton/api/getDefaultConfigXML?checksum=5a9fb2b8d056a63a7c735d30235e6c39397a160 we get

``` xml
<response>
    <returncode>FAILED</returncode>
    <errors>
        <error key='checksumError' message='You did not pass the checksum security check'/>
    </errors>
</response>
```

**Comment by ffdixon** [comment]
Good catch.  We can add in <returncode> and <message> to align it with the other API calls.

**Comment by GhaziTriki** [comment]
I think a full check of API methods needs to be done, I also found that ```join``` API have the same format as ```getDefaultConfigXML```

**Comment by jfederico** [comment]
I didn't see this before. On getDefaultConfigXML I don't know. I haven't work on that, but on Join requests there must have been changed when I changed the response to html by default. see #3130

I can check the Join, although all the changes I did before are no longer in master

**Comment by jfederico** [comment]
The bottom line of this problem is that the "backward compatibility code" for showing errors was executed before the one is used now (in the join at least), so what we need to fix really is the method that produces the response and get rid off for once the "backward compatibility" code we have had for a time.

In fact the new code was never executed because the if conditions of the "backward compatibility code" were executed before and they enclose a return

**Comment by niravpateljoin** [comment]
Hi 

instead of this url 

http://test-install.blindsidenetworks.com/bigbluebutton/api/getMeetings?checksum=d23fef405937517be465ffccae12d5c1103a5e0

You have to run 

http://test-install.blindsidenetworks.com/bigbluebutton/api/getMeetings?checksum=d23fef405937517be465ffccae12d5c1103a5e00

Definately you will get all meetings.
