### ISSUE TITLE
Sort order of UsersModule

### ISSUE THREAD

**Issue by emanuelpv** [bigbluebutton/bigbluebutton#3198]
Hi, all.
I'd like to show all audience on UsersModule in particular sort order hierarchy like: 

-Sponsor
-Project Manager
-Member of Project 01
-Member of Project 02
-Member of Project *

How can I do? Where to start?

Regard, Emanuel

**Comment by capilkey** [comment]
This isn't an issue with BBB and it would be more appropriate to post the question to our developer mailing list (https://groups.google.com/forum/?fromgroups=#!forum/bigbluebutton-dev) instead of here. 

To answer your question though, the existing sort function can be found here, https://github.com/bigbluebutton/bigbluebutton/blob/master/bigbluebutton-client/src/org/bigbluebutton/main/model/users/Conference.as#L83-L131
