### ISSUE TITLE
Playback of recording does not work on Puffin browser

### ISSUE THREAD

**Issue by ffdixon** [bigbluebutton/bigbluebutton#3329]
Playback of a BigBlueButton recording does not work on latest version of Puffin Browser version 5.1.0 (15481) UI revision (19).

**Comment by capilkey** [comment]
Isn't the Puffin browser for the Flash content specifically? Was it supposed to work with the recordings?

**Comment by jfederico** [comment]
On Firefox 47.0.1, (it works fine on Chrome)
- With a recording with no audio, no webcam, only presentation and chat  I need to reload the page in order to get it to work
- With a recording with no audio but an active webcam (plus the presentation and audio), it doesn't load at all
![image](https://cloud.githubusercontent.com/assets/578359/18064197/5227999a-6dfc-11e6-9889-87142587e82f.png)
