### ISSUE TITLE
Newline in LTI descriptiontext causes connection error

### ISSUE THREAD

**Issue by jimethn** [bigbluebutton/bigbluebutton#3335]
In Blackboard we have the LTI tool configured for BBB. If the description of the BBB link contains linefeeds (or paragraph breaks using the HTML "P" or "DIV" elements), the session fails to load and BBB gives the error "Connection could not be established."

**Comment by jfederico** [comment]
This is a bug not in the BigBlueButton LTI broker but in Blackboard itself. It is actually a very old and very well known bug. I don't have the reference now because I don't have access to behind.blackboard.com

But you can either try the alternative consumer written by Stephen Vickers http://projects.oscelot.org/gf/project/bb-basiclti/

Or, update blackboard. It seems that the latest doesn't have the error (as you can not even add a description to the links). Last time I checked out Bb was here https://www.coursesites.com/webapps/Bb-sites-course-creation-BBLEARN/pages/index.html
