### ISSUE TITLE
Using HTTPS in bigbluebutton LTI integration not working

### ISSUE THREAD

**Issue by ffdixon** [bigbluebutton/bigbluebutton#3361]
When using bbb-lti package with HTTP it works, but switching the BigBlueButton server to HTTPS is causing an issue with the integration.  

Reported in this thread

  https://groups.google.com/d/msg/bigbluebutton-setup/gCOgRHix6SA/aL5oH80WGgAJ

**Comment by jfederico** [comment]
Turns out that because this is a request served through a proxy, even though Nginx is sending the scheme to Tomcat 

`proxy_set_header   X-Forwarded-Proto $http_x_forwarded_proto;`

Tomcat is not passing it to the application, so the HttpServletRequest.isSecure() validation (added in December 2014 for supporting https) always returns false.

https://github.com/bigbluebutton/bigbluebutton/blob/master/bbb-lti/grails-app/controllers/org/bigbluebutton/ToolController.groovy#L59

So, the fix is as simple as adding a secure="true" to the tomcat connector in sever.xml.


    ```
<Connector port="8080" protocol="HTTP/1.1"
               connectionTimeout="20000"
               URIEncoding="UTF-8"
               redirectPort="8443" secure="true" />

```

See:
https://tomcat.apache.org/tomcat-7.0-doc/config/http.html

**Comment by jfederico** [comment]
This valve needs to be added to /etc/tomcat7/server.xml in packaging

`<Valve className="org.apache.catalina.valves.RemoteIpValve" remoteIpHeader="x-forwarded-for" proxiesHeader="x-forwarded-by" protocolHeader="x-forwarded-proto" />`

**Comment by b0bbybacc** [comment]
I am not seeing an instance where this works for me,

**Comment by jfederico** [comment]
@b0bbybacc did you got it to work?, did you try test-install? http://docs.bigbluebutton.org/install/lti.html

**Comment by rciville** [comment]
I was running into exactly this issue with https and LTI while configuring a new BBB server and external LMS , just as described here. I was googling for a solution and found this. The Tomcat tweak worked perfectly in five minutes. Is this issue closed or was this a work around with a better fix still in the works? Thank you. Richard
