### ISSUE TITLE
Upload Chinese txt document by UTF8/GBK

### ISSUE THREAD

**Issue by 13328108** [bigbluebutton/bigbluebutton#3480]
As windows default using chinese GBK encoding in txt document . When I upload this document to the meeting , I can see  messy code  on the whiteboard.

but when I save this document with UTF8 . Then  upload ,  I can see the  correct chinese fonts on the whiteboard.

So, can BBB  encoding all document to UTF8 in uploading automatic  ?

Many thanks!

**Comment by mikhailnov** [comment]
No, it cannot be done in default upstream BBB settings, because it is nearly impossible to heurestically detect non-UTF8 ecodings. You can try to set up the default the default encoding for non-UTF8 text documents in Libreoffice which converts them into PDF, or file a bug at http://bugs.documentfoundation.org if there is no such setting or it works incorrectly.

**Comment by ffdixon** [comment]
Merged into https://github.com/bigbluebutton/bigbluebutton/issues/3176
