### ISSUE TITLE
Faster desktop sharing by launching via JNLP file

### ISSUE THREAD

**Issue by ffdixon** [bigbluebutton/bigbluebutton#3520]
Currently, desktop sharing runs as an applet within the browser.  Recently, Chrome stopped allowing applets to run within the browser.

Convert the desktop sharing to an external Java application that can be loaded via a Java Network Launch Protocol File (JNLP).  This will make it compatible with Chrome and enable faster desktop sharing as the Java application will have more access to the CPU.

Other desirable features
   * Add to the ability to Pause/Resume the desktop sharing
   * Capture the mouse cursor

**Comment by ffdixon** [comment]
The feature is now in BigBlueButton 1.1-dev.  You can try it out on http://demo.bigbluebutton.org/

**Comment by kresteliov** [comment]
Hi
I'm sorry, but I do not speak English, I write using a translation from google.
I ran into the problem on version 1.1 when I started the translation of the desktop through Java (JNLP) in any browser.
The fact is that the server and clients do not have access to the Internet, in such a situation the launch of Java takes a very long time.
Due to the very long launch of Java, the screen demonstration stops, never having started.
How can I increase the time it takes to start Java?
Thank you in advance.
http://ipic.su/img/img7/fs/Screenshot_67.1505226221.jpg

**Comment by ffdixon** [comment]
Hi there, 

Instead of posting comments to a closed issue, can we get you to post to our bigbluebutton-setup mailing list (see https://bigbluebutton.org/support) and we'll help you there.

When you post, try accessing https://demo.bigbluebutton.org/ and let us know if you encounter the same issue.  

> Due to the very long launch of Java, the screen demonstration stops, never having started.

Java Webstart will cache the download ... if the first time it times out, can you try doing it a second time after and let us know if it successfully launches (there won't be any delay for downloading it).

Regards,... Fred

**Comment by kresteliov** [comment]
Спасибо за Ваш ответ.
Проблема возникает именно с Java, когда клиент Java не имеет доступа к сети интернет проверка всегда длится очень долго.
Если использовать https://demo.bigbluebutton.org/ такой проблемы не происходит, т.к. клиент имеет доступ в интенет и запуск Java  происходит очень быстро.
Заранее спасибо за понимание.

**Comment by kresteliov** [comment]
Thanks for your reply.
The problem occurs precisely with Java, when the Java client does not have access to the Internet, the check always takes a very long time.
If you use https://demo.bigbluebutton.org/ such a problem does not occur, because the client has access to the intet and the launch of Java is very fast.
Thank you in advance for your understanding.

**Comment by kresteliov** [comment]
Hi.
Solved the problem of long Java launch if the client does not have access to the Internet in the following way:
in the settings "Advanced -> Perform signed code certificate only -> Do not check (not recommended)", after that it started running instantly.
For the future, I would like to be able to change the waiting time for launching a Java if Oracle changes its policy and forbids disabling certificate checking for offline
