### ISSUE TITLE
Fix icon centering in the Actions Bar

### ISSUE THREAD

**Issue by OZhurbenko** [bigbluebutton/bigbluebutton#3576]
All the icons in the actions bar are slightly moved down in both Chrome and Firefox.

![centered_icons_bug_1](https://cloud.githubusercontent.com/assets/9299997/22084198/1a2b3464-dd9d-11e6-87c3-186c76c7c00d.jpg) ![centered_icons_bug_2](https://cloud.githubusercontent.com/assets/9299997/22084249/5eaa4c4c-dd9d-11e6-963a-263e19150c1b.jpg) ![centered_icons_bug_3](https://cloud.githubusercontent.com/assets/9299997/22084255/637c16e2-dd9d-11e6-9181-e02fec742522.jpg)

Steps to reproduce:
- "Join Audio" and "Status" buttons are visible right after logging into the html5 client.
- "Actions" button appears when you make yourself a presenter.
- "Mute" button appears when you join the audio.

**Comment by antobinary** [comment]
@tylercopeland - Is this one on your end? - it seems the icon itself is not centered on its square

**Comment by tylercopeland** [comment]
@OZhurbenko @antobinary I believe this is caused by the <span> tag around the icon. 

To fix this, change the line-height found in "._imports_ui_components_button__styles__button" from 1.5 to 1. 

You'll also need to adjust the vertical padding in "._imports_ui_components_button__styles__lg" from 0.5rem 1.25rem to 0.6rem 1.25rem.

Below is a screenshot of the raise hand button with the adjusted styles. 

<img width="211" alt="screen shot 2017-11-30 at 9 39 14 am" src="https://user-images.githubusercontent.com/1273169/33436217-76e5c774-d5b2-11e7-94a7-1f26b5f514f1.png">

**Comment by antobinary** [comment]
![screenshot from 2017-11-30 10-39-45](https://user-images.githubusercontent.com/6312397/33439343-36bfd96a-d5bb-11e7-82dd-b1bdc83e9e22.png)
To me it seems the issue is within the icon item itself - Is there a way to center the font onto it's square?

**Comment by tylercopeland** [comment]
@antobinary for this icon, I purposely left aligned it to limit the visual change when the "X" is introduced. Actually, this icon will be removed entirely and replaced with the phone icon shortly to match the Flash 2.0 client. There is an open Github Issue to create the phone icon, I should be able to get to it by the end of this week.

**Comment by antobinary** [comment]
Resolved
