### ISSUE TITLE
[Development] Setting up BigBlueButton

### ISSUE THREAD

**Issue by rajikaimal** [bigbluebutton/bigbluebutton#3673]
I'm following the instructions on this [readme](https://github.com/bigbluebutton/bigbluebutton/blob/master/DEVELOPMENT.md). 
When executing the following command
```
ant -f frameworks/build.xml thirdparty-downloads
```

I'm getting the following error.

`BUILD FAILED
/home/rajika/dev/tools/apache-flex-sdk-4.13.0-bin/frameworks/build.xml:1076: The following error occurred while executing this line:
/home/rajika/dev/tools/apache-flex-sdk-4.13.0-bin/frameworks/downloads.xml:183: Can't get http://swfobject.googlecode.com/files/swfobject_2_2.zip to /home/rajika/dev/tools/apache-flex-sdk-4.13.0-bin/in/swfobject_2_2.zip
` 
According to the error, this resource is not available.
Any suggestions ?

Thank you.

**Comment by capilkey** [comment]
Please post questions like this to our developer mailing list (https://groups.google.com/forum/?fromgroups=#!forum/bigbluebutton-dev) instead of Github.

To answer you question though there's a step right above that line in the instructions that tells you how to download swfobject manually to get around the issue of the dependency being moved. make sure you're using the most up to date instructions here, http://docs.bigbluebutton.org/install/setup.html
