### ISSUE TITLE
Close private chat functionality in the html5 client

### ISSUE THREAD

**Issue by antobinary** [bigbluebutton/bigbluebutton#3681]
Desired behaviour:
When closing private chat, reopening it will display the old private correspondence between the two users.

Implementation details:
On the client side:
Keep track of private chat conversations in a Session Storage object. When the user closes a private chat conversation, the object should reflect the change. Only display private chat conversations that have not been explicitly closed. The Session Storage object can be as minimal as list of userID's of correspondents for whom private chat was closed.
Please test the cases of client refresh and client reconnect. Also make sure that the conversation reappears if a new message is sent from the other side
On the server side:
No changes.

Note: This implementation is slightly different than what we have in the Flash client. There old private correspondence is forever lost upon closing of the respective chat tab. Reopening it only displays chat messages occurred after the last closing of the tab

**Comment by oswaldoacauan** [comment]
My 2 cents:

When the user close the chat, we should store (session storage) the `userID` and the `from_time` from the last message of that chat.

In the chat list, we should filter private chats based on the `userID` and `from_time` stored on the session.

This way if the user receives a new private message it will popup in the chat list even if that userID is in the closed list, since the message will have a `from_time` greater than the one stored on the session.
And we can even filter messages in the chat to mimic the Flash behavior if we want.

We can go even further and pass this data when subscribing to the chat collection and filter those messages on the publication.
