### ISSUE TITLE
1.1Beta.  SurfacePro recording play button does not work.

### ISSUE THREAD

**Issue by hostbbb** [bigbluebutton/bigbluebutton#3694]
Surface Pro with chrome browser.

On 1.1beta.    The PLAY button will not start a recording.  Need to use slider.

Don't have device to debug.

**Comment by ffdixon** [comment]
We tested in an [Acer Icona W4-820](https://www.amazon.com/Acer-Iconia-W4-820-2894-8-Inch-Windows/dp/B00G1YJ5B4) tablet and the playback worked for Chrome.

We're looking to test it in a Surface Pro.

**Comment by pascalstjean** [comment]
![2017-03-21](https://cloud.githubusercontent.com/assets/2713040/24171824/5b41cc7a-0e5c-11e7-97a7-73d2556be256.png)

Chrome on Surface Pro 4

**Comment by capilkey** [comment]
With help from Gil Yoder on the bbb-dev Google Group it turns out this issue isn't specific to Surface Pro, but rather any environment that has a mouse and is identified as touch. 

Acorn Media Player which we use for our controls in the recordings has code to detect whether or not it's a touch environment and then using that information it binds to either "click" or "touchstart". It does this for performance reasons because if you bind to "click" on a tablet there can be up to a 300ms delay before actually firing the click event. The problem is that there now exists environments where you can have both a mouse and a touch device together and in those cases if you bind to just the "touchstart" event it will never be fired if the user clicks with a mouse.

Most of the workarounds involve binding to both click and touchstart and then somehow stopping the second follow up event from being processed. The following stackoverflow answer looks to be the best solution in my opinion http://stackoverflow.com/a/36452427. Another possible solution is to call preventDefault() on the event.

The relevant lines in Acorn Media Player are:

https://github.com/bigbluebutton/bigbluebutton/blob/master/record-and-playback/presentation/playback/presentation/0.9.0/acornmediaplayer/jquery.acornmediaplayer.js#L50

and

https://github.com/bigbluebutton/bigbluebutton/blob/master/record-and-playback/presentation/playback/presentation/0.9.0/acornmediaplayer/jquery.acornmediaplayer.js#L898-L899
