### ISSUE TITLE
Change recordings to archive, process, and publish in parallel

### ISSUE THREAD

**Issue by ffdixon** [bigbluebutton/bigbluebutton#3744]
Currently, the recording processing archives all recordings first, then processes all archived recordings, then publishes all recordings.

The problem is the publishing of very short recordings could be delayed by the publishing of a very large recording that.

Modify the record and playback scripts so the archive, process, and publish steps can occur in parallel.  This should reduce the time from a meeting finish to a recording publish.

**Comment by ffdixon** [comment]
We've broken down the recording process into four components

  * bbb-rap-archive-worker.service 
  * bbb-rap-sanity-worker.service 
  * bbb-rap-process-worker.service 
  * bbb-rap-publish-worker.service

As a recording works through the four processes, the command `bbb-record --watch` will now show the status each state.

Here what it looks like when the first two steps are finished

~~~

Internal MeetingID                                               Time                APVD APVDE RAS Slides Processed            Published           External MeetingID
------------------------------------------------------  ---------------------------- ---- ----- --- ------ -------------------- ------------------  -------------------
6e35e3b2778883f5db637d7a5dba0a427f692e91-1490721375493  Tue Mar 28 17:16:15 UTC 2017 XX   XX  X   X      5                                          English 101

--
NEXT                         LEFT    LAST                         PASSED  UNIT                  ACTIVATES
Tue 2017-03-28 17:21:20 UTC  6s left Tue 2017-03-28 17:20:50 UTC  23s ago bbb-record-core.timer bbb-record-core.target

1 timers listed.
--
● bbb-rap-archive-worker.service - BigBlueButton recording and playback archive worker
   Loaded: loaded (/usr/lib/systemd/system/bbb-rap-archive-worker.service; static; vendor preset: enabled)
   Active: inactive (dead) since Tue 2017-03-28 17:20:19 UTC; 54s ago
Condition: start condition failed at Tue 2017-03-28 17:20:50 UTC; 23s ago
           ConditionPathExistsGlob=/var/bigbluebutton/recording/status/recorded/*.done was not met
  Process: 10590 ExecStart=/usr/local/bigbluebutton/core/scripts/rap-archive-worker.rb (code=exited, status=0/SUCCESS)
 Main PID: 10590 (code=exited, status=0/SUCCESS)

Mar 28 17:20:18 xxx-ubuntu-8gb-nyc3-01 systemd[1]: Started BigBlueButton recording and playback archive worker.

● bbb-rap-sanity-worker.service - BigBlueButton recording and playback sanity check worker
   Loaded: loaded (/usr/lib/systemd/system/bbb-rap-sanity-worker.service; static; vendor preset: enabled)
   Active: inactive (dead) since Tue 2017-03-28 17:20:51 UTC; 22s ago
  Process: 11606 ExecStart=/usr/local/bigbluebutton/core/scripts/rap-sanity-worker.rb (code=exited, status=0/SUCCESS)
 Main PID: 11606 (code=exited, status=0/SUCCESS)

Mar 28 17:20:50 xxx-ubuntu-8gb-nyc3-01 systemd[1]: Started BigBlueButton recording and playback sanity check worker.

● bbb-rap-process-worker.service - BigBlueButton recording and playback process worker
   Loaded: loaded (/usr/lib/systemd/system/bbb-rap-process-worker.service; static; vendor preset: enabled)
   Active: inactive (dead)
Condition: start condition failed at Tue 2017-03-28 17:20:50 UTC; 23s ago
           ConditionPathExistsGlob=/var/bigbluebutton/recording/status/sanity/*.done was not met

Mar 28 17:13:50 xxx-ubuntu-8gb-nyc3-01 systemd[1]: Stopped BigBlueButton recording and playback process worker.

● bbb-rap-publish-worker.service - BigBlueButton recording and playback publish worker
   Loaded: loaded (/usr/lib/systemd/system/bbb-rap-publish-worker.service; static; vendor preset: enabled)
   Active: inactive (dead)
Condition: start condition failed at Tue 2017-03-28 17:20:50 UTC; 23s ago
           ConditionPathExistsGlob=/var/bigbluebutton/recording/status/processed/*.done was not met

Mar 28 17:13:50 xxx-ubuntu-8gb-nyc3-01 systemd[1]: Stopped BigBlueButton recording and playback publish worker.
--
~~~

And when all four steps have been completed (they all show `SUCCESS`)

~~~
Every 2.0s: bbb-record --list-recent                                                                                                                                      Tue Mar 28 17:22:11 2017

Internal MeetingID                                               Time                APVD APVDE RAS Slides Processed            Published           External MeetingID
------------------------------------------------------  ---------------------------- ---- ----- --- ------ -------------------- ------------------  -------------------
6e35e3b2778883f5db637d7a5dba0a427f692e91-1490721375493  Tue Mar 28 17:16:15 UTC 2017 XX   XX  X          5                      presentation        English 101

--
NEXT                         LEFT     LAST                         PASSED  UNIT                  ACTIVATES
Tue 2017-03-28 17:22:22 UTC  10s left Tue 2017-03-28 17:21:52 UTC  19s ago bbb-record-core.timer bbb-record-core.target

1 timers listed.
--
● bbb-rap-archive-worker.service - BigBlueButton recording and playback archive worker
   Loaded: loaded (/usr/lib/systemd/system/bbb-rap-archive-worker.service; static; vendor preset: enabled)
   Active: inactive (dead) since Tue 2017-03-28 17:20:19 UTC; 1min 51s ago
Condition: start condition failed at Tue 2017-03-28 17:21:52 UTC; 19s ago
           ConditionPathExistsGlob=/var/bigbluebutton/recording/status/recorded/*.done was not met
  Process: 10590 ExecStart=/usr/local/bigbluebutton/core/scripts/rap-archive-worker.rb (code=exited, status=0/SUCCESS)
 Main PID: 10590 (code=exited, status=0/SUCCESS)

Mar 28 17:20:18 xxx-ubuntu-8gb-nyc3-01 systemd[1]: Started BigBlueButton recording and playback archive worker.

● bbb-rap-sanity-worker.service - BigBlueButton recording and playback sanity check worker
   Loaded: loaded (/usr/lib/systemd/system/bbb-rap-sanity-worker.service; static; vendor preset: enabled)
   Active: inactive (dead) since Tue 2017-03-28 17:20:51 UTC; 1min 20s ago
Condition: start condition failed at Tue 2017-03-28 17:21:52 UTC; 19s ago
           ConditionPathExistsGlob=/var/bigbluebutton/recording/status/archived/*.done was not met
  Process: 11606 ExecStart=/usr/local/bigbluebutton/core/scripts/rap-sanity-worker.rb (code=exited, status=0/SUCCESS)
 Main PID: 11606 (code=exited, status=0/SUCCESS)

Mar 28 17:20:50 xxx-ubuntu-8gb-nyc3-01 systemd[1]: Started BigBlueButton recording and playback sanity check worker.

● bbb-rap-process-worker.service - BigBlueButton recording and playback process worker
   Loaded: loaded (/usr/lib/systemd/system/bbb-rap-process-worker.service; static; vendor preset: enabled)
   Active: inactive (dead) since Tue 2017-03-28 17:21:41 UTC; 29s ago
Condition: start condition failed at Tue 2017-03-28 17:21:52 UTC; 19s ago
           ConditionPathExistsGlob=/var/bigbluebutton/recording/status/sanity/*.done was not met
  Process: 12622 ExecStart=/usr/local/bigbluebutton/core/scripts/rap-process-worker.rb (code=exited, status=0/SUCCESS)
 Main PID: 12622 (code=exited, status=0/SUCCESS)

Mar 28 17:21:21 xxx-ubuntu-8gb-nyc3-01 systemd[1]: Started BigBlueButton recording and playback process worker.

● bbb-rap-publish-worker.service - BigBlueButton recording and playback publish worker
   Loaded: loaded (/usr/lib/systemd/system/bbb-rap-publish-worker.service; static; vendor preset: enabled)
   Active: inactive (dead) since Tue 2017-03-28 17:21:52 UTC; 18s ago
  Process: 13662 ExecStart=/usr/local/bigbluebutton/core/scripts/rap-publish-worker.rb (code=exited, status=0/SUCCESS)
 Main PID: 13662 (code=exited, status=0/SUCCESS)

Mar 28 17:21:52 xxx-ubuntu-8gb-nyc3-01 systemd[1]: Started BigBlueButton recording and playback publish worker.
--
~~~

**Comment by mori5ive** [comment]
hi @ffdixon , in my case 4 worker has success but no access to recording file from API get recordings.
Internal MeetingID                                               Time                APVD APVDE RAS Slides Processed            Published           External MeetingID
------------------------------------------------------  ---------------------------- ---- ----- --- ------ -------------------- ------------------  -------------------
cf9fbc6061ef22768ecc89ce5b9a75d3d444d67a-1598343506881  Tue Aug 25 12:48:26 +0430 2020  X    XX X         40                                          lkFKEdR3yenHM4qmy7maVeLl
01acfd37e69d91a37f9eeac5e6bd4b5aebc23384-1598342179803  Tue Aug 25 12:26:19 +0430 2020  X    XX X         40                                          TD6d0fLSvmkJzBd0VCjarXGS
e8fe8a92c9ba191d54b075fe2b8965b319a82e38-1598340060784  Tue Aug 25 11:51:00 +0430 2020  X    XX X         40                                          7tPaYOhXHqOteRPScHYCdH35
fb77116bfca14423fb6c98dc4747edf7f337b185-1598339739074  Tue Aug 25 11:45:39 +0430 2020  X    XX X         40                                          2htihSngdUystxToqhe6fsRn
eecc95361601e85228ee4c02772af4302d11ffd5-1598339690957  Tue Aug 25 11:44:50 +0430 2020  X    XX X         40                                          aWCxSjhBBf76vce8EkrCc4TV
3b0053199c0666bd132baac7e7b4d2a8b0de1b8d-1598339655321  Tue Aug 25 11:44:15 +0430 2020  X    XX X         40                                          01Ylq54obvISUbLWsViFbeuB
4f9e4ff054a453031a21aca83566b8842042ccd1-1598339327142  Tue Aug 25 11:38:47 +0430 2020  X    XX X         40                                          oMtzYrOBwDDiiWnjZfWCrLkb
30a176e9ad63ddb3a17390078da20bed07772519-1598339286809  Tue Aug 25 11:38:06 +0430 2020  X    XX X         40                                          5LAiAPj7yWBFWGCgosADwznZ
ea935068551630f300f30ded933ac0094d5bf567-1598339283131  Tue Aug 25 11:38:03 +0430 2020  X    XX X         40                                          ZYmUAomAojkqx2ftzaliLwdb
9e996a09be4a4e76dc2f84fa8ecc563405a189b8-1598339247641  Tue Aug 25 11:37:27 +0430 2020  X    XX X         40                                          kSNDKRcuywUYQzhwSXoJIWxY
0405a8596eadb306a3c385d6fa2e3d1af5ecba45-1598339246968  Tue Aug 25 11:37:26 +0430 2020  X    XX X         40                                          xYpwQjPw0amE9ve2dqcy39El
a6e77b9882143243e741f71e6bb9eeff197c3fd3-1598339245440  Tue Aug 25 11:37:25 +0430 2020  X    XX X         40                                          QJkiYTwJX9fpJTkSmo91Fke1

**Comment by SmartgenTeam** [comment]
root@ip-172-31-16-114:/var/bigbluebutton/recording# bbb-record --watch

Every 2.0s: bbb-record --list-recent                                                                                                                                    Wed Sep  9 02:39:10 2020

Internal MeetingID                                               Time                APVD APVDE RAS Slides Processed            Published           External MeetingID
------------------------------------------------------  ---------------------------- ---- ----- --- ------ -------------------- ------------------  -------------------
643509d56bcba75fa74b7fe2817bdb6a963d8d8f-1599596971678  Tue Sep 8 20:29:31 UTC 2020   X   XXX X          0                      presentation        70fe26f5-e36a-4ac9-8922-d0684ad15ff5
be38eec8f7dc1bc902ac19527759c135f4daad70-1599591917292  Tue Sep 8 19:05:17 UTC 2020   X   XXX X          0                                          f4wa480ohitpqxjhtwfteprmilb8qzt5dpfb9o6n
e79edf2a918a5977e8e268f2a080676a20f2cb4e-1599591696682  Tue Sep 8 19:01:36 UTC 2020   X                  0
be38eec8f7dc1bc902ac19527759c135f4daad70-1599591591273  Tue Sep 8 18:59:51 UTC 2020   X   XXX X          0                                          f4wa480ohitpqxjhtwfteprmilb8qzt5dpfb9o6n
c7365abb731c05549b4b340a5dafacee6c17435e-1599590530576  Tue Sep 8 18:42:10 UTC 2020   X    XX X          0                                          8f5d240f-6418-434d-b30b-92b7d0c3dd1c
be38eec8f7dc1bc902ac19527759c135f4daad70-1599590386791  Tue Sep 8 18:39:46 UTC 2020   X                  0
77f3241f903ef8bf16de1cd5498b42f4058f5504-1599589179725  Tue Sep 8 18:19:39 UTC 2020   X   XXXXX          0                                          c0c8c7e5-927e-46c6-850d-015bccc3adfd
1d002934220237015dec418c984dc17f1d36c670-1599589132819  Tue Sep 8 18:18:52 UTC 2020   X   XXX X          0                                          71e81cd0-30ec-4822-9a9a-c9b79b67b80f
23cffb55f6ee0e4da18acb3d7c850b9378fa6b1d-1599587951868  Tue Sep 8 17:59:11 UTC 2020   X   XXX X         12                      presentation        d82dbd67-d309-4fd8-9d3a-49005fdbb503
caf6653ec868a2e749bf079a3bea54e1de1aeb09-1599586368232  Tue Sep 8 17:32:48 UTC 2020   X    XX X         12                                          6b21ac8c-d35a-482b-8fb6-333b9f75b3ee
21a01135655a4eeb1620ec189f0a2165ab10e1b1-1599585766957  Tue Sep 8 17:22:46 UTC 2020   X   XXX X         12                      presentation        ewn8ibhmz6ebyhyorp0cjxihujccgqq5d5bw1bao
be38eec8f7dc1bc902ac19527759c135f4daad70-1599585736029  Tue Sep 8 17:22:16 UTC 2020   X   XXX X         12                                          f4wa480ohitpqxjhtwfteprmilb8qzt5dpfb9o6n

--
NEXT                         LEFT     LAST                         PASSED UNIT                  ACTIVATES
Wed 2020-09-09 02:39:34 UTC  23s left Wed 2020-09-09 02:39:04 UTC  6s ago bbb-record-core.timer bbb-record-core.target

1 timers listed.
--
    bbb-rap-archive-worker.service - BigBlueButton recording and playback archive worker
   Loaded: loaded (/usr/lib/systemd/system/bbb-rap-archive-worker.service; static; vendor preset: enabled)
   Active: inactive (dead) since Tue 2020-09-08 20:34:09 UTC; 6h ago
Condition: start condition failed at Wed 2020-09-09 02:39:04 UTC; 6s ago
           ConditionPathExistsGlob=/var/bigbluebutton/recording/status/recorded/*.done was not met
  Process: 23107 ExecStart=/usr/local/bigbluebutton/core/scripts/rap-archive-worker.rb (code=exited, status=0/SUCCESS)
 Main PID: 23107 (code=exited, status=0/SUCCESS)

Sep 08 20:34:08 ip-172-31-16-114 systemd[1]: Started BigBlueButton recording and playback archive worker.

There are recordings in raw folder but not publishing

**Comment by matiasilva** [comment]
Please don't revive an old issue. If you need help, follow the instructions here: https://docs.bigbluebutton.org/2.2/getting-help.html

**Comment by Facsete** [comment]
Good morning Fred Dixon. My name is Ricardo and I work at a college in Brazil. We are using the Big Blue Button Tool and on the date of 20/09/2020 we had to re-install it for presenting some errors. After resetting the tool, we return the bakup files from the / var / bigbluebutton folder and the tool stopped showing the recordings made. Could you please help us correct?

Following the bbb error troubleshooting theme on their page, I used the command bbb-record --list is the same one returned the error: Warning: Journal has been rotated since unit was started. Log output is incomplete or unavailable.


● bbb-rap-publish-worker.service - BigBlueButton recording and playback publish worker
   Loaded: loaded (/usr/lib/systemd/system/bbb-rap-publish-worker.service; static; vendor preset: enabled)
   Active: inactive (dead) since Mon 2020-09-28 12:17:22 UTC; 21s ago
  Process: 4101 ExecStart=/usr/local/bigbluebutton/core/scripts/rap-publish-worker.rb (code=exited, status=0/SUCCESS)
Main PID: 4101 (code=exited, status=0/SUCCESS)

/usr/local/bigbluebutton/core/scripts/rap-publish-worker.rb
/usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:10: warning: constant Gem::ConfigMap is deprecated
/usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:10: warning: constant Gem::ConfigMap is deprecated
/usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:29: warning: constant Gem::ConfigMap is deprecated
/usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:30: warning: constant Gem::ConfigMap is deprecated
/usr/local/lib/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:92:in `require': cannot load such file -- ../lib/recordandplayback (LoadError)
        from /usr/local/lib/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:92:in `require'
        from /usr/local/bigbluebutton/core/scripts/rap-publish-worker.rb:21:in `<main>'

**Comment by Facsete** [comment]
root@webclassfacsete:~# gem -v
/usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:10: warning: con                              stant Gem::ConfigMap is deprecated
/usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:10: warning: con                              stant Gem::ConfigMap is deprecated
/usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:29: warning: con                              stant Gem::ConfigMap is deprecated
/usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:30: warning: con                              stant Gem::ConfigMap is deprecated
/usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:10: warning: con                              stant Gem::ConfigMap is deprecated
/usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:10: warning: con                              stant Gem::ConfigMap is deprecated
/usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:29: warning: con                              stant Gem::ConfigMap is deprecated
/usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:30: warning: con                              stant Gem::ConfigMap is deprecated
3.1.4

**Comment by Facsete** [comment]
root@webclassfacsete:~# gem list
/usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:10: warning: constant Gem::ConfigMap is deprecated
/usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:10: warning: constant Gem::ConfigMap is deprecated
/usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:29: warning: constant Gem::ConfigMap is deprecated
/usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:30: warning: constant Gem::ConfigMap is deprecated
/usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:10: warning: constant Gem::ConfigMap is deprecated
/usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:10: warning: constant Gem::ConfigMap is deprecated
/usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:29: warning: constant Gem::ConfigMap is deprecated
/usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:30: warning: constant Gem::ConfigMap is deprecated

*** LOCAL GEMS ***

/usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:10: warning: constant Gem::ConfigMap is deprecated
/usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:10: warning: constant Gem::ConfigMap is deprecated
absolute_time (1.0.0)
builder (3.2.4, 3.2.3)
bundler (2.1.4)
crass (1.0.5)
did_you_mean (1.0.0)
fastimage (2.1.5)
ffi (1.11.1)
fnv (0.2.0)
java_properties (0.0.4)
journald-logger (2.0.4)
journald-native (1.0.11)
jwt (2.2.1)
locale (2.1.2)
loofah (2.3.1)
mini_portile2 (2.4.0)
minitest (5.8.4)
net-telnet (0.1.1)
nokogiri (1.10.8)
open4 (1.3.4)
power_assert (0.2.7)
rake (10.5.0)
rb-inotify (0.10.0)
redis (4.1.2)
rubygems-update (3.1.4)
rubyzip (1.3.0)
test-unit (3.1.7)
trollop (2.1.3)
