### ISSUE TITLE
Zoom in/out in recordings close but not exact

### ISSUE THREAD

**Issue by ffdixon** [bigbluebutton/bigbluebutton#3774]
The playback of zoom in/out could be improved to use more area of the playback. 

Here's how it looks live

![image](https://cloud.githubusercontent.com/assets/290351/24581128/1399e164-16db-11e7-9803-f0e01fa29ebe.png)

Here's how it looks in the recording

![image](https://cloud.githubusercontent.com/assets/290351/24581125/03664102-16db-11e7-9226-a6857a4f5d71.png)

(Notice how it's showing more than the original view in the recording.

Here is the test recording

  https://demo.bigbluebutton.org/playback/presentation/0.9.0/playback.html?meetingId=9604e3f2a3ef11efa9ff346c5e173edbc43aa692-1491068914593

Attached is the test document.
[Test_document_PDF.pdf](https://github.com/bigbluebutton/bigbluebutton/files/887859/Test_document_PDF.pdf)

Reported in

  https://groups.google.com/d/msg/bigbluebutton-dev/jcQ8P-Svs8E/5DgWHVEzAAAJ

**Comment by capilkey** [comment]
The difference in the two images is aspect ratio, it's nothing to do with zoom levels. I made a better recording where I drew the boundaries as they were in the client. https://demo.bigbluebutton.org/playback/presentation/0.9.0/playback.html?meetingId=6e35e3b2778883f5db637d7a5dba0a427f692e91-1491086362404

At 1 min in I switch the presentation from fit-to-page (default) to fit-to-width and that's when the desync starts. You can clearly see it when you compare where the recording puts my mouse to where the line actually gets drawn because the two use different relative positions to place themselves.

The problem would be solved by adding code to handle fit-to-width to the recordings.

**Comment by pedrobmarin** [comment]
@ffdixon is this still an issue?

**Comment by kepstin** [comment]
As best I can tell, this was a problem with the fit-to-width code in the flash client presentation area passing the wrong region in the events. I think it's obsolete now that we've switched to HTML5 client.

If we still have fit-to-width issues causing the wrong part of the slide to be shown, they should be opened as new issues - against the html5 client, not the recording system.
