### ISSUE TITLE
On recording the text fields are sometimes not cleared

### ISSUE THREAD

**Issue by ffdixon** [bigbluebutton/bigbluebutton#3827]
In the presentation recording format, the text fields are not always cleared when the presentation moves to a new page.  

Here's a video showing how the the string "tTestE" is not cleared from the previous page (see 0:33)

  https://demo.bigbluebutton.org/playback/presentation/0.9.0/playback.html?meetingId=b6ccb589cb5450b591f0523ff4d5ed51253e68e4-1492465803243

**Comment by capilkey** [comment]
My guess is that you aren't closing the text input before switching pages. I think the order of events is TextEdited -> ChangePage -> TextPublished and the recording scripts are assuming that the TextPublished event is for the new page instead of the original one. We had a bug like this in the Flash client where the text would spill over because we weren't checking the whiteboardId when receiving an annotation.

**Comment by ffdixon** [comment]
Hi Chad,

I think you are right -- I did a quick test when I added some text annotations, and on the last text annotation I left it in edit mode and moved to the next slide.  The annotation appeared on the next slide.

https://demo.bigbluebutton.org/playback/presentation/0.9.0/playback.html?meetingId=b6ccb589cb5450b591f0523ff4d5ed51253e68e4-1492508050457

What do you think is the best way to solve this?

**Comment by capilkey** [comment]
I've never looked into how the processing scripts handle the annotations, but the only way to really handle it fully is to check the whiteboardId for the event against the current whiteboardId.

**Comment by kepstin** [comment]
This is fixed in #3853
