### ISSUE TITLE
Font size in playback

### ISSUE THREAD

**Issue by pedrobmarin** [bigbluebutton/bigbluebutton#3856]
We got a bug report on Mconf about an issue involving a mismatch in font sizes from flash client to playback. Flash has a fixed size for fonts and zooming in and out make font sizes look different as you guys probably already know.
The problem was that in playback we weren't using the normalized font size to process it's size according to the view size. It looked something like this in the client:
![screenshot from 2017-04-27 11-18-50](https://cloud.githubusercontent.com/assets/1778398/25488087/7dbe666c-2b3c-11e7-8a88-01e419356035.png)
And like this in playback:
![screenshot from 2017-04-27 11-26-55](https://cloud.githubusercontent.com/assets/1778398/25488093/81c5bd46-2b3c-11e7-8362-df616ef1add3.png)

If you guys can confirm it we can send a pull request of what we have done to fix it.

**Comment by kepstin** [comment]
Yes, this is an issue that we've known about for a while. I'm curious how you have fixed it - I think it would require some changes to the flash client?

Even in the Live meeting in the Flash client, I don't think the font sizes match between different people with the same meeting open right now, since it depends on screen size and zoom levels…

**Comment by pedrobmarin** [comment]
https://github.com/pedrobmarin/bigbluebutton/commit/660574fcfabdb0bf4cf657c12a87d1129b038402

**Comment by kepstin** [comment]
Ah, yes, that makes sense. Please open a pull request and tag me as a reviewer! I'm going to do some extra testing, but this is a simple enough fix that we can probably get this into 1.1.

**Comment by kepstin** [comment]
Fixed in #3859
