### ISSUE TITLE
[HTML5] Poll doesn't work if there is no presentation

### ISSUE THREAD

**Issue by JaeeunCho** [bigbluebutton/bigbluebutton#4005]
#1.
![11](https://user-images.githubusercontent.com/19368114/26947449-bd1ae9a8-4c60-11e7-815d-5a0a5043ae94.jpg)

2.
![12](https://user-images.githubusercontent.com/19368114/26947461-cbb350ae-4c60-11e7-9993-8543bf3cad6e.jpg)

3.
![13](https://user-images.githubusercontent.com/19368114/26947479-e1cbf224-4c60-11e7-8e21-213cd00f3f97.jpg)

1. remove uploaded presentation file through trash box icon and click close button.
2. create poll
3. nothing is displayed on HTML5-client and no console error.
4. no actions button

**Comment by OZhurbenko** [comment]
Polling buttons are a part of a PresentationContainer.

I suspect that it's caused by [This]https://github.com/bigbluebutton/bigbluebutton/blob/master/bigbluebutton-html5/imports/ui/components/media/container.jsx#L33-L37) part or the one above in the constructor.
No presentation means that it switches to a default content, and Polling buttons are not a part it.

There are 2 issues here:
1. Deskshare and Video currently replace the Presentation. If it stays this way, then PollingContainer should be moved up to Media, otherwise it's not gonna work with Deskshare and Video.
2. DefaultContent is not displayed now for some reason. But even if it was - it still keeps Button examples from a year ago. We need to either implement something to show users instead of the black screen ( drag&drop presentation upload for presenters ? ) or just remove it completely.

**Comment by antobinary** [comment]
Merge into #6710
