### ISSUE TITLE
Apply current layout is setting the layout in different meetings

### ISSUE THREAD

**Issue by pedrobmarin** [bigbluebutton/bigbluebutton#4158]
Joined dev2 in one meeting, changed the layout and applied to all users.
Joined another meeting in dev2, the layout I got was the one I applied at the first one

**Comment by capilkey** [comment]
Good catch. I'm pretty sure it's because the Layouts class is set with everything as static (https://github.com/bigbluebutton/bigbluebutton/blob/bbb-2x-mconf/akka-bbb-apps/src/main/scala/org/bigbluebutton/core/models/Layouts.scala). See the model usage in one of the message handlers https://github.com/bigbluebutton/bigbluebutton/blob/bbb-2x-mconf/akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/layout/GetCurrentLayoutReqMsgHdlr.scala#L23.

The functions and data need to be moved to the class from the object and then create an instance in the LiveMeeting.

**Comment by ritzalam** [comment]
Can you please take a crack at this Chad?

**Comment by capilkey** [comment]
Sure. I'm fixing the getRecordings response builder right now, but I will do this next.

**Comment by capilkey** [comment]
Fixed in #4177.
