### ISSUE TITLE
Add new options to a shared note - suggestions

### ISSUE THREAD

**Issue by marshel** [bigbluebutton/bigbluebutton#4387]
- Add a thumbs "up/down" button on each shared note.
- Allow a tabbed window of shared notes.
- Allow the moderators to delete/close a shared note.

**Comment by ffdixon** [comment]
Got your feedback ...  a questions

> Add a thumbs "up/down" button on each shared note.

What is the use case your are thinking this will address?

> Allow a tabbed window of shared notes.

We could, but it might be harder to follow the discussions.  We thought it better to have distinct windows so users could follow updates to all the notes at a glance.

> Allow the moderators to delete/close a shared note.

We could ... but one problem is that if a moderator closes the shared notes, they get a warning, but other users don't have any warning.  When closed, the shared notes window will disappear without any ability to save the information.

In some ways, that's OK because another user could delete all the shared notes (or the moderator could clear the shared notes).  We'll look at putting in the close button in the future.

**Comment by marshel** [comment]
> What is the use case your are thinking this will address?

When some students express an idea, it may be or not what their colleagues are thinking or even on a bussiness meeting this could be the case.

This kind of "rating" system will allow the presenter to better understand the class idea over the subject , of whats is being said on the note, or even as a quick exercise or informal pool.
It is a practice already ok for the "millennials" to use hence the social media and some project management SaS like trello. 
I believe the results of the "thumbs up/down" may be anonymous or just for the presenter/moderator.

> We could, but it might be harder to follow the discussions. We thought it better to have distinct windows so users could follow updates to all the notes at a glance.

> We could ... but one problem is that if a moderator closes the shared notes, they get a warning, but other users don't have any warning. When closed, the shared notes window will disappear without any ability to save the information.

Ok, I believe all you folks got on right track and the system will evolve over the versions. 

Some way of controlling the notes on the display (most notebooks on my country are still on 720p resolution) and maybe a "hide" note from viewers may be a interesting enhancement to avoid shared notes display nightmare.

**Comment by ffdixon** [comment]
Closing as this was an issue related to the Flash client (the project has moved to an HTML5 client).

We're now using Etherpad for the shared notes in BigBlueButton HTML5 client in 2.2.  Check it out at 

  https://test.bigbluebutton.org/
