### ISSUE TITLE
v2 Beta: How to Enable/Disable tooltips + red pointer only without displaying mouse pointer arrow?

### ISSUE THREAD

**Issue by zenny** [bigbluebutton/bigbluebutton#4495]
Hi,

1. How to enable/disable tooltips at the behest of the presenter?

1.1 Imho, the tooltips may not be necessary for the presenter once he gets used to the bbb. So an option to enable/disable tooltips would be handy.

1.2 Second, is there a way to only display the annotation toolbar only to the presenter?

2. How to only use a red pointer (like laser pointer) without displaying the mouse pointer arrow while annotating the presentation? The mouse pointer arrow works like a distration.

Just my wishful thinking.

Cheers,
/z

**Comment by capilkey** [comment]
1. The tooltips can't be disabled. It's not feasible to turn them on and off.

1.1 A good tooltip shows information not available by just looking at a button. It might include a longer version of the function or a text equivalent of the icon used on the button. Tooltips are a standard and I wouldn't support removing them.

1.2 The whiteboard toolbar only shows when you can draw. If viewers are seeing the whiteboard toolbar in 2.0 it's because the presenter has turned on multi-user whiteboard by selecting the button at the bottom of the bar.

2. The red dot and the native mouse pointer represent two different things. The red dot is what the viewers see and has a delay on it because the messages have to travel. The mouse pointer is where the mouse actually is and the red dot will eventually catch up. If we removed either the presenter would lose information available to them.
