### ISSUE TITLE
2.0 player has no fullscreen button

### ISSUE THREAD

**Issue by kovaldn** [bigbluebutton/bigbluebutton#4606]
In the player, version 2.0 there is no more button to view the recording of the desktop on the whole screen/ 
![2017-10-30_22-53-25](https://user-images.githubusercontent.com/1854808/32192490-5d3bdc78-bdc5-11e7-9372-68f026cd9c2f.png)

**Comment by ZmoNkk** [comment]
Turns out this fullscreen button only appears in the HTML markup if webcam video present in the webinar session. Such behaviour may be intentional, but is not suitable for our needs, as students want to fullscreen deskshare video or presentation slides instead. 

As a temporary fix we have added another button that does exactly that. Implementation is pretty straightforward. 

May anyone from the dev team comment on behavior of the fullscreen button? Is it intended that it fullscreens only webcam video? I am happy to provide a PR for that, but would like to talk things out first.

**Comment by capilkey** [comment]
The recording playback is a bunch of different files (images, text, and audio or video). Everything on the page is synced up to the main media file. The main media file will either be an audio track or if there were webcams in the meeting it will be a video instead. 

In previous versions of the playback the deskshare video would be put into the main media file, but in 2.0 the recordings were altered so that the deskshare video was kept as a standalone video. Keeping the deskshare as a standalone video allowed us to automatically place the deskshare video where the presentation images normally are. It's a much better experience than before because you don't need to press the button to swap the sections like before. The downside is that the controls only affect the main media file to which they are attached. 

The fullscreen button could maybe be changed to affect the deskshare portion, but what happens if there's also webcams and someone wanted those fullscreen instead. I'm not sure what the best approach would be.

You've also never been able to fullscreen the presentation images it's only ever affected the main video file.

**Comment by ZmoNkk** [comment]
Thanks for your input! 

One of the ways we see it is to make a dropdown list on button click, which would allow user to select either fullscreen presentation\deskshare or webcam video. Is this worth the PR, in your opinion? I am not sure if there is anyone else struggling with this.

**Comment by capilkey** [comment]
A dropdown might not be a bad idea. I think there would need to be some
checks to determine what to show though. For instance don't offer to full
screen the webcams if it's an audio recording.

If you want to submit a PR I'd be happy to review it. We'll need a signed
commiter agreement before it can be merged though.
http://docs.bigbluebutton.org/support/faq.html#contributing-to-bigbluebutton

**Comment by pedrobmarin** [comment]
Done in https://github.com/bigbluebutton/bbb-playback
