### ISSUE TITLE
Missing translation for chat input max/min characteres

### ISSUE THREAD

**Issue by Tainan404** [bigbluebutton/bigbluebutton#4730]
Messages are fallbacking to theirs ID`s since the translation is missing

![deepinscreenshot_select-area_20171127115443](https://user-images.githubusercontent.com/15806883/33270212-66c8f8c4-d36a-11e7-8415-a292f51081c2.png)

![deepinscreenshot_select-area_20171127115510](https://user-images.githubusercontent.com/15806883/33270213-66ed9ada-d36a-11e7-8853-b62d66e3dbd3.png)

**Comment by OZhurbenko** [comment]
It's simply because there none of the locale files contain "errorMaxMessageLength" string.
It tries to go to default "English", but the string with that id is not there as well.

The issue should be something like: "Add a default string for the "app.chat.errorMaxMessageLength" message to the /private/locales/en.json
