### ISSUE TITLE
Remove react-router

### ISSUE THREAD

**Issue by OZhurbenko** [bigbluebutton/bigbluebutton#4767]
We kind of avoided the react-router update, since the latest one wasn't backwards compatible with the 3.x.x 
But there are some new features that we need, e.g `innerRef` is one of them, which allows us not to use hacks, fake wrappers and findDOMNode() in order to get a reference to the underlying Link element.

It would be great to update `react-router` after the 2.0 release, to keep our code base up-to-date.

**Comment by jfsiebel** [comment]
`react-router 4` doesn't support named components (https://github.com/ReactTraining/react-router/blob/v3/docs/API.md#named-components), so we'll need to rethink how we render user list an chat.

**Comment by oswaldoacauan** [comment]
> 1) What was the obstacle?
> 2) Is it still there
> 3) Should we try this now in 2.2?
@antobinary - Anton Georgiev [3:17 PM]

1) They removed the option to use routes to pass down props to the parent route (or something along those lines). See https://github.com/ReactTraining/react-router/blob/v3/docs/API.md#named-components
2) Probably, need to check if they re added that but I doubt since the new router is not mean to be backwards compatible and is a full rewrite.
3) I dont think so, its easier to just remove the router and use React.State or Meteor.Session

**Comment by antobinary** [comment]
Done in #6162
