### ISSUE TITLE
Language selector appears in English, not each in your language.

### ISSUE THREAD

**Issue by Tainan404** [bigbluebutton/bigbluebutton#4847]
Flash:
![deepinscreenshot_select-area_20171219140334](https://user-images.githubusercontent.com/15806883/34166225-8befa7e4-e4c5-11e7-9e52-db766677d24e.png)

HTML5:
![deepinscreenshot_select-area_20171219140404](https://user-images.githubusercontent.com/15806883/34166269-98d3d976-e4c5-11e7-944d-83604b7562e9.png)

**Comment by MaximKhlobystov** [comment]
Can you provide more details on the screenshots? I switched my browsers to German and can see HTML5 client detecting it just fine in both Chrome and Firefox:
![lang](https://user-images.githubusercontent.com/5004762/34167321-6af5104e-e4af-11e7-9f14-f4f7da52518e.png)

Flash client still shows English by default, but I assume it's intentional.

**Comment by antobinary** [comment]
I think the point here is the _labels_ for the different languages are not 'localized'
English, French, German, ..
vs
English, Français, Deutsch, ..

**Comment by MaximKhlobystov** [comment]
Ah OK. Got it. Makes sense.

**Comment by capilkey** [comment]
You can find the Flash locale list here, https://github.com/bigbluebutton/bigbluebutton/blob/master/bigbluebutton-client/resources/prod/locales.xml. Each locale has a code, English name, and native name.

**Comment by antobinary** [comment]
This is what we currently use but it's missing the native name https://github.com/bigbluebutton/bigbluebutton/blob/v2.0.x-release/bigbluebutton-html5/imports/utils/locales.js

**Comment by Tainan404** [comment]
I was thinking of using the plugin [locale-code](https://www.npmjs.com/package/locale-code) and grabbing all the available locations in 'private / locales' and generating the name from that list so when there is a new language it auto generates it.

**Comment by capilkey** [comment]
The downside is that you're stuck with whatever format the plugin uses. That plugin expects dashes and we use underscores for instance. We'd also be stuck with whatever name it spits out. No huge issues, but something to consider.

**Comment by oswaldoacauan** [comment]
@capilkey well, dash is the [W3](https://www.w3.org/TR/html401/struct/dirlang.html#langcodes) and [ECMAScript](https://tc39.github.io/ecma402/#sec-internal-slots) standard.

I'm not sure why we use underline :man_shrugging:

**Comment by OZhurbenko** [comment]
@oswaldoacauan I think that's what Transifex does, it's nor really our choice.

**Comment by 00000000001234567890** [comment]
Hello, I am a shareholder and in order to help those who are rejected by banks,
I make a loan of between € 5,000 to € 50,000 with a rate of 3% if you are in need of loan
, please contact me by our email address so that i can tell you if i can help you or not .... thanks and
may God bless all your managements.
mail: creditfrance6@gmail.com

Cordially ...

**Comment by oswaldoacauan** [comment]
@OZhurbenko since we are the ones that grab and save the files, we could always replace underline with dash if that would make our life easier.

**Comment by antobinary** [comment]
Resolved!
