### ISSUE TITLE
Visual enhancements to the closed captioning experience

### ISSUE THREAD

**Issue by tylercopeland** [bigbluebutton/bigbluebutton#4966]
<img width="993" alt="screen shot 2018-01-15 at 1 41 33 pm" src="https://user-images.githubusercontent.com/1273169/34957053-e6c6a944-f9f9-11e7-913d-d79870100e54.png">

**Comment by tylercopeland** [comment]
After building out the designs breakout rooms, polling and shared notes experience for the HMTL5 client, we've established a layout principle where text/input interactions live on the left-hand side beside the main sidebar. 

I took that same approach for the latest version of the closed caption experience. 

**Participant View** 
![html5-closed-caption-3](https://user-images.githubusercontent.com/1273169/44747377-09932c80-aadb-11e8-83d7-54eccf3c2635.png)

**Closed Caption Input**
![html5-closed-caption](https://user-images.githubusercontent.com/1273169/44747418-2596ce00-aadb-11e8-8f25-0c09ad665965.png)

![html5-closed-caption-2](https://user-images.githubusercontent.com/1273169/44747426-2a5b8200-aadb-11e8-9c24-68b7e62fca5f.png)

**Comment by capilkey** [comment]
I don't think we want to close off Closed Captions like this. If someone needs the live captions during a meeting they would need to constantly be switching between CC and chat in order to see all of the content in a meeting and follow along with any conversations.

From the publisher side they would also have difficulties with CC closed off because they wouldn't be able to follow the conversation either. Things like question and answer periods or heavy text use would be rather difficult.

**Comment by ffdixon** [comment]
We're thinking of using EtherPad to implement the Closed Captioning in the HTML5 client.  Some open questions

- [ ] Can we restrict EtherPad to only one editor (the cartographer)?
- [ ] Can we enable viewers to a view-only EtherPad where they can change the font size (without triggering a change in font size for others)?
- [ ] Can we use the resulting EtherPad file to create the subtitles in a recording?

**Comment by capilkey** [comment]
To expand on the problems:
1. The current implementation allows a moderator to take control (ownership) of a locale and they are given sole rights to edit it. Any other moderator can take control from them and there's clear indications on the screen when that happens. Can we give one user edit rights and what would happen if those edit rights were revoked?
2. The viewers need to be restricted from editing, but the viewing experience for them is very important. They need to be able to change the font size, font colour, and background colour so that they can make the text readable for themselves. Is it possible to make local changes and have them propagated to all of the text in the document and also make the formatting changes local only?
3. For the recordings we need to be able to get the history of changes to recreate the progression and produce a final SRT (or similar) caption file. Can we get the diff history out of a recorded meeting and can that be used in a script to create an SRT file?

**Comment by ffdixon** [comment]
Here's a look at the UI in the Flash client for changing the styles

![image](https://user-images.githubusercontent.com/290351/53981311-42dad380-40e0-11e9-8d02-21921bf03d2a.png)

**Comment by antobinary** [comment]
Closed in #7138 and #7654
