### ISSUE TITLE
Creating/joining a group chat

### ISSUE THREAD

**Issue by oswaldoacauan** [bigbluebutton/bigbluebutton#4989]
Flash design for reference
![](https://i.imgur.com/3lFbE3n.png)

**Comment by antobinary** [comment]
@tylercopeland is there any change here?

**Comment by tylercopeland** [comment]
Here's a mockup for the HTML5 client group chat experience. 

### Presenter Experience

**HTML5 client default state**
To start a new group chat, a presenter must click the (+) to the right of the messages label. 

![html5-group-chat-1 1](https://user-images.githubusercontent.com/1273169/48922041-e37aef80-ee71-11e8-902c-587d7afdf479.png)

**New chat panel**
Once the panel is open, a presenter can enter the name of the new chat group in the input field and click create to start a new group conversation. 

![html5-group-chat-1 2](https://user-images.githubusercontent.com/1273169/48922320-dced7780-ee73-11e8-8f82-e8146956b741.png)

<hr> 

### Participant Experience

**Interacting with a new chat group**
New group conversations are displayed in the sidebar. A can navigate between multiple group conversations by selecting the group chat name from the list. 

![html5-group-chat-1 3](https://user-images.githubusercontent.com/1273169/48925938-6498ad80-ee97-11e8-92a1-4a32fd74cd41.png)

**Selecting a group conversation**
Select the (+) button to view group conversations to join. A participant will only go through this experience if they have decided to close a group conversation that they already had open. 

![html5-group-chat-1 4](https://user-images.githubusercontent.com/1273169/48925943-6c585200-ee97-11e8-9efb-cdc469aa27ff.png)

@oswaldoacauan @antobinary @ffdixon "Selecting a group conversation" from a participants point of view is an area where I'd like feedback on. 

In the Flash client, we currently allow participants to close group conversations. A reason why we went this route was to declutter the interface because a new group chat means a new module. Whereas in the HTML5 client we've been able to come up with an intuitive way to easily compartmentalize all conversations in a list.

In the mockup above, I have a participant clicking the (+) that opens up a panel to view all group conversations. From there, they can join using the "join" button. _(Probably not the best option, however, it's consistent with the presenter experience)_

So, my question is which of the following options should we move forward with?

**Option 1 -**  Keep this option so that it's consitent between the presenter and participants expeirence. 

or 

**Option 2 -**  Remove the functionality of allowing a participant to close a group conversation. This will omit the need of displaying the (+) button and opening the new panel to see/join group conversations.
