### ISSUE TITLE
bbb-lti not using lis_person_sourcedid

### ISSUE THREAD

**Issue by ffdixon** [bigbluebutton/bigbluebutton#5005]
When testing with open edX, the LTI launch passes the user's name via lis_person_sourcedid, as in

~~~
lis_person_sourcedid=admin
~~~

However, when BigBlueButton launches, it shows the name as "Attendee". 

![image](https://user-images.githubusercontent.com/290351/35196220-3613b54e-fe9d-11e7-8793-7018ecd536bc.png)

Looks like it's set here

https://github.com/bigbluebutton/bigbluebutton/blob/v2.0.x-release/bbb-lti/grails-app/services/org/bigbluebutton/BigbluebuttonService.groovy#L228

Extend the LTI integration so it uses lis_person_sourcedid (if passed) for the fullName.

**Comment by ffdixon** [comment]
We could test with this

  http://ltiapps.net/test/tc.php

**Comment by jfederico** [comment]
That is because the default edX implementation is wrong. They should be passing:
lis_person_name_given=Jane
lis_person_name_family=Public
lis_person_name_full=Jane Q. Public
Or provide a way to enable the sending of public parameters.

They are passing admin as the lis_person_sourcedid when thoy should be passing the actual internal ID for that user e.g xxxx-yyyy-zzzz, or 1, 2, 3 ... 1000 in the case of Moodle.

If we we make it work for this particular use we have to extend the tool in a way we can assign profiles so every privider can be treated different.

**Comment by GhaziTriki** [comment]
The latest version of `LTI XBlock` in edX sends the parameters correctly:

```
lis_person_contact_email_primary=user@email.sample
lis_person_name_family=First Name
lis_person_name_full=First Name Last Name
lis_person_name_given=Last Name
lis_person_sourcedid=edxUserName
```

All the parameters listed above are mandatory in their platform in the user profile settings and they always pull them in their LTI requests.

**Comment by GhaziTriki** [comment]
The case I described above is when `Send extra parameters` is sent to `True`. When it is set to false can see my user name as `Moderator` when add a custome parameter `lis_person_sourcedid=admin`. The reason is that edX sends `Instructor` in `roles`.

**Comment by ffdixon** [comment]
@GhaziTriki, with the recent updates to`bbb-lt` can we close this one now?

**Comment by GhaziTriki** [comment]
@ffdixon We can close this issue after the latest update of `bbb-lti`. My two previous comments explains how `lis_person_sourcedid` is used by edX.

**Comment by ffdixon** [comment]
Closing as this is not an issue in the latest version of edX as it is properly passing the username in LTI.
