### ISSUE TITLE
The following WebRTC issues have been detected: Error 1002: Can not establish a WebSocket connection. Would you like to try Flash instead?

### ISSUE THREAD

**Issue by neutron92** [bigbluebutton/bigbluebutton#5319]
The following WebRTC issues have been detected: Error 1002: Can not establish a WebSocket connection. Would you like to try Flash instead?

**Comment by neutron92** [comment]
![image](https://user-images.githubusercontent.com/6135555/38432461-c8fd05da-39c7-11e8-9c0e-9aaff06a9260.png)

**Comment by neutron92** [comment]
![image](https://user-images.githubusercontent.com/6135555/38432480-d9472d58-39c7-11e8-9e40-f14bc1298aac.png)

**Comment by neutron92** [comment]
![image](https://user-images.githubusercontent.com/6135555/38434368-5d9b621c-39ce-11e8-9dec-f9a2443a0b3f.png)

**Comment by ffdixon** [comment]
Hi there,

You've already opened up this issue at https://github.com/bigbluebutton/bbb-install/issues/11.

Opening the same issue in multiple issue trackers does not get you a solution faster.  It has the opposite  effect as it causes more work for others to respond in multiple places.  

We're going to close this issue here and move the discussion to the above URL.
