### ISSUE TITLE
Add option to clear previous recording marks

### ISSUE THREAD

**Issue by ffdixon** [bigbluebutton/bigbluebutton#5361]
For use cases where a student is recording an assignment submission, for example, they may make a number of attempts during a session.

The Start/Stop Recording button makes it easy to record segments, but there is currently no way to clear previous segments.

When Starting/Stopping recording, add a checkbox to also clear out the previous recording marks

![image](https://user-images.githubusercontent.com/290351/38892351-fe0584f6-4254-11e8-8e83-3e5c389c5a0b.png)

This is unchecked by default.

**Comment by tylercopeland** [comment]
@ffdixon I put togther two mockups based on your concept above and the new modal designs we're using in the 2.0 client. 

**Simplified Option** - Title, two buttons and the input item

![bbb-flash_recording-marks-modal-2](https://user-images.githubusercontent.com/1273169/38910321-c2910f48-4296-11e8-89d7-1187723a6d56.png)

**Extended Option** - The same concept as above, but I've added additional copy for a description and in context help. This concept might take a bit more effort due to localizing the content, but having "in-context hep" will add a nice touch to the interface and a place for participants to get more insights on using the BigBlueButton recording feature. 

![bbb-flash_recording-marks-modal-1](https://user-images.githubusercontent.com/1273169/38910318-be35387a-4296-11e8-8a08-123899958835.png)

**Comment by ffdixon** [comment]
Hi Tyler, we should be able to do the second as the localization shouldn't be hard as it will be another locale string with a URL (similar to the copyright string).
