### ISSUE TITLE
API to extend session length if the preset time is near exhaustion

### ISSUE THREAD

**Issue by agrlayush** [bigbluebutton/bigbluebutton#5803]
While creating a session we pass session duration, but at times the session may need few extra minutes to finish. A feature to increase the session duration will help complete the session without having to recreate a meeting and resume.

**Comment by ffdixon** [comment]
Good suggestion.  Currently, when the meeting is created it's not possible to change the value for duration.

We need to add an API call such as

~~~
setDuration
~~~

which takes two parameters: `meetingID` and `duration`.

This way, a front-end could extend (or shorten) the duration as needed.

**Comment by wungaz** [comment]
This would be a great feature, the admin should be able to add more minutes

**Comment by Rajesh98y** [comment]
is this implemented?
am not able to use this api

**Comment by matiasilva** [comment]
@Rajesh98y as indicated in the above comments, this is still an idea in progress. At present there is no way to accomplish the issue's request, and you will have to appropriately set meeting times.

**Comment by Subdarub** [comment]
I would also approve of this feature.
From a teachers perspective its not a rare occasion, that students might say, they will need a few more minutes to finish their group project.
But if the Breakoutrooms are going to run out, they wont be able to finish their work or you would have to create new breakoutrooms. Which takes time away from the lesson, so would setting a longer time for the breakoutrooms, because in no way shaper or form, are the students going to be on time if you dont force them back to the main room after the set period of time.

**Comment by ffdixon** [comment]
Implemented the ability to extend duration of breakout rooms in 2.4.  Keeping this ticket open as we don't yet have the ability for the moderator to extend the duration of the main room if a time limit was set when creating the room.

**Comment by ebsir** [comment]
Is this implemented, is there some option to prolong session time?

**Comment by ffdixon** [comment]
Of course!  BigBlueButton is open source, and you are welcome to modify and use it under the open source licence.

**Comment by singleseeker** [comment]
any update?

**Comment by piszczu4** [comment]
any update?
