### ISSUE TITLE
Audio joining configuration not applied

### ISSUE THREAD

**Issue by antobinary** [bigbluebutton/bigbluebutton#5841]
autoJoin, listenOnlyMode, forceListenOnly and skipCheck control the audio participation of users in the HTML5 client in the same way they do in the Flash client:

"autoJoin": true means we want to display the microphone vs listen only choice immediately after login

"listenOnlyMode": false - do not allow joining as listen only

"forceListenOnly": true - do not allow full audio for attendees (note this requires "listenOnlyMode": true)

"skipCheck": true skips echo test when joining full audio

**Comment by oswaldoacauan** [comment]
This was implemented in #5221

**Comment by antobinary** [comment]
I'm currently unable to automatically join as listenOnly on login. I see the audio modal. The feature was implemented but seems some edge cases are missing (or not applied)

**Comment by antobinary** [comment]
Seems I was joining as moderator. `forceListenOnly` is applied only to attendees. All seems to work fine. Closing

**Comment by oswaldoacauan** [comment]
@esaribeiro the configurations under the `settings.json` are only related to the HTML5 Client. The Flash client uses the `config.xml` file and you can check the documentation [here](http://docs.bigbluebutton.org/install/client-configuration.html#phone-module).

**Comment by Tainan404** [comment]
Hey @esaribeiro, in html5 the config to auto join as listen only is 
```
"autoJoin": true
"listenOnlyMode": true
"forceListenOnly": true
"skipCheck": false
```
`skipCheck` is related to skip echo test for voice users.

**Comment by esaribeiro** [comment]
Thanks, Oswaldo.

Do you know if this params works fine on Flash version?
Because i've tried changing this params the config.xml for Flash version and settings-dev.json for Html5, but only the Html5 version worked.


Em 20 de ago de 2018 9:35 AM, Oswaldo Acauan <notifications@github.com> escreveu:

@esaribeiro<https://github.com/esaribeiro> the configurations under the settings.json are only related to the HTML5 Client. The Flash client uses the config.xml file and you can check the documentation here<http://docs.bigbluebutton.org/install/client-configuration.html#phone-module>.

**Comment by capilkey** [comment]
@esaribeiro You can also lock the microphone and any viewers will join as listen-only.
