### ISSUE TITLE
Adjustments to logClient

### ISSUE THREAD

**Issue by antobinary** [bigbluebutton/bigbluebutton#5912]
*    make the configuration for log that you added in both json's spread over several lines -

```
{ "log": [
    "a": "b",
    "c": "d",
...
]}

```

*   rename 'log' to 'clientLog' and the old "log" on the bottom of the jsons to "serverLog"

*    add default value for clientLog - to log to console
* add documentation similar to the `logging` section in http://docs.bigbluebutton.org/install/client-configuration.html#main-parameters

**Comment by capilkey** [comment]
There's a section in one of the documentation pages that talks about how to set up a URL logger in nginx that should also be referenced in the documentation. Using the URL logger helps to separate the client logs from the server logs so that the server logs don't get overwhelmed by the multitude of clients.
