### ISSUE TITLE
surface pro 4 issues: pen on whiteboard and screen share

### ISSUE THREAD

**Issue by igtemesvari** [bigbluebutton/bigbluebutton#5966]
When using my pen on my surface pro 4, it can get buggy. What I mean by this is when I write with my pen on the whiteboard, the whiteboard will get long lines which appear out of nowhere while I'm writing. It's kind of hard to explain, until you actually try it, or witness it yourself. Also, sometimes when writing, the screen will zoom in, thinking I had double tapped with my pen (but, of course I did not double tap). Then, it is extremely difficult to double tap (on purpose this time) to un-zoom back out from the zoomed view--super irritating.

The other issue is the screen share on the pro 4. I can get the java program to run perfectly fine, but when it starts up, the viewers say that they can only see a very limited window of what I am actually sharing (in this case, it is always my entire screen). So, I have to ask them what they see and then manipulate my screen by dragging windows around to an area where they can see just enough of what I'm trying to show them--again, even more irritating.

I really enjoy using BBB and love the product, but these issues alone have been swaying me to reconsider BBB altogether.

If you have any information on how to fix either of these issues, please help me out.
Thank you.
Best,
Ivan

**Comment by capilkey** [comment]
What browser are you using? 
Can you try the HTML5 client to see if the issues present there also (test.bigbluebutton.org). You'll need to use Firefox or Chrome with the HTML5 client.

The writing and zooming issues are outside of our control because we just deal with the events that we get from the Flash plugin. The Java issue is strange and one I've never heard of before, but that is our code. My guess would be that it's something weird with how the OS says how big the screen is.

**Comment by capilkey** [comment]
Can you confirm that Chrome handles the pen input better? It wouldn't surprise me, but I just want to be sure.

The reason why I said OS for the cause of the screen size issue is that the Java code has to check for the screen size when it starts sharing the full screen and if the width/height that's returned is incorrect there might be no way of finding the correct values. As a workaround you could maybe try sharing a region and just resize the region so that it fills all, or most, of your screen.

**Comment by igtemesvari** [comment]
Yes, it does. And, your tip about sharing a region is exactly what I thought might be a solution.

I’ll get back to you on that one.

Thank you very much for your help.

P.S. Apparently after some MS updates and Edge updates, these issues came out of nowhere and I thought it was BBB. These issues were non-existent a year ago…should’ve know to try Chrome. I tried Firefox, but didn’t get any luck with that.

Best,

 

--

Ivan Temesvari M.A. M.S.

Oakton Community College

Coordinator of Computer Science

Assistant Professor of Mathematics and Computer Science

1600 E. Golf Rd. Des Plaines, IL 60016 Rm. 2224

847-376-7065

 <http://www.oakton.edu/~itemesva> Oakton Computer Science

**Comment by igtemesvari** [comment]
The full screen nor the region screen share work. Here is what I get:



 

--

Ivan Temesvari M.A. M.S.

Oakton Community College

Coordinator of Computer Science

Assistant Professor of Mathematics and Computer Science

1600 E. Golf Rd. Des Plaines, IL 60016 Rm. 2224

847-376-7065

 <http://www.oakton.edu/~itemesva> Oakton Computer Science

**Comment by capilkey** [comment]
I think Github ate the image you tried to attach.

**Comment by igtemesvari** [comment]
Basically, you observe the same issues with the portion of the screen not visible.

Resizing the screen just makes what you see smaller and even worse.

Greenlight is the way to go from now on.

It is a front end for BBB. It solves the screen sharing issue and Chrome solves the whiteboard and Surface Pro 4 issues.

I’m all set for now.

Thank you for all of your input.

Best,

 

Ivan
