### ISSUE TITLE
Chrome browser version 69

### ISSUE THREAD

**Issue by caphill7** [bigbluebutton/bigbluebutton#6041]
I noticed that the client is detecting Chrome 69, that just released today, as being out of date. It puts the notification (!) and when clicked states "Your browser (Chrome 69) is not up-to-date. Recommend updating to the latest version." Which, of course, Cr69 is the latest version.

**Comment by capilkey** [comment]
Are you running a development client? If you are then the VERSION to look for probably just needs to be filled in the config.xml.

**Comment by caphill7** [comment]
Packaged client

**Comment by capilkey** [comment]
I've got Chrome 69 and I don't see any warning when connecting to our demo server (demo.bigbluebutton.org) so it's likely a config issue not a code issue. The packaged client stores its config.xml at /var/www/bigbluebutton/client/conf/config.xml and look for the browser version line (https://github.com/bigbluebutton/bigbluebutton/blob/master/bigbluebutton-client/resources/config.xml.template#L16). Can you paste it back here please.

Also, support requests should be directed to the most appropriate mailing list (https://groups.google.com/forum/#!forum/bigbluebutton-dev or https://groups.google.com/forum/#!forum/bigbluebutton-setup) so that the the Github issues don't get cluttered with non-issues.

**Comment by caphill7** [comment]
Line from config.xml:
<browserVersions chrome="62" firefox="56" flash="23"/>

**Comment by ffdixon** [comment]
@caphill7 If you change it to chrome="70" and restart BigBlueButton does the warning go away?

**Comment by IgorDePaula** [comment]
I download on docker, and in chrome 69 open directly in flash and not allow me choice between html5 or flash.

**Comment by ffdixon** [comment]
Closing as this was an issue related to the Flash client (the project has moved to an HTML5 client).
