### ISSUE TITLE
Who is talking indicator for large sessions

### ISSUE THREAD

**Issue by tylercopeland** [bigbluebutton/bigbluebutton#6042]
In large sessions, at times it is hard to identify who is currently talking. Especially if there is a use case where someone enters the session late and has loud background noise.

**Comment by tylercopeland** [comment]
@oswaldoacauan @ffdixon @antobinary 

Below is a first pass at the talking indicator. Would love to hear your thoughts. 

![html5-talking-indicator](https://user-images.githubusercontent.com/1273169/48927099-70896d00-eea1-11e8-8131-963e9479b553.png)

**Comment by GhaziTriki** [comment]
In some cases the sound is good but there are many participants. We are not able to know who is talking without scrolling down the users' list.

**Comment by tylercopeland** [comment]
@GhaziTriki what are your thoughts on the initial mockups above? Or do you have any thoughts or recommendations on this experience within the HTML5 client?

**Comment by capilkey** [comment]
The only issue that I see is that it doesn't have space to show multiple people talking. Usually the problem is that people are talking over each other or someone is on open mic and it will activate periodically and to solve those problems you need to be able to see multiple rows at the same time. I had thoughts to display an overlay similar to what Discord does over top of video games.

**Comment by mtsonline** [comment]
please considder using this video floor indication as source or a new display-energy-level (to be introduzed) so the energy-level set to 0 (to keep audio quality) does not break the speakers indication:
#8388

**Comment by tylercopeland** [comment]
@ffdixon @antobinary - I'm going to close this issue since it's a current feature.
