### ISSUE TITLE
could not change text in presentation upload modal in html5 client

### ISSUE THREAD

**Issue by farshidmahmoodi2017** [bigbluebutton/bigbluebutton#6077]
I want to change this text in presentation upload modal in html5 client:
"As a presenter in BigBlueButton, you have the ability of uploading any office document or PDF file. We recommend for the best results, to please upload a PDF file."
Where can I update this text?

**Comment by antobinary** [comment]
Hi @farshidmahmoodi2017 
This is the code line where we store the above mentioned message: https://github.com/bigbluebutton/bigbluebutton/blob/v2.0.x-release/bigbluebutton-html5/private/locales/en.json#L62

You can change it in `/usr/share/meteor/bundle/programs/server/assets/app/locales/en.json` on a server with bbb-html5 package installed (and then restart bbb-html5)

Note that you will have to change (or at least remove) the value string for other languages in the same directory. Otherwise your users would be seeing different content depending on their locale.

Alternatively, you could set up a development environment and make any code changes you desire by following http://docs.bigbluebutton.org/html/html5-dev.html

Best regards,
Anton Georgiev
