### ISSUE TITLE
Update logout options for HTML5 client

### ISSUE THREAD

**Issue by ffdixon** [bigbluebutton/bigbluebutton#6124]
Currently, there are three options when a moderator logs out of the HTML5 client

![image](https://user-images.githubusercontent.com/290351/46230938-2b7d0a80-c338-11e8-8a07-1b431128a083.png)

However, it isn't clear to the user that the 3rd option is clickable.

**Comment by capilkey** [comment]
This is what the Flash version of the logout confirm looks like:
![image](https://user-images.githubusercontent.com/1395090/46231329-87945e80-c339-11e8-8e68-156f7cb8a59b.png)

All three options are on one line and the language is consistent through all of the options. The other important factor in the Flash version is that all of the buttons are clearly denoted and easy to distinguish from the non-interactable text

**Comment by capilkey** [comment]
The initial discussion that brought this up can be found here, https://groups.google.com/d/msg/bigbluebutton-dev/brI7-RK23ps/eisGrGWhAQAJ.

**Comment by tylercopeland** [comment]
@ffdixon @capilkey thanks for pointing this out. 

I can easily see how the current implementation is confusing. We might want to use the medium-sized modal (the one being used in the audio connection flow) for this experience. If we do go down that path, it would look visually similar to the Flash client. 

Let me explore a few options.

**Comment by antobinary** [comment]
To me it seems like the confusion is because on the HTML5 the buttons are not bordered - i.e. they don't look like a button. The type of modal (full-screen or not) is not problematic.

@tylercopeland Could we simply add a border to the buttons [Cancel] and [Yes and close the session]?

**Comment by capilkey** [comment]
The lack of a border is probably the biggest source of confusion. The
second factor is that the options are split up which makes it seem like
they aren't related.

**Comment by tylercopeland** [comment]
@antobinary yes, let's move forward with adding an outline around our secondary actions. 

We can come up with a new rule where: 

**Primary action** = blue
**Secondary action** = white + outline
**Tertiary action** = blue link

Looking at this now a grey link is too close to our paragraph text. 

I also agree with @capilkey that it is probably best to group information and actions together. 

Here are a few mockups that I've put together for this experience. 

**Option 1**
![html5-logout-1](https://user-images.githubusercontent.com/1273169/46299703-ec38fe80-c56f-11e8-94df-562b03de2883.png)

**Option 2**
![html5-logout-2](https://user-images.githubusercontent.com/1273169/46299736-ff4bce80-c56f-11e8-9cef-bea01edbc224.png)

**Option 3**
![html5-logout-3](https://user-images.githubusercontent.com/1273169/46299747-0672dc80-c570-11e8-9dba-3ba640defce6.png)

Also, I noticed that we are mixing terminology in both of our clients, "meeting" and "session". I think we should stick with using "sessions" since it's a word that can be used in both the education and business space.

**Comment by capilkey** [comment]
I'm partial to the non-blocking modal in Option 3. No excessive white space.

**Comment by antobinary** [comment]
Could we use a darker color for the outline/text? All 3 options look like 2 of the 3 options are inactive...

**Comment by kepstin** [comment]
The current colours don't meet accessibility requirements for contrast.
![screenshot_2018-10-01 webaim color contrast checker](https://user-images.githubusercontent.com/38788/46300453-c876b800-c571-11e8-89b1-b60f3e5a3373.png)

**Comment by tylercopeland** [comment]
That's my fault, I selected the wrong grey colour from our colour palette. 

With this next iteration, I decided to use our blue colour versus the grey for the text and outline. Some might think that the "greyed" buttons are dissabled buttons. (probably overthinking it, but it's a rational for using the blue).  

**Option 1**
![html5-logout-1](https://user-images.githubusercontent.com/1273169/46307398-cc600580-c584-11e8-86dc-3d97144ba927.png)


**Opion 2**
![html5-logout-2](https://user-images.githubusercontent.com/1273169/46307400-d124b980-c584-11e8-884d-31d9fc3a33b1.png)


**Option 3**
![html5-logout-3](https://user-images.githubusercontent.com/1273169/46307405-d41faa00-c584-11e8-8945-3b421ea5a5ee.png)

I do agree with @capilkey that using th full screen modal is not necessary for the logout experience. @antobinary based on our available resources and timeline, I'll let you choose which direction is best. But, if we do decided to go down the small modal route, I'd recommend also addressing this issue at the same time, https://github.com/bigbluebutton/bigbluebutton/issues/6016.
