### ISSUE TITLE
sudo is used from bbb-conf

### ISSUE THREAD

**Issue by mikhailnov** [bigbluebutton/bigbluebutton#6281]
Why is `sudo` used in `bbb-conf`? My debootstrap'ed Ubuntu did not have sudo, it's not needed in a container.

**Comment by ffdixon** [comment]
Not all capabilities in `bbb-conf` require sudo, such as printing out the shared secret for the server.  

It's been a while since we looked at how bbb-conf asks for elevated privileges.  We could look at removing all references to sudo in the next release and just have folks run `bbb-conf` as root.

**Comment by mikhailnov** [comment]
I've reworked it to use sudo to only when it's  not root. But actually we cannot be sure that the user has sudoers capabilities.
