### ISSUE TITLE
Make the record indicator a toggle on/off button

### ISSUE THREAD

**Issue by tylercopeland** [bigbluebutton/bigbluebutton#6290]
Also, when turning the recording off, prompt the user with a "Are you sure you want to stop" modal.

**Comment by tylercopeland** [comment]
Through user feedback, we've identified that it's not clear how to start/stop a recording in the HTML5 client. 

An updated experience discussed amongst the group is having the current recording indicator act as a toggle turning the recording on and off. The plus side of adding this functionality is that it will mimic a familiar experience we see today in the Flash client. 

Below are mockups of a presenter starting and stopping a recording. 

**Recording default state**

![html5-recording-1](https://user-images.githubusercontent.com/1273169/48921547-5c784800-ee6e-11e8-8b43-24fbace92eb2.png)


**Modal, start recording**

![html5-recording-2](https://user-images.githubusercontent.com/1273169/48921549-613cfc00-ee6e-11e8-9ae1-9ce05a319520.png)

**Recording active state**

![html5-recording-3](https://user-images.githubusercontent.com/1273169/48921552-6437ec80-ee6e-11e8-9b5f-a0ba17e39126.png)


**Modal, stop recording**

![html5-recording-4](https://user-images.githubusercontent.com/1273169/48921555-669a4680-ee6e-11e8-9840-97eb3c090bf8.png)

**Comment by ux-jules** [comment]
I think the mockups show a better user experience then what it currently is. Currently, the HTML5 version, I had a hard time figuring out how to start the recording. It is not common or obvious to have to click on a plus icon to find the option to start a recording. I think the mockup solves that problem nicely.

**Comment by ux-jules** [comment]
A couple of suggestions:
(1) When you start a recording not only have the circle turn red, but have a pause button next to it. It might be unclear to users that when they click on the red circle to stop the recording if they will be able to start it up again, and have it be the same recording instead of ending up with two video files. With a pause button the user will be able to pause the recording and know that they can start it right back up and end up with just one video file.

(2) When you hit the record button there is no feedback letting the user know which part of the screen is getting recorded. Most recording software outlines, usually with a red box, what part of the screen is getting recorded. I suggest having this feedback for the user. When I didn't see this outline, I was confused as to whether the record function was working. As an added bonus, let the user change the area of the screen that is getting recorded.
