### ISSUE TITLE
iOS speaker list is not available

### ISSUE THREAD

**Issue by antobinary** [bigbluebutton/bigbluebutton#6590]
![screenshot from 2019-01-18 12-22-59](https://user-images.githubusercontent.com/6312397/51402568-d39f2500-1b1b-11e9-80ad-7ce879bf2e46.png)

`navigator.mediaDevices.enumerateDevices();`

**Comment by gustavotrott** [comment]
I really can't obtain the list of output audio devices, even in desktop Safari.

This is a Safari limitation, we can see in Webkit "bugs":
https://bugs.webkit.org/show_bug.cgi?id=179415
https://bugs.webkit.org/show_bug.cgi?id=184141

In this case we could change the combo value for safari to show `Default` instead of `no audiooutput found`.
