### ISSUE TITLE
Locked private chat should not affect moderators

### ISSUE THREAD

**Issue by antobinary** [bigbluebutton/bigbluebutton#6600]

**Comment by jfsiebel** [comment]
Can't reproduce this error, for me moderators are always unaffected.

**Comment by capilkey** [comment]
I'm not 100% sure about the original report because there isn't much information, but in 2.0 the locked viewers could still private chat with moderators when they're locked. I just tried this in 2.2 Flash though and user's are shown the ability to chat back, but when they send the message they're ejected from the meeting.

We're going to want the ability for viewers to private chat with moderators when private chat is locked, but it's broken upstream from the client right now.

**Comment by antobinary** [comment]
@capilkey sounds like you are describing https://github.com/bigbluebutton/bigbluebutton/issues/6671

**Comment by capilkey** [comment]
That is what I'm describing. Again, there wasn't much information here so they seem similar. Was this about moderators not being able to initiate private chat?
