### ISSUE TITLE
Utilize text extracted from slides for accessibility

### ISSUE THREAD

**Issue by antobinary** [bigbluebutton/bigbluebutton#6692]

**Comment by antobinary** [comment]
@KDSBrowne What are your suggestions for utilizing the text?

**Comment by capilkey** [comment]
For context, in the Flash client we set the slide text as the accessibility description of the slide container.
```
slideLoader.accessibilityDescription = ResourceUtil.getInstance().getString("bbb.presentation.slideloader.starttext") + 
                                       page.txtData + ResourceUtil.getInstance().getString("bbb.presentation.slideloader.endtext");
```
And then the text on either end is
```
bbb.presentation.slideloader.starttext = Slide text start
bbb.presentation.slideloader.endtext = Slide text end
```
I did it this way because if the slide is very wordy I figured that it would be a problem to know what is being read isn't from us, but is dynamic to the content.
