### ISSUE TITLE
Set Default Language Html5 Client

### ISSUE THREAD

**Issue by MHZarei** [bigbluebutton/bigbluebutton#6757]
I want change default language in html5 client, I changed bbb_localization.js but it doesn't work.
Also see `/usr/share/meteor/bundle/programs/server/assets/app/config/settings-production.json` file, but not exist any parameter for default language.

How can I change default language?

**Comment by antobinary** [comment]
Hi @MHZarei 
There is https://github.com/bigbluebutton/bigbluebutton/blob/v2.0.x-release/bigbluebutton-html5/private/config/settings-production.json#L25 - the fallback language.
What language do you want the client to be in? Just for you or for all users on the server? What is your the desired locale set in your browser?

**Comment by MHZarei** [comment]
I changed **fallback language** to '**de**' and restart html5 service, but it doen't work. I used private browsing to join meeting (as new user).

**Comment by KDSBrowne** [comment]
Hey @MHZarei

The `fallbackLocale` in the settings represents the locale that is guaranteed to contain a full listing of all the formatted strings in the client.

When the client loads, it tries to use your browsers perferred locale. If the locale does not exist or only contains a portion of the strings it is merged with the `fallbackLocale` to fill in any missing translations. Due to this merging the client will either show a mix the perferred and `fallbackLocale` languages or just the `fallbackLocale` language.

The following shows setting the browsers preferred language in Chrome, the ordering of the language list matters.

![settings](https://user-images.githubusercontent.com/22058534/53252310-91be4d00-368c-11e9-97f7-39e3b98fe766.gif)

**Comment by antobinary** [comment]
We now have `overrideLocale` in settings.yml
See #8336  for more info
