### ISSUE TITLE
Screen sharing stops from working and cannot be restarted

### ISSUE THREAD

**Issue by GhaziTriki** [bigbluebutton/bigbluebutton#6763]
In the latest 2.0-RC11 release, in some cases the screen sharing in HTML5 client stops from working and cannot be restarted.

**Comment by prlanzarin** [comment]
Can you detail the problem a bit further so I'm able to debug it?
i.e.: OS, browser; the error behaviour (in some cases: what cases? Cannot be restarted: does it pop any error?); console logs and bbb-webrtc-sfu logs that showcase the error you're describing.

**Comment by ffdixon** [comment]
@GhaziTriki Are you still finding this in 2.2-beta?

**Comment by ffdixon** [comment]
Closing this issue as it is quite old now and we've done a lot of updates to the HTML5 client since originally reported.  If anyone reading this thread encounters a similar problem, please test first with

  https://demo.bigbluebutton.org/

and if you encounter an issue, let us know

  https://bigbluebutton.org/support
