### ISSUE TITLE
Detect mobile and default to disabled webcams (via Settings -> Data savings)

### ISSUE THREAD

**Issue by antobinary** [bigbluebutton/bigbluebutton#6860]
Mobile devices (generally speaking) risk overheating when multiple webcams are active in a meeting. In order to optimize the experience for mobile users, we should limit the number of streams. As step 1 in that goal, we should set default value for Data saving -> webcams as disabled. Users should be able to switch the flag manually but the default on login should be webcams off.
It would also be nice if we could show a toast notification that such setting (disabled webcams) was enforced by detecting the environment

**Comment by atar3d** [comment]
Video is an important and basic part of a meeting. if the default on login is webcams off, then Users will interpret this as a system failure.  users will not understand why the video does not work, and why you need to take action so that it will work.
If the Motivation is that a mobile device will not show more than x number of cameras, it is advisable to limit only third or fourth camera from appearing and hide the rest.

**Comment by ffdixon** [comment]
A variation of this is to only show one webcam on the mobile device: the presenter.

**Comment by capilkey** [comment]
@jfsiebel's PR does as directed, but the original plan is flawed. We need to give more control to the user about what they want to do because if we just cut off the non-presenter webcams then we'll cut down on the usefulness of BBB.

In my mind we need to ask the user what they want to do. If we try to be too smart and automatically do stuff then we'll miss. We don't know if a person is in a voice chat instead of a presentation focused class. We don't know if they really need an ancillary webcam for accessibility (sign language stream). 

If we detected when there's a non-presenter, non-local user webcam and asked the user something like, "We've detected that you're on a mobile device, do you want to only see the presenter's webcam to reduce bandwith and increase battery life?". If they say "Yes" then we can filter the others out, but if they say "No" then we can defer to their choice.

Another concern would be how could the person change their mind about the previous selection. We could show a dummy webcam box with [+] and it would allow them to add webcams. We would only need to show the extra box when there are webcams that are hidden and then the user could show individual webcams or override the filter completely and go back to seeing every webcam.

We could also extend the menu that is on every webcam to offer the option to hide the webcam. Something like that would make the filtering and selection useful for desktop users also.

**Comment by antobinary** [comment]
In BigBlueButton 2.3 there's a few settings which (in my opinion) suffice to address mobile webcams data savings.

In settings.yml the default number of webcams that load on mobile is capped
```
      mobilePageSizes:
        moderator: 2
        viewer: 2
```

Also in #11758 the access to Data Savings is 1 click away rather than burried in the Settings menus
