### ISSUE TITLE
User dropdown doesn't close when notes panel is open

### ISSUE THREAD

**Issue by tylercopeland** [bigbluebutton/bigbluebutton#6943]
If you click on a users name within the sidebar to open the user dropdown and then click into the notes panel, the user dropdown doesn't close. 

<img width="1440" alt="screen shot 2019-03-07 at 2 54 26 pm" src="https://user-images.githubusercontent.com/1273169/53985171-f5169900-40e8-11e9-820e-cceb14fe8cad.png">

**Comment by KDSBrowne** [comment]
Etherpad hogs all events that happen within the iframe, because of this the event handler on the window listening for the click to close the dropdown is never fired. If you click anywhere outside of the iframe the dropdown will close.

**Comment by capilkey** [comment]
Would it be the same as a page focus lost? I notice that the menu stays open if you click on another application also.

**Comment by KDSBrowne** [comment]
The listener to close the dropdown is on the `document.window`, so clicking another application wont trigger it either.

**Comment by capilkey** [comment]
Is there no way to detect when the page loses focus though? I swear I've seen this done in other websites.

**Comment by jfsiebel** [comment]
Maybe with https://developer.mozilla.org/en-US/docs/Web/API/Page_Visibility_API?

**Comment by lfzawacki** [comment]
> Maybe with https://developer.mozilla.org/en-US/docs/Web/API/Page_Visibility_API?

In this case you might look into the focus detection and not visibility, because the window can still be visible even if it has lost focus. For example, the code we use to [detect visibility of the window in html5](https://github.com/bigbluebutton/bigbluebutton/blob/master/bigbluebutton-html5/imports/utils/visibilityEvent.js) will still return true for a window without focus or partially hidden by other windows.

**Comment by JustinMogel** [comment]
Tested this on 2.3-alpha-8 with Fifrefox 87.0 on Windows and did not encounter this bug.
The dropdown menu closes when clicking on shared notes
