### ISSUE TITLE
iOS webcam list not available 

### ISSUE THREAD

**Issue by KDSBrowne** [bigbluebutton/bigbluebutton#6947]
Webcams not detected in iOS, tested on version 12.1.4.  It seems to work using iOS 12.2 (beta)

![ios-no-cam](https://user-images.githubusercontent.com/22058534/53991582-f223a480-40f8-11e9-9f7d-315171116ddf.jpg)

https://github.com/bigbluebutton/bigbluebutton/issues/6590

**Comment by ffdixon** [comment]
On my iPhone 8, I'm running the iOS 12.2 beta and confirm that its working for me.

**Comment by gustavotrott** [comment]
The problem is in getUserMedia constraints:
`
{video: {width: {max: 320}, height: {max: 240}, deviceId: {exact: "1CC4CF8B254A418C3B4FF819B27FA368E5B750D9"}}}`

BBB is setting the resolution to a low value like 320x240. There is an issue where iOS cannot give this resolution: https://bugs.webkit.org/show_bug.cgi?id=176349

If I change to 640x380 it works!
Should I include a condition for ios or we should consider change the default resolution?

**Comment by prlanzarin** [comment]
Try changing the height/width constraints to `ideal` instead of `max` in `settings.yml`, keeping 320x240, and say what your results were. I can't reproduce this problem with my mac here (probably because of its Safari version), so any help is welcome. 

We won't change the default resolution for now, so we're going to have to find a workaround.

**Comment by gustavotrott** [comment]
I tried using `ideal` but received the same error: `Error: Invalid constraint`

For me the problem occurs only in ios, in my macOs is working with 320x240.

@prlanzarin , what about change the constraint manually only for ios before the `getUserMedia`?
```
constraints.video.width = { max: 640 };
constraints.video.height = { max: 480 };
```

It's ok or we should avoid this resolution even for ios?

**Comment by prlanzarin** [comment]
That workaround will suffice for now.
