### ISSUE TITLE
Unable to export Shared Notes

### ISSUE THREAD

**Issue by ffdixon** [bigbluebutton/bigbluebutton#6950]
When trying to export shared notes on demo and test, the server is returning a 401 authorization required error

![image](https://user-images.githubusercontent.com/290351/54002588-26a95780-411d-11e9-858b-44a344d81672.png)

**Comment by fcecagno** [comment]
@pedrobmarin can you take a look on this?
I confirmed there was no recent change on https://github.com/bigbluebutton/bigbluebutton/blob/master/bigbluebutton-html5/imports/ui/components/note/service.js, and the nginx config is identical to bbb-webrtc-sfu.

**Comment by pedrobmarin** [comment]
Hmm, I see. I'm afraid we will have to open this request for now since we are not storing the user session token inside Etherpad. It would probably be easy to do it and then we could just sign Etherpad built-in calls with the token and all be authenticated in nginx but I rather wait to do something like this after we update our branch with Etherpad version 1.7.5+

For now we could simply add a `$` in nginx location regex:
```
location ~ "^\/pad\/p\/(\w+)$" {
    rewrite                /pad/(.*) /$1 break;
    rewrite                ^/pad$ /pad/ permanent;
    proxy_pass             http://localhost:9001;
    proxy_pass_header      Server;
    proxy_redirect         / /pad;
    proxy_set_header       Host $host;
    proxy_buffering off;

    auth_request /bigbluebutton/connection/checkAuthorization;
    auth_request_set $auth_status $upstream_status;
}
```

**Comment by pedrobmarin** [comment]
I believe this was resolved with nginx modifications

**Comment by ffdixon** [comment]
Resolved.
