### ISSUE TITLE
Adjustments to Breakouts experience

### ISSUE THREAD

**Issue by antobinary** [bigbluebutton/bigbluebutton#7026]
1) Adjust the calculation of how many users are in the breakouts. In this case we were 6 but it displayed 18 
![Screenshot from 2019-03-14 13-26-19](https://user-images.githubusercontent.com/6312397/54379058-0c143880-465f-11e9-9947-2642bc0bd12a.png)

2) Rename 'Return audio' to 'Leave audio in <room name>'
![Screenshot from 2019-03-14 13-34-16](https://user-images.githubusercontent.com/6312397/54379108-21896280-465f-11e9-876e-e48d145b0735.png)

**Comment by ffdixon** [comment]
I just held a session on the latest build and the room count was 1, but there were 8 users in the breakout rooms.  @Tainan404 can you test the latest build and see if you can reproduce.

**Comment by capilkey** [comment]
The counts for the number of users in a breakout room is still incorrect.

**Comment by capilkey** [comment]
Did a test on the 396 build (last week's build). There were 7 people total in the main meeting. There were two breakout rooms. The first breakout room was listed as having 7 people. The second breakout room was listed as having 4 people. The actual counts in each room were 4 and 1 respectively.

The breakout rooms were opened with the option of self-assigning a room, but that shouldn't have had any effect.

**Comment by capilkey** [comment]
The breakout room collection that is being used to generate the count for the number of users in a breakout room is completely useless for what it's being used for in the panel. The BreakoutRoom.users is an array of every joinURL created for that specific breakout room and which users it applies to. There are tons of cases where a breakout room join URL is created, but the meeting is never actually joined. The base where people are self-assigning a room is particularly bad because it generates a URL when the select box changes instead of when they click to join the room.
