### ISSUE TITLE
Poll results are not displayed when screen sharing is active

### ISSUE THREAD

**Issue by ffdixon** [bigbluebutton/bigbluebutton#7058]
This is for a future update.  

Currently, the poll results are only rendered on the presentation area, which means if the presenter is sharing their screen, viewers can not see the results.

Alternatives would be to display the polling results in the chat or in a new window.

**Comment by nchauvat** [comment]
I have the same issue. My slides are in HTML with https://revealjs.com and I have to share my screen to display them, which means that if I try to poll viewers about what is displayed, the results of the poll are not shown unless I stop sharing my screen. The same happens when I write notes or code as I teach and want to poll viewers about their understanding/the best option. This keeps me switching on and off the screen sharing.

**Comment by ownhardy** [comment]
+1 for this very useful improvement. 
This would make polls much more easily usable when showing a slide show on a shared screen.

**Comment by matiasilva** [comment]
@ownhardy I've seen you do this on a few other issues, here's an extract from https://github.com/dear-github/dear-github

> Issues often accumulate content-less “+1” comments which serve only to spam the maintainers and any others subscribed to the issue.

Instead, please use the "thumbs up" reaction on the first comment. Thanks for your comments!

**Comment by ffdixon** [comment]
In BigBlueButton 2.3 we'll be showing the poll results in the chat as well (we're doing this specifically for the case when your sharing your screen and you want everyone to see the results of the poll).

**Comment by antobinary** [comment]
In BBB 2.3.x the poll results are published to the public chat too (by default)

![Screenshot from 2021-04-15 11-02-06](https://user-images.githubusercontent.com/6312397/114891647-0eb36000-9dda-11eb-9024-609e89012c0f.png)
