### ISSUE TITLE
Add server option to enable moderator to unmute viewers

### ISSUE THREAD

**Issue by ffdixon** [bigbluebutton/bigbluebutton#7092]
Adding this option to the server will enabled BigBlueButton 2.2-beta to have same functionality in this regard as 2.0.

This option will be `false` by default, but can be set to `true` by the administrator.

**Comment by capilkey** [comment]
This is more involved than just a server option. The clients and the server need to be in-sync with what the client is allowed to show to the user. It could be done with a configuration option in each client and in akka-apps, but that will open up failure points if someone changes one setting and not the others. The only foolproof way is to set it in akka-apps and then have messages to request whether moderators can unmute and then request it from each of the client types.

**Comment by priyobanget** [comment]
Hi @ffdixon 
I've recently updated the bbb-html5 using this command in my Ubuntu:
> apt-get install bbb-html5
Where can i find the option to enable moderator to unmute viewers?

**Comment by priyobanget** [comment]
I am using  BigBlueButton 2.2-beta

**Comment by ffdixon** [comment]
This is an open issue and not yet implemented.  When you see a pull request against this issue, you'll know we're getting close to implementing it.

**Comment by mikhailnov** [comment]
This is a very big problem for us, our workflow involves regular manual muting and unmuting users, and I 've come here because I found out that starting with v2.2 moderators and authed users can mute, but cannot unmute users.

Also, our moderators (speakers) have reported that they get kicked away from webinar room, I have studied logs and see e.g.
```
2736097","userId":"w_os9g9xzqgba0"}},"core":{"header":{"name":"DisconnectClientSysMsg","meetingId":"c97b6fd5d1c69f4eec70d3577c5f11e4c5c99eb0-1554042736097"},"body":{"meetingId":"c97b6fd5d1c69f4eec70d3577c5f11e4c5c99eb0-1554042736097","userId":"w_os9g9xzqgba0","ejectedBy":"SYSTEM","reason":"No permission to unmute user."}}}
```
![Снимок экрана_2019-03-31_19-00-30](https://user-images.githubusercontent.com/15802528/55294597-b8e70780-540c-11e9-96e0-e2a2fd392d3d.png)

Can you please point to commit which made this change/regression? It has really broken many things.

**Comment by mikhailnov** [comment]
@capilkey Do I understand corrctly, that commit https://github.com/bigbluebutton/bigbluebutton/commit/860fd2a5df15410566de3af5d9809e73c5dc59b7 makes it impossible to mute all users and then unmute some of them without unmuting all others?!
`// We no longer want to unmute users when meeting mute is turned off`
This also severely breaks worksflow, because we often mute all users when there is a lot of noise and then unmute one by one when they need to talk.

P.S. I am talking about online classes with children, moderators do a lot of work disabling and enabling microphones when needed.

**Comment by ffdixon** [comment]
@mikhailnov We just released BigBlueButton 2.2-beta3, see

 https://github.com/bigbluebutton/bigbluebutton/releases/tag/2.2-beta-3

If you are running an older version, can you upgrade to this version.  

> Also, our moderators (speakers) have reported that they get kicked away from webinar room, I have studied logs and see e.g.

We'll take a closer look tomorrow.

**Comment by capilkey** [comment]
@mikhailnov There's more to it than just that one commit in akka-apps. As I mentioned in my first comment, the client and server need to be in sync with what permissions a user has. We're not going to remove the protections completely so in order to make it configurable there's a decent amount of work to make sure that all parts are on the same page and an administrator can't break things. 

For the ejection, it would be useful to know the client build number that you're using and which button or element was selected right before the ejection. I cleaned up some potential ejection edge cases a couple of weeks ago, but there might still be more out there.

**Comment by mikhailnov** [comment]
>  it would be useful to know the client build number that you're using

Seems that ejections happened in 2.2, 2.2-beta2 and now 2.2-beta3. Unfortunately, I can't reproduce them, when I tried to reproduce, the button for unmuting was not clickable. May be in thee days between 2.2 and 2.2-beta2 (before https://github.com/bigbluebutton/bigbluebutton/commit/860fd2a5df15410566de3af5d9809e73c5dc59b7#diff-9450bd07f3918665fe9fecd72609b341) that button was clickable, but I did not know about the problem. The last ejection was reported with 2.2-beta3:

```
$ dpkg -l | grep ^ii | awk '{print $2, $3}' | grep bbb-
bbb-apps 1:2.2.0-19
bbb-apps-akka 2.2.0-41
bbb-apps-screenshare 1:2.2.0-19
bbb-apps-sip 1:2.2.0-10
bbb-apps-video 1:2.2.0-18
bbb-apps-video-broadcast 1:2.2.0-8
bbb-client 1:2.2.0-29
bbb-config 1:2.2.0-62
bbb-etherpad 1:2.2.0-34
bbb-freeswitch-core 2:2.2.0-27
bbb-freeswitch-sounds 1:1.6.7-9
bbb-fsesl-akka 2.2.0-26
bbb-html5 1:2.2.0-349
bbb-mkclean 1:0.8.7-4
bbb-playback-presentation 1:2.2.0-17
bbb-record-core 1:2.2.0-29
bbb-red5 1:1.0.10-16
bbb-swftools 1:0.9.2-2
bbb-transcode-akka 2.2.0-7
bbb-web 1:2.2.0-77
bbb-webrtc-sfu 1:2.2.0-48
```

@ffdixon I'm using beta3 already

**Comment by antobinary** [comment]
Implemented in #7234

**Comment by mikhailnov** [comment]
You probably meant https://github.com/bigbluebutton/bigbluebutton/pull/7270, not #7234 
Did I understand correctly that it can be controlled only via API and cannot be enbaled in config globally?

**Comment by capilkey** [comment]
There's a property in bigbluebutton.properties that can be set to configure it globally. https://github.com/bigbluebutton/bigbluebutton/pull/7270/files#diff-ac0049d8c38674d6bc36e8ae927ec926R196.

Once beta7 is out you might need to add it to bigbluebutton.properties manually. I'm not 100% sure how the preservation of bigbluebutton.properties works on an update.

**Comment by mikhailnov** [comment]
Thanks for explaining! I missed `bigbluebutton.properties` when looked through the changes in that pull request.

**Comment by mikhailnov** [comment]
It works, thank you for fixing it!

**Comment by eftodi** [comment]
just do this: 
sudo  vi /usr/share/bbb-web/WEB-INF/classes/bigbluebutton.properties

# Unmute users
# Gives moderators permisson to unmute other users
allowModsToUnmuteUsers=false

change to true
