### ISSUE TITLE
Chat improvements

### ISSUE THREAD

**Issue by vitormateusalmeida** [bigbluebutton/bigbluebutton#7110]
A suggestion to be implemented

- **In the chat, a user can mark another**
- **The marked user receive a notification**

>![image](https://user-images.githubusercontent.com/9675166/55004070-4d3e0e00-4fb8-11e9-8f7c-7c5da4b85d2b.png)

- **Can be open a private chat with marked user when click above his name**

>![image](https://user-images.githubusercontent.com/9675166/55003380-174c5a00-4fb7-11e9-9c7a-b6342d3866e8.png)

- **Can respond a message**

>![image](https://user-images.githubusercontent.com/9675166/55005548-f2f27c80-4fba-11e9-8c0a-fbb6102695e9.png)

>![image](https://user-images.githubusercontent.com/9675166/55006363-621ca080-4fbc-11e9-96fe-a04e8d79763b.png)

**Comment by capilkey** [comment]
Replies would be tricky because there's no way to reference another message as they don't have uids. We're going to have to add uids at some point so we can do edits/deletions, but that's probably not appropriate for this release.

I think the simplest thing would be to show the prompt with potential matches to the "@*" pattern and then highlight messages that contain your name. That would probably satisfy most of the big desire and then the fancy stuff could be added later.

**Comment by cod3r0k** [comment]
Hi, is it solve yet?
