### ISSUE TITLE
The create breakout room modal is missing some users

### ISSUE THREAD

**Issue by antobinary** [bigbluebutton/bigbluebutton#7292]
The list of `Not assigned` users for breakouts does not update with new [late] joiners. The counter sometimes** is adjusted
![Screenshot from 2019-04-23 15-02-07](https://user-images.githubusercontent.com/6312397/56608452-c9883900-65d8-11e9-9714-ce29933e6eb8.png)

**Comment by Tainan404** [comment]
That's by design, I followed the flash client behavior when implemented it.

![Peek 2019-04-23 16-29](https://user-images.githubusercontent.com/15806883/56610251-618c1f80-65e5-11e9-8997-9c98d820280d.gif)

**Comment by capilkey** [comment]
The Flash client list not updating is a bug not a feature.

**Comment by akiwenziec** [comment]
The list of "not assigned" users in the breakout room control panel does not populate with the correct current users connected - does not **only** affect late joins to the session.

**Comment by capilkey** [comment]
It also did pick up some late joiners when we were trying it out. When testing we also opened and closed the breakout room creation modal a couple of times to see if the list would change and it would not.

Every user in the meeting was a viewer except for the one moderator/presenter.

There was also no visible connection between the groups of users who appeared in the "Not assigned" list and who did not. There was a mix of listen-only, full audio, and no audio in both groups.

**Comment by akiwenziec** [comment]
In the Flash client when a user joins late they will appear in the "not assigned" list when the moderator "closes" the breakout room create and re-initiates the "create breakout room" - see video below:

https://www.youtube.com/watch?v=tVi_0pApQD4&feature=youtu.be

This is not the case in the HTML5 client - the "not assigned" list does not update if the moderator "cancels/closes" the breakout room create modal and restarts the create process **after** the late joins have connected for several minutes.

**Comment by capilkey** [comment]
I took a look at the filtering of the breakout room users and I think this issue has the same core problem as the breakout room user count issue in #7026. There's currently no collection that has an accurate view of the users in the breakout rooms. In both the create breakout room modal and the breakout room panel, they try to use other information to guess at who is in a breakout room. The create modal filters externalUserIds that are online (false positives) and the breakout room panel counts the number of join URLs that have been created (doesn't mean they're still there or ever joined). In both cases they fail because they're trying to draw conclusions from bad data.

There's a specific message sent to moderators that includes an up to date listing of all the users in the breakout rooms (UpdateBreakoutUsersEvtMsg) that could be used to fill a collection. The other way to get accurate users would be to actually find the users who are in the main meeting's breakout rooms rather than doing open searches. I'm fairly certain there's a property on the breakout room that associates it back to the parent meeting and the search could be done based on that.

**Comment by capilkey** [comment]
Another thing I feel like needs to be addressed is the block of code that does the filtering the create breakout room modal. It's a mess. If someone wanted to extend that out and add more filtering it would be a disaster (#7186). 

```js
const getBreakoutUser = user => Users.find({
  extId: new RegExp(`^${user.userId}`),
  connectionStatus: 'online',
}).fetch();

const currentBreakoutUsers = userArray => userArray.length === 1;

const filterBreakoutUsers = filter => users => users.filter(filter);

const filterUsersNotAssigned = filterBreakoutUsers(currentBreakoutUsers);

const mapUsersToNotAssined = mapFunction => users => users.map(mapFunction);

const flatUsersArray = usersArray => usersArray.reduce((acc, users) => [...acc, ...users], []);

/*
  The concept of pipe is simple
  it combines n functions. It’s a pipe flowing left-to-right,
  calling each function with the output of the last one.
*/
const getUsersNotAssigned = fp.pipe(
  mapUsersToNotAssined(getBreakoutUser),
  filterUsersNotAssigned,
  flatUsersArray,
)
```
https://github.com/bigbluebutton/bigbluebutton/blob/master/bigbluebutton-html5/imports/ui/components/actions-bar/service.js#L16-L40
