### ISSUE TITLE
Share screen html5

### ISSUE THREAD

**Issue by mjencabh** [bigbluebutton/bigbluebutton#7434]
using internal ip I get at fail sound everytime i try to hit/activate share screen.
Im using both firefox and chrome and its the same.
Everything seems to be fine when running bbb-conf --check .

**Comment by ffdixon** [comment]
Are you able to share your screen with https://demo.bigbluebutton.org/?

**Comment by mjencabh** [comment]
Yes i am- i dont get an promt with the posibility to accept share on my server but i do get one on yours.

**Comment by ffdixon** [comment]
Is your server configured with SSL certificate?  The browsers will not allow screen sharing without a SSL certificate and the client loaded through HTTPS

**Comment by mjencabh** [comment]
Ahh its not on SSL yet because its on internal ip 10.0.0.10

**Comment by ffdixon** [comment]
For the browsers: no SSL certificate, no screen share.  The fix is to assign your server a hostname, obtain an SSL certificate for the hostname, and configure your BigBlueButton server to use the certificate.  See

 
   http://docs.bigbluebutton.org/2.2/install.html#configure-ssl-on-your-bigbluebutton-server

**Comment by mjencabh** [comment]
Yes im waiting for our organisation to route. just thought that I could test it without also..
Thx for clarifying this!

**Comment by mjencabh** [comment]
Have same isue now with SSL opend op new isue https://github.com/bigbluebutton/bigbluebutton/issues/7572
