### ISSUE TITLE
Guest promotion

### ISSUE THREAD

**Issue by pedrobmarin** [bigbluebutton/bigbluebutton#7460]
When an user is set as guest but the policy is ALWAYS_ACCEPT he joins and the moderator has the option to promote him but akka-apps ignores the message. This gives a broken feeling in the client side

**Comment by pedrobmarin** [comment]
I'm not completely sure how `guest` work on bigbluebutton. Originally it was designed to be a role for users that are not authenticated at the external application that manages bbb api calls. So, in greenlight, I would expect that's a role for someone that doesn't necessarily has a greenlight account.
The way I see it this is a feature that lacks support at the html5 client right now

**Comment by antobinary** [comment]
In #9617 we no longer provide the option to promote a guest. If the need arises in the future, we can implement it. Until then just removing the menu suffices. I am not really aware of a use case where an external user (invited via link) would require moderator permissions. Note that they can still be given presenter status.

**Comment by n-st** [comment]
@antobinary Note that the "guest" role is also applied to logged-in (Greenlight) users when the room is set to "require moderator confirmation before joining". At least for those users, it should be possible to promote them to moderators (since they do not gain moderator privileges even if they are a co-owner of the room). The corresponding issue (#9523) was closed in favour of this one…

**Comment by pedrobmarin** [comment]
I think it's fair to keep this issue opened since it gathers other 3 requests about the review of this feature

**Comment by nicolopez77** [comment]
> @antobinary Note that the "guest" role is also applied to logged-in (Greenlight) users when the room is set to "require moderator confirmation before joining". At least for those users, it should be possible to promote them to moderators (since they do not gain moderator privileges even if they are a co-owner of the room). The corresponding issue (#9523) was closed in favour of this one…

In my opinion there are two reasons:
1) It's quite confusing for the users that they can promote any other user if the room does not require approval, but thy can't if the room requires approval. So this behavior would not be related to "guest users", but to the moderator's approval.
2) What's the reason for NOT letting a guest user to be a moderator? Why should you restrict the tool in that way? I have users complaining because of that. There are teachers or presenters that have a registered user, and some times they have someone to help with the moderation (to close other's mics). They were doing that quite fin, and then for security reasons they started to use the "require approval" feature, and now they lose the ability to have a guest moderator.

**Comment by victorcoya** [comment]
I fully agree with nicolopez77, it's a nonsense to restrict users and prevent them for promoting a guest, as they already do when the room does not require approval

**Comment by trs80** [comment]
This also applies (IIRC, I need to test), if the user in greenlight has been given shared control of the room, and so should have moderator privileges when joining, instead they come in as guests who can't be promoted. The use case for this was to have a moderated room, but someone else helping approve the guests while the owner runs the presentation.

**Comment by nicolopez77** [comment]
Feature request created #9644 . Please vote :)
