### ISSUE TITLE
Chat username offset when user offline

### ISSUE THREAD

**Issue by antobinary** [bigbluebutton/bigbluebutton#7478]
![Screenshot from 2019-05-21 14-23-12](https://user-images.githubusercontent.com/6312397/58120860-152c0380-7bd4-11e9-8370-cd9aedc7fc44.png)

**Comment by tylercopeland** [comment]
Using the browser's inspector, I believe this is happening because of the negative top and bottom margin (as seen in the screenshot below). 

![Screen Shot 2019-05-21 at 2 52 26 PM](https://user-images.githubusercontent.com/1273169/58122886-97b6c200-7bd8-11e9-8715-8949ae581541.png)

Once it's removed, the interface goes back to it's original form. 

![Screen Shot 2019-05-21 at 2 59 40 PM](https://user-images.githubusercontent.com/1273169/58123110-19a6eb00-7bd9-11e9-9c1c-fb3b912739ec.png)
