### ISSUE TITLE
Presenter indicator problem in Safari

### ISSUE THREAD

**Issue by jfsiebel** [bigbluebutton/bigbluebutton#7514]
The presenter indicator on user list is broken in Safari 12.1 browser.

![image](https://user-images.githubusercontent.com/2110278/58433128-105fc780-808c-11e9-82ce-ea82c1ce6389.png)

**Comment by GhaziTriki** [comment]
There is a similar issue with Opera. Is Opera officially supported?

**Comment by daminebenz** [comment]
I confirm, it's happening in opera PC or mobile also
![image](https://user-images.githubusercontent.com/33185490/63949446-cacae600-ca50-11e9-8088-d1c48f6403d1.png)

**Comment by tylercopeland** [comment]
@jfsiebel @GhaziTriki @daminebenq it seems like this is an issue. It came to my attention seeing this picture on twitter. -> https://twitter.com/mhstrinidad/status/1242227859428495361/photo/1

I believe the issue is being caused by the default width and height of "0" on the :before item containing the presenter indicator. If we set the width and height to 16px by 16px it appears correctly in Safari.
 
![Screen Shot 2020-03-23 at 11 21 17 PM](https://user-images.githubusercontent.com/1273169/77384995-41b52c80-6d5d-11ea-8b27-54e2cd3ff39c.png)
