### ISSUE TITLE
Bigblubutton 2.2 camera High definition

### ISSUE THREAD

**Issue by datphamict** [bigbluebutton/bigbluebutton#7613]
Dear all

In file settings.yml has config such as:
  __cameraProfiles:
    ....
      - id: hd
        name: High definition
        default: false
        constraints:
          width:
            max: 1280
          height:
           max: 960_

But i access to http://test.bigbluebutton.org and share camera:

![ảnh](https://user-images.githubusercontent.com/38518509/59416008-c5191900-8dee-11e9-900e-16109540bf11.png)

Why can't i open camera with High definition ?

**Comment by ffdixon** [comment]
Hmm ... not sure what you are asking -- are you saying you can't select 'High quality' or are you saying if you select 'High quality' your camera does not share?

**Comment by capilkey** [comment]
There's four potential profiles in settings.yml. The largest one is "High Definition" and is 1280x960 as seen in the original post.

@datphamict The reason that you don't see "High Definition" is because your device didn't return back a stream matching the requested dimensions. You can use the Quick Scan function on this page, https://webrtchacks.github.io/WebRTC-Camera-Resolution/, to get a second opinion on which profiles are supported.

**Comment by datphamict** [comment]
Thank you capilkey.
