### ISSUE TITLE
Hardware acceleration kurento

### ISSUE THREAD

**Issue by Pionegr** [bigbluebutton/bigbluebutton#7658]
Hi! 
When using webcams, the CPU load is very high. As I understand it, kurento is using a gstreamer that has hardware acceleration via gstreamer-vaapi. Will using a GPU reduce the load on the CPU? 
Thanks!

**Comment by prlanzarin** [comment]
I don't think it'll alleaviate the current high CPU usage we've been seeing. The `vaapi` plugins are useful when we're talking about encoding/decoding, and we do none of that currently (since we operate as SFU and there's only repayloading/decryption/encryption going on).

I've been profiling the media server to find bottlenecks and try to optimize its CPU usage (which I agree is indeed too high for a packet router approach). It'll be a tiresome work, so I can't promise anything nor a date. If I'm able to optimize any of it, it'll likely be through an incremental approach. We'll try to keep the community informed on that effort, though.

**Comment by prlanzarin** [comment]
Closing this as a non-issue. If something comes to fruition regarding CPU improvements I'll open a proper one to track it.
