### ISSUE TITLE
Improve take ownership button

### ISSUE THREAD

**Issue by jfsiebel** [bigbluebutton/bigbluebutton#7671]
![cc-take-ownership](https://user-images.githubusercontent.com/2110278/60038479-d5e94a80-968a-11e9-98c2-169d4b0c1f2f.png)

Maybe change to something more like this:

![image](https://user-images.githubusercontent.com/2110278/60038619-3bd5d200-968b-11e9-80fd-1409ed5ce4b6.png)

Any suggestion @tylercopeland?

**Comment by tylercopeland** [comment]
I think the current icon is valid. As someone who is looking to take ownership, you are looking to begin writing (hence the pencil). The part that looks off is the icon size and the alignment with the icon below. 

There are two options we can go with. 

1) Change the icon to a button (as recommended above). 

or 

2) Update the icon size (16px by 16px) and align the icon so that it's side by side. 

As I'm writing this, I'm assuming aligning the icons is complex since the export icon is coming from Etherpad. Therefore, my recommendation is to use a button. Thoughts @antobinary?

**Comment by antobinary** [comment]
I am leaning towards proceeding with Option 1 as outlined by @tylercopeland above. I'd also add some text to the label, not just the icon. Something like
:pen: `Take over`

Or just text
`Take over`

But to maintain the consistency with the `Start Dictation` button in other contexts
Alternatives to `Take over` would be
 -  `Input captions` with tooltip [You will be assigned as the owner of <locale> captions]
 -  ...  

We also agreed to try to keep the capitalization for the first letter of the phrase only so I'd recommend tweaking the `Start Dictation` to be `Start dictation` too.

**Comment by tylercopeland** [comment]
![Screenshot from 2019-06-26 17-14-30](https://user-images.githubusercontent.com/1273169/60290159-214b6500-98e6-11e9-9c56-ef15dcaadbdd.png)

Overall I think the implementation looks great. Having a button clearly indicates to the user where to click to take ownership of the [English] captions.

One thought I had is when and why do we use tooltips in a button scenario? Typically in our interface, we only introduce tooltips for icon buttons and this is because the icon itself might not be descriptive enough. For buttons to be effective, the text within the button should be clear enough to not need a tooltip. If we choose to go down the path of adding tooltips within our buttons, this means it's a new principle and opens the door of potentially having an interface full of tooltips for every interaction that a user takes. We had this before in the earlier version of the HTML5 client and it wasn't a pleasant experience. 

Therefore, I would recommend we remove the tooltip and update the text in the button to read "Take over captions".  As a user reads from left to right it should read "English     [Take over captions]".

**Comment by capilkey** [comment]
"Take over" or "Take over captions" doesn't really explain what will actually happen. We know what it does because we've used it. A tooltip helps to explain more information for people who are unfamiliar.

**Comment by tylercopeland** [comment]
We can continue to iterate on the text for the button [Take Ownership] is another option. The user is already in the context of "English Closed Captions" and they are about to take ownership of it. 

This is also a scenario where after you go through it once, you've become instantly familiar with the experience.

If we do decide to go with the tooltip approach we need to understand why we are adding a tooltip to this one button scenario and make sure it's consistency throughout the interface.

**Comment by diegobenetti** [comment]
Indeed, the regular behavior of Button component is to receive an icon (and tooltip text) or a label text. This button would be the first one in the application to have both label text and tooltip.

In order to keep this pattern we could use @tylercopeland suggestion to remove the tooltip and change the label to "Take over captions" or maybe only "Take over". If the user is seeing this button it is because he has already clicked in "CC [language]", so the user will know that he is going to take over the closed captions if he clicks the button.

**Comment by capilkey** [comment]
You assume so much to get a happy, easy scenario. The words "Take over" are ambiguous you can take over so many different things. The short text could be taking over control of all captions, or one caption. What rights do you actually get when you "take over"? In this case it's to "Take over control of editing the specific caption locale", but there's no way to understand that from three words.

**Comment by antobinary** [comment]
Looks like either way we need a way to provide more information.
Option A: Keep things as they are implemented by Diego's #7691  (this is button+label+tooltip)
Option B: Retract back to using the pencil icon with no label but with the same lengthy tooltip (this is button+icon+tooltip)
Option C: 
Label "Take over caption", no tooltip on the button.
Icon :information_source: to the right of the button with tooltip "You will be assigned as the owner of the <locale> caption"

My pick would be Option A, resulting in a precedent on the client where we have both a label and a tooltip. I think this will be one of few exceptions of the case. I have been tempted to include a tooltip for other complex functionalities like in the guest management context (abstaining from concretizing to avoid off-topics) but will only do it in case of dire need to provide more context (like here).

Are there options not mentioned or anything left out?

**Comment by tylercopeland** [comment]
I think there are assumptions on both sides. To get a real answer would be to conduct proper usability testing on this experience. 

@antobinary I'm okay with this option since it's already developed. But as a group, we need to understand why and when we are using tooltips. Otherwise, we get scenarios as we see below and I'd like to avoid having meaningless tooltips within the interface. 

![Screen Shot 2019-06-27 at 5 09 35 PM](https://user-images.githubusercontent.com/1273169/60301068-73988000-98fe-11e9-9aef-118f171263e8.png)

**Comment by capilkey** [comment]
That's a left over from when the recording toggle was just the circle icon, not an intentional choice that I'm aware of.
