### ISSUE TITLE
why not h265?

### ISSUE THREAD

**Issue by zsinba** [bigbluebutton/bigbluebutton#7677]
In the configuration file, I see that the configuration parameters are all h264 configuration parameters. Okay? Is that because we only use H264?Do we support H265 or do we intend to support it? If not, why?
Thank you for your reply.

**Comment by ffdixon** [comment]
> In the configuration file, I see that the configuration parameters are all h264 configuration parameters. 

What version of BigBlueButton are you looking at?  We recommend you use BigBlueButton 2.2-beta for the best support of mobile devices.

In BigBlueButton 2.2-beta, we choose VP8 as the default because it's the common denominator between Chrome and FireFox on desktop and laptop, Chrome on Chromebook and Android devices (6.0+), and Safari Mobile (iOS 12.2+).  All these environment support VP8.

The problem you run into using h265 (or h264) is the codec is patent encumbered and requires a license.  There are many Android phone manufactures that have not licensed this codec from MPEG LA and, as such, only support VP8.

Based on the above, we would recommend updating to BigBlueButton 2.2-beta and leave the video settings as default for VP8.

**Comment by zsinba** [comment]
I'm using version 2.2.I asked this question because when I was playing video (1280*1920), I had an awkward experience.
I'm using the Flash version, but I can't use the Html5 version yet because I don't have multi-camera support.
In the configuration of profiles. XML, where can I find the meaning of these parameters?


![image](https://user-images.githubusercontent.com/890157/60103368-1089da80-9792-11e9-824d-28c52017f378.png)

h264Level
h264Profile
Where can I find the Settings for these two parameters?

**Comment by zsinba** [comment]
Can I upgrade to H265 by myself?

**Comment by prlanzarin** [comment]
I'm almost certain Flash doesn't support H.265, so no, you can't.
That's the situation for WebRTC (the HTML5 client) as well.
