### ISSUE TITLE
export NODE_EXTRA_CA_CERTS 

### ISSUE THREAD

**Issue by RasimKalimullin** [bigbluebutton/bigbluebutton#7690]
Hello! 
I use a corporate certification authority. But bbb-html5 does not trust the certificate until I add
export NODE_EXTRA_CA_CERTS = / usr / local / share / ca-certificates / ca.crt
to file
/usr/share/meteor/bundle/systemd_start.sh
So everything works, but after the upgrade, I have to do it again. 
Is there another way?
Thanks!

**Comment by capilkey** [comment]
Are you sure that was all that was needed to get a self-signed certificate working? I haven't tried to do this since we split bbb-web into its own process, but there used to be a need to modify the Java cert store also.

You could also just set that environment variable anywhere else that isn't managed by a package. If you google for "set environment variable" you'll find a few example about how to set it in a more permanent location.

**Comment by Pionegr** [comment]
This is not a self-signed certificate.It is a certificate signed by a corporate CA. The root certificate is located on the path  / usr / local / share / ca-certificates / ca.crt. It is valid for the OS, but not for nodejs

**Comment by capilkey** [comment]
The same issues apply to both self-signed and certs and ones from an internal CA.

**Comment by ffdixon** [comment]
Is this a documentation update or code update?

**Comment by Pionegr** [comment]
I add 
export NODE_EXTRA_CA_CERTS=/usr/local/share/ca-certificates/ca.crt
to /etc/profile
Result:
root@bbb:~# env|grep NODE_EXTRA_CA_CERTS
NODE_EXTRA_CA_CERTS=/usr/local/share/ca-certificates/ca.crt
But I see a white screen instead of a presentation.Editing systemd_start.sh solves the problem
