### ISSUE TITLE
BigBlueButton 2.2-beta-12 has a bug, Flash WebRTC screensharing  can not be share 

### ISSUE THREAD

**Issue by caojincool** [bigbluebutton/bigbluebutton#7704]
![image](https://user-images.githubusercontent.com/466750/60409467-51e91280-9bf6-11e9-8a53-4654d621c802.png)

**Comment by prlanzarin** [comment]
The screenshare RTP-RTMP bridge has been disabled by default since beta 6 and our switch to VP8. Although we should turn off the option in the default Flash config as well to avoid this kind of misunderstanding, it's not supposed to work out of the box anymore.

If you wanna have it working, you'll have to change some configs on bbb-webrtc-sfu (`/usr/local/bigbluebutton/bbb-webrtc-sfu/config/default.yml`) and then restart the component (`sudo systemctl restart bbb-webrtc-sfu`):
  * Change the default content codec to H.264 (`conference-media-specs.codec_video_content: H264`)
  * Set `screenshareEnableFlashRTPBridge` to `true`
  * Set `screenshareKeyframeInterval` to `2`

**Comment by caojincool** [comment]
Thank you very much

**Comment by quoctamld** [comment]
BigBlueButton 2.2.5 has a bug, Flash WebRTC screensharing can not be share
![e0afdc98b31e4940100f](https://user-images.githubusercontent.com/9252421/82518553-d499f980-9b49-11ea-8740-a783c7d365a8.jpg)
Help me!
Thanks!
