### ISSUE TITLE
FireFox - graphic issue when going full screen from small window

### ISSUE THREAD

**Issue by antobinary** [bigbluebutton/bigbluebutton#7842]
The entire section where the action bar typically is, is missing

**Comment by WorldCodeCentral** [comment]
Hello antobinary, do you mean you want the section that is clicked to expand to the full width and height of the browser viewport instead of going fullscreen? The term fullscreen means using the complete screen of the monitor, so all bars should be hidden.

Then again the same thing happens if the browser is not in a small window but maximized. So maybe that's not what you mean?

**Comment by pedrobmarin** [comment]
@antobinary is this still an issue?

**Comment by antobinary** [comment]
Unable to reproduce
