### ISSUE TITLE
Echo in conference

### ISSUE THREAD

**Issue by netlabs** [bigbluebutton/bigbluebutton#7862]
Hello Team,

I am running latest build of BBB. I am facing echo issues while having conference for some users. Not all the time.  Any idea how to prevent this?

**Comment by capilkey** [comment]
The most common reason for echo is someone using speakers instead of earbuds or a headset. There could also be an echo if you have two people in the same room both sharing their mics.

The way to tell would be to look through the users list when it happens and see whose mic is picking up noise and highlighting.

**Comment by netlabs** [comment]
No one is using head set. And people are in different rooms. Is there any tweak that needs to be done?

**Comment by ffdixon** [comment]
Are you able to follow who is causing the echo -- you'll see there headset highlight each time you talk.  If you mute that person, does the echo stop?

**Comment by netlabs** [comment]
Main point is only the person who speaks gets echo on his speaker.

**Comment by ffdixon** [comment]
The moderator can mute any microphone, so if you have two students next to each other, they will cause echo and the Moderator would need to mute them.
