### ISSUE TITLE
Error log on 'stream_cursor'

### ISSUE THREAD

**Issue by vitormateusalmeida** [bigbluebutton/bigbluebutton#7890]
I get this error in second user when presenter disable the multi user option.

![image](https://user-images.githubusercontent.com/9675166/62550839-4f0abe80-b841-11e9-901b-0a5d886e439e.png)

**Comment by capilkey** [comment]
There's two ways to cause this. The cursor sending is throttled so if a person is moving the mouse when they lose access then the client will still send afterwards. The other way that this happens is when the cursor listener is unmounted it sends one last update of (-1, -1) because that forces the cursor off the screen and hides it.

My proposed fix would be to allow updates of negative values through and the server should already have a 5s grace period.
