### ISSUE TITLE
Setting font size 100%

### ISSUE THREAD

**Issue by tylercopeland** [bigbluebutton/bigbluebutton#7938]
![Screen Shot 2019-08-15 at 11 41 32 AM](https://user-images.githubusercontent.com/1273169/63106835-b9161880-bf51-11e9-90f3-9f525e7ba83a.png)

Several iterations ago, we reduce the overall font-size in the client (which looks great). But from a user seeing this for the first time, shouldn't the default font-size read  100% and not 90%?

**Comment by KDSBrowne** [comment]
It was part of the accessibility requirement to display the font-size in `%` vs `px`.
The pixel conversions were taken from the reference provided by the auditor.
http://pxtoem.com

https://github.com/bigbluebutton/bigbluebutton/blob/master/bigbluebutton-html5/imports/ui/components/settings/submenus/application/component.jsx#L157

**Comment by tylercopeland** [comment]
@KDSBrowne I'm totally fine with using a percentage, I just thought that if you set the base size (in our case 14px), that's 100%.

**Comment by KDSBrowne** [comment]
I think we experimented with something like:

`    const pixelPercentage = {
      '12px': '90%',
      '14px': '100%',
      '16px': '110%',
      '18px': '120%',
      '20px': '135%',
    };
`

If i remember correctly, we didn't go forward with these values because when the client would load and display the default at 100%. The experience was strange in that it felt like there was not much control over decreasing the font-size compared to increasing.

**Comment by tylercopeland** [comment]
@KDSBrowne interesting, so there seems to be a lot of thinking that went into this. I'll mark it as closed.
