### ISSUE TITLE
Users are able to join breakout several times in different active tabs

### ISSUE THREAD

**Issue by antobinary** [bigbluebutton/bigbluebutton#8029]

**Comment by capilkey** [comment]
Is this limited to the moderator? If it's on free-join can viewers do it also?

**Comment by daminebenz** [comment]
yes even a viewer can when the breakoutrooms are allowed for a viewer
![zaeaeae](https://user-images.githubusercontent.com/33185490/63959459-952ef880-ca62-11e9-9f41-cf8670657b0a.gif)

**Comment by capilkey** [comment]
Had a feeling it would be possible with viewers also.

I'm not sure how we would fix this because when you join a breakout room you're using a join URL and we don't have the concept of one time joins. If we instead checked to see if anyone with a matching userId was in that breakout room already there would still be a delay because they could just click the link multiple times quickly.
