### ISSUE TITLE
iPhone 6s and 5s turn phone with webcam ON problem

### ISSUE THREAD

**Issue by daminebenz** [bigbluebutton/bigbluebutton#8057]
Hi BBB,

1) open dev22 from your iphone 5s or 6s
2) enable webcam
3) turn the screen from Vertical to Horizontal or from Horizontal from Vertical
4) after some seconds your Webcam stops and you disconnect from Video

**NOTE:** NO CONSOLE LOGS ERRORS
![BLWB4555](https://user-images.githubusercontent.com/33185490/64264222-4f14e180-cf07-11e9-9293-234e01bb1b67.gif)

**Comment by prlanzarin** [comment]
This is an issue, but not ours. It's a mobile Safari problem where rotating the camera to the left pauses the media flow. It's fully reproducible on a P2P WebRTC environment outside of BigBlueButton (e.g.: appr.tc).

The webcam is turned off because the server detects that no media has gone through the server for a specific amount of time and forcefully closes it.

I suggest that this should be closed as a non-issue.

**Comment by daminebenz** [comment]
diplucate in #7680; Closing this issue !
