### ISSUE TITLE
ios youtube video autoplay problem on safari

### ISSUE THREAD

**Issue by daminebenz** [bigbluebutton/bigbluebutton#8091]
hi guys,

to reproduce: 
1) go to dev22 from an iphone or ipad and from your desktop using any browser
2) start from your desktop as Presenter
3) start youtube video sharing
4) the autoplay won't start on the other devices

![image](https://user-images.githubusercontent.com/33185490/64620358-174fe300-d3ba-11e9-9dca-e50596fe4bf4.png)

**Comment by prlanzarin** [comment]
Does it work if you click the play button, though? Autoplay not starting right away is a feasible thing to happen due to browser policies and there's not much we can do about it. However, if you click the play button and it doesn't start or starts out of sync, than this is an issue.

**Comment by daminebenz** [comment]
@prlanzarin yes it works when you tap play
actually, it's just about autoplaying, if you just tap play, it synchronizes with the lecture

**Comment by prlanzarin** [comment]
I'll let others chime in, but I don't think this is an issue then. This is just YouTube behaving properly due to the autoplay policy (media with audio is not allowed to autoplay if not binded to an user action, for lots of reason; and this is triggered by some obscure metrics).

Best we could do is maybe start the stream muted (if possible) to minimize autoplay occurrences. But then again, it's working as intended.

**Comment by daminebenz** [comment]
but it's not because of safari policy, because on mac desktop it works fine !

**Comment by prlanzarin** [comment]
You're admitting that they behave the same, but they don't. macOS's Safari uses an inference engine to decide to block automatic playback, which I don't think iOS does. iOS is also more restrictive due to the premise that the user might be on a cellular network and sucking their data plan isn't a good idea.

As I said, muting before playing it will autoplay the video, but the stream will be muted and the user still have to do an user action to unmute it (as it would have to do to play the stream on autoplay block). It's just a question to decide whether we think muted automatic playback is a good idea or not (there are arguments in favor of this ie I don't like being blasted with music unexpectedly on desktop when I join a meeting; but for the end user the experience will be similar).

**Comment by capilkey** [comment]
It would only be an issue if there was no way for the user to play the video (there's a giant red button), or if after they played the video it didn't synchronize with everyone else (it syncs). The rest of the stuff about whether it plays automatically is out of our hands.
