### ISSUE TITLE
incompatibility with Yandex Browser

### ISSUE THREAD

**Issue by daminebenz** [bigbluebutton/bigbluebutton#8101]
Hi BBB,

**browsers market share in Russia:** [source](https://gs.statcounter.com/browser-market-share/all/russian-federation)
![image](https://user-images.githubusercontent.com/33185490/64704291-74b06680-d484-11e9-9785-942a48f8f719.png)

and after testing BBB on it, sadly we don't support it
![image](https://user-images.githubusercontent.com/33185490/64705309-243a0880-d486-11e9-8243-58d4d12e2ba4.png)

**Comment by ffdixon** [comment]
Can you test with 

  https://test.webrtc.org/

and let us know if Yandex supports WebRTC.

**Comment by daminebenz** [comment]
unfortunately not giving a good test result
![image](https://user-images.githubusercontent.com/33185490/64706983-b93e0100-d488-11e9-97e9-1fff69625fb0.png)

**Comment by ffdixon** [comment]
Yeah, the browser must first support WebRTC before you can use it with BigBlueButton (or any other WebRTC-based application).

**Comment by prlanzarin** [comment]
That's not accurate. I don't know what's up with that test.webrtc output (might be related to connectivity and/or permission and/or a bug with the test tool itself), but Yandex is a Chromium-based browser and WebRTC works just fine with it.

The problem here is that we don't have an Yandex entry in the `minBrowserVersions` config in settings.yml by default, so the browser will only get the legacy client. If that is set up, Yandex will work just fine.
