### ISSUE TITLE
Update avatar in chat to match the users participation in breakout rooms

### ISSUE THREAD

**Issue by ffdixon** [bigbluebutton/bigbluebutton#8121]
Currently, when a student in a breakout room types a chat message, the Users list shows their corresponding breakout room (i.e. `1`), but not the chat message

![image](https://user-images.githubusercontent.com/290351/64932344-41ffc880-d80c-11e9-8092-81250a4d6dd1.png)

The use case is when an instructor has 50+ students and someone from a breakout room is asking for help, they have to first scroll through the Users list to find which breakout room the user is in.

While it may be expensive to keep the avatars for all chat messages sync for all messages , it would be useful to show the breakout room number for just message sent by a user when they were in a breakout room.

**Comment by capilkey** [comment]
> While it may be expensive to keep the avatars for all chat messages sync for all messages , it would be useful to show the breakout room number for just message sent by a user when they were in a breakout room.

That's not a thing that can be done with the current messages. Whether or not a person is in a breakout room isn't included in the information nor does it make sense to include breakout information in a chat message. It would also be weird because if you didn't update the rendered message then the number would appear even after breakout rooms had been closed or the user had left that specific breakout room.

**Comment by ffdixon** [comment]
Got it.  If we can have the messages update with their current breakout room assignment, and not have it be too expensive, that would be best.
