### ISSUE TITLE
Start with presentation minimized

### ISSUE THREAD

**Issue by ffdixon** [bigbluebutton/bigbluebutton#8129]
Some organizations using BigBlueButton want the presentation area to start minimized, regardless if there is a webcam visible or not.

We want to provide parameters for the `join` URL to start the BigBlueButton client in this sate..

Thinking out loud, one way to implement this would be to relax the constraint that the presentation can't be minimized unless there are (at least) one webcam displayed.  In other words, add two parameters to the `join` URL that triggers the following behaviour

  1. Relax the constraint and allow the presentation to be minimized without a webcam visible
  1. Start with the presentation minimized

**Comment by capilkey** [comment]
We already have a property for "autoSwapLayout" which will automatically minimize the presentation. We also have the minimize button on the top-right of the presentation area to hide the presentation. The restriction is that both only kick in when there's at least one webcam. I think removing the webcam check from both places would solve it without needing to add any new properties.

**Comment by basisbit** [comment]
@capilkey this change broke using `autoSwapLayout: true` and `hidePresentation: false` when a default presentation file is set, because now the presentation is always hidden when a user joins. Shouldn't autoSwapLayout only swap to video-only layout when there is no presentation to be shown because one of a)`hidePresentation: true` or b) no default presentation and moderator did not upload a presentation yet nor start screen sharing / youtube or c) mod uploaded a presentation and then later on deleted it without selecting the default one and also there is no screensharing or youtube running currently?

**Comment by mrjive** [comment]
Hi everyone.
I have a question: wouldn't it be handy to have a "show presentation" or "start with presentation minimized" parameter in the room settings?
Thank you!
