### ISSUE TITLE
Documantation page for html5 install in BBB2.0 is missing

### ISSUE THREAD

**Issue by Brullworfel** [bigbluebutton/bigbluebutton#8167]
There is a link from BBB2.0 install documentation (http://docs.bigbluebutton.org/install/install.html#install-the-html5-client) to this page: http://docs.bigbluebutton.org/html/html5-install.html

But page is missing. Impossible to install without this instruction. I get it from web archive: http://web.archive.org/web/20180811164704/http://docs.bigbluebutton.org/html/html5-install.html

**Comment by ffdixon** [comment]
Use this page for installing BigBlueButton 2.2-beta (with HTML5 client), see

  http://docs.bigbluebutton.org/2.2/install.html

We'll update the older links and close this issue when updated.

**Comment by Brullworfel** [comment]
> Use this page for installing BigBlueButton 2.2-beta (with HTML5 client), see
> 
> http://docs.bigbluebutton.org/2.2/install.html
> 
> We'll update the older links and close this issue when updated.

Thanks. But we used 2.2 and it's very unstable. We downgrade to stable 2.0. release. In this issue I talk about 2.0.

**Comment by ffdixon** [comment]
Can you tell us more about the instability you found in 2.2-beta.  There have been others running it in production for quite a few months.  Can you tell us the issues you encountered.

**Comment by Brullworfel** [comment]
Hello!

When connecting a large number of people (we had about 170 participants online), the interface became very slow.

The list of participants did not scroll to the end, the last participants in the list could not be seen.

The presenter was periodically thrown out of the conference, each time he had to reconnect the sound. His video hung on the first break and he couldn’t turn it on anymore until the end of the webinar.

Despite the fact that I blocked the participants' microphones, periodically someone could turn on the microphone (https://github.com/bigbluebutton/bigbluebutton/issues/8164 ). It was very difficult to find who did this on a large users list, because the microphone and headphone icons were very small and the same color (look https://github.com/bigbluebutton/bigbluebutton/issues/8165 )

A lot of users who usually attend our webinars were not able to log in because they received messages that their browser was allegedly out of date. At the same time, they used modern browsers with WebrTS support (look https://github.com/bigbluebutton/bigbluebutton/issues/8152 )

It was the worst webinar in 2.5 years. I thought I would be fired the next day.

**Comment by Brullworfel** [comment]
I had to restart the server completely right in the middle of the webinar, because the situation was completely out of control. At this moment, we lost a third of the participants who did not connect anymore. After the reboot, everything worked fine for only a few minutes, after which the teacher again began to throw out the audio conference, and his video again stopped working.

One would think that we have a weak server. However, the tool 'top' on server showed a load of about 1-1.5 during this webinar, and there was a lot of free RAM.

On the same server, we does webinars with up to 350 participants with BBB 2.0, and everything went well.

**Comment by ffdixon** [comment]
@Brullworfel BigBlueButton 2.0 was released in [March 28, 2019](http://docs.bigbluebutton.org/support/release-notes.html#release-20), but since then all of our development efforts have focused on BigBlueButton 2.2-beta, which provides a full HTML5 client (you don't need to run Flash anymore).

We had asked earlier, is it an option for you to upgrade your server to the latest build of [BigBlueButton 2.2-beta](http://docs.bigbluebutton.org/2.2/install.html)?  We don't plan on making any more enhancements to 2.0.  We had also asked if there was a missing feature in BigBlueButton 2.2-beta that you only had in BigBlueButton 2.0?

> When connecting a large number of people (we had about 170 participants online), the interface became very slow.

Yes, we've done some improvements in BigBlueButton 2.2-beta to issues of the interface, especially around chat and screen updates as users join.  

> On the same server, we does webinars with up to 350 participants with BBB 2.0, and everything went well.

Wow, that's amazing.  In our documentation, we [recommend using BigBlueButton for 100 users (or less)](http://docs.bigbluebutton.org/support/faq.html#how-many-simultaneous-users-can-bigbluebutton-support), but that is not hard coded.


We know of companies that have been running BigBlueButton 2.2-beta in production for months now, and we've been steadily hardening the product.  If you can't upgrade your server, and you can't tell us why you can't upgrade your server, we invite you to setup an account on [demo.bigblubutton.org](https://demo.bigbluebutton.org) and try it for your next webinar.  

Finally, you may be wondering why we still call it 'beta'.  It's because we are still working on the product, though it is nearing a release candidate following our [development process](http://docs.bigbluebutton.org/support/faq.html#bigbluebutton-development-process).

Looking forward to your feedback on the above.

**Comment by Brullworfel** [comment]
> @Brullworfel BigBlueButton 2.0 was released in [March 28, 2019](http://docs.bigbluebutton.org/support/release-notes.html#release-20), but since then all of our development efforts have focused on BigBlueButton 2.2-beta, which provides a full HTML5 client (you don't need to run Flash anymore).
> 
> We had asked earlier, is it an option for you to upgrade your server to the latest build of [BigBlueButton 2.2-beta](http://docs.bigbluebutton.org/2.2/install.html)? We don't plan on making any more enhancements to 2.0. We had also asked if there was a missing feature in BigBlueButton 2.2-beta that you only had in BigBlueButton 2.0?
> 
> > When connecting a large number of people (we had about 170 participants online), the interface became very slow.
> 
> Yes, we've done some improvements in BigBlueButton 2.2-beta to issues of the interface, especially around chat and screen updates as users join.
> 
> > On the same server, we does webinars with up to 350 participants with BBB 2.0, and everything went well.
> 
> Wow, that's amazing. In our documentation, we [recommend using BigBlueButton for 100 users (or less)](http://docs.bigbluebutton.org/support/faq.html#how-many-simultaneous-users-can-bigbluebutton-support), but that is not hard coded.
> 
> We know of companies that have been running BigBlueButton 2.2-beta in production for months now, and we've been steadily hardening the product. If you can't upgrade your server, and you can't tell us why you can't upgrade your server, we invite you to setup an account on [demo.bigblubutton.org](https://demo.bigbluebutton.org) and try it for your next webinar.
> 
> Finally, you may be wondering why we still call it 'beta'. It's because we are still working on the product, though it is nearing a release candidate following our [development process](http://docs.bigbluebutton.org/support/faq.html#bigbluebutton-development-process).
> 
> Looking forward to your feedback on the above.

Perhaps you misunderstood me. All the described horror occurred precisely on version 2.2. After which I decided to downgrade to 2.0. And I found that the installation instructions for 2.0 are broken.

I will probably give a second chance to version 2.2 after its release.

Thanks you!

**Comment by ffdixon** [comment]
Yes, do give us another look after we get to BigBlueButton 2.2-RC.  

Your sessions are exceeding the recommend size for BigBluerButton, which is 100 users or less.  We don't hard-code that limit, so you are able to have 101, 102, and so on.

However, sessions of 170 are much larger than what we test, and sessions of 350 users are quite amazing (I suspect that was on the older Flash client).

You are (more than) welcome to try using BigBlueButton at whatever size of session you wish, but our development efforts are focused on making sure sessions of 100 users (or less) are working well.

For a bit more background, our focus in the BigBlueButton project is enabling the instructor to *engage* their students.  There isn't much engagement that goes on in 100+ meetings -- it's more of a webinar-type presentation.  

While the use case for holding 100+ users is valid, it's a very small portion of the overall class size.  In a recent sampling of 100,000 meetings done by one of the companies using BigBlueButton at scale, only about 30 sessions were greater than 100+ users.

You may say that your use cases are *always* going to be larger than 100, and that you want to use BigBlueButton (which is great), but be aware that it's not a use case that is the focus of our project.

We'd rather focus on the 99,970 sessions and ensure they go well and, for the 30 or so that are larger than 100, do our best to accommodate the increased size.
