### ISSUE TITLE
Video/Screen sharing always loading

### ISSUE THREAD

**Issue by hagianghi** [bigbluebutton/bigbluebutton#8236]
![Untitled](https://user-images.githubusercontent.com/20183808/67377762-5d4eb800-f5b0-11e9-83d0-7f39cbc6aea7.png)
Hello, 

Today I tried to install latest version of BigBlueButton, It's working well, but when I using desktop or webcam sharing, it's always loading.

please help 

Thanks for support

**Comment by ffdixon** [comment]
Can you try it against https://demo.bigbluebutton.org/ and let us know if it works for you on that server.

**Comment by alekzander7c4** [comment]
> 
> 
> Can you try it against https://demo.bigbluebutton.org/ and let us know if it works for you on that server.

Hello, I have a similar problem on my server and on your server https://demo.bigbluebutton.org/ too, when I use my corporate network. When I use my home network on your server https://demo.bigbluebutton.org/ everything works. 
TCP ports 80, 443, 1935, 7443 and UDP ports in the range 16384 - 32768 were open on corporate network. Maybe I should open additional ports for new version with HTML5.

**Comment by ffdixon** [comment]
@alekzander7c4 I would towards the firewall that is on your corporate network.  Depending on how aggressive it is in blocking traffic.

> TCP ports 80, 443, 1935, 7443 and UDP ports in the range 16384 - 32768 were open on corporate network. 

For the HTML5 client you only need 80, 443, and UDP ports in the range 16384 - 32768.  

  http://docs.bigbluebutton.org/2.2/install.html#minimum-server-requirements

If's a good bet that 80 and 443 **are** working (which is needed for setup of the video/screen sharing), but UDP connections **are not** working (which is needed for transmission of the video/screen sharing).

I would double-check the settings on your firewall, see

  http://docs.bigbluebutton.org/2.2/configure-firewall.html#testing-the-firewall

**Comment by alekzander7c4** [comment]
@ffdixon Thank you very much for your reply.
I checked the firewall using the instructions on the link and all ports were open. But our network engineer advised me to change size network packets transmitted from BBB server from 1460 to 1380, he saw that they do not pass in length (some problems with DF don't fragment flag for sending packets)
So, I temporarily changed the MTU value to 1380 on the network interface
`ip link set mtu 1380 dev ens160`
and after that everything works well.
Can you advise what to do next:
- leave the MTU 1380 on the network interface
- or I can change packets size in BBB configuration files,
- or how to fix problem with DF (don't fragment flag) for sending packets.

![image_2019_11_01T14_40_59_705Z](https://user-images.githubusercontent.com/57225320/68048602-92ae8080-fce9-11e9-8381-398c5ec8c12f.png)

![image_2019_11_01T14_42_05_601Z](https://user-images.githubusercontent.com/57225320/68048561-7dd1ed00-fce9-11e9-8e07-cb64266aebe8.png)


P.S. I apologize for my English, I know it is terrible. I hope everything is clear.

**Comment by ffdixon** [comment]
Thanks for sharing this -- it will definitely help out others.  Not sure the answer to the questions you ask, but we'll do a bit more research and let you know.

**Comment by hagianghi** [comment]
Thanks for sharing

**Comment by hagianghi** [comment]
Thanks Bro,

Today I try to change MTU packet size to 1380 on network interface, it's work on my server

**Comment by alekzander7c4** [comment]
Some additional information:
The problem is caused by intermediate routers or vpn tunnels between the server and the host.
For example, server and host when establishing a connection set MTU 1500. But routers or vpn tunnels between server and host can pass smaller MTU packets (for example MTU 1400). By default, intermediate routers or VPN tunnels must send ICMP message "fragmentation needed and DF set" to server or host, and server or host should reduce the packet size and send it again ([PMTUD](https://en.wikipedia.org/wiki/Path_MTU_Discovery)). But some providers, or as in our case, corporate network engineers, configure their networks so that the large packets drops and the ICMP message "fragmentation needed and DF set" is not sent to server or host.

Solution:
1. Set MTU packet size manually on network interface
2. Disable DF (not recommended)
3. Configure your network do not drop large packets
If I am mistaken, please correct.

I hope everything is clear.

**Comment by GhaziTriki** [comment]
Hello @ffdixon ,

We have some students that have noticed this issue in live meetings, about 20 on 100. Seen in two servers, even on Chrome 79.0.3945.88. We have logs we can share.

**Comment by iatalay19** [comment]
bunu nasıl uygulayacağız çözemedim bir türlü
