### ISSUE TITLE
Can not login into room Error: User could not log in HTML5, hit 401

### ISSUE THREAD

**Issue by ThienPhuc92** [bigbluebutton/bigbluebutton#8242]
**Problem**
I am developing to custom bigbluebutton-html5. Everything ok util I merge commit from bigbluebutton master yesterday. Then I can no longer enter the room. It alway show

![image](https://user-images.githubusercontent.com/15994841/67451813-a0aa3480-f64b-11e9-963e-bede204bd459.png)

**Solution:** 

I see a commit add redis timestamp then after i remove it. Then I can login to room normally

![image](https://user-images.githubusercontent.com/15994841/67451682-4a3cf600-f64b-11e9-8054-e9e8d4821ce2.png)

**Comment by antobinary** [comment]
@ThienPhuc92 This likely happened because the version of the source code was not matching the version of the remaining BBB packages. I am glad you resolved it but the correct way to do it would be to make sure you are working on the right branch of the repo, corresponding to your packages repo. I will be closing this issue now, apologies, looks like I missed it when it originally came in.

**Comment by ThienPhuc92** [comment]
Thank you so much. I will follow what you say!
