### ISSUE TITLE
Add setting for not to scaling screenshare recordings

### ISSUE THREAD

**Issue by rockenren** [bigbluebutton/bigbluebutton#8325]
Hello,

can you please add setting for not to scale screenshare recordings and use raw record resolution?

For now, if screenshare host have screen resolution of 1920x1080 (in my case host shares whole desktop), raw screenshare record also have image size of 1920x1080, but after recording processing it scales to 1280x720 what makes screenshare recording "very" blurry.

There is some settings for screenshare processing in /usr/local/bigbluebutton/core/scripts/screenshare.yml but this is fixed values.

I understand that with higher video resolution it will take more space on disk.

**Comment by antobinary** [comment]
@kepstin Is there a configuration for this or is there a workaround?

**Comment by pedrobmarin** [comment]
The remaining issue here is that all the screenshared content will be recorded in a single media file and screens/tabs/whatever may have different dimensions. If the problem is only with the downscaling, you can try your luck at https://github.com/bigbluebutton/bigbluebutton/blob/8a640877b29b9302bb79209b516ee17319e2927c/record-and-playback/presentation/scripts/presentation.yml#L4-L8 but be aware of https://github.com/bigbluebutton/bigbluebutton/blob/ef337acbe6055beac8fb8f41ebe633caca5443db/record-and-playback/core/lib/recordandplayback/generators/video.rb#L122-L151
