### ISSUE TITLE
Unmute all users not working

### ISSUE THREAD

**Issue by GhaziTriki** [bigbluebutton/bigbluebutton#8340]
Unmuting the meeting after muting all users does not work.

**Comment by prlanzarin** [comment]
Is this still a thing? Any additional details?

**Comment by pedrobmarin** [comment]
Tested at v2.3 develop and it's working as expected.

I think this meeting policy might be a little confusing and that may be the reason why this issue was reported. When you mute a meeting you automatically mute all current voice users and all new voice users will join muted. Undoing that will not unmute all muted users but will change the muted on join policy. The only way an user can actively unmute someone else is individually by setting https://github.com/bigbluebutton/bigbluebutton/blob/ef337acbe6055beac8fb8f41ebe633caca5443db/bigbluebutton-web/grails-app/conf/bigbluebutton.properties#L224-L226
