### ISSUE TITLE
Add a maximize button for presentation in mobile please

### ISSUE THREAD

**Issue by Brullworfel** [bigbluebutton/bigbluebutton#8347]
Hello! There is no way to maximize presentation in mobile. If text on presentation is small and there is turned on webcams, it's very hard to view anything on presentation on small screens! Thanks.

![2019-11-20 09 23 14](https://user-images.githubusercontent.com/12401672/69217464-657e2100-0b77-11ea-81bb-73c58295c2fc.jpg)
![2019-11-20 09 23 09](https://user-images.githubusercontent.com/12401672/69217468-6747e480-0b77-11ea-9529-e153f261917b.jpg)

**Comment by ffdixon** [comment]
This may help: we're working on automatically putting the webcams to the left of the presentation, which should keep the presentation large when you rotate the phone.

**Comment by antobinary** [comment]
@Brullworfel , what model phone / OS version / Browser + version  is this? I just tested and my Android 6, FireFox and could see the maximize button on the bottom-right hand corner of the presentation and I could also use it.

**Comment by Brullworfel** [comment]
> @Brullworfel , what model phone / OS version / Browser + version is this? I just tested and my Android 6, FireFox and could see the maximize button on the bottom-right hand corner of the presentation and I could also use it.

iPhone 7, iOS 13, Safari, BigBlueButton 2 build 763.

**Comment by antobinary** [comment]
We actually do not show the button on iPhones https://github.com/bigbluebutton/bigbluebutton/blob/master/bigbluebutton-html5/imports/ui/components/fullscreen-button/container.jsx#L9

because the API is not available on iOS other than iPad

https://developer.mozilla.org/en-US/docs/Web/API/DocumentOrShadowRoot/fullscreenElement 

![Screenshot from 2019-11-21 14-12-05](https://user-images.githubusercontent.com/6312397/69368897-fb45a900-0c68-11ea-9f51-e29f148b2ac5.png)

If the API becomes available in Safari on iPhone in the future we will adapt the client
