### ISSUE TITLE
remoteIceCandidates property

### ISSUE THREAD

**Issue by Foxprodev** [bigbluebutton/bigbluebutton#8450]
We still have `remoteIceCandidates` in `org.bigbluebutton.web.services.turn.StunTurnService`. That was a useful feature to easily pass NAT. 
Can you return this feature removed by this PR #4380?

**Comment by ffdixon** [comment]
@capilkey What do you think?

**Comment by capilkey** [comment]
If I remember correctly I removed the code because we didn't use it and I wasn't exactly sure how to test it so it wasn't being maintained. Our docs about working with a firewall should be enough to get past server-side NAT. It might be an easier approach though so I think it's worth a second look.

**Comment by pedrobmarin** [comment]
@prlanzarin and @mariogasparoni should we leave this opened?

**Comment by prlanzarin** [comment]
This is the old remote candidate spoofing from 1.1 and 2.0. It was a useful hack from olden times (FS < 1.8) for situations where we could not force advertisement of both intranet and public IPs in FreeSWITCH's SDP. So if we needed that scenario to work, we needed that hack implemented.

I believe @znerol's (great) work on https://github.com/bigbluebutton/bigbluebutton/pull/11846 addresses that scenario in a less archaic way. 

I'm closing this regardless of whether that PR is merged because the property is gone, the old SIP.js is gone and I don't think we need to re-implement this.
