### ISSUE TITLE
Offline Mode

### ISSUE THREAD

**Issue by besingamkb** [bigbluebutton/bigbluebutton#8476]
Can we run this fully on offline mode? i mean there is a network but without internet?

**Comment by ffdixon** [comment]
BigBlueButton is a real-time application for sharing content and media with others in a live session.  It needs an active internet connection.

**Comment by falcon129** [comment]
Hello
I am using BBB 1.1 in an offline mode institute , i am using http and is connected to ILIAS through a plugin ,
I installed fresh copy of BBB2.2 , Video/Audio not working using HTTP thus i installed ssl from local CA server ,  but still have errors to connect to :
Error: Could not connect to the configured hostname/IP address
#
#    https://bbb22.training.td/

Can i force the BBB server server to use CA server instead of internet CA's

**Comment by capilkey** [comment]
@falcon129 It's technically possible, but it's more difficult. The CA will have to be added to the server and potentially to the Java cert store. You'll also have to either add it to node.js or edit settings.yml and change `loadSlidesFromHttpAlways` to "true".

**Comment by falcon129** [comment]
Thank you for answering ,
Do you have any one who try it that he can share his experience .
