### ISSUE TITLE
Presentation Minimise Button - transparent background request

### ISSUE THREAD

**Issue by aogilvie** [bigbluebutton/bigbluebutton#8501]
Hi pretty straight forward request. To make the minimise button transparent just like the full screen button. I tested `rgba(0,0,0,0.4)` and that works nicely, though I leave that up to someone more pro at UI/UX.

Here are some screenshots at different resolutions:

![example2](https://user-images.githubusercontent.com/970364/72508077-63d78d80-3888-11ea-9c69-685c8cda396e.png)

![example](https://user-images.githubusercontent.com/970364/72508085-676b1480-3888-11ea-8e45-1bb254e0b9c8.png)

**Comment by ffdixon** [comment]
Thanks (as always) for your feedback!  @tylercopeland What do you think?

**Comment by tylercopeland** [comment]
@aogilvie, thank you for your feedback!

@ffdixon I don’t mind this, it does make it less prominent. One update I would make is reducing the padding so that it aligns with the full-screen button below. 

Before moving forward, I wouldn’t mind getting @KDSBrowne feedback from an accessibility standpoint. At first glance, it is hard to notice the “minus” icon, especially when the button is overlaid on top of thE presentation with text. Also, we would need to confirm this button needs a sufficient color contrast ratio to meet the necessary accessibility requirements.

**Comment by mrkeksi** [comment]
I would prefer to add a bar at the bottom of the presentation, like moderators do. There you can also add the minimize button and the download button. The minimize button has been replaced here (in the picture) by an arrow in the corner.

![image](https://user-images.githubusercontent.com/8763656/117379385-a5ee6d80-aed7-11eb-998d-da0aa7e92dea.png)

**Comment by antobinary** [comment]
Resolved in https://github.com/bigbluebutton/bigbluebutton/pull/13306 (in a different way - via action button minimize)
