### ISSUE TITLE
Don't group messages more than a minute apart or maximum of 10 messages

### ISSUE THREAD

**Issue by daminebenq** [bigbluebutton/bigbluebutton#8532]
Sending many messages from the same user without interruptions and without reconnections, shows all of his messages in a single group of messages showing only one time the time from when the user started sending messages.
![Peek 2020-01-23 11-32](https://user-images.githubusercontent.com/5144311/72993600-6aa85800-3dd4-11ea-9009-988081ea52ea.gif)

**Comment by antobinary** [comment]
As far as I know this behaviour was desired. Successive chats by the same author do not show a new timestamp if within X seconds. This seems to be an extreme case of it :smile_cat: 
Just confirming with @capilkey before closing

**Comment by kepstin** [comment]
We should probably show the timestamp again if it's been at least some amount of time (a minute? a couple minutes?) since the last time a timestamp was shown, just so people in the meeting have an idea of how fast messages have been arriving.

It is a bit of a special case / corner case tho, since normally multiple people will be chatting, or there will be gaps...

**Comment by capilkey** [comment]
I just renamed the issue. We used to show the name after 1 minute and we never did grouping like we are now. I think I'm going to explore breaking the grouping after 5-10 messages and see what looks best

**Comment by daminebenq** [comment]
duplicate of #8554 8554 !

**Comment by daminebenq** [comment]
duplicate of #8554  !
