### ISSUE TITLE
How to close orphan conference room?

### ISSUE THREAD

**Issue by etaddigital** [bigbluebutton/bigbluebutton#8534]
Sometimes, when a user close a conference room from the browser close tab (not using the end season option from drop-down menu) the season became orphan and can not be accessed or closed.
Is there away to close these rooms?

**Comment by antobinary** [comment]
Hi @etaddigital,
Typically the meetings are closed due to inactivity within 5 minutes, provided that there are no users in them. In your case do you see any users in these 'orphan' conferences? You can use the API MATE interface to trigger a 'getMeetings' call, see https://mconf.github.io/api-mate/

You can use `$ bbb-conf --secret` to easily obtain a url to API MATE populating your server's domain and salt

**Comment by capilkey** [comment]
I think the default is that the meetings will close after 1 minute of no one being in them. The meetings will timeout and be destroyed after creation if no one joins them within 5 minutes.
