### ISSUE TITLE
Webcam zoom ( close up )

### ISSUE THREAD

**Issue by alfonsofernandezyf** [bigbluebutton/bigbluebutton#8542]
**Is your feature request related to a problem? Please describe.**
It would be useful to be able to tap or click tu zoom, for doing closeups in the midle of the conference. 

**Describe the solution you'd like**
Enable a digital zoom for your webcam, so each user can zoom on ther own cam.

**Describe alternatives you've considered**
Adding a "+" button on the webcam view

**Additional context**
Sometimes you need to focus on particular place of the picture to explain something.

**Comment by prlanzarin** [comment]
I'd bet there are 3rd party, virtual camera software which allow you to do that.

Implementing this on our side means handling dynamic camera viewports, communicating them from client to server and orchestrating that stuff between potentially different camera views.

So it'd code bloating and error prone. Although I acknowledge the validity of the enhancement request, I'm closing this for the time being because it can be worked around with 3rd party software.
