### ISSUE TITLE
Yandex browser cannot load BBB HTML5 on iOS devices

### ISSUE THREAD

**Issue by antobinary** [bigbluebutton/bigbluebutton#8550]
https://github.com/bigbluebutton/bigbluebutton/pull/8541 addressed Yandex browser on desktop and Android.
However, iOS Yandex still has issues with BBB HTML5

**Comment by daminebenq** [comment]
**Problems on iPad and iPhone, it doesn't redirect into the meeting at all after the login page !**
![Image from iOS](https://user-images.githubusercontent.com/5144311/73101864-644ad680-3ecf-11ea-898b-2fdc22b6abda.png)
![Image from iOS (1)](https://user-images.githubusercontent.com/5144311/73101922-80e70e80-3ecf-11ea-90e9-6804a4b9b4b3.png)

**Comment by capilkey** [comment]
Yandex on iOS won't work because there's no WebRTC support. It looks like it might not be possible to differentiate the platform that the Yandex browser is running on, but we'd know for sure based on the printout from the /html5client/useragent endpoint. If the platform isn't represented then we're left with determining why the client doesn't load and then we have to show a message when they try to use WebRTC.
