### ISSUE TITLE
Is it possible to support PDF with embeded audio file in it?

### ISSUE THREAD

**Issue by yayaxueyu2019** [bigbluebutton/bigbluebutton#8649]
**Is your feature request related to a problem? Please describe.**
We use BBB to teach online English lessons and we often need play play audio during class. Now there are PDF files with audio file (mp3) embeded into it.   Children can read and tap to play inside the same PDF page.  It really help language teachers to improve the teaching experiences if we can have this feature in BBB room. 

**Describe the solution you'd like**
I my idea, I will uploaded my PDF (with mp3 embeded) to BBB, and I can click on some preset audio button in the PDF to play while teaching students in the page.

**Describe alternatives you've considered**
I'm not a coder, so I can't provide alternatives in that way.

**Additional context**
No, but those PDF (embeded with mp3) is easy to find. (Here I will 
[MHE_Rdg_Wonders_LvRdr_G1_On-Level_U2W2_07.pdf](https://github.com/bigbluebutton/bigbluebutton/files/4225561/MHE_Rdg_Wonders_LvRdr_G1_On-Level_U2W2_07.pdf)
attach one)

**Comment by ice6** [comment]
I think this will be hard to implement, because Chrome does not support it natively. pdf.js does not support this feature.
The Adobe Reader supports it with a security caution.
Upload the file, and let the students install Adobe Reader, and download it to play.

By the way, the example you provide is so fun. I read it through :)

**Comment by yayaxueyu2019** [comment]
Thanks, I know it is a tough job to do. Now we have the teachers playing the audio on another browser tab which loads a Moodle page associated with the same course. It works okay if the Internet is fast.

**Comment by ffdixon** [comment]
We don't have any plans to support embedded media in PDF documents.  The open source tool chain we use to convert PDF pages in to SVG doesn't support it.

**Comment by thewebsitefactorylondon** [comment]
Hello
Is there any way to upload audio / mp3 files through upload option? We have the same requirements as @yayaxueyu2019 - we run English language courses like IELTS etc, and it is very good to have this option where a teacher can play the audio recordings for students? Same as how the External Video links option. Is this going to be implemented anytime soon? I tried playing an audio file on a Chrome tab and shared my screen but no luck, I guess maybe due to voice cancellation feature this didn't work.
Other than this your software has helped us a lot!!
Thank you!

**Comment by Sea444** [comment]
Pleas no rich media content in PDF. It's a security nightmare...

**Comment by basisbit** [comment]
Closing this issue because there are no plans to support rich media content from PDF presentation files anytime soon.
