### ISSUE TITLE
Can we have more layout options for the video window?

### ISSUE THREAD

**Issue by yayaxueyu2019** [bigbluebutton/bigbluebutton#8746]
**Is your feature request related to a problem? Please describe.**
I'd rather say it's a improvement request.  Now most pdf files are on portrait direction and when loaded into BBB room, the texts would be too small to read if we show the whole pdf. So in most cases we need to use the <-> button to enlarge the pdf. However when we do this, we can only show about half of the file, upper half or lower half.  The problem is that teachers often need to roll the screen up and down the let student to complete an class activity, for example, the question info are on the upper part of the screen and the answers art on the lower part. 

**Describe the solution you'd like**
I think there might be two ways to make improvements on this:
1, allow video window floating on top of the pdf file, then we can free the space taken by the video windows previously.
2, allow video reposition to the side bar, for example, the user list section is quite empty in most cases. We don't have long list of users.  

**Describe alternatives you've considered**
it's said above.

**Additional context**
I uploaded a video capture to show how a teacher needs to roll up and down to complete a simple teaching task. It's annoying when the teacher has to do it many times.  Also I make a simple mockup to show the improvement idea. In fact, I think we can merge User List and Public Chat into one section, with two tabs. We don't need to see the user list that often. All in all, we need to show make as much room for teaching area as possible. 
 
![layout-improvement](https://user-images.githubusercontent.com/56071188/76281949-4abfeb80-62d1-11ea-81ac-bf558d9de09b.jpg)

[layout-problem.zip](https://github.com/bigbluebutton/bigbluebutton/files/4310397/layout-problem.zip)

**Comment by iSamof** [comment]
I appreciate combining the user list and public chat is helpful for the OP's scenario but may not be helpful in others. When conducting discussions etc, if someone put their hand up in the user list, the moderator should see it in order to unmute the person.

Overall, I'd prefer keeping all components of a room (whiteboard, presentation, chat, user list, etc) as independent elements that can be separated from each other (in the future) ... in the hope that soon we will have a layout manager and the ability to reposition the components. This enables each org to create multiple preset layout that suits it. And if the layout manager also allows switching on/off the components, one can create layout templates that suit different applications.

This latter paragraph is the main reason I suggest combining user list and chat ... or any other component will become a problem down the line.

**Comment by matiasilva** [comment]
A layout manager is currently being built (see #8729)! I'd suggest keeping an eye out for that if it comes out in the 2.3 beta.
