### ISSUE TITLE
Maximum practical capacity of a meeting

### ISSUE THREAD

**Issue by hhuseyinpay** [bigbluebutton/bigbluebutton#8748]
Hi, we are planning to make a meeting for +5000 users. Is it possible? If so which machine do you think sufficient for this job on google cloud? What do you think about  n1-highcpu-16 - https://cloud.google.com/compute/all-pricing#n1_high-cpu_machine_types ?

**Comment by capilkey** [comment]
BigBlueButton isn't designed for large-scale webinar usage (500+ users). We recommend using the BBB 2.2 client with 100 users or less in a meeting.

**Comment by hhuseyinpay** [comment]
Thank you for reply. So suppose there are 100 users attend to per meeting, how many meeting can continue without a problem  at the same time?

**Comment by capilkey** [comment]
The number of meetings would depend on what's happening in them and what is happening on the server. If you have a server that's at capacity and then a meeting ends and the recording starts processing it will affect the meeting performance. There are too many variables to give hard numbers for capacity of a server, but I wouldn't put more than 500 users on a very very powerful server.

As for the question about 5000 people watching the same content, you're into livestreaming at that scale. You could stream it on Youtube for instance. Another option would be to record ahead of time because you're not getting interactivity at that scale anyways.

**Comment by andrettix-soto** [comment]
capilkey, but if I can have 50 users ... that equals 2,500 connections, right?
So if I block all the webcam and microphones. I just leave the presenter sharing their screen and their webcam ... so could I have 2,000 people listening to the presentation without a problem?

**Comment by matiasilva** [comment]
Hi @andrettix-soto. Again, as stated above, there are too many variables. I suggest you perform a load test with your specific conditions. In any case, BigBlueButton scales better when there are many servers that are centrally loadbalanced.

**Comment by capilkey** [comment]
@andrettix-soto Disclosure, I'm not longer working on BBB so things might have changed, but I assume it's probably the same.

The client isn't designed for large scale webinars with 500+ users in them. Each user that you add to the meeting adds load that isn't just from the media streams and you will have performance issues on the server and in a user's browser. My original reply to this issue about keeping meetings to 100 or less still likely applies.
