### ISSUE TITLE
Does BBB auto record the voice?

### ISSUE THREAD

**Issue by mabras** [bigbluebutton/bigbluebutton#8751]
I have noticed the BBB auto recording the auto without hitting the record button. I have checked the raw files on server and there is a `opus` file, which contain the sound session. My problem is that I have clients open the conference room for a long time and this cause A) more disk space, B) long time for processing the raw files to produce the playback. Is there a way to avoid this?
Thanks

**Comment by ffdixon** [comment]
In the future,  post such questions to bigbluebutton-dev and we'll help you there.  

  https://bigbluebutton.org/support/community/

If in helping you we see a bug or feature needed, we'll open an issue here to track it.

Have you enabled auto-start of recording by editing the bigbluebutton.properties file?  OPUS uses minimal space for audio recordings, but if you record a lot of audio, it will still take a lot of space.

**Comment by mabras** [comment]
No, I have not:
```
autoStartRecording=false
```

**Comment by capilkey** [comment]
We intentionally record the audio for the full conference and then cut it down at the processing step because it allows for changing the recording start/stop marks after the meeting is over. This is useful when someone forgets to start the recording until the end of the meeting.

The best option is to put a default duration of something like 8-10 hours or 2x the longest meeting you want to support. When the duration is set it will make sure that someone sitting in a meeting wont use up all of your disk space.
