### ISSUE TITLE
Choosing which screen to share on multiscreen systems

### ISSUE THREAD

**Issue by gerazov** [bigbluebutton/bigbluebutton#8785]
Just starting to use bbb - it's awesome! Great work guys :clap: 

**Is your feature request related to a problem? Please describe.**
I wanna share just the screen where I'm doing the demo, and keep the other one for reference. Plus viewing double screens might be tricky for users on a single screen.

**Describe the solution you'd like**
Choose which screen to share in the dropdown menu.

**Comment by prlanzarin** [comment]
That's currently out of our reach. The available displays in the screen sharing picker are given by the browser according to their capabilities in their current environment. I know that ie Chrome on Windows supports choosing specific displays, but it doesn't on Linux. So it's on the browser vendors to implement that.

If I may suggest something to achieve what you want, you might choose to share an **application** (if you're doing the "demo" on one), and then you can drag the app to whichever display you wish, as long as it stays on focus.

**Comment by gerazov** [comment]
thanks @prlanzarin! The solution you propose is cool as it keeps focus on the app you're sharing, but sometimes it's tricky if you plot a figure say in Spyder and you have to change apps and restart sharing. Also the students reported that they have to manually refresh their browsers to get the new screen.

I found a possible workaround using OBS - a free software for live streaming and recording, as outlined here https://github.com/jitsi/jitsi-meet/issues/2894. Basically have a screen capturing app that you reference in BBB. I could not get the whole screen though - I could not get rid of the menu toolbar in OBS, and setting it in Projector mode made it stay on top.

It would be nice if there's a simpler app to do it more smoothly :wink: 

Maybe it's not the right place, but here's some feedback if you'd like to hear - I just had my first class and found the experience quite rewarding - the group chat, the polls and the whiteboard all were great to use. 90% of my 20 students were satisfied with the platform :+1: :+1: 
Major issues reported were sound quality and lag. These might be due to poor internet connections as most students found the audio quality OK. However, we tried a proprietary platform for the last class and the audio and screen sharing were noticeably improved for most participants - even those that reported lag. So there might be room for improvement on the VoIP end of things. Maybe switching to Opus might help?

**Comment by prlanzarin** [comment]
> It would be nice if there's a simpler app to do it more smoothly wink

Yeah, OBS is my go to solution for this kind of stuff, so I personally can't recommend anything better than that hehe. Out of curiosity: what browser (+version) and OS (+version) are you using? As I mentioned, I know some browser+OS combos let you capture different screens, so it'd be good to have an ideia of what's your environment.

> Maybe it's not the right place, but here's some feedback if you'd like to hear - I just had my first class and found the experience quite rewarding - the group chat, the polls and the whiteboard all were great to use. 90% of my 20 students were satisfied with the platform +1 +1
Major issues reported were sound quality and lag. These might be due to poor internet connections as most students found the audio quality OK. However, we tried a proprietary platform for the last class and the audio and screen sharing were noticeably improved for most participants - even those that reported lag. So there might be room for improvement on the VoIP end of things. Maybe switching to Opus might help?

We do have improvements we can do about media reliability regarding poor networking conditions (and there's continued work in that area). We already use OPUS for audio, but sometimes it's tricky to get it's adaptation parameters right. And there might be other underlying factors that even OPUS can't quite grasp (jittery connections, server overloads, etc). Might I ask which audio mode were the affected users into, microphone or listen only?

**Comment by gerazov** [comment]
I'm on Plasma Manjaro 19.0.2 (kernel 5.4) myself, using Firefox v74. As you say it's probably Linux specific, maybe moving to Wayland will fix it?

How to you set OBS to just show the screen with no interface?

The best I could do is get rid of all the docks and status bar and full screen it. This leaves the menu visible though:
![image](https://user-images.githubusercontent.com/15214418/76785369-9bde4c80-67b5-11ea-80f9-a04cb5e145f1.png)

If I select Fullscreen Projector (Preview) I get the whole screen but then it stays on top of other applications.

The students were using both modes, and those with microphones were muted. Does muting work like being in listening mode?

**Comment by gerazov** [comment]
I opened a Bug on Firefox's bugzilla to see if they can help https://bugzilla.mozilla.org/show_bug.cgi?id=1623013

**Comment by gerazov** [comment]
Ok I found a workaround that works.

1. Run OBS Studio, 
2. In `File > Settings` uncheck `Make projectors always on top`
3. Now right-click on the screen and start `Windowed projector (Preview)`
4. In BBB share the `Windowed projector (Preview)`

And voila :smile:

**Comment by matiasilva** [comment]
Great discussion. Closed as this is out of our control.
