### ISSUE TITLE
BBB with heavy load

### ISSUE THREAD

**Issue by bbbmm** [bigbluebutton/bigbluebutton#8801]
I want to start with expressing how happy we are in using BBB during this critical timing. Thank you for all the great work!! it is a project well made!

We have installed and configured BBB with Moodle, all functionality are working fine.

The issue we are facing is related to the heavy use of the system.

In these days we are using BB heavily in delivering all campus classes virtually.
We have installed and configured our own BBB server in AWS with c.9xlarg instance having 1T storage attached.

Our BBB is not accepting the heavy connections, we have in average of 4 classes batches per day, every batch contains average of 50 sessions, each session run for 2 hours, each session has average of 20 participant. Every session is getting recorded. This is being in practice daily.

What is happening is once the sessions start to increase in number > 30 and total participant > 300 most of mediators will start getting kicked out from their sessions and the gradually the students. BBB is not be able to recover the rejoining for them all it  just recover some and all the others will get stuck in the page loading.

With a note that the server resources are not getting utilized to the max, not even reaching 50%, CPU, RAM, SWAP,.... 

HELP! How can we overcome this? What configuration we need to change to tune the performance to accept this heavy load?

Once again thank you for the brilliant solution.

Best Wishes,

**Comment by capilkey** [comment]
There's no configuration to tune the performance. You're just exceeding the capacity of one BigBlueButton server. The solution is multiple BBB servers and a BBB-specific load balancer in front of them.

This is one example of a BBB load balancer, https://groups.google.com/forum/#!topic/bigbluebutton-dev/T3WKHrwpTnQ

**Comment by GremL1N** [comment]
If you use recordings, maybe you got disk IO limits? It may looks like system slow but resouces are free. `iotop` or `atop` are usefull for diagnostic this.
Also you can move recordings to another disk\server.

**Comment by bbbmm** [comment]
Thank you so much for the both replies.

We are very excited and started working on implementing the BBB load balancer.

Many thanks again

**Comment by ffdixon** [comment]
A BigBlueButton load balancer already exists, see https://github.com/blindsidenetworks/scalelite

**Comment by shareefhiasat** [comment]
Hi @ffdixon 

I woul really need your help guys....

I intend to host BigBlueButton on my AWS server!
My plan is to follow the installtion and setup instructions in docs....

As i saw load balancer here! am confused should i concerned about it, for me its easier to **scale** vertically, on HW level.

Another **concern**, My case is not huge its around 1000 user with host will share his screen or
resources/slides etc... ( may be his face camera only to be show to 1000 users)
_Refering to_ i still not sure what is the max capacity on

1. Software limitation level?
2. Hardware/Network ? how to benchmark and know which size is suitable for my case
 
https://github.com/bigbluebutton/bigbluebutton/issues/9142

**Comment by basisbit** [comment]
The event message handling of BigBlueButton is implemented using NodeJS+Meteor and in BigBlueButton the session state is one big object, thus it can process all the clients event messages only with one CPU thread on one CPU core. As soon as you hit 100% utilization of that CPU, you reached maximum capacity of that server. Just adding even more CPU cores thus does not improve the amount of users you can handle on one server. With BBB 2.3, the event handling of participant list, Whiteboard and chat will be split into its own NodeJS/Meteor processes, thus improving scalability and handling high loads. Anyways, it is best to have many cheap dedicated servers / VMs with dedicated CPU cores and then use Scalelite to distribute the sessions to the different servers, thus allowing many thousands of concurrent sessions to happen at the same time, if necessary.

**Comment by ha3ant** [comment]
I have one G9 dedicated server with 128GB Ram and 32 core with 1Gig Ethernet, installed two VM on that, and install BBB on them. so each machine has 16 real core (32 virtual) and 64GB of Ram. but the problem is here: when the concurrent users grow more than 300(~330) the hell will be starting! :x
the new users have a big delay on join, the current users expulse from sessions!
The 'top' command shows me the _**idle**_ CPU usage up to 65% and only 10% memory use!
I can't find what's wrong for me!
Anyone can help me?

**Comment by ccomincini** [comment]
> A BigBlueButton load balancer already exists, see https://github.com/blindsidenetworks/scalelite
@ffdixonplease help me to understand better about load balancer: from what I've understood the load balancer spreads subsequent meetings on the first available and less used server, accordingly to the settings ( I can give higher priority to one or one other server in the group of BBB servers behind the balancer).
Now, what I' would like a Load balancer to do, is to consider the BBB servers in the group as one, as a cluster, and spread the single incoming connections on the first available and less used (or with the highest priority) server, in a way that let users connect in high number to a single meeting, and not to "only" let host a lot of little meetings (that is a truly a useful thing)

So the question is: is there something that let me do this? because It seems to me that the true limit is not on the number of meetings, but on the number of people in a single meeting.

Thanks for the answer

**Comment by ffdixon** [comment]
This issue is closed.  In the future, can you post your messages to [bigbluebutton-dev](https://groups.google.com/forum/#!forum/bigbluebutton-dev) where the community can help you out.

> in a way that let users connect in high number to a single meeting

Scalelite can help with horizontal scaling (lots of individual meetings), but to achieve greater vertical scaling (more users in a single meeting), you'll find that BigBlueButton 2.3-dev (currently under development) will get you further.

We're working on 2.3-alpha3 which will be announced to the above bigbluebutton-dev mailing list when its ready.
