### ISSUE TITLE
Filesharing Fileexchange

### ISSUE THREAD

**Issue by wemakefuture** [bigbluebutton/bigbluebutton#8817]
Hello a file exchange/upload by students would be amazing. 

https://support.zoom.us/hc/en-us/articles/209605493-In-Meeting-File-Transfer

Zoom Supports it. Would be amazing. 

Thanks!

**Comment by basisbit** [comment]
(just my personal opinion, not the opinion of all the developers of the BBB project)
I'd argue that if such a feature is needed, an extra servers running nextcloud or similar should be set up. Otherwise, the BigBlueButton server would have additional network load spikes, thus impacting audio + video performance of the servers.
Additionally, BigBlueButton is a project for implementing an easy to use web conferencing system, not a copy of zoom which has feature creep. For many use cases (when BBB is used with a learning tool like moodle, or even nextcloud), that feature would also be redundant.

**Comment by prlanzarin** [comment]
Duplicate of https://github.com/bigbluebutton/bigbluebutton/issues/952
