### ISSUE TITLE
Add to documentation Prometheus exporter & Grafana dashboard

### ISSUE THREAD

**Issue by greenstatic** [bigbluebutton/bigbluebutton#8831]
I have created a Prometheus exporter for BigBlueButton that relays various metrics using the XML API BigBlueButton exposes. The exporter can be found here: [https://github.com/greenstatic/bigbluebutton-exporter](https://github.com/greenstatic/bigbluebutton-exporter).

Using the exporter and the Grafana dashboard bundled with it, one can monitor their BBB server and create alerts.

It would be great if this was referenced in the documentation so administrators can monitor their BigBlueButton installations.

**Comment by basisbit** [comment]
Thank you for publishing your metrics exporter! Could you please create a pull request in the [documentation repository](https://github.com/bigbluebutton/bigbluebutton.github.io), so that others can make use of the exporter? Maybe a new "monitoring" page for the documentation with general suggestions, some links to Prometheus/Grafana install tutorials and also best practices for collecting the desired data would be nice.
