### ISSUE TITLE
Media could not reach the server (Error 1020) .

### ISSUE THREAD

**Issue by Mindsage** [bigbluebutton/bigbluebutton#8843]
New and first-time install of bbb 2.2.  This is a VMware instance for test purposes. 
Audio works fine, but when trying to share video this error is encountered: 
Media could not reach the server (Error 1020) .

**Installation type**
Used bbb-install script (had to correct a few things regarding the sip IP)

**Additional context**
It also says the machine IP is not the same as its domain name (for the demo).

**Comment by Mindsage** [comment]
Is there anything I can collect?  a debug out?   Video test works fine on the bbb environment, but on ours it errors out.

**Comment by lonesomewalker** [comment]
It says, your ip and used domain do not match.
So there will be no connection.

**Comment by ffdixon** [comment]
> It says, your ip and used domain do not match.

That is incorrect.  `sudo bbb-conf --check` will always print out this warning as it is doing a string comparison between an IP addres and hostname.  

Try accessing your server using FireFox and share a webcam.  After the error, open a new tab and go to `about:webrtc` and see what IP addresses/ports your server provided for the media connection.  You should see the external IP address of your server listed here.

**Comment by Mindsage** [comment]
Thanks Fred, I did that, and most addresses look good (client and bbb host) except for this one
172.19.0.1:29281/tcp(host)    which is not an address I've ever seen.

**Comment by wfmarcelo** [comment]
I had the same problem, and I solved it adding the external ip in the kurento config file.

/etc/kurento/modules/kurento/WebRtcEndpoint.conf.ini

Just find the line with externalAddress=xxx.xxx.xxx.xxx and put your external ip address.

**Comment by prlanzarin** [comment]
`externalIpAddress` works, but be aware that it only accepts one IP. So you'll get stuck with either IPv4 or IPv6 if you need dual stack. I plan to extend it to become a list of IPs in the near future, but there are some other priorities up in the queue right now.

Recommended way is setting up a STUN server as detailed in https://docs.bigbluebutton.org/2.2/configure-firewall.html#extra-steps-when-server-is-behind-nat. It'll get both IPv4 and IPv6 addresses if correctly set up.

**Comment by Salamit** [comment]
Hi, I already had a STUN server address and port setup but I sometimes get the error.

**Comment by FransGH** [comment]
I have a user that often get's the 1020 error but not always. Looking at the source-code, the 1020 comes after a hardcoded 15sec timeout. See https://github.com/bigbluebutton/bigbluebutton/blob/master/bigbluebutton-html5/imports/ui/components/video-provider/component.jsx

Would it be possible to make this timeout configurable on the server in order to support/troubleshoot what appear to be slower systems/networks?

**Comment by prlanzarin** [comment]
@FransGH we should make it configurable, yeah. 

About the issue per se, **intermittent** 1020s usually are due to a lack of a TURN server or a misconfigured one. Other, less probable options are the server being overloaded or a *very* troubled network (very rarely it should take longer than 15s seconds to find a connectivity pair if it's possible). And you can debug it using either about:webrtc (FF) or chrome://webrtc-internals (chrome) even after the timeout elapsed since they store the peer connection lifespan and the traded ICE candidates (which may explain connectivity issues) between server and client.

**Comment by flipreverse** [comment]
I had the same issue. I solved it by setting `networkInterfaces` in `/etc/kurento/modules/kurento/WebRtcEndpoint.conf.ini`. I used the interface that is connected to the internet. This option was introduced in Kurento [6.13](https://doc-kurento.readthedocs.io/en/6.13.0/project/relnotes/v6_13_0.html).

**Comment by prlanzarin** [comment]
That interface won't fetch IPv6 candidates, so be careful when using it. That's why it's not set by default nor documented.

**Comment by flipreverse** [comment]
Mhmkay. But why is it such a hard thing to establish an IPv6 WebRTC session?
Without the aforementioned option, I'm able to establish an audio session. However, I cannot establish a webcam session. This applies only to FF74.0. Same system (Ubuntu 19.10), Chromium works perfectly fine.
I do not have a TURN server configured on both ends.

**Comment by prlanzarin** [comment]
@flipreverse It's not hard. The option just came in that way from upstream libnice folks. I want (very much) to make an extension for it to also gather IPv6 candidates, because I consider it a very important optimization. Just haven't got the time to do it yet.

About TURN: you don't need to have it setup on both ends. Kurento should never need a TURN server. A STUN should suffice.

If the networkInterfaces option is the only thing doing it for you, I guess it's probably due to the fact that you have too many network interfaces server-side or a conflicting bridge interface (please confirm) that messes up with libnice's ICE lifecycle. I've seen it happen. If that's the case, keep the option on (and wait till I or someone extend it to also work with IPv6) or try to trim down the  number of interfaces (ie if you use docker, you can change your container's network mode to host instead of vbridging everything).

**Comment by flipreverse** [comment]
> If the networkInterfaces option is the only thing doing it for you, I guess it's probably due to the fact that you have too many network interfaces server-side or a conflicting bridge interface (please confirm) that messes up with libnice's ICE lifecycle. I've seen it happen. If that's the case, keep the option on (and wait till I or someone extend it to also work with IPv6) or try to trim down the number of interfaces (ie if you use docker, you can change your container's network mode to host instead of vbridging everything).
Yeah, I do have like four network interfaces (+ the one for the greenlight docker container) on the server-side. Additionally, two of them are connected to the outside subnet.

So, might it be possible Chrome is using their own version of libnice? However, it works on chrome having `networkInterfaces` option disabled.

**Comment by basisbit** [comment]
@Mindsage were you able to solve this problem in the mean time?

**Comment by aakatev** [comment]
Had the same issue on one of our server's today too. Solved using @ flipreverse solution. For some reason server was trying to connect to internal IP. Setting `networkInterfaces` in `/etc/kurento/modules/kurento/WebRtcEndpoint.conf.ini` did the trick. Good way to debug was using `about:webrtc` in Firefox.
