### ISSUE TITLE
Is it possible to have two pdf's open in a Room at the same time and not have them disappear when you end session?

### ISSUE THREAD

**Issue by hippylover** [bigbluebutton/bigbluebutton#8848]
Edit. I changed the topic. See third post.

When you upload a pdf with the Action button inside a Room, and then click end session, or logout, the pdf is back to the default.pdf when you Start a Room again...

How can i make bbb not forget the presentation?

**Comment by jibon57** [comment]
You can follow this: http://docs.bigbluebutton.org/2.2/customize.html#change-the-default-presentation

**Comment by hippylover** [comment]
Iv'e already changed the default.pdf. Actually i have to rephrase the question. This is the new question: Is it possible to have two pdf's open in a Room at the same time. So you would "tab" inbetween them? I also need bbb to not forget about the pdf's when one ends the session... I will edit the OP.

**Comment by capilkey** [comment]
BigBlueButton doesn't keep state between sessions so nothing uploaded during a meeting can be stored for the next session. It's designed this way so that a meeting can start up on any BBB server and it will function the same which makes load balancing between many servers much easier.

There is an API to pre-upload a presentation to a meeting when it is created (http://docs.bigbluebutton.org/dev/api.html#pre-upload-slides). There are some front-end systems that have implemented it.

**Comment by hippylover** [comment]
Hm. Interesting. Ok, well the way i see it the "extrapresentation.pdf"(in addition to the default.pdf) are still living on the server(if not removed by cron script), so whatever code that is neccessary to bring it up in the internal viewer when the user uploads a presentation and the upload is finished, will bring it back up again when the room is entered another time.

But then i'd need tabs inside the pdf viewer window... i don't know how much work this is or if it's even a great idea. I have a client asking for this but i don't know how much work it is.

**Comment by hippylover** [comment]
It seems that if i don't end the session or logout but just press the back button, the room remembers the latest pdf/presentation.

**Comment by hippylover** [comment]
AFAIK the only problem is roomadmins not wanting to reupload old material. If there were some place admins/teachers could upload teaching materials through an interface and then click a dropdown list on the Presentation screen to load said teachingmaterial... This is a feature request i suppose. Maybe i should make a new thread but i'd like to get input first.

**Comment by capilkey** [comment]
The files were still available to you after you backed out of the page and rejoined because you rejoined before the meeting ended. If you back out and wait ~1.5 minutes and enter again you should get a fresh meeting.

Also the converted files might be on the server, but that doesn't mean that they are accessible to other meetings on the server. All presentations are stored under a directory named after the internal meetingId. The internal meetingId is unique to each meeting. The reason we do this is because in a load balanced environment a teacher could start their Math 101 class on Tuesday and have their class on server1.mydomain.com and then when they have their Thursday Math 101 class it could get placed on server 7.mydomain.com. There's no bridging between BBB servers so the file would have to be reuploaded anyways.

The pre-uploading should be done in the front-end system that you're using to start your meetings and when done this way works quite well. I think the Moodle integration has it implemented.

**Comment by hippylover** [comment]
> The reason we do this is because in a load balanced environment a teacher could start their Math 101 class on Tuesday and have their class on server1.mydomain.com and then when they have their Thursday Math 101 class it could get placed on server 7.mydomain.com.

Ok, i have no such environment but isn't there a need for common storage for all the teachers? There could be a place where teachers could upload stuff and then access it from presentation with a dropdown. Even per-teacher permanent storage i think could be an idea.

**Comment by capilkey** [comment]
We have to balance all of the use cases and methods for managing meetings. Another thing we have to consider is cases where multiple organizations could be running meetings on the same server and their data can't cross. It can get complicated.

It's somewhat of a tangent, but we have some changes in the works for the next release that will make the upload messages non-blocking so the rest of the meeting can continue while the teacher waits for the files to convert. The designs have the conversion progress showing as toast messages in the top-right. We've also started work on showing the new presentation after the first slide has been converted rather than waiting for the full presentation to be converted before showing it. Both of those changes together should be a much better experience.

**Comment by hippylover** [comment]
Ok, well that is good news. If you are not against it i will write a feature request for common storage and per-user storage with an eye to perhaps developing this myself(perhaps)

**Comment by basisbit** [comment]
closing this because all questions were answered.
