### ISSUE TITLE
error on line 1 at column 153: Extra content at the end of the document

### ISSUE THREAD

**Issue by vipinblue** [bigbluebutton/bigbluebutton#8868]
Every time  when I tey join to a session I'm getting this error 

`This page contains the following errors:
error on line 1 at column 153: Extra content at the end of the document
Below is a rendering of the page up to the first error.`

here is link [http://live.acadox.net/bigbluebutton/api/join?meetingID=Demo+Meeting&fullName=admin&password=mp&checksum=e64d85070c5537b94c87e98427e5f5d2b2cdbf30](http://live.acadox.net/bigbluebutton/api/join?meetingID=Demo+Meeting&fullName=admin&password=mp&checksum=e64d85070c5537b94c87e98427e5f5d2b2cdbf30)

my server configure 

`BigBlueButton Server 1.0.0-beta (931)
                    Kernel version: 3.13.0-67-generic
                      Distribution: Ubuntu 14.04.3 LTS (64-bit)
                            Memory: 7300 MB

/var/www/bigbluebutton/client/conf/config.xml (bbb-client)
                Port test (tunnel): live.acadox.net
                              Red5: live.acadox.net
              useWebrtcIfAvailable: true

/opt/freeswitch/conf/sip_profiles/external.xml (FreeSWITCH)
                    websocket port: 5066
                    WebRTC enabled: true

/etc/nginx/sites-available/bigbluebutton (nginx)
                       server name: live.acadox.net
                              port: 80
                    bbb-client dir: /var/www/bigbluebutton

/var/lib/tomcat7/webapps/bigbluebutton/WEB-INF/classes/bigbluebutton.properties (bbb-web)
                      bbb-web host: live.acadox.net

/var/lib/tomcat7/webapps/demo/bbb_api_conf.jsp (API demos)
                           api url: live.acadox.net

/usr/share/red5/webapps/bigbluebutton/WEB-INF/red5-web.xml (red5)
                  voice conference: FreeSWITCH
                     capture video: true
                   capture desktop: true

/usr/local/bigbluebutton/core/scripts/bigbluebutton.yml (record and playback)
                     playback host: live.acadox.net

`

**Comment by capilkey** [comment]
BigBlueButton 1.0 was released four years ago and we no longer support it.  My recommendation would be to setup a fresh Ubuntu 16.04 server and install BBB 2.2.

**Comment by vipinblue** [comment]
Thank you so much reply, can you tell me is there any option to upgrade instead of fresh install or I can get backup of database

**Comment by capilkey** [comment]
BigBlueButton doesn't have a database to backup. Theoretically you could probably upgrade the existing server, but if something goes wrong then you'll be left with no working BBB server. It's much safer to set up a new server and once the new server is working and you can run meetings you can copy the recordings over from the old server.

Steps for transferring recordings, http://docs.bigbluebutton.org/2.2/customize.html#transfer-published-recordings-from-another-server.

Extra steps due to the recordings being from such an old version, http://docs.bigbluebutton.org/2.2/customize.html#migrate-recordings-from-a-previous-version
