### ISSUE TITLE
Activation of microphone as listener - how to allow a single student to talk?

### ISSUE THREAD

**Issue by AInteriorB** [bigbluebutton/bigbluebutton#8934]
A typical situation is that I have a room of students and deny their microphones. Now there is no easy way to allow a single student to talk.

Option 1) I allow the microphones when the students join the room, but then I have a chaos of speaking students until I deny the microphones. (Mute is no option because they can enable it again).

Option 2) I disallow the microphones when the students join. In this case they automatically join as "listeners". If I now allow a single student to talk, he needs to quit and rejoin the audio conference with microphone enabled.

Is there no better way to handle this very common use case? We had the same problem in a virtual club conference where the board members should be allowed to speak but not the listeners. It is not easy to tell everybody to leave and join the audio conference again after they have been unlocked.

Thanks a lot :-)

**Comment by fenio** [comment]
So first of all thanks for this very nice project. We chose it cause it looks to be the most mature one and scalable. We would like to use it for schools as a solution for current lockdown ;)

I went over dozens of bugreports to make sure it hasn't been reported previously. This one is the most similar to mine concerns, suggestions so I'm using it instead of opening new issue.

I'm trying to find a way to make meeting more interactive and at the same time disallow students to make a mess. AFAICS it is possible to block students' microphones but only globally. Or to unmute them globally and then mute particular users. But I found no way to moderate discussion in an easy manner so block microphones by default and unmute student who wants to talk.

In some other issue I found explanation that possibility to unmute students was removed due to security concerns. Which is perfectly fine. But how about solution where student raises hand and then teacher unmutes him/her?

That would require making "raise hand" separate button and make status changes more visible for teacher but such issues were reported already (#7972, #2346) so this is something being worked on or at least considered. 

I find possibility to moderate meeting rather basic functionality and I'm pretty surprised the way it works currently. Are there any plans to improve it?
Or maybe it is possible to achieve stricter but flexible control over students with current version by configuration settings? I tried to look for it but I didn't find needed settings.

The reason I need that is because we're trying to deploy this solution for primary schools so for 8-12 years old kids. You can ask adults to behave politely and to mute and unmute only when they need it. It's pretty hard to convince children to do so ;)

**Comment by einhirn** [comment]
I'd suggest a modal dialog asking "Moderator XY asks you to unmute your Microphone - Yes go ahead / No, thanks".
This way the security concerns could be adressed properly. They would still apply after a hand was raised, because you don't know when your microphone will be unmuted.

**Comment by AInteriorB** [comment]
> I'm trying to find a way to make meeting more interactive and at the same time disallow students to make a mess. AFAICS it is possible to block students' microphones but only globally. Or to unmute them globally and then mute particular users. But I found no way to moderate discussion in an easy manner so block microphones by default and unmute student who wants to talk.

You can globally disallow microphones and then **unlock** single students. But then they have to rejoin the audio conference if they had joined as "listeners" (automatically). That's why I opened this issue.

**Comment by fenio** [comment]
Yeah I tried different ways of managing it and found them to be impractical.
If BBB aims at eLearning and not only as alternative to videoconferencing systems then I think ability to manage / moderate meetings should be improved.
Extra button to raise hand. Extra notifications of this fact to moderator. Ability to allow someone to talk. All of these need to be just easier and less confusing.

**Comment by pnijjar** [comment]
I use Greenlight. My workaround has been: 
- Set users to mute when entering the room (in Greenlight settings). They can then join with microphones.
- When class is going to start use the "Lock users" to lock microphones. The students will KEEP microphone settings.
- Now use "mute everyone except presenter" and make the student the presenter.

I agree that allowing people to join only with "listen only" if the lock settings prohibit microphones is the wrong behaviour. You should be able to join with microphones regardless. Then this problem goes away.

**Comment by matiasilva** [comment]
Usually students have the courtesy to mute themselves when others are talking. I would recommend you encourage this behavior.
