### ISSUE TITLE
Whiteboard: Cannot draw with Wacom tablet

### ISSUE THREAD

**Issue by fefrei** [bigbluebutton/bigbluebutton#8972]
**Describe the bug**
While sharing slides, the annotation tools don't work with an attached Wacom tablet.

**To Reproduce**
1. Have an external Wacom tablet attached.
2. Join a Meeting.
3. Become presenter.
4. Select the pen tool.
5. Drag accross the slide. Also, try tapping it.

**Expected behavior**
I expect the pen to work as if I used the mouse.

**Actual behavior**
The whiteboard tools freeze while the pen is down. More specifically:

- While the pen is hovering, the red dot is following my mouse cursor.
- Once the pen touches the surface, I can continue moving the mouse, but the red dot is frozen in place.
- Once the pen leaves the surface, the red dot follows the mouse again, and nothing was drawn.
- Tapping with the pen does result in a dot. (Dragging produces nothing, not even a dot.)

**BBB version (optional):**
`BigBlueButton Server 2.2.2 (1781)`

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Firefox
 - Version 74

**Additional context**
This may be the same problem as mentioned [here](https://community.canvaslms.com/thread/43316-bigbluebutton-on-macos-with-wacom-pen-tablet).

**Comment by DrBones** [comment]
Same issue is occurring on my end with a Wacom CTL-490 on Windows 10 in Firefox 74.0 (64-bit).

The pen becomes responsive again for me when disabling "Use Windows Ink" in the Wacom Settings under "Mapping". This however does not really fix the issue since then I see jittery artifacts when drawing/writing at a normal to quick pace. This does not occur with the mouse or with the pen in other programs (Photoshop, etc).

Neither issue exists in Chrome (80.0.3987.149 (Official Build) (64-bit))
With or without "Use Windows Ink" enabled, I can draw smooth lines. Also, I perceive the performance, especially the lag when drawing, to be much better. Which is a pity, since Firefox' performance is better in other areas and their privacy ideology seems to be much more agreeable.

**Comment by capilkey** [comment]
Drawing tablets should work and I've used a few different ones in the past fine. All we have access to are the mouse movements and whether or not a mouse button was pressed and we're reliant on the browser telling us those things.

A better test would be to try drawing in a different browser-based drawing tool because native applications aren't an equal comparison.

**Comment by Tainan404** [comment]
I tested it on a Wacom one and it works fine

**Comment by fefrei** [comment]
I can confirm that I also cannot draw in awwapp.com in Firefox using the Wacom tablet, so it's probably a Firefox issue.

**Comment by longxia01** [comment]
why not have a try with Browser chrome .

I tried an older [XP-PEN Star 06 digital painting tablet](https://www.xp-pen.com/product/49.html) with zoom whiteboard and found that It's not great but it'll get the job done.
