### ISSUE TITLE
HTML client development server stuck at 3 loading dots.

### ISSUE THREAD

**Issue by akshaykatale99** [bigbluebutton/bigbluebutton#8981]
i have installed development code. it runs and compiled successfully but stuck at loading 3 dots..

Showing this in after compile..

=> Started your app.

=> App running at: http://localhost:1414/
I20200403-18:58:36.856(0)? info: {"logCode":"was_not_provided","logDescription":"Connection to Meteor took 0.00s","extraInfo":{"validUser":"notFound"},"userInfo":{}}

but when try to access it on browser it stuct at this - 

![image](https://user-images.githubusercontent.com/12472207/78395723-a26d2080-760b-11ea-8428-7e13ee8c40e3.png)

**Comment by mrzegocki** [comment]
i have the same situation, but i installing via bbb-install.sh (fresh ubuntu 16 server LTS). When i tried join into room via greenlight i have 3 stucked dots, after few second i got 401.

in Web browser console i see: 

uncaught exception: Call to userChangedLocalSettings failed because Meteor is not connected

**Comment by matiasilva** [comment]
For development support => https://groups.google.com/forum/#!forum/bigbluebutton-dev, for general support => https://groups.google.com/forum/#!forum/bigbluebutton-setup.
