### ISSUE TITLE
notReadableError: Could not start video source 

### ISSUE THREAD

**Issue by agustinmono** [bigbluebutton/bigbluebutton#9000]
A few users have tried to share the webcam and they have this error:

"notReadableError: Could not start video source "
http://prntscr.com/ru7db6

they tested on a different software and the webcam its functional
https://imgur.com/a/d5NoHUb

alto chrome permissions are ok
https://imgur.com/a/hqWBVyq

Thanks

**Comment by prlanzarin** [comment]
@agustinmono NotReadableError usually mean one of two things: the webcam is already in use by another application and/or the browser can't fetch the device due to incompatibility issues. 

Correct way of troubleshooting this issue with your users is testing it in another browser based application. Recommend trying it out on https://webrtc.github.io/samples/src/content/getusermedia/gum/.

Trying it out on a native application (like in the screenshot you pasted) helps little.

**Comment by basisbit** [comment]
@agustinmono were you able to resolve this problem? Can this issue be closed?

**Comment by christf** [comment]
I am also seeing this when I have multiple /dev/video devices and one of them is being blocked.
This means other devices cannot be used.

**Comment by prlanzarin** [comment]
@christf  yes, we are aware of that. The adequate issue for this is https://github.com/bigbluebutton/bigbluebutton/issues/9943.
Hopefully I'll be able to tackle this soon.

**Comment by christf** [comment]
thank you - in that case, no need to re-open this one.

**Comment by pbek** [comment]
I also get the error message `NotReadableError: Could not start video source` in Chrome (or a similar one in Firefox) when I have a physical webcam and a virtual webcam (OBS Studio) under Linux. The physical webcam is used by OBS and BBB seems to try to access the physical webcam (that is in use) instead of letting the user select which webcam to use. The virtual webcam works perfectly with https://webcamtests.com/ or other webpages.

**Comment by prlanzarin** [comment]
As I said, the adequate issue for this is https://github.com/bigbluebutton/bigbluebutton/issues/9943, and it has been fixed by https://github.com/bigbluebutton/bigbluebutton/pull/11068 (which will land in the next release).

**Comment by pbek** [comment]
Ah, sorry and thank you very much, @prlanzarin!
