### ISSUE TITLE
Use lossless or wideband audio codec

### ISSUE THREAD

**Issue by trs80** [bigbluebutton/bigbluebutton#9015]
**Describe the bug**
We have music tutors trying to teach over BBB, and they've noticed some compression and other audio glitches. I see that BBB is using Opus, is there any way to make it use a wideband codec like G.722 or a higher bitrate.

**To Reproduce**
1. Conduct a music lesson over BBB

**Expected behavior**
Audio is clear 100% of the time

**Actual behavior**
Audio is compressed and artifacted occasionally

**Additional context**
Obviously there's device audio quality issues that we're looking at, but it'd be nice to eliminate the codec as a possible problem. I tried editing freeswitch vars.xml putting PCMA at the start global_code_prefs and outbound_codec_prefs but it still negotiated Opus.

**Comment by Arthus** [comment]
Hi,
just a random guy passing by. I currently don't run BBB myself, but maybe I can help you.

Please have a look at https://github.com/bigbluebutton/bbb-webrtc-sfu/blob/6a6425a057684ba749809ba85298a5c94325fcfa/config/default.example.yml
In line 188 the Opus Bitrate is set to 30kBit. Naturally that won't be enough for music. Maybe you can increase that to 64kBit vor even 96kBit and test your quality again.

G.722 won't hell at all. Those Codecs are not meant to be used for music and use a max sampling rate of 16kHz and have a frequency range of only 50 to 7000Hz. G.722 will propably only make things worse. Because of that you also have to check: 
Afaik Chrome doesn't support Opus for WebRTC so your lecturer nicht want to usw Firefox, so Opus (your only real choice for music) can even be used.

**Comment by trs80** [comment]
I don't think that file is relevant since the audio goes to FreeSwitch, not the SFU. Looking at the SDP, I see `a=rtpmap:111 opus/48000/2`. I found `/opt/freeswitch/conf/autoload_configs/conference.conf.xml` which has a plausible `<profile name="video-mcu-stereo">` but increasing the rate there didn't change the SDP.
