### ISSUE TITLE
Users appearing in wrong room (accidental "room hijacking")

### ISSUE THREAD

**Issue by defnull** [bigbluebutton/bigbluebutton#9024]
**Describe the bug**
Several users have reported that they joined the wrong meeting after following a greenlight invitation link. The greenlight room id, external and internal meeting IDs are all completely different, so there is no ID conflict. We cannot find any hints in the (very verbose) logs how that may have happend.

**To Reproduce**
Not reproduce-able, but happened at least twice (BBB 2.2.2 and 2.2.3) on a heavily loaded server with about 350 participants and 100 meetings.

**Expected behavior**
Users join the meeting they expect.

**Actual behavior**
Users join a different meeting and everyone involved is quite confused. This affects multiple users, but only a single meeting at a time. We had an entire group of users accidentally bombing a running conference today.

**Additional context**
We also see Kurento accumulate open UDP sockets until a limit of around 30k is reached, at which point we have to restart Kurento. This seems to confuse bbb-webrtc-sfu (I think), which leads to 'duplicate' users in many rooms. Not the same issue, but probably related.

**Comment by capilkey** [comment]
You would only get crossover if you had a collision on the meeting name or voice bridge. If you know the name of a user that should have been in the room and a user that shouldn't have been in the room you can find their join URLs and figure out what went wrong.

You can find the URLs in /var/log/nginx/bigbluebutton.access.log

**Comment by defnull** [comment]
All relevant IDs (Greenlight `/b/<id>` link, `<meetingName>`, `<meetingID>`, `<internalMeetingID>`) were distinct and the affected groups did not know each other, so it can be ruled out that they just accidentally clicked the wrong link. There are no duplicates in the Greenlight rooms table, or the meetings listing of BBB. The two rooms still exist, we did not change anything, but now the mixup no longer happens for that pair of rooms. So the issue is just temporary. But it happened three times in two days now, so there must be _something_ going on under the hood. I'll try to extract the relevant requests from the logfile.

**Comment by defnull** [comment]
According to the access logs, there were no conflicts. The `/bigbluebutton/api/join` requests have correct and distinct `meetingID`s. The `sessionToken`s are distinct.

**Comment by capilkey** [comment]
What about the voice bridge

**Comment by capilkey** [comment]
I don't know if Greenlight passes specific voiceBridges so you might have to get the meeting information to know for sure. Or you could also look in the FreeSWITCH logs for the two users. The FS logs are in /opt/freeswitch/var/log/freeswitch/freeswitch.log

**Comment by mouhsinelonly** [comment]
same thing happend to me but as @capilkey said it was due to same voicebridge port been used, that is way i omitted sending voicebridge port and left to bbb to handle it.

**Comment by defnull** [comment]
I see both users getting the same vbridge despite being in different BBB rooms according to the access logs and meetings listing at that time. The timing matches the incident.

    53e6d939-cc33-43d0-997b-119af718f166 2020-04-07 12:44:20.343576 [DEBUG] mod_dptools.c:1672 SET sofia/external/w_oXXX_1-bbbID-Tim XXX@XXX.de [vbridge]=[82455]
    0eec0412-3c34-4b09-8b7e-9ec6facc4223 2020-04-07 13:12:55.683613 [DEBUG] mod_dptools.c:1672 SET sofia/external/w_2XXX_1-bbbID-Hannes XXX@XXX.de [vbridge]=[82455]

That is the issue (I guess). How can this happen? What next?

**Comment by capilkey** [comment]
`sudo zgrep "82455" /var/log/bigbluebutton.access.log*`

Post that result back. Make sure to remove the checksums at the end of the URLs

**Comment by defnull** [comment]
No relevant matches. The `/api/join/` requests do not contain an explicit voice bridge.

**Comment by defnull** [comment]
In syslog: 

    Apr  7 12:44:17 bbb-test bbb-apps-akka[1176]: https://XXX.de/b/tim-cz3-p4t),VoiceProp(82455,82455,613-555-1234,true), ...
    Apr  7 13:12:42 bbb-test bbb-apps-akka[1176]: http://XXX.de/b/han-knk-7c6),VoiceProp(82455,82455,613-555-1234,false), ...

**Comment by capilkey** [comment]
I was looking for the create request for the meetings.

If no voice bridge is passed on the create then bbb-web will generate a random one. I'm not familiar with how the voice bridge generation happens, but it might be possible that there's a chance for a collision to occur if it doesn't check to see if the voice bridge is unused.

**Comment by defnull** [comment]
> I was looking for the create request for the meetings.
Both meetings were quite old. I'll search for the matching log entries tomorrow, if they are still there and not rotated out.

**Comment by mouhsinelonly** [comment]
This issue happened again it is rare but it does happen I think assigned voice bridge port should be checked if it is in use or not before assigning it to another session

**Comment by defnull** [comment]
Greenlight does not set a voiceBridge when creating meetings, so the mechanism how "BigBlueButton will assign a random unused number for the meeting." must be flawed somehow?
Oh, and the customer reported that chat was also mixed up. Is chat bound to the voiceBridge number, or is that a completely different issue?

**Comment by symptog** [comment]
We've also got colliding meetings.

```
$ grep 16499 /event | grep -i bridge | sort -u
2f169fb188c7928b214d1de23e6a69b211068ac1-1587021187639/events.xml: <bridge>16499</bridge>
37f1e19b73258a52ad3976a56e97d3a131962adf-1587023750593/events.xml: <bridge>16499</bridge>
```

https://github.com/bigbluebutton/bigbluebutton/blob/v2.2.5/bbb-common-web/src/main/java/org/bigbluebutton/api/ParamsProcessorUtil.java#L335

`processTelVoice` only generates a random number if none is stated. 

Contrary to what is stated in the documentation, the VoiceBridge is not unique to the freeswitch.
It is not checked whether the VoiceBridge is already in use.

**Comment by mouhsinelonly** [comment]
anyone has any idea how to fix this, even if it is a workaround ?

**Comment by JurRutten** [comment]
+1 We are experiencing the same issue, any ideas/workarounds?

**Comment by defnull** [comment]
You can increase the number of digits for the conference key and reduce the risk of collisions via https://github.com/bigbluebutton/bigbluebutton/blob/41f19a2cd1bc7dae76cbd805cdc3ddfbf1e6ab18/bigbluebutton-web/grails-app/conf/bigbluebutton.properties#L114 I guess. Not really a solution, though.

**Comment by JurRutten** [comment]
We start meetings using the api, we will be implementing our own 'unique generator' and will handing this to the api. This should solve the problem for us.

**Comment by ritzalam** [comment]
In `/opt/freeswitch/conf/dialplan/default` change these 2 files

```
bbb_conference.xml
bbb_echo_test.xml
```

Change `\d{5,6}` to `\d{9,10}` which changes the voice conf to 9-digits with the 10th digit the breakout room.

Change `bigbluebutton/bigbluebutton-web/grails-app/conf/bigbluebutton.properties` `defaultNumDigitsForTelVoice=5` to 9. 

Or when calling the api, pass the voiceBridge param with the 9-digit number.

**Comment by elor** [comment]
First off: I've been the moderator of the colliding meeting mentioned by symptog.
I'd like that not to happen again, so here goes:

I can see a few ways of fixing this issue.
I'm still working on setting up a working test environment, though.

There are two different problems:

1. Randomly generated voicebridge Id isn't guaranteed to be unique
2. API-provided voiceBridge Id isn't checked for uniqueness (as far as I can see)

Fortunately, only primary webrooms are affected.
Breakout rooms only append a single-digit identifier to a supposedly unique VoiceBridge Id, so they should remain unique, excluding MeetingService.java from changes.

I'll concentrate on Problem 1.
Problem 2 is outside the scope of this Issue (#9024).

The following files are involved:
[ParamsProcessorUtil.java](https://github.com/bigbluebutton/bigbluebutton/blob/v2.2.5/bbb-common-web/src/main/java/org/bigbluebutton/api/ParamsProcessorUtil.java#L630): processCreateParams() calls processTelVoice(), which generates a random VoiceBridge Id through
org.apache.commons.lang3.RandomStringUtils.
[ApiController.groovy](https://github.com/bigbluebutton/bigbluebutton/blob/v2.2.5/bigbluebutton-web/grails-app/controllers/org/bigbluebutton/web/controllers/ApiController.groovy#L134): Passes the results of processCreateParams() directly to MeetingService.createMeeting() without validation
[MeetingService.java](https://github.com/bigbluebutton/bigbluebutton/blob/develop/bbb-common-web/src/main/java/org/bigbluebutton/api/MeetingService.java#L278-L288): createMeeting() doesn't check for VoiceBridge ID collision. MeetingService.meetings is the list of current and past meetings.

The issue could be fixed in all three files:
`ParamsProcessorUtil`: Collisions could be checked early. Would require an API change. Too invasive in my opinion.

`MeetingService`: createMeeting() could `return false` if VoiceBridge or WebVoice are equal to an entry in MeetingService.meetings. Would result in the wrong error message (`nonUniqueMeetingIdError`) instead of the meeting collision, but if the wrong VoiceBridge Id made it this far, it's probably best not to start the colliding meeting and get a slightly wrong error instead.

`ApiController`: Call `processTelVoice()` and validate against current meetings before calling `processCreateParams()`. Retry on TelVoice collision. Requires inclusion of ApiParams.
`IMeetingService.java` hints at the unimplemented method `  boolean isMeetingWithVoiceBridgeExist(String voiceBridge);`, which would be ideal and relatively easy to implement - maybe I'll do that.

I'll try the following:
1. `return false` in MeetingService.createMeeting() if a colliding meeting exists (TelVoice and WebVoice) - this avoids meeting collisions even when forced through the API, also solving Problem 2.
2. Retry `processTelVoice()` a few times until a unique VoiceBridge Id is generated. This avoids ApiErrors when no TelVoice was passed to the API.

What do you think?

What did I miss?

Merge Request in preparation, but I'd really like to test it properly first.

**Comment by KimBrodowski** [comment]
We're also affected and will deploy the workaround mentioned above for now.
