### ISSUE TITLE
Reducing the number of concurrent threads

### ISSUE THREAD

**Issue by renehamburger** [bigbluebutton/bigbluebutton#9035]
I'm sorry for having to post this here, but there was no response to [my two posts on this](https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/bigbluebutton-setup/H_6ySxFvm8E/aMe6J4fwAwAJ) in the BigBlueButton-Setup group: Is there any way to limit the number of concurrent threads the BBB-services start? I tried using the JAVA switch `-Dserver.tomcat.max-threads=5` for some of the BBB Spring Boot applications and also some of the config settings that appear to relate to the number of threads in `/usr/share/red5/conf/red5.properties`, but neither had any effect.

**Comment by basisbit** [comment]
You might want to take a look at the bigbluebutton [architecture summary](http://docs.bigbluebutton.org/2.2/architecture.html) . You'll see that bbb uses a bunch of different applications for various tasks. BBB is not just one single application where you could easily limit the amount of threads.

Anyways, your virtualization environment sounds like it won't be suitable for a real-time audio/video relaying application at all. BBB (especially freeswitch and kurento) needs almost exclusive access to the CPU cores without any scheduler occasionally deciding that something else might be more urgent or otherwise there will be very likely bad audio-/video quality. Thats also one of the reasons why the BigBlueButton documentation suggest to install bbb on a bare metal / dedicated physical server, not just a "dedicated virtual machine": see http://docs.bigbluebutton.org/2.2/install.html#minimum-server-requirements

**Comment by basisbit** [comment]
closing this issue here because limiting the amount of concurrent threads is not desirable for any BigBlueButton service in production. Please don't try running BigBlueButton servers on such resource-starved virtualization platforms which are not suitable for low-latency audio&videoconferencing platforms.
