### ISSUE TITLE
Mute button not showing after lock/unlock viewers.

### ISSUE THREAD

**Issue by hasahmad** [bigbluebutton/bigbluebutton#9087]
When your start meeting and Lock Viewers -> lock Mic. Save Settings.
Now when someone joins, they do not see the mic button (cannot mute or unmute themselves).
Even after unlocking the settings and refreshing the page the user still cannot see mic button to unmute themselves.

**Comment by ffdixon** [comment]
When the viewer's microphone is locked, viewers are joining as Listen Only, which means they are subscribing to an audio stream served by Kurento.

Since it's listen-only, there is no mute/unmute of a microphone.

This is an optimization to reduce CPU overhead -- it's more efficient to listen to an audio stream than join a 2-way audio stream and be muted.

We might change this in the future, but the listen only audio stream allows more people to join a session as the CPU overhead is less.
