### ISSUE TITLE
User limit calculator

### ISSUE THREAD

**Issue by Quadrocompile** [bigbluebutton/bigbluebutton#9142]
**Is your feature request related to a problem? Please describe.**
I find it very hard to estimate the numer of user my server is able to handle. E.g. my server well exceeds the minimum requirements. Taking the estimated 150 users for the minimum requirements into account, the server should be able to handle a lot more.

**Describe the solution you'd like**
A "best effort" calculator in which you can enter your hardware specc to get a rough estimate of the number of supported user.

**Additional context**
E.g. my server runs on a i7-6700 with 4cores/8threads@3,4Ghz, 64GB DDR4 mem and a dedicated  1GBit/s link. What would be a rough estimate for this hardware configuration?

**Comment by iSamof** [comment]
I like the idea and note your (reasonable) "best effort" assertion.

The challenge is, for the same spec you may be able to sustain hundreds of audio only users and no schreen share/recording/presentation while a maximum of 50 users could stress the server when 30 of them share medium res video and there is screen sharing too.

Building on your idea, if such a calculator is created (not difficult to do):
- the output could provide estimates rough for typical scenarios of 
  Heavy usage (X videos and ...)
  Medium usage (presenter video only and screen share)
  Low usage (audio and chat only and ...)
- Some way for contributors to contribute specs and data to a pool to empirically refine the estimates over time

We are using Netdata which is a fantastic free tool suggested by BBB team (many thanks for that) and we are getting surgical information on every resource on our servers when meetings are happening. 

The OP could install this to gain major insights re capacity. But the wider point is this: Netdata's db can be exported. This could provide the empirical engine for the Capacity Planning and Estimation tool --> CaPE :-)

**Comment by basisbit** [comment]
How would you handle 
- different CPU architectures (current Xeon 8 core + HT vs a few years old Avoton 8 core - maybe 10x difference in supported video users count), 
- bare metal vs LXC vs kvm vs VMware and overprovisioning,
- various features like recording or chat being enabled/disabled
- different webcam stream bandwidths
- different TLS / nginx / firewall / buffering / ... configurations
- certain parts being single-threaded like node.js & event-processing, thus limiting the maximum users count for a single server (to something between maybe 150 to 400?)

Instead of writing such a user limit calculator tool, I'd suggest improving the already available documentation and 
- especially explaining why bare metal or at least dedicated CPU cores are so important, 
- explaining why 1000 users in one session doesn't work even with a 64 core CPU server and a TB of RAM, 
- explaining how Scalelite helps in loadbalancing sessions to the available servers,
- explain that BBB does MCU for audio and SFU for video
- explain that client bandwidth and CPU especially on a bit older hardware limits amount of concurrent video participants while still at usable performance

**Comment by TriStarGod** [comment]
Why not create a list for people to report their setup and the capacity they can support? Its not an exact spec but with more data, a better estimate can be determined.

**Comment by adriansalvatori** [comment]
"explaining why 1000 users in one session doesn't work even with a 64 core CPU server and a TB of RAM,"

Where can I get more info about this?

**Comment by basisbit** [comment]
>Where can I get more info about this?

by reading various forum threads about this topic. The tldr is: All the UI events are transmitted and processed by code written using meteor and running in a NodeJS process. NodeJS is mostly just single-threaded where you need access to the session state. Thus the limit of how many users can use one BBB server in one or a few sessions is limited by how much a single CPU core can handle. Thus, set up Scalelite as horizontal sessions load balancer and thus split different sessions to different server.

**Comment by ffdixon** [comment]
To add to this issue, there is work underway in BigBlueButton 2.3 (still in development) to provide multiple meteor (and therefore multiple NodeJS processes).  See

  https://github.com/bigbluebutton/bigbluebutton/pull/8788

**Comment by pedrobmarin** [comment]
Doesn't the docs have anything regarding this?
