### ISSUE TITLE
Problem: Telephone dial-up is only possible if at least one person with a microphone has joined

### ISSUE THREAD

**Issue by Sea444** [bigbluebutton/bigbluebutton#9161]
**Describe the bug**
SiP-Connection is activated. When calling BBB-Server I hear "Please enter the conference pin number". After entering the pin number connection stops, phone call is terminated.

**To Reproduce**
1. Call phone number of BBB-Server
2. Wait until you hear "Please enter the conference pin number"
3. Enter conference pin number

**Expected behavior**
User is connected to the conference.

**Actual behavior**
Phone call is terminated by BBB-server.

**Smartphone (please complete the following information):**
 - different phones

Does anybody has an idea how to fix this problem?

**Comment by cnet24** [comment]
I noticed the same problem that the PIN code, although it was generated, is not active until the head conference starts, i.e. at least one user must log into the room as a listener.
I think this is not a desirable effect.

**Comment by ffdixon** [comment]
Are you pressing the `#` key at the end?  

Check the settings in `/opt/freeswitch/etc/freeswitch/autoload_configs/conference.conf.xml` which defines the keys as

~~~
    <group name="default">
      <control action="mute" digits="0"/>
      <control action="deaf mute" digits="*"/>
      <control action="energy up" digits="9"/>
      <control action="energy equ" digits="8"/>
      <control action="energy dn" digits="7"/>
      <control action="vol talk up" digits="3"/>
      <control action="vol talk zero" digits="2"/>
      <control action="vol talk dn" digits="1"/>
      <control action="vol listen up" digits="6"/>
      <control action="vol listen zero" digits="5"/>
      <control action="vol listen dn" digits="4"/>
      <control action="hangup" digits="#"/>
    </group>
~~~

If you comment out the last entry, as in

~~~
      <!-- control action="hangup" digits="#"/-->
~~~

then users won't inadvertently hang up when they press `#`.

**Comment by cnet24** [comment]
I did not make myself clear. I meant that if we want to join the room and we are the first user despite the fact that the PIN code has been generated, it is not active because there is no conference on FreeSwitch yet.

![2020-04-21_091034](https://user-images.githubusercontent.com/48276574/79836073-fe77c900-83af-11ea-9d41-526d638b2aa7.png)

**Comment by tisoft** [comment]
I had the same problem, I commented out one of the conditions in the example dial plan:

```
<extension name="check_if_conference_active">
 <!--condition field="${conference ${pin} list}" expression="/sofia/g" /-->
 <condition field="destination_number" expression="^SEND_TO_CONFERENCE$">
   <action application="set" data="bbb_authorized=true"/>
   <action application="transfer" data="${pin} XML default"/>
 </condition>
</extension>
```

This seems to work for me and sends the phone call to the correct room. This does have a caveat though. Now every pin is accepted, if it doesn't match a valid conference pin, a new SIP conference is created. This does not create a room in BBB, though. At least it is usable for me now this way.

The real bug is probably that something in the `<condition field="${conference ${pin} list}" expression="/sofia/g" />` condition is incorrect.

**Comment by hbruch** [comment]
To my understanding, the first participant should not automatically start the session. I‘d expect him/her to hear a message like ‚the conference has not been started yet, please wait‘ or alike.
That way, the moderator would need to start the conference via bbb. Later on, one could introduce a moderator PIN to start a conf via PIN.

**Comment by Sea444** [comment]
@ffdixon : Maybe this should be labeled as bug?

**Comment by Sea444** [comment]
@tisoft Workaround works. :-)
@hbruch Yes, a "the conference has not been started yet, please wait" would be great. But workaround of tisoft ist better than just terminating session like BBB does at the moment...

**Comment by lonesomewalker** [comment]
I consider this not as a bug.
One person should at least be in the conference, otherwise the PIN can't be known.
So this person easily could start the FreeSWITCH session.

Otherwise: what should the person calling from outside expect?
Music on hold? Silence?

**Comment by alexanderjackson** [comment]
If the first person decides to close the "How would you like to join the audio?" modal without selecting "Microphone" or "Listen only" it's also not possible to access the meeting via dial-in.

Same issue if everyone decides to "Leave audio" and no one else is dialed in. 

Currently there must always be at least one active audio channel before anyone can gain access via phone. So I would consider this a bug..

**Comment by tisoft** [comment]
I see several possible options here:

- If the audio conference is not open yet, open it as soon as the first person calls in.
Maybe add a message "You are the only person in this conference"
  - This is a bit like my workaround, but my workaround will always succeed, so if a user dials the wrong meeting PIN he will be in an empty room unconnected to any real meeting, this should not happen
- If the audio conference is not open yet, put the phone caller in a waiting room and transfer him to the meeting as soon as
  - it is started by someone using the computer audio
  - someone allows them in the meeting manually (something like the waiting room feature for meeting rooms)
  - someone with a moderator pin joins by phone
    - Mostly usefull, if the moderator/user PINs for a room would be static, so phone only conferences would be possible
- Only show the phone dialin information as soon as the first person has joined by computer audio. At least the conference is open then
- Have personal phone PINs, so each user not connecting with computer audio will get his own pin, which is attached to his video session. Downside would be, no phone only users (I think this is how zoom does it)

My personal favorite combination of the options would be:

- Have static moderator/user PINs per meeting room, so they can be send out together with the meeting link, this also allows to use bbb for phone only conferences
- If a user joins the web meeting and clicks the phone button there, he gets a personal pin, that "joins" the web session with the phone session. The phone would now work the same as the users computer microphone, so clicking mute would mute his phone, transfering the web user to an breakout room will transfer the phone, too
- If the meeting has no waiting room configured, allow each phone caller directly into the audio conference. Play a message You are the only participant/There are X participants in this call
- If the meeting has a waiting room, put phone callers in a waiting conference and play a message stating that, maybe play some horrible music :hear_no_evil:  The phone call would be transferred to the real conference, as soon as it is allowed by a moderator in the web UI or someone joins with a moderator PIN
- If a user dials an invalid PIN, ask him again for the PIN

Hope you get my ideas. :smile: 

All options from a user perspective. I have no clue what is possible technically...

**Comment by Sea444** [comment]
I don't see why there sholud be a difference between joining by computer/micro or dial-in. 

Expected behaviour:

- First audio participant gets "You're currently the only person in this conference" and then silence or music (https://docs.bigbluebutton.org/2.2/customize.html#enable-background-music-when-only-one-person-is-in-a-session)


Actual behaviour

- computer/micro: first audio participant gets :"You're currently the only person in this conference" and then silence or music (https://docs.bigbluebutton.org/2.2/customize.html#enable-background-music-when-only-one-person-is-in-a-session)

- dial-in: first audio participant can't join audio conference. Phone call is terminated without any informations to the caller



Maybe @liske could help? He/she made a PR for Freeswitch dialplan in https://github.com/bigbluebutton/bigbluebutton.github.io/pull/137/files

**Comment by liske** [comment]
The root cause is the condition checking as @tisoft  has already found in 
 https://github.com/bigbluebutton/bigbluebutton/issues/9161#issuecomment-617601390

It is reproducible using the `/opt/freeswitch/bin/fs_cli` command. Before *any* audio channel is enabled (no need for microphone):

```
freeswitch@hostname> conference list
+OK No active conferences.
```

As soon at least one single user enables listen (or listen+mic):

```
freeswitch@hostname> conference list
+OK Conference 23340 (1 member rate: 48000 flags: running|answered|enforce_min|dynamic|exit_sound|enter_sound|json_status)
18;sofia/external/GLOBAL_AUDIO_23340@X.X.X.X;a2fe4f49-f5ea-4c8b-96e0-d0988e65cdaa;GLOBAL_AUDIO_23340;GLOBAL_AUDIO_23340;hear|speak|floor;0;0;100
```

Removing the condition is IMHO no valid option since the user would not recognize wrong PINs. I also think it should be absolutely valid option to use a BBB meeting with dialin users, only.

Adding a simple API endpoint for PIN validity checking or adding some dummy conference party on meeting start (i.e. something like /dev/null sink) could work.

**Comment by lonesomewalker** [comment]
Seriously, if you want a dialin-only conference, please install FreeSWITCH.

**Comment by Sea444** [comment]
@lonesomewalker : I think that was misleadingly expressed. It's not about classic telephone conferences, but web conferences (e.g. with chat, whiteboard, screen sharing, ...), in which all participants (have to) join in via telephone/dial-in.
Many workplaces in companies and public authorities are classically equipped with normal computers, monitors and landline telephones. Due to the lack of a microphone/headset, these employees are forced to dial in via telephone. 

@liske 

> Adding a simple API endpoint for PIN validity checking or adding some dummy conference party on meeting start (i.e. something like /dev/null sink) could work.

Yeah, that would be great. Unfortunately I cannot implement this myself. I hope someone has the experience and time to fix this bug.

**Comment by steffen-moser** [comment]
I would clearly consider the current behavior as a bug. 

At least it generates support requests from time to time and we already had teachers who broke up (or, let's better say, didn't even start up) sessions because of this. It is not so uncommon. 

Germany's broadband internet infrastructure, especially in rural areas, is not the best, politely spoken. Some people (and some of our professors) are required to use 3G or 4G cellular connectivity in order to bring their home-network online. In the evening hours, when we offer courses for extra-occupational leaners, these cellular networks are often heavily loaded. While the available data rates are sufficient for showing slides or using a common whiteboard in Big Blue Button, the audio easily gets disturbed due to large latency jitter or even packet loss. For this reason, the teachers who know about this situation start using the phone from the beginning. They have a plain old telephone line as an alternative. 

When they join as the first users and nobody has connected with microphone mode or at least listen-only mode, they are kicked off after typing the PIN. This is not intuitive and should be fixed.

Interesting note: We also have people who can still transmit a stuttering low-resolution video stream. Listeners typically accept low quality and interruption time there. At the same time, they won't accept a low-quality audio signal. 

Switching to a plain audio-conference is not a solution. BBB offers great features for collaborative work. As the phone support is there, I don't see any reason why we should not make it as comfortable and intuitive as possible for the users.

**Comment by MarcelWaldvogel** [comment]
I think this bug should be fixed (I just ran into it myself while testing dialin).

However, if — for whatever reason — it should not be fixed, then the first user (actually, any user before the first successful audio join), should not see the phone option (here: "Mit dem Telefon teilnehmen") in the audio selection dialog.
![Screenshot from 2020-05-16 15-46-28](https://user-images.githubusercontent.com/3014737/82121325-74dbd100-978c-11ea-9b2c-59b7a54217d5.png)

**Comment by noodles101** [comment]
The dial-up user should at least get an audio message that therea are no users are in the room before it hang up.

**Comment by andbag** [comment]
This dial plan informs the user to dial in again later before BBB hangs up. The playback is a composition of existing sound snippets.

```xml
<extension name="from_my_provider">
 <condition field="destination_number" expression="^EXTERNALDID">
   <action application="answer"/>
   <action application="sleep" data="1000"/>
   <!-- workaround for issue 9478 -->
   <action application="play_and_get_digits" data="5 6 3 7000 # ivr/ivr-please_enter_pin_followed_by_pound.wav ivr/ivr-that_was_an_invalid_entry.wav pin \d+"/>
   <action application="transfer" data="SEND_TO_CONFERENCE XML public"/>
 </condition>
</extension>
<extension name="check_if_conference_active">
 <condition field="${conference ${pin} list}" expression="/sofia/g">
   <condition field="destination_number" expression="^SEND_TO_CONFERENCE$">
     <action application="set" data="bbb_authorized=true"/>
     <action application="transfer" data="${pin} XML default"/>
   </condition>
   <!-- audio message if no users are in the room: "You are the only person in the conference or that was an invalid entry. Please try it again. Goodbye." -->
   <anti-action application="set" data="playback_delimiter=!"/>
   <anti-action application="set" data="playback_sleep_val=500"/>
   <anti-action application="playback" data="conference/conf-alone.wav!ivr/ivr-or.wav!ivr/ivr-that_was_an_invalid_entry.wav!ivr/ivr-please_try_again.wav!conference/conf-goodbye.wav" />
 </condition>
</extension>
```

**Comment by fireba11** [comment]
@andbag that's an improvement, however fixing this would be important for our use case:
we got quite a lot of users not having audio eqipment (or at least no mic) with their PCs, so they want to use BBB to share screen, presentation etc. and all use dial-in in addition to their browser. currently due to this issue that is not possible, and they lack the mic needed to open the audio.

**Comment by andbag** [comment]
@fireba11 During my tests no microphone was necessary. It was sufficient if at least **one participant** joined the conference via BBB with "listen only". I know that it is a workaround, but do the users' computers really have no sound device to select "listen only"? Even if the device is not used for active listening.

**Comment by fireba11** [comment]
@andbag thanks for the hint, i'll verify that. if yes it would be a viable workaround for now

**Comment by FreeScholar** [comment]
Suggestion from a non-coder...If the first person to enter is on dial-in phone, how easy would it be to trigger the creation of a 'ghost user' that could enter the room first, using audio and create the PIN The ghost user would be invisible and could be removed by the next audio user that logs in, or remain throughout a session with all parties on dial-in phones?

**Comment by hostbbb** [comment]
The 1 person in conference code, stops anyone from entering a 5 digit number and fat fingering the wrong one and ending in empty conference room.   the dialplan makes sure the conference exists already. Also fraud can initiated by users having free audio conferences...  enter 77777 and everyone uses freeswitch.

Alternatively.... it is possible to have the dialplan look at BBB's backend, and verify the voicebridge is currently associated with a valid meeting.  With this code,  there is no longer the need to have someone joined first...  As long as the vbridge matches one from an active meeting you let them in.  This can be done by looking at mongo collection, or making getMeetings API call to bbb web.

The is done by adding a inline DB call in freeswitch dialplan....  doable with a few lines of code.

The issue is when using a load balancer,  is to take 1 number, and route the call to the proper BBB server.  in this case you need to ensure the conference number is unique across the cluster.
