### ISSUE TITLE
CPU usage 90%

### ISSUE THREAD

**Issue by agustinmono** [bigbluebutton/bigbluebutton#9180]
Hi, The Datacenter tells me that im at 80% of the CPU usage

My server machine should be able to hanlde +1500 users acording to documentation,
how can I improove the performance? or what would be a good setup for 1500 users

![image](https://user-images.githubusercontent.com/50418223/79872731-895ec080-83bc-11ea-84b8-46e10ec5133a.png)

each of the 8 servers:

![image](https://user-images.githubusercontent.com/50418223/79873748-e018ca00-83bd-11ea-8778-e1014cb5420f.png)

is there a way to setup a maximun ammount of cammeras?

**Comment by beatwiz** [comment]
In our case, high load is due to webcam usage derives from the number of active connections. When the load is high, CPU and RAM usage is always below 10%. But the number of connections, thats a different story.

Just now, a server that has 45 active webcams, if they share the webcams not only to the presenter, but between themselves:

netstat -an | wc -l
10679 

+10k active connections and the load goes skyrocket

Anyone has any idea if this can be optimized?

**Comment by agustinmono** [comment]
Cant tell how many connections but CPU went to 100% , not the virtual cpu, the phisic CPU

**Comment by tarunb999** [comment]
@agustinmono where can I view the details you showed in your first message please? 
Are there any set of server commands in bbb installation?

**Comment by meuhland** [comment]
Somehow I'm thinking you are hitting the same wall a bunch of us are hitting regarding kurento as seen in a couple issues including : #8982

**Comment by agustinmono** [comment]
> @agustinmono where can I view the details you showed in your first message please?
> Are there any set of server commands in bbb installation?

first image is the Scalelite server
https://github.com/blindsidenetworks/scalelite/

second image is the comand:  
`lscpu`

**Comment by iSamof** [comment]
This may help: 

Reducing webcam quality to low discussed here: https://github.com/bigbluebutton/bigbluebutton/issues/9007

They also discuss performance in this thread (about speeding up recordings): [8770](https://github.com/bigbluebutton/bigbluebutton/issues/8770)

If possible, I think it would help to use one ticket for performance ... it would be easier to keep up and avoid repetition.

**Comment by basisbit** [comment]
@agustinmono where did you get the numbers from that made you think the 24 cores bare metal server running vmware machines can handle 1500+ concurrent users? The minimal hardware requirements states 4 CPU dedicated bare metal CPU cores for roughly 100 concurrent users using audio and a few using video. 24/4=6 "servers within requirements". Let's assume roughly 10% of CPU overhead for VMware (overhead for packet routing + virtual vmware network interfaces + memory access control + all the kernel/user-space context switches from freeswitch slowed by vmware). Additionally you'll need some CPU power for scalelite and also for the VMware host which manages the VMs and takes stats, does CPU scheduling,.... So, I'd assume 5 servers with dedicated 4 real CPU cores. That would result in 500+ concurrent users (more if you disable the recording feature - thus also no post processing of the video - and also have few people using webcam video or webrtc desktop sharing). The physical CPU supports hyper-threading, which helps get a few percent more users, but that should not make too much of a difference.

The screenshot in the first post shows 778 connected users and 70 sharing their webcam.  That sounds within expectations from what I'd assume. Giving the 8 VMs a total of 64 virtual CPUs probably caused the VMware host to do quite agressively CPU sheduling optimizations, thus I'd assume that audio quality wasn't good and some people probably lost audio connection because of quality measuring timeouts being hit.

**Comment by basisbit** [comment]
@beatwiz you might want to track network bandwidth and CPU usage at the same time. When there are 40 users in a session all sharing their webcam at 1Mb/s quality setting to the other 39 users, that already results in 1560Mb/s outbound traffic from the server. If that server has a 1Gb/s network card or uplink peering is saturated, then not all the traffic arrives at all the users computers, which means that kurento (which also does video frame based "switching" of all the 1.6Gb/s video traffic) has to keep track of how much traffic arrived at the clients and then adjusts the rate of transmitted video frames (additional CPU load).

So, at 1Mb/s video quality:
40 people in 1 room and all sharing webcam: 1560Mb/s just for the video data
35 people in 1 room and all sharing webcam: 1190Mb/s just for the video data
...
30 people -> 870Mb/s total server outbound video traffic
20 -> 380Mb/s

At 200Kb/s video quality:
40 -> 312Mb/s
20 -> 76Mb/s

Also regarding connection count, when there are 40 people in a session sharing their webcams:
40*39 = 1560 outbound connections from nginx server to clients for video streams
1560 intraprocess connections for those video streams between kurento and nginx
40 connections for chat/users-list/whiteboard event updates between client and nginx
40 connections for chat/users-list/whiteboard event updates betweeen nginx and node.js server
40 connections for audio from users to nginx
40 connections for microphone-audio from client to freeswitch
40 connections for speaker-audio from freeswitch to client
probably a bunch of inter-process connections between node.js, freeswitch, database, redis, kurento, etherpad-lite, ...
So, the high open and closed sockets count that `netstat -an | wc -l` shows can be considered normal - most of these are just inter-process and should not noticeably impact performance.

**Comment by agustinmono** [comment]
Thanks a lot for the detailed info!

Ok, so with this specs my maximun is 800 avg. 

Whats better to have 8 VM with 8 vCPU or 16 with 4 vCPU ?

Thanks again @basisbit

**Comment by basisbit** [comment]
On a 24 core physical CPU, I would not assign 64 virtual CPUs. So, I'd go with less VMs than what you mentioned. Regarding how many cores per VM depends on how many concurrent video users you want to support in a single session, if the recording feature is available for the rooms or not (if the recording button is available, the whole meeting already gets recorded -> post progressing) and other settings. You'll have to collect usage data and figure out for yourself what CPU per VM ration best works for your users group and configuration.

**Comment by jibon57** [comment]
@basisbit, thanks for excellent explanation. Just need to know the clear about `Physical CPU`. For example:  `Intel Xeon E5-1650v4 - 6 c / 12 t - 3.6 GHz / 4 GHz` . So, are there 6 physical CPU?

**Comment by basisbit** [comment]
the two threads per CPU core don't result in 200% power, but instead according to [Intel for typical computing tasks](https://software.intel.com/en-us/articles/how-to-determine-the-effectiveness-of-hyper-threading-technology-with-an-application/) it results in maybe 130%. With how KVM works and because of recent CPU security bugs, many people stopped counting in Hyper Threading threads into performance calculations.

Anyways, the Intel Xeon E5-1650v4has 6 physical CPU cores, plus it uses hyper threading to squeeze out some more computational power by optimizing execution order and lots of other tricks (thus the two threads per physical CPU core.

**Comment by tarunb999** [comment]
By the way ..is there anyway to know how many physical cores are there to my allotted server with n number of Virtual cores??

**Comment by basisbit** [comment]
@tarunb999 ask your server provider. If the description of your server rental offer does not include anything about "dedicated CPU core", then very likely that system will not work with acceptable audio + video quality with BigBlueButton once you get some actual load on there.

**Comment by basisbit** [comment]
closing this issue because the initial question from agustinmono was answered and there was no new response for more than a month.
