### ISSUE TITLE
Language interpretation

### ISSUE THREAD

**Issue by etopian** [bigbluebutton/bigbluebutton#9199]
A user is interested in multiple languages.

https://support.zoom.us/hc/en-us/articles/360034919791-Language-interpretation-in-meetings-and-webinars

`When the meeting or webinar starts, the host can start the interpretation feature, which will give the interpreters access to their own audio channels. Attendees can select an audio channel to hear their language of choice. Attendees will hear the translated audio and can choose if they want to hear the original audio at a lower volume.  `

**Comment by DenysNosov** [comment]
It's nice Idea!!!!

**Comment by ostasevych** [comment]
Are any chance to implement this feature, which supposes several channels to be available to users to select to join with?..

**Comment by ostasevych** [comment]
I found a workaround which may be furthermore improved/developed in a more interactive and friendly level.

**Pre-conditions:**
1. ability to change names of the rooms (now they looks like Room 1, Room 2...)
2. ability to make the break out rooms not dependant on the time limit, so the participants may stay in the rooms as long as they want
3. ability for every participant to join and quit from the room by their own

As you may see my suggestion is to use the features of break out rooms for simultaneous translations. 

The case and possible solution:
1. Let's say the work language of the meeting is Ukrainian.
2. We have 3 groups: English, French and German speaking ones.
3. We have 3 interpeters: Ukr-Eng, Ukr-Fre, Ukr-Ger.
4. The presenter speaks Ukrainian and starts the meeting.
5. After the meeting starts we create 3 break-out rooms (by now with the length of the session to be conducted by the presenter or even the whole event): English, French and German (by now 1,2,3) and let participants know that they may join one of them or to stay in the main room (click Close button).
6. Interpreters are assigned to the rooms depending on the language.
7. BBB allows to listen and talk in both rooms (wider before breaking out) and in broken out rooms.
8. So lecturer remains in the main room with those, who would like to continue to listen in Ukrainian, other participants join the rooms upon their will to listen in other languages.
9. Interpreters remain active in both rooms: in the wider room as listeners, and speakers (with mic) in a broken room. They may open two windows of browsers with the wider room and with break out room and place them close to each other: following the lecturer and seeing the needs of listeners. 
10. When the session is finished moderator may close broken out rooms and bring participants back again to the wider room (if needed).

This may work,  I assume.

**Comment by matiasilva** [comment]
Referring everyone here to #4047 for steps to implement this.

**Comment by croseln** [comment]
This would be a great feature. We are part of the European Federalists and trying to switch from zoom to BBB. Our events are all digital now and since we have the possibility to talk and discuss with people all over Europe, we decided to simultaneously translate some of our discussions  with the zoom feature. It works quite well and it's easy to use for both, translator and whoever needs a translation. Everyone is volunteering to do it and being able to explain and use the translation tool in a matter of minutes is key. But unfortunately that's the problem with the workaround. It's to complicated for the people who are using it and for us to explain. In zoom, the host of the meeting will set everything up and whoever needs it, only has to click the right button.  Straight forward and easy. 
If there was an easy to use and manage interpretation functionality, we'd very happy to use BBB for our europewide events. I am sure you are aware of the recent bad news around zoom and discussing about the future of Europe on an European Server in accordance with the GDPR just makes more sense as well.

**Comment by matiasilva** [comment]
Glad to know you're interested. Since you are part of a larger group, perhaps you might be interested in funding the development of this and if so you can reach out to the companies that provide commercial support for BigBlueButton: https://bigbluebutton.org/commercial-support/

**Comment by ostasevych** [comment]
Hi everybody! Are any updates on adding functionality of language interpretation (separate audio channels in the form of virtual mixer)? In fact this stops from using BBB in multinational environments and pushes towards well-known solution which name starts on "Z".

**Comment by wemoeller** [comment]
We are working in this here: #2642 

is this a duplicate?!

**Comment by ffdixon** [comment]
Merged into #2642
