### ISSUE TITLE
Audio issues on Breakout rooms in iOS

### ISSUE THREAD

**Issue by arvidnilber** [bigbluebutton/bigbluebutton#9201]
Describe the bug
Audio is lost when returning from a breakout on iPad

Other, non-iPad participants, can hear audio and each other speaking indicating that the issue is on the receiving (iPad) side.

Reloading the browser tab and rejoining the conference does not restore receiving audio. Echo test fails, retry doesn't resolve the issue.

Copying the conference URL into a new browser tab resolves the issue.

To Reproduce
Steps to reproduce the behaviour:

move participants into a timed breakout
Wait till the breakout closes
Have participants join the original meeting
iPad participants no longer hear audio
Expected behaviour
All participants, including those on iPad should have working audio

Actual behaviour
Participants on iPad don't hear audio. Others can hear them talk.
All non-iPad participants can also hear each other as well as the participants on iPad.

Screenshots
n/a

Desktop (please complete the following information):

Device: iPad Air 2 and others
OS: iPadOS
Browser: Safari
Version: 13.4 and earlier (tested 13.2 and 13.3.1)

**Comment by frank-miller9** [comment]
I can confirm the same for windows desktop, tested with latest Firefox, Chrome, Edge Chromium.

**Comment by frank-miller9** [comment]
I guess it's not a browser issue, because now I tested it also with firefox mobile.
It worked now with firefox desktop, but only once.

BBB recognize, that the person is speaking (the border appears) but no sound is send.

It seems, that there is a collision in the sound transfer, when I login in the chat twice from the same pc, then also one account is not working properly. So probably the audio is still caught by the breakout room?

**Comment by ffdixon** [comment]
It's a known issue with Safari (desktop and mobile).  

See for more discussion https://github.com/bigbluebutton/bigbluebutton/issues/8857

**Comment by Domdom6474** [comment]
Hi, 
I have, _quite regularly_, encountered various issues when people come back from a breakout room (me being the presenter / opener of the main meeting room). One is the same as described here: the person, upon rejoinning the main meeting room can hear the other participants but not speak (i.e. no sound is sent), or, on the contrary can speak but not hear, or not enable their camera... 
We use a version of BigBlueButton hosted by a third party and I have no means of knowing which version they are running. All I could gather is that the Greenlight version is 2.7.8. 

**At this point in time, what is the best "fix" proposed?** Ask the people to leave the room, close their web browser and then reopen their web browser and rejoing the main meeting room? Should they flush their cache and/or cookies too? 

The issue happened with "students" using FireFox or Google Chrome (latest versions) on PCs under Windows 10 or Windows 7. 
I apologise for not providing very much details, but, as said, the BBB server we use is hosted by a third party whose server we have no access to and the "students" are also third parties whom we can interrogate on what OS and browser they use but whose envireonment we cannot control... 

Anyway, thanks in advance for any suggestion on what to do when a "student" encounters audio or video issues when rejoining the main room form a breakout room.

**Comment by ffdixon** [comment]
@Domdom6474 The first question we ask is always what version of BigBlueButton are you running (what is in the about box)?

> One is the same as described here: the person, upon rejoinning the main meeting room can hear the other participants but not speak (i.e. no sound is sent), or, on the contrary can speak but not hear, or not enable their camera...

This issue was fixed in iOS 14.2.  See Webkit bug [215270](https://bugs.webkit.org/show_bug.cgi?id=215270).

**Comment by Domdom6474** [comment]
@ffdixonThanks for taking the time to answer my post. 
As I mentionned in my post, I have no way of telling what version of BBB my provider is running. 
I know that the Greenlight version is 2.7.8 (bottom of the screen), but there is **no** "about box" anywhere in the interface (as you can see in the screenshot below)
![2020-12-10_screenshot-bbb-1 wsweet cloud](https://user-images.githubusercontent.com/60553068/101773352-f4483d80-3aec-11eb-84dc-f5c06349b678.png)

With respect to "This issue was fixed in iOS 14.2. See Webkit bug 215270." I don't understand, because the problems were experienced on Windows platforms, not iOS...

**Comment by ffdixon** [comment]
Can you try holding a session on our demo server at https://demo.bigbluebutton.org/ and let us know if you encounter the same issues with breakout rooms.  The demo server is running a build of 2.2.31 (still in development), but will help narrow down if the issue is on the user end or on the server end.
