### ISSUE TITLE
Grabbing locales with transifex

### ISSUE THREAD

**Issue by haviduck** [bigbluebutton/bigbluebutton#9211]
Heya, 
Ive translated this to norwegian via transifex (Thanks for letting me, id be very happy to see this implemented in next commit). mind you, norwegian is a severely narrow language, so stuff like error messages is just no use in trying to translate without getting big laughs from endusers. 

However, the docs are over my head when it comes to grabbing the locale and testing it. 
ive found the transifex.sh and have tried pulling as described, but it says "nb_NO" is empty and ends there. 

Id be very greatful if u could give me a quick step-by-step howto on how id grab the locale so i can test it out here?

**Comment by antobinary** [comment]
Hi @haviduck ,
Just a note that I pulled the latest 2.2 locales and added nb_NO with that. Thank you for the translation!
In terms of how to grab the locale - I am not too sure at this point, would have to dig deeper. I took a minute and spotted that there is a Transifex link on each language I have access to for `Download for use` resulting in `for_use_bigbluebutton-v22-html5-client_enjson_nb_NO.json`

I will leave this issue open for now in case others want to chime in. Otherwise we pull the locales pretty much every time we are about to release a new major/minor version of BBB. We are likely to tweak the work flow in the future to make it more predictive and automated (currently there is a high likelihood that new locales can break the client as in #9219 )

**Comment by haviduck** [comment]
> Hi @haviduck ,
> Just a note that I pulled the latest 2.2 locales and added nb_NO with that. Thank you for the translation!
> In terms of how to grab the locale - I am not too sure at this point, would have to dig deeper. I took a minute and spotted that there is a Transifex link on each language I have access to for `Download for use` resulting in `for_use_bigbluebutton-v22-html5-client_enjson_nb_NO.json`
> 
> I will leave this issue open for now in case others want to chime in. Otherwise we pull the locales pretty much every time we are about to release a new major/minor version of BBB. We are likely to tweak the work flow in the future to make it more predictive and automated (currently there is a high likelihood that new locales can break the client as in #9219 )


Ah great, thank you!
yeah, i tried adding that json to that meteror locale directory. itll show up in the language selector, but it goes bonkers when selected. im gonna wait till i can pull it :)

**Comment by antobinary** [comment]
@haviduck ,

>  itll show up in the language selector, but it goes bonkers when selected

Yes, new languages we need to also wire up in intl.jsx see #9218

> If i did some shitty translations and edit it, will it automatically be pulled on next rel?

Yes, as long as the improvements are in Transifex, they will make their way here in the normal pulling-locales process.

**Comment by haviduck** [comment]
i had messed up the translation variables using brackets instead of curlybrackets. changed them all now and hoping 2.10.0 comes out shortly so my changes are applied :)
