### ISSUE TITLE
Audio crackly Problem (Audio like robot)

### ISSUE THREAD

**Issue by MrCapitalist** [bigbluebutton/bigbluebutton#9250]
Hello
I installed BBB and config it on a dedicated server with 24 cores CPU and 64GB RAM and 450 GB SSD... Ubuntu 16.04.6 and Let's Encrypt SSL...

When we have a total of 15 online users on server, sounds recieve terrible!! It hears like robot sound with a lot of parasite. I found [this link](https://pastebin.com/8Fs9qG0w) in BBB google group and changed that configurations but my problem not resolved! The internet connection of our users and I is strong.

I haven't any problem when I check `bbb-conf --status` and `bbb-conf --check`

How can I increase audio quality? 

This is a sample of audio break: https://voca.ro/jyZDarZWsmt

**Comment by mtsonline** [comment]
Hi,

so what did you change in the conference conf? just decreased the energy-level? I would not set that to 0 because the speaking indicator won't work anymore. set it to 20 or something.
you can set the interval to 10 this will help to get better quality.
what settings do you have in opus.conf.xml?

you could set the following, that works best for us ... but keep an eye on the lip sync. we have not tested these settings with large and long lasting conferences yet and audio and video may get out of sync... 
feel free to test it and please get back with your results. :-)

<configuration name="opus.conf"> 

      <settings> 
        <param name="use-vbr" value="0"/> 
        <param name="use-dtx" value="0"/> 
        <param name="complexity" value="10"/> 
        <param name="packet-loss-percent" value="8"/> 
        <param name="keep-fec-enabled" value="1"/> 
        <param name="use-jb-lookahead" value="1"/> 
        <param name="advertise-useinbandfec" value="1"/> 
        <param name="maxaveragebitrate" value="255000"/> 
        <param name="adjust-bitrate" value="1"/> 
      </settings> 
</configuration> 



cheers
Martin

**Comment by mtsonline** [comment]
`<configuration name="opus.conf"> 

      <settings> 
        <param name="use-vbr" value="0"/> 
        <param name="use-dtx" value="0"/> 
        <param name="complexity" value="10"/> 
        <param name="packet-loss-percent" value="8"/> 
        <param name="keep-fec-enabled" value="1"/> 
        <param name="use-jb-lookahead" value="1"/> 
        <param name="advertise-useinbandfec" value="1"/> 
        <param name="maxaveragebitrate" value="255000"/> 
        <param name="adjust-bitrate" value="1"/> 
      </settings> 
</configuration> 
`

**Comment by SasanGF** [comment]
@mtsonline 

I changed all of energy-level to 20 and paste <profile name="cdquality"> tag name from [that link](https://pastebin.com/8Fs9qG0w) to conference.conf.xml

In opus.conf.xml I paste the values of [this link](https://pastebin.com/8Fs9qG0w) too

**Comment by SasanGF** [comment]
This is my [conference.conf.xml](https://pastebin.com/nnvvmv6Q)
And this is my [opus.conf.xml](https://pastebin.com/tbvTwb8V)

**Comment by mtsonline** [comment]
please try to change opus to my settings. disabling forward error correction may not be a good idea.

**Comment by SasanGF** [comment]
I changed it to your settings but unfortunatly it doesn't improve anything :(

**Comment by mtsonline** [comment]
I have no more ideas on the audio settings.
maybe you have a bandwith or network problem?

**Comment by SasanGF** [comment]
No we don't have any limit in our bandwidth or hardware of server

**Comment by Sea444** [comment]
Your audio sample sounds a lot like bandwidth problems. Have you tried using another BBB-server for comparing? https://demo.bigbluebutton.org/gl/ or https://treffen.kbu.freifunk.net/ff or https://conf.ccc-ffm.de/b

**Comment by ffdixon** [comment]
@SasanGF Can you try a conference on https://demo.bigbluebutton.org/ and let us know how the audio goes there.

**Comment by mtsonline** [comment]
@SasanGF  and please try to set the following in your opus conf:
maxaveragebitrate: 16000
complexity: 5

would be interesting if something (beside lower audio quality) changes.

@ffdixon  
regarding our crackly noises I now played arround with lowering quality and also was able to remove these crackly noises with that - as if they too where bandwith related, but this on stable connections, which is very confusing. If you have some ideas or comments, please leave them in the thread (will give more details on it there now):
https://groups.google.com/d/msgid/bigbluebutton-setup/aea2e811-7d9a-0237-a08f-2e357313080f%40mtsonline.at

p.s. @ffdixon  on 24th you got an email from me regarding the dev list, due to mailserver change I am not shure if you got that, please let me know, thanks.

**Comment by SasanGF** [comment]
Hi
My problem was solved a lot by changing some of my customized settings to default values. I think my problem comes from BBB bugs because I think my customization doesn't change any important system core (or professional) features!

I changed these:

In VMWare ESXI Panel:
CPU Core: 24  // Cores per Socket: 12  >>> CPU Core: 24  // Cores per Socket: 1
Memory Reservation: None >>> 65536 MB

I changed all of these files to default parameteres:
/opt/freeswitch/etc/freeswitch/autoload_configs/conference.conf.xml
/opt/freeswitch/etc/freeswitch/autoload_configs/opus.conf.xml
/opt/freeswitch/etc/freeswitch/dialplan/default/bbb_conference.xml
/opt/freeswitch/etc/freeswitch/dialplan/default/bbb_echo_test.xml
/opt/freeswitch/etc/freeswitch/dialplan/default/bbb_echo_to_conference.xml

In `/usr/share/meteor/bundle/systemd_start.sh`
ENVIRONMENT_TYPE=development >>> ENVIRONMENT_TYPE=production 

In `/usr/share/bbb-web/WEB-INF/classes/bigbluebutton.properties`
numConversionThreads=5 >>> numConversionThreads=2
numFileProcessorThreads=4 >>> numFileProcessorThreads=2
Uncomment `native2ascii -encoding UTF8 bigbluebutton.properties bigbluebutton.properties` because I changed `defaultWelcomeMessage` and `defaultWelcomeMessageFooter` to UTF-8 characters
muteOnStart=true >>> muteOnStart=false
lockSettingsLockOnJoinConfigurable=true >>> lockSettingsLockOnJoinConfigurable=false

In `/usr/share/meteor/bundle/programs/server/assets/app/config/settings.yml`
askForFeedbackOnLogout: true >>> askForFeedbackOnLogout: false
enableNetworkInformation: true >>> enableNetworkInformation: false
enableNetworkMonitoring: true >>> enableNetworkMonitoring: false
clientLog options that has been changed from [this instruction](https://github.com/bigbluebutton/bigbluebutton/issues/9217#issuecomment-619166642) chnaged to >>>
`clientLog:
    server: {enabled: true, level: info}
    console: {enabled: true, level: debug}
    external: {enabled: false, level: info, url: 'https://LOG_HOST/html5Log', method: POST,
      throttleInterval: 400, flushOnClose: true, logTag: ""}
`

memoryMonitoring:
    stat:
      enabled: true >>> enabled: false
    leak:
      enabled: true >>> enabled: false
    heapdump:
      enabled: true >>> enabled: false


In `/usr/share/etherpad-lite/settings.json`

`"toolbar": {
    "left": [
      ["bold", "italic", "underline", "strikethrough"],
      ["orderedlist", "unorderedlist", "indent", "outdent"],
      ["undo", "redo"],
    ],
    "right": [
      ["importexport","settings"]
    ]
  },`

to 

`"toolbar": {
    "left": [
      ["bold", "italic", "underline", "strikethrough"],
      ["orderedlist", "unorderedlist", "undo", "redo"]
    ],
    "right": [["importexport"]]
  },
`

These are all of my customization that when I revert them back, my problem resolved!!!! But why?! Are they important for audio crack problem?!

**Comment by SasanGF** [comment]
In addition, I feel there is still some noise in audio. I hear some "tick tick" sound in every 3-4 words of users speech. 

Even now I have a new problem. I think this problem will increase when my active users increase. I have 50 users in 6 rooms now and Server hardware is consuming abnormally. Why?

https://pasteboard.co/J5yB7NA.png
https://pasteboard.co/J5yBw8K.png

**Comment by mtsonline** [comment]
Hi,


I guess only things that could have impact are:


1.  In VMWare ESXI Panel:

* CPU Core: 24 // Cores per Socket: 12 >>> CPU Core: 24 // Cores per 
Socket: 1

* Memory Reservation: None >>> 65536 MB

Could you change them one by one back and see if your problems reoccoure?


2. In addition, I feel there is still some noise in audio. I hear some 
"tick tick" sound in every 3-4 words of users speech.


that is why we are searching for better settings / a solution. there are 
others that have this noises - join us at the thread I posted above - we 
want to get ridd of this crackly noises ;-)


3. Even now I have a new problem. I think this problem will increase 
when my active users increase. I have 50 users in 6 rooms now and Server 
hardware is consuming abnormally. Why?


maybe because of the cpu settings being changed? ...if you try 1. maybe 
you see a difference here too?


cheers

Martin

**Comment by SasanGF** [comment]
No I didn't change anything from last day! These problems occures now and nobody can join rooms! When enter a room, three loading indicator dots freeze for 1 minute and show this error: 401
Unauthorized!!

**Comment by mtsonline** [comment]
sorry do not understand you. you wrote you did the changes above, now you write you did not change anything?
or do you mean since the changes above - when everything worked again, you did not do any further changes and bbb stopped working now?

check if bbb is up with bbb-conf --status 
and have a look at the logs.

**Comment by SasanGF** [comment]
I'm sorry for my bad language. Yes I changed above settings 2 days ago and 17 hours ago I reverted them back to default and audio problem solved a lot (But I think when users increase, problem come back)

But now the user entering problem occurs and I don't know why :| 
In `bbb-conf --status` and `bbb-conf --check` everythins in OK

**Comment by basisbit** [comment]
Sorry, but this definitely looks like not a problem of BigBlueButton itself, but instead rather a problem of your setup, either hardware capacity and VMWare setup (did you assign more virtual cores to your machines than the host has physical CPU cores - not counting HyperThreading cores?) or your setup is not secured according to [the documentation](https://docs.bigbluebutton.org/2.2/customize.html#secure-your-system--restrict-access-to-specific-ports) and thus your freeswitch is spammed by brute force attacks or possibly is misused already.

For any further support questions, please use the BBB setup forum at https://groups.google.com/forum/#!forum/bigbluebutton-setup . Thanks.
