### ISSUE TITLE
Voice latency (delay)

### ISSUE THREAD

**Issue by mjencabh** [bigbluebutton/bigbluebutton#9320]
Hello

we are running in production but after updating to latest BBB we are having a lot of sound problems.
The sound of participants are very behind the webcam. We are on our own bare metal server and it worked fine before the update.

Any ideas? or is this a bug?

**Comment by jfraf** [comment]
Same issue here. I did not upgrade to version 2.2.6, but applied the jitterbuffer modifications described in https://github.com/bigbluebutton/bigbluebutton/issues/7007#issuecomment-619399667 since we have massive issues with audio crackling. 

Jitterbuffer helped with crackling, but audio/video not being in sync is quite annoying.

**Comment by a-ttila** [comment]
Same with me. I have more BBB servers, on bare metal works fine, but in vmware VM-s, AFTER the upgrade, massice delay are there. Before the upgrade, everything was just fine on the VMs.

**Comment by a-ttila** [comment]
https://github.com/bigbluebutton/bigbluebutton/issues/7007#issuecomment-621414985
