### ISSUE TITLE
Upload Published Recording to S3 using Post Script

### ISSUE THREAD

**Issue by kshitij12345** [bigbluebutton/bigbluebutton#9353]
@ffdixon 

I am trying to upload the published playback files to s3.
I have added a post script in `/usr/local/bigbluebutton/core/scripts/post_publish` as follows

```
require "trollop"
require File.expand_path('../../../lib/recordandplayback', __FILE__)

opts = Trollop::options do
  opt :meeting_id, "Meeting id to archive", :type => String
end
meeting_id = opts[:meeting_id]

logger = Logger.new("/var/log/bigbluebutton/post_publish.log", 'weekly' )
logger.level = Logger::INFO
BigBlueButton.logger = logger

published_files = "/var/bigbluebutton/published/presentation/#{meeting_id}"
meeting_metadata = BigBlueButton::Events.get_meeting_metadata("/var/bigbluebutton/recording/raw/#{meeting_id}/events.xml")

#
# Put your code here
#
BigBlueButton.logger.info("S3 Uploader Running.")
meeting_id = "#{meeting_id}"
aws_s3_cmd = "aws s3 sync " + published_files + " s3://some-s3-bucket/" + meeting_id
BigBlueButton.logger.info(aws_s3_cmd)
status = system(aws_s3_cmd)
BigBlueButton.logger.info(status)
BigBlueButton.logger.info("End Script")
exit 0
```

However the `aws sync` fails. I see that when the script is being processed, the `/var/bigbluebutton/published/presentation/#{meeting_id}` is not present. Once the script has executed the files exists and if I run the `sync` then it works. 

Is this the expected behaviour, from the documentation I feel that the files would be available when `post_publish` script is called.

Is there any other way to do the same?

Thanks.

**Comment by paul1278** [comment]
Maybe you can find some messages written to the logs here: `/var/log/bigbluebutton/post_publish.log`

**Comment by kshitij12345** [comment]
@paul1278 Thanks for the reply. I have checked the log file. The log is
```
I, [2020-04-30T13:29:29.157397 #20333]  INFO -- : Task: Getting meeting metadata
I, [2020-04-30T13:29:29.158889 #20333]  INFO -- : S3 Uploader Running.
I, [2020-04-30T13:29:29.158948 #20333]  INFO -- : aws s3 sync /var/bigbluebutton/published/presentation/some-id s3://some-bucket/some-id
I, [2020-04-30T13:29:29.441769 #20333]  INFO -- : nil
I, [2020-04-30T13:29:29.441858 #20333]  INFO -- : End Script
```
The system function returns `nil`. Also when the logging starts I see that the folder doesn't exist till that point. Post that the folder exists and if I copy the logged command, it works.

**Comment by paul1278** [comment]
Interesting, but I guess this should work because we have a post_publish script running which uses those files.

According to ruby-docs, `system()` returns `nil` if command execution fails, maybe when calling `system("echo $?")`, you can get the error-code from the aws-call.

**Comment by kshitij12345** [comment]
Thanks will try that.

**Comment by paul1278** [comment]
Ok but you got no output of the echo-command? Also nothing on the other log-file?
Maybe do a `system("echo $? > /some/directory/temp_output.txt")`

**Comment by kshitij12345** [comment]
Turns out that `aws` was unable to access the credentials.

Also output the command line using `open3` helped with the debugging.
https://stackoverflow.com/questions/690151/getting-output-of-system-calls-in-ruby

`/var/log/bigbluebutton/bbb-rap-worker.log` was useful as well.

@paul1278 Thank You very much.

**Comment by rohitcoder** [comment]
This is one of the way you can use to move BBB recordings to s3 server https://github.com/rohitcoder/BBB-AWS-S3

This is working for me

**Comment by vlasov01** [comment]
Hi @rohitcoder !
 The link to your repo is broken. Could you please revise it?

**Comment by rohitcoder** [comment]
> Hi @rohitcoder !
> 
>  The link to your repo is broken. Could you please revise it?

@vlasov01 
Now this should work

**Comment by vlasov01** [comment]
> > Hi @rohitcoder !
> > The link to your repo is broken. Could you please revise it?
> 
> @vlasov01
> Now this should work

@rohitcoder 
Thank you!

**Comment by Kernelogy** [comment]
@kshitij12345 Your code is neat and simple. Yet, I m facing the same issue 
Did u find any solution for the problem.. 

I thought that there may be a delay in copying the files to published/presentation by the corresponding process before the post_publish.rb is called
So I added 
sleep 300 #seconds
to your code so that the it may delay the execution of the post_publish.rb script before the actual files are being created/copied in the said location.

But it is of no use. Any idea. Help Please

Note:

I think the thread/process associated to copying/creating published meeting files is not finishing the job until the whole script is executed, so that this issue prevailing. If this is the case how can we overcome this.

**Comment by kshitij12345** [comment]
In my case, the problem was the script didn't have sufficient privileges to push to AWS. Can you echo till what point your script works and see if any command in the shell throws an error.

Also I think, @rohitcoder has a nice solution https://github.com/rohitcoder/BBB-AWS-S3 . Can you try to see if it works?

**Comment by Kernelogy** [comment]
@kshitij12345 Thanks for the reply, 

I tried @rohitcoder 's python script. And BBB-AWS-S3 script is I m using as of now. The script does the job nice, after some tweaking. 
But there are some logical problems I face with
- When BBB-AWS-S3 and BBB-RECORD does their jobs at the same time, i.e, while publishing script copying the files to /var/bigbluebutton/published/presentation directory it may leads to missing of some files/improper uploads to S3
- If we do not delete the presentation files while uploading to S3 using BBB-AWS-S3 script then it is leading to multiple put requests to S3 in every 5 min duration
- Multiple process of the BBB-AWS-S3 script is running at the same time as the Cron is set to 5 mins.
- If we try increasing  the Cron duration then the meeting is not getting uploaded to S3 by the time the meeting ends.
The above are some logical problems if face with while using @rohitcoder 's script

So because of the above mentioned reasons I tried with the script of yours. But I m facing the same problems as you mentioned in the beginning. The post_publish.rb file cannot find the files in the intented location when it is invoked thru post_publish script of BBB-RECORD. But when I manually run the aws s3 sync it is getting updated.

**Comment by Kernelogy** [comment]
Alas! Finally found a solution 
Without the need for CRON, the below script get invoked when the meeting gets to published state.
And the corresponding meeting files are uploaded to S3

As @kshitij12345 refered before the problem with `aws s3 sync` is, it was not able to retrive aws credentials

```
#!/usr/bin/ruby
# encoding: UTF-8

require "trollop"
require 'aws-sdk-s3'

require File.expand_path('../../../lib/recordandplayback', __FILE__)

opts = Trollop::options do
  opt :meeting_id, "Meeting id to archive", :type => String
  opt :format, "Playback format name", :type => String
end
meeting_id = opts[:meeting_id]

logger = Logger.new("/var/log/bigbluebutton/post_publish.log", 'weekly' )
logger.level = Logger::INFO
BigBlueButton.logger = logger

published_files = "/var/bigbluebutton/published/presentation/#{meeting_id}"
meeting_metadata = BigBlueButton::Events.get_meeting_metadata("/var/bigbluebutton/recording/raw/#{meeting_id}/events.xml")

#
# S3 Upload Code
#

def object_uploaded?(s3_client, bucket_name, file, object_key)
    if File.directory?(file)
        response = s3_client.put_object({
            bucket: bucket_name,
            key: object_key,
        })
    else
        data = File.open(file)
        response = s3_client.put_object({
            bucket: bucket_name,
            key: object_key,
            body: data
        })
        data.close
    end    

    if response.etag
      return true
    else
      return false
    end
  rescue StandardError => e
    puts "Error uploading object: #{e.message}"
    return false
end


bucket_name = 'BUCKET-NAME'
region = 'REGION'
s3_client = Aws::S3::Client.new(
    region: region,
    credentials: Aws::Credentials.new('AWS-CLIENT-ID','AWS-CLIENT-SECRET')    
)

BigBlueButton.logger.info("S3 Uploader Running for meeting #{meeting_id}")
Dir.glob("#{published_files}/**/*") {|file|
  tmp = file
  bucket_file = tmp.gsub("/var/bigbluebutton/published/presentation/","")
  puts "File => #{file}"  
  if object_uploaded?(s3_client, bucket_name, file, bucket_file)
    BigBlueButton.logger.info("#{bucket_file} uploaded successfully!") #IF NEEDED
  else
    BigBlueButton.logger.info("#{bucket_file} upload failed!") #IF NEEDED
  end
}
BigBlueButton.logger.info("S3 Upload completed for meeting #{meeting_id}")

exit 0
```
