### ISSUE TITLE
mp4 enable but not showing

### ISSUE THREAD

**Issue by mjencabh** [bigbluebutton/bigbluebutton#9364]
Hello

I have been added mp4 /usr/local/bigbluebutton/core/scripts/presentation.yml so both webm and mp4 should be compiled. However only webm file (presentation) is showing in frontend Greenlight.
Not sure if the problem is in BBB og Greenlight?

Hop someone can help me with this.

Running: BBB  2.2.5 Greenlight 2.5.5

**Comment by pedrobmarin** [comment]
This will only affect recordings processed after the change has been done. Old recordings will be the same unless you reprocess them. If you keep both webm and mp4 your browser will automatically chose one of them. I would say you would only fetch for mp4 using Safari or any iOS browser (since they run the same thing under the hood).
mp4 should be enough for the majority of desktop/mobile browsers. You could drop webm if that's not something mandatory in your setup

**Comment by mjencabh** [comment]
Ahh thought that it would show both in front-end :) will test it.

**Comment by mjencabh** [comment]
Hmm my bad. I had the impression that it would turn the everything in to mp4- but it still cant show deskshare or presentation :(
