### ISSUE TITLE
Random viewing records

### ISSUE THREAD

**Issue by Magnou17** [bigbluebutton/bigbluebutton#9372]
I'am using BigBlueButton v2.2.6
In a session the record look to be fine but when i stop and come back in grrenlight i don't see any record! and sometimes i find a record of the day before!
Some body have got this issue (and resolved)?
Thanks
Rgds
Chris

**Comment by felcaetano** [comment]
This is expected behavior.  The raw recording files need to be processed (merging webcam, audio, chat, presentation all together) before publishing. The speed may vary for each hardware and number of recordings in the queue.
Some people on  #8770 claim you can speed this up but I haven't tested myself.

**Comment by dseral** [comment]
Take a look this is your problem..
https://github.com/bigbluebutton/bigbluebutton/pull/9249
