### ISSUE TITLE
Why special STUN-Server for Freeswitch?

### ISSUE THREAD

**Issue by Sea444** [bigbluebutton/bigbluebutton#9387]
When installing BBB with install.sh you can set parameter STUN-Server. 

But obviously the STUN-Server from install.sh isn't used in every matter. Running `bbb-conf --check` shows for FREESWITCH another STUN-Server for FREESWITCH . Why?

```
/opt/freeswitch/etc/freeswitch/vars.xml (FreeSWITCH)
                       local_ip_v4: xxx.xxx.xx.xxx
                   external_rtp_ip: stun:stun.freeswitch.org
                   external_sip_ip: stun:stun.freeswitch.org
```

**Comment by alexanderjackson** [comment]
I am trying to understand this too.

I assume the Freeswitch STUN server configuration is irrelevant for the WebRTC standard used by the BBB HTML5 client. Instead the client uses the TURN server configuration from `/usr/share/bbb-web/WEB-INF/classes/spring/turn-stun-servers.xml`. 

If I understood this correctly, the TURN server relays client connections to the BBB server while the STUN protocol allows hosts behind a NAT to determine their public IP and a response port.

So the STUN protocol allows NAT clients to communicate directly with the server instead of relaying  through a TURN server.

**Comment by lbehm** [comment]
This option is for freeswitch to detect the current network environment (NAT).

More specifically, on startup freeswitch tries to fetch a reply from these stun servers, and uses that information to determine it's real external IP address. The actual external IP address is relevant for the ICE candidate selection process, to detect which candidates are the direct external interface.

If known, I recommend to use your actual IPv4/IPv6 addresses in these settings.
