### ISSUE TITLE
apply-lib.sh not updated, BBB_WEB_CONFIG not defined

### ISSUE THREAD

**Issue by hbruch** [bigbluebutton/bigbluebutton#9404]
**Describe the bug**
bbb-conf/apply-lib.sh is not updated between. I.e. variable BBB_WEB_CONFIG was not defined after update to version 2.2.9 via
```sh
sudo apt-get update
sudo apt-get dist-upgrade
sudo bbb-conf --setip <myIp>
sudo bbb-conf --check
```

**Installation type**
Via bbb-install script.

**Comment by trs80** [comment]
`/etc/bigbluebutton/bbb-conf/apply-lib.sh` is in `/var/lib/dpkg/info/bbb-config.conffiles` so the non-interactive apt upgrade probably left the original version there rather than replacing it with the new one. I think the solution is to move that file to `/var/lib/bbb-conf` and symlink it in to `/etc` per https://www.debian.org/doc/manuals/maint-guide/dother.en.html#conffiles

**Comment by trs80** [comment]
Maybe it's not that, it seems bbb-conf package 1:2.2.0-182 just doesn't include the updated apply-lib.sh that's in the repo.

**Comment by antobinary** [comment]
Merging into https://github.com/bigbluebutton/bigbluebutton/issues/11009
