### ISSUE TITLE
request for better performance in meeting

### ISSUE THREAD

**Issue by jshosseini** [bigbluebutton/bigbluebutton#9405]
First of all thanks for your great software. I suggest these modifications to better performance
1- Moderator is able to mute all users. But we should able to active muted users microphone in any moment too as well as webcams.
2- In custom polls we should able to create question in addition to answers.

**Comment by rriscado** [comment]
Hi,

Answer 1:
- Moderators can unmute users if the parameter "allowModsToUnmuteUsers = yes" is the one used in the so-called "create" API.
- Allowing the moderator to start the WebCam remotely is a hard action, because we need the user's authorization to the browser has access to the webcam.

Answer 2: 
-You are right. This would be an excellent improvement.

This is my opinion. Will wait for the developers to know their opinions.

**Comment by jshosseini** [comment]
> 
> 
> Hi,
> 
> Answer 1:
> 
>     * Moderators can unmute users if the parameter "allowModsToUnmuteUsers = yes" is the one used in the so-called "create" API.
> 
>     * Allowing the moderator to start the WebCam remotely is a hard action, because we need the user's authorization to the browser has access to the webcam.
> 
> 
> Answer 2:
> 
>     * You are right. This would be an excellent improvement.
> 
> 
> This is my opinion. Will wait for the developers to know their opinions.

Thank you for your reply.

**Comment by jshosseini** [comment]
I found the configuration, 
in bigbluebutton-web\grails-app\conf\bigbluebutton.properties
allowModsToUnmuteUsers = true
