### ISSUE TITLE
Why did You close the issue "Application screen share shows no "sub-windows" on Linux KDE #9356". 

### ISSUE THREAD

**Issue by schaale0705** [bigbluebutton/bigbluebutton#9415]
THE ISSUE "Application screen share shows no "sub-windows" on Linux KDE #9356" IS *NOT* SOLVED. I can confirm the problem described (openSuSE Leap 15.1). And: it does NOT depend on the browser. It is definitely a BBB issue. 'Zoom' does not have any problem to share single screens. As long as this issue is not solved BBB is unusable for me and most of my colleagues.

I am looking very much forward to a solution of this problem. Thank You!

Kindest regards, Michael

**Comment by prlanzarin** [comment]
As for why the issue was closed: it's described in the issue. The OP closed it, it wasn't anyone from the BBB team.

Can't compare screen capture between Zoom (a **native** application) and BBB (a **browser based** application) in that way. We rely on **browsers** to provide screen capture. If the browsers aren't picking up sub-windows on application sharing, it's probably some sort of bug and/or limitation in how the **browser** captures the screen specifically on KDE/Plasma. Please try to reproduce on another **browser based, WebRTC application**. If the problem is widespread, than this issue would fit better in Mozilla's/Chromium's/"whatever browser you use" trackers.

**Comment by schaale0705** [comment]
OK, so BBB cannot handle split screens. Got the message. I tested BBB with chromium, firefox and opera - without any change in the result. From my point of view this issue disqualifies BBB for me and my problems. I do really prefer and support open-source products but at the end things must work because daily life is not a playground. So, finally 'zoom' remains the only alternative for me. Sorry.

All the best and kindest regards, Michael

**Comment by bwurst** [comment]
BBB can handle split screens and several kinds of windows to share quite fine **if the browser does**. I'm using it on Linux.
Maybe you are on a Wayland session. Wayland support is not complete in most browsers, so when I'm on wayland, I cannot choose all applications to share but only those on X11 compatibility layer.

If a browser based tool is not the right for you: Don't blame a cat for not being a dog.

**Comment by schaale0705** [comment]
... :-)=) .. I prefer dogs to cats .... I can only repeat that it does NOT work. No matter what browser is used. The issue Wayland yes/no is not that easy to solve in openSuSE Leap 15.1 without spoiling everything. So, yes, an unflexible browser based tool is obviously not that what I need. I do not have the time to play around to test different ideas for days and days and days, I simply have to be productive. I'll give BBB a try - say in a year - and I will see if it has become more flexible. Good luck and all the best!!

**Comment by basisbit** [comment]
@schaale0705 BigBlueButton is an open source software project. The same is true for Chromium and Firefox. So, please feel free to fix the problem in your favorite webbrowser instead of just opening yet another duplicate issue. BBB uses the web-rtc standard and thus has known limitations, which the developers accept.

**Comment by schaale0705** [comment]
OK, got he message, returning to Zoom and closing the issue. Thank You.
