### ISSUE TITLE
remembering audio/video source between sessions?

### ISSUE THREAD

**Issue by hvdort** [bigbluebutton/bigbluebutton#9479]
It would be very useful if the choice for audio/video source could be remembered between sessions. (maybe in a cookie?). For now, on each connection, we must do the echo-test, also when entering a breakout room.
Additional: fast switching between sources like jitsimeet: 
![image](https://user-images.githubusercontent.com/64264862/81477750-af3bf000-9219-11ea-9dec-94a7652ae1fa.png)
Is that possible?

**Comment by matiasilva** [comment]
You can disable the echo test if you wish. Additionally, the video/audio source are determined by the permissions you set with your browser. So that's the first part.

As for your addition at the end, I see that as a genuinely useful feature. For now, the user must leave and reenter the audio bridge manually. Please submit that as a separate issue under "enhancement" and close this one.

**Comment by hex-m** [comment]
Switching devices has it's own issue now: #9723

**Comment by antobinary** [comment]
Merging into #9723
