### ISSUE TITLE
Desktop Share can't share terminal (console) from Fedora 32 

### ISSUE THREAD

**Issue by rezaervani** [bigbluebutton/bigbluebutton#9484]
We've upgraded our BBB to 2.2.9

Use Greenlight 2.0 with Docker

Everything work fine. Just find a problem when use Desktop Share, it only detect my browser, and telegram window. But it can't share all my desktop (it just show black blank window), and not detect terminal application window from my fedora laptop.

Is there something I forgot to configured ?

Thank you,

**Comment by basisbit** [comment]
This is not a bug of BigBlueButton, but instead must be a problem of your webbrowser or your X Server setup. BigBlueButton only uses the standardized WebRTC API and thus has no influence on this.
Please close this issue here and instead use the support from your webbrowser manufacturer.
Also, you can test this using the [WebRTC screen sharing sample](https://www.webrtc-experiment.com/Pluginfree-Screen-Sharing/).

**Comment by rezaervani** [comment]
OK. Thank you

I found the problem is on Wayland. I change to X11, and it work perfectly

Thank you very much,
