### ISSUE TITLE
Desktop sharing don't work when the number of attendants are above 8  

### ISSUE THREAD

**Issue by Happy-2020** [bigbluebutton/bigbluebutton#9497]
Hi, 

I am renting a dedicated hosting server from vultr.com, which is, 4Core, 8Gbyte RAM, instance. As the document saying... this satisfies the minimum system requirements for bigbluebutton, and if it meets, bigbluebutton can host up to 128 at a time.

Everything is fine with the great help of this community.

Did a final test yesterday, and we have found the desktop sharing stops working when there are more than 8 people in it.

Wasted tons of time to find the answer, but I couldn't mange it yet.

If someone has similar experiences, please kindly teach me to find a solution. It would be a great help to me.

Thanks!

**Comment by basisbit** [comment]
This issue tracker here is for development issues only. The issue template (which you deleted) contains a short note abot this. Please use the support forums/mailinglists: https://groups.google.com/forum/#!forum/bigbluebutton-setup

When asking in the support-forum, please provide the output of `bbb-conf --check` and also use `bbb-conf -watch` to check the BigBlueButton log files for something that might hint at the actual problem. Instead of saying "stops working", please explain in detail what steps you did and what happened then.

**Comment by basisbit** [comment]
I am not sure what the down-vote is supposed to do. This issue tracker here would overflow with issues if it also contained all the various support requests. The mailing list / forum is much better suitable for handling the amount of support questions and makes it very easy for searching similar problem reports while also allowing other BigBlueButton users to join in with their knowledge.
You did not provide any usable information like debug log entries, details about your setup, what messages are shown in the webbrowser developer tools console, and so on.
