### ISSUE TITLE
Is there any possible way to make a mobile app for bbb?

### ISSUE THREAD

**Issue by hackzie** [bigbluebutton/bigbluebutton#9513]
I have tried running it in web view but it is not possible as BBB runs in Chromium engine only. So, is there any other possible way to develop an app for it using android studio?

**Comment by bwurst** [comment]
Can you describe what are the problems with using BBB on mobile devices? Our conferences have most users connected with phones and they're happy with it.

Using an app would lead to problems in user experience because BBB is regularly started via clicking a link inside greenlight, moodle or any other web application. How should the mobile device choose when to launch the BBB app?

**Comment by hackzie** [comment]
@bwurst Sir, actually one of my client is demanding a personal app for bbb . So, i wanted to give him android app with his branding. He does not want to use google chrome. It would be great help if you will tell me just to create a fully functional web app for bbb.

**Comment by frank-miller9** [comment]
There are severall App creation tools for websites: https://trendblog.net/create-android-app-from-website/

**Comment by hackzie** [comment]
Yes, I know that sir. I have tried making app with those and android studio as well but there is same problem in every app, i.e. The web cam is not working. That`s why i asked for help if we could do something to make its web cam work in android application as well.

**Comment by agussang** [comment]
> Can you describe what are the problems with using BBB on mobile devices? Our conferences have most users connected with phones and they're happy with it.
> 
> Using an app would lead to problems in user experience because BBB is regularly started via clicking a link inside greenlight, moodle or any other web application. How should the mobile device choose when to launch the BBB app?

probelm is audio missing randomly, so user must log out closed browser and re-join room. any solution for this case?

**Comment by ostasevych** [comment]
Separate app will allow to have own notifications, allow to be on top of other windows, have own sandbox, have own priorities - that means, that if your browser is frozen due to overload, your app will continue to work. I tried to generate an app using free tools, and found that one of main issues is breaking out into the rooms, when in fact a NEW tab opens in your browser. That complicates the task.

**Comment by matiasilva** [comment]
Closed for same reasons as the above issue.
