### ISSUE TITLE
Don't prompt to use Chrome on iPad when doing screen sharing

### ISSUE THREAD

**Issue by ffdixon** [bigbluebutton/bigbluebutton#9543]
**Describe the bug**
User is prompted to switch to Chrome on iPad when trying to do screen sharing, which will not work.

**To Reproduce**
1. Go to test.bigbluebutton.org
2. Try screen sharing

**Expected behavior**
The message should say Screen Sharing is not supported on iOS (iPhone or iPad) at this time.

**Screenshots**
This is the erroneous message.

![image](https://user-images.githubusercontent.com/290351/81973428-21ce1680-95f2-11ea-9161-792175994dd3.png)

**Smartphone (please complete the following information):**
 - Device: iPad
 - OS: iOS 13.4.1
 - Safari Mobile

**Comment by prlanzarin** [comment]
Can't we just make the unavailability string browser agnostic? i.e.: `Screensharing is not supported in this browser.`
First because it'll cover Safari clones (ie Chrome, Firefox on iOS). Second because when we deprecate gUM-based screensharing and rely only on getDisplayMedia availability, we can get rid of the Safari checks and the localization will be there and ready for it.

**Comment by basisbit** [comment]
Would also be nice to have a `try anyways` button, so incorrectly detected browser types / clones can still be used, if they provide the required API.

**Comment by prlanzarin** [comment]
@basisbit that won't be needed once https://github.com/bigbluebutton/bigbluebutton/pull/9542 is merged because the Safari check is enriched with a getDisplayMedia availability check.
