### ISSUE TITLE
TURN errors only in Chrome

### ISSUE THREAD

**Issue by kensington** [bigbluebutton/bigbluebutton#9584]
**Describe the bug**
When trying to use BBB with TURN configured, sharing a webcam in Chrome fails with error 1020. Sharing a webcam in Firefox works as expected.

When inspecting the coturn logs, repeated, numerous 401 unauthorised errors are reported while Chrome is attempting to share webcam. When testing with Firefox, the usual small number of initial 401 errors are logged followed by regular logs that indicate connection is successful.

**To Reproduce**
1. Install BBB with coturn
2. Join a meeting with Firefox and share the webcam - it works
3. Join a meeting with Chrome and share a webcam - it fails and coturn logs are filled with 401 unauthorised errors

**Expected behavior**
Sharing a webcam is successful in Chrome.

**Actual behavior**
Sharing a webcam is only successful in Firefox.

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser: Firefox / Chrome
 - 76.0.1 / 81.0.4044.113

**Smartphone (please complete the following information):**
 - n/a

**Additional context**
The stark difference in coturn logs between Firefox and Chrome seems to suggest that in both cases they connect successfully to the coturn server, but Chrome is never able to authenticate.

**Comment by ffdixon** [comment]
Can you try it with

  https://test.bigbluebutton.org/

and let us know if you get the same results.

**Comment by congyijun** [comment]
@kensington 

Could you share the "/usr/share/bbb-web/WEB-INF/classes/spring/turn-stun-servers.xml" with us?

**Comment by kensington** [comment]
> Can you try it with
> 
> https://test.bigbluebutton.org/
> 
> and let us know if you get the same results.

I do get the same results (works in Firefox, not in Chrome) on that test instance.

**Comment by kensington** [comment]
> @kensington
> 
> Could you share the "/usr/share/bbb-web/WEB-INF/classes/spring/turn-stun-servers.xml" with us?

```
<?xml version="1.0" encoding="UTF-8"?>
<beans xmlns="http://www.springframework.org/schema/beans"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://www.springframework.org/schema/beans
        http://www.springframework.org/schema/beans/spring-beans-2.5.xsd">
    <bean id="stun0" class="org.bigbluebutton.web.services.turn.StunServer">
        <constructor-arg index="0" value="stun:turn.xyz.com"/>
    </bean>
    <bean id="turn0" class="org.bigbluebutton.web.services.turn.TurnServer">
        <constructor-arg index="0" value="xyz"/>
        <constructor-arg index="1"
value="turns:turn.xyz.com:443?transport=tcp"/>
        <constructor-arg index="2" value="86400"/>
    </bean>
    <bean id="turn1" class="org.bigbluebutton.web.services.turn.TurnServer">
        <constructor-arg index="0" value="xyz"/>
        <constructor-arg index="1"
value="turn:turn.xyz.com:443?transport=tcp"/>
        <constructor-arg index="2" value="86400"/>
    </bean>
    <bean id="stunTurnService"
            class="org.bigbluebutton.web.services.turn.StunTurnService">
        <property name="stunServers">
            <set>
                <ref bean="stun0"/>
            </set>
        </property>
        <property name="turnServers">
            <set>
                <ref bean="turn0"/>
                <ref bean="turn1"/>                
            </set>
        </property>
    </bean>
</beans>
```

**Comment by lonesomewalker** [comment]
If not already solved...
debug the connection to your TURN server by:
https://webrtc.github.io/samples/src/content/peerconnection/trickle-ice/

![stun](https://user-images.githubusercontent.com/856110/82742670-59ab2b80-9d61-11ea-8add-e8ec0ce0ed83.jpg)
(please notice the stun: before your server name)

This will test your TURN server for a working STUN connection.
Should worl flawlessly, otherwise your config is broken.

Next step:
uncomment the line with static-auth-secret
write below a new line:
user=username:password

Again use the website before, delete the old server entry and this time enter:

![turn](https://user-images.githubusercontent.com/856110/82742690-92e39b80-9d61-11ea-8394-f800f9f24e32.jpg)

This should also work.
If not, check that your server has the following entries in the config:

listening-ip=youripv4
listening-ip=youripv6
relay-ip=youripv4
relay-ip=youripv6

We had this several times with our clients that the servers were available by IPv6, but the TURN server was not listening...

This should also be a reference for future issues.

We have a similar setup script like bbb-install.sh for our turn servers, based on the install instructions from BigBlueButton setup page.

**Comment by kensington** [comment]
@lonesomewalker while I do have IPv6 available locally, the server has no IPv6 available.

I tested using that link and STUN reports okay. TURN only passed the test after temporarily disabling `use-auth-secret` - with it still in place, the logs were full of 'unauthorized' errors, much in the way they were when using BBB with Chrome (but not Firefox).

**Comment by matiasilva** [comment]
Any update to this?
