### ISSUE TITLE
Custom HTML5 client development echo test

### ISSUE THREAD

**Issue by ranevaibhav95** [bigbluebutton/bigbluebutton#9585]
I am on latest version of bigbluebutton (2.2.10). I wanted to do some changes in html5 client. After doing the changes and running it, the echo test never stops. 

**To Reproduce**
After following steps to customize the html5 client in https://docs.bigbluebutton.org/2.2/dev.html#developing-the-html5-client

Till "npm start"
Then start a meeting and click on "microphone"

**Expected behavior**
Echo test option should have been displayed with thumbs up and thumbs down popup

**Actual behavior**
Echo test doesnt stop

BigBlueButton Server 2.2.10

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version: 81.0.4044.138 (Official Build) (64-bit)

**Comment by basisbit** [comment]
This issue tracker here is not for support requests, but instead only for development of the BigBlueButton project itself.
To get support, please ask at https://groups.google.com/forum/#!forum/bigbluebutton-dev

**Comment by ranevaibhav95** [comment]
But in the first place i need to know that this is a bug or not?If its a bug then i am at the right place right?

**Comment by rmattes** [comment]
Just updated from the apt-repository and experience the same problem, the echo test works but there are no thumbs-{up|down} icons on the echo test dialog. The icon to close that dialog doesn't work either.

Here's the log of the upgrade that triggered the change
```
[UPGRADE] bbb-apps:amd64 1:2.2.0-42 -> 1:2.2.0-44
[UPGRADE] bbb-apps-akka:amd64 2.2.0-80 -> 2.2.0-86
[UPGRADE] bbb-apps-screenshare:amd64 1:2.2.0-42 -> 1:2.2.0-44
[UPGRADE] bbb-apps-video:amd64 1:2.2.0-39 -> 1:2.2.0-41
[UPGRADE] bbb-client:amd64 1:2.2.0-33 -> 1:2.2.0-40
[UPGRADE] bbb-config:amd64 1:2.2.0-173 -> 1:2.2.0-185
[UPGRADE] bbb-freeswitch-core:amd64 2:2.2.0-103 -> 2:2.2.0-112
[UPGRADE] bbb-fsesl-akka:amd64 2.2.0-62 -> 2.2.0-64
[UPGRADE] bbb-html5:amd64 1:2.2.0-882 -> 1:2.2.0-925
[UPGRADE] bbb-playback-presentation:amd64 1:2.2.0-28 -> 1:2.2.0-29
[UPGRADE] bbb-record-core:amd64 1:2.2.0-63 -> 1:2.2.0-65
[UPGRADE] bbb-web:amd64 1:2.2.0-123 -> 1:2.2.0-128
```

**Comment by basisbit** [comment]
please check the console log of the webbrowser developer Tools for any warnings or errors. (press F12 key to open it in Firefox or Chrome, then reload the page and make the problem appear again, now you should see some infor, warning and error messages in the console log).

Usually the mentioned problem is caused by one of the services on the server not having started successfully (run `bbb-conf --check` and `bbb-conf --status`) or because after the update the command `bbb-conf --setip your.domain.tld` was not run. Also make sure that all your BBB configuration modifications are also part of [the `apply-config.sh` script](https://docs.bigbluebutton.org/2.2/customize.html#automatically-apply-configuration-changes-on-restart) which automatically gets executed when you run `bbb-conf --setip your.domain.tld` after the update.
