### ISSUE TITLE
When require moderator approval before joining is set, no user can be promoted to moderator

### ISSUE THREAD

**Issue by trs80** [bigbluebutton/bigbluebutton#9600]
**Describe the bug**
If the waiting room is on, attendees can't be promoted to moderator

**To Reproduce**
1. Go to demo.bigbluebutton.org
2. Turn on 'Require moderator approval before joining'
3. Start the room, and admit an attendee
4. Click on user to bring up menu and click 'Promote to moderator'

**Expected behavior**
The user becomes a moderator

**Actual behavior**
Nothing happens

**BBB version (optional):**
BigBlueButton Server 2.2.11 (1944)
Also tested on demo.bigbluebutton.org

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser: Firefox
 - Version: 68.7 ESR

**Comment by lonesomewalker** [comment]
Can confirm this, we also had this issue with one of our customers today.
If you turn of the "Require moderator approval", a guest can be promoted to moderator role.

**Comment by ffdixon** [comment]
Good catch.

**Comment by pedrobmarin** [comment]
Duplicated https://github.com/bigbluebutton/bigbluebutton/issues/7460

**Comment by nicolopez77** [comment]
Pedro you proposed to hide the promotion to guests. In my opinion, the solution should be to make the guest promotion work. Am I wrong?

**Comment by pedrobmarin** [comment]
By design, `guests` cannot be promoted in bigbluebutton.
I agree with you that it shouldn't be like that but to make such change right now could impact other users that already adopt the guest feature as it is. I hope to see the change you asked (and myself asked https://github.com/bigbluebutton/bigbluebutton/issues/7460) in some future release.

**Comment by nicolopez77** [comment]
Pedro, when the room does not require approval, guest users can be promoted without any problem, that works fine. That's why I understand the right solution is to behave the same way. Are you sure that is "a feature" that without approval you can promote them, and with approval you can't? I would say no. In fact that is confusing! Just my humble opinion.

**Comment by pedrobmarin** [comment]
Can you explain a little more about what is a room that does not require approval? What are you considering to be a guest?
This is the server-side control on user's promotion:
https://github.com/bigbluebutton/bigbluebutton/blob/da9489c9dde1e1d0a3da942b95d95def66dd6105/akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/users/ChangeUserRoleCmdMsgHdlr.scala#L32-L43
Promotions are only enabled to non-guest users.

**Comment by nicolopez77** [comment]
@pedrobmarin Apologies if I didn't use the right terminology, I'm not so experienced with the project yet. The behavior I see (and others reported in the google group as wel) is when the room was created with the guestPolicy=ALWAYS_ACCEPT , then you can promote any user as moderator. But if you created the room with guestPolicy=ASK_MODERATOR , then the menu option is shown but the user is not promoted. In both cases, the users are VIEWERS. Not sure if the code you are showing is connected to this issue.

**Comment by pedrobmarin** [comment]
Nothing will change on that behalf. If you could promote someone before, you will still be able to do so.
There is a wild role entitled `guest` that is used in some particular cases. You can identify guest users by checking at the users' list, they will be labled as _Guest_. Those users can't be promoted. The thing we tried to manage on that commit was to simple not show the promote option for something moderators won't be able to execute whatsoever.

**Comment by nicolopez77** [comment]
I can understand that from a technical point of view, but not from a user's perspective. Is there a way we can request the feature to have the same behavior for any kind of user (guest or not)? I see at least 5 guys reporting this as a bug in the google group (https://groups.google.com/forum/#!topic/bigbluebutton-dev/W56HWasv5z8), I guess many more could be interested. Thanks!!! @ffdixon @pedrobmarin

**Comment by pedrobmarin** [comment]
This is the point where we go full circle as I agreed with you before that's the behaviour I would expect from the guest feature. Since the changes to make it work as we want lies under a design level of the product, it's more complicated to modify and guarantee nobody loses from it. I hope this is something we could add to bbb core in future releases but right now we can only make sure the UI is in sync on what an user is able to do or not.

**Comment by nicolopez77** [comment]
Hi Pedro, no full circle at all. I understood (but not agreed) what is the current behavior of the guest feature. 
I'm just asking if there is a process for the community to request changes or new features, because I see I'm not the only one interested. I would like to follow the right process and not to leave it in the comments of a closed ticket as now, if possible. Thanks again for your help!

**Comment by pedrobmarin** [comment]
I was the one who agreed with you and the person who took the time to answer all your questions. All I said was that I was one of the interested people on the change you proposed.
If you try to open a new issue you will probably see there is an option for `Feature request`. That's usually the place people can ask for new things.
Have a great evening. No problem at all!
