### ISSUE TITLE
User parameters (addUserSettings) are not used in Breakout Rooms.

### ISSUE THREAD

**Issue by rriscado** [bigbluebutton/bigbluebutton#9612]
User parameters (addUserSettings) are not used in Breakout Rooms.

All participants in the Breakout Rooms enter as MODERATOR and without user parameters applied.

We need to apply in all Breakout Rooms the same parameters as the main room!

Is it the same problem related in this issue?https://github.com/bigbluebutton/bigbluebutton/issues/9375
@tdjac0bs @jfsiebel

**Comment by jfsiebel** [comment]
Good morning @rriscado 

It's not related to #9375, the users are moderators by default in breakout rooms and custom settings are not forwarded into breakout rooms.

**Comment by rriscado** [comment]
> Good morning @rriscado
> 
> It's not related to #9375, the users are moderators by default in breakout rooms and custom settings are not forwarded into breakout rooms.

Good morning @jfsiebel 

Is it possible to apply these restrictions in Breakout Rooms by parameter?
Will this feature be implemented in the future?

**Comment by esaribeiro** [comment]
Hi!
I agree with @rriscado about the importance of applying the same main room restrictions in the breakout rooms.

I appreciate if this issue is implemented.

**Comment by rriscado** [comment]
Good morning @jfsiebel 

Thank you for this feature!!!


I found another problem with the user parameters.

When using the guest variable (true or false) in join call, the user parameters are ignored.
Fyi: This issue occurs when the user join in the main room.

Do I need to open another ticket to correct this new issue?

**Comment by jfsiebel** [comment]
Hi @rriscado,
I think it's better to open a new issue.

**Comment by rriscado** [comment]
> Hi @rriscado,
> I think it's better to open a new issue.

No problem!!

I opened the new issue https://github.com/bigbluebutton/bigbluebutton/issues/9737

**Comment by rriscado** [comment]
Hi @jfsiebel,

I've already tested your changes. 
It's working, but the role in the breakout room isn't the same to the main room.

This is a problem  when we use for example the "userdata-forceListenOnly = true". This parameter is ignored when the user is a Moderator.

This problem afects webinars, where the participants can't share your audio.

**Comment by antobinary** [comment]
Hi @rriscado ,
Just to clarify - you are setting all viewers to join the main room with forced listenOnly but also want to force listenOnly to everybody who enters breakouts?

I see several obstacles to this but it mostly boils down to the fact that you want to carry over the roles of main room participants into the breakouts.
This is conflicting with the way Breakout rooms were designed to be used and are used by the vast majority of BBB users. Have you looked into a way to "chain" several normal meetings rather than using Breakouts? Perhaps using set of parameters
- disable feedback dialog
- custom logoutUrl
-moderator ends the meeting, which leads to users being redirected to logoutUrl where you could use some logic to redirect some users into a new meetingA and the rest into new meetingB

**Comment by rriscado** [comment]
Hi @antobinary ,

You're right.
This scenario is very specific to my use case.
The implementation made by jfsiebel alread works for me.


But to answer your question:

Example: One webinar where the moderator open one breakout room to permit listeners to access audio and video resources that are not available in the main room.

This creates an overhead on the server because that is sized for rooms where only the moderator share your video and audio.


Maybe if the BBB has an API parameter to disable the breakout room, the administrator may choose between enable or disable.
