### ISSUE TITLE
Promote guest user to moderator 

### ISSUE THREAD

**Issue by nicolopez77** [bigbluebutton/bigbluebutton#9644]
When a room is opened with the policy guestPolicy=ASK_MODERATOR , the users are flagged as "guest". Currently guest users cannot be promoted to moderator.
This feature request is to allow the promotion of guests to moderator.

**Comment by fenice325** [comment]
This feature is really important for doing conferences with BBB. The room is owned by the host, the speaker/presenter is external and the viewers should be able to see the speaker's webcam but not the webcam of the other viewers. So, we need to get the webcams on lock or on "not seen by other viewers". The audience needs to be joined via approval (otherwise we experience BBB bombing). So also the speaker is first an approved guest, which we then need to promote to moderator in order to get the camera distribution right.

**Comment by lookas1** [comment]
I can see od demo.bigbluebutton.com whenever I send a link with ASK_MODERATOR guest policy set I can see invited users are not "guests" Where exactly this is being set? Should I pass some extra parameter to a room?

**Comment by bumblebee87kfu** [comment]
@nicolopez77 Do you have any news about that feature?

**Comment by papaschrumpf** [comment]
@nicolopez77 Any news on that? We are struggling with the same issue.

**Comment by nicolopez77** [comment]
@papaschrumpf some time ago we updated our BBB to v 2.2.26 and our Greenlight as well, and it started to work! Not sure if it was a change on BBB, or the way Greenlight calls BBB...I just know it works.

**Comment by papaschrumpf** [comment]
@nicolopez77 We are running BBB 2.2.31 but Greenlight 2.5. Guess I'll try updating Greenlight then.

**Comment by papaschrumpf** [comment]
Update: Greenlight Update worked perfectly fine. Thanks @nicolopez77

**Comment by nicolopez77** [comment]
> Update: Greenlight Update worked perfectly fine. Thanks @nicolopez77

Glad to hear that!

**Comment by pedrobmarin** [comment]
Long story short, a `guest` still cannot be promoted in `v2.2`.

What happened was that I asked Greenlight developers to avoid setting the `guest` param for users at any chance. This may sound weird because you all know you can promote your "guests" now. Turns out they are not `guest` guests and only non-moderator guests. I think this confusing and I'm sure everyone else thinks the same but trust me these are the rules of the game right now to everything work as you expected.

`v2.3`, on the other hand, has a new configuration option I included to avoid a chunk of this weirdeness (https://github.com/bigbluebutton/bigbluebutton/pull/11215). When we turn the switch on it the most you will notice is that the waiting guest panel will be missing some extra buttons and, indeed, you will be able to promote `guest` guests.
