### ISSUE TITLE
Error 1020

### ISSUE THREAD

**Issue by Magnou17** [bigbluebutton/bigbluebutton#9668]
Hi,
I am using bbb v2.2.12 on a platform behind a firewall and NAT. 
Sometime i get error 1020 when i launch my webcam share. How to set to suppress this error?
Rgds
Chris

**Comment by basisbit** [comment]
Sorry, but this issue tracker here is only for BigBlueButton software development related issues. Please use this mailing list / forum for your support request: https://groups.google.com/forum/#!forum/bigbluebutton-setup

Error 1020 usually is caused by either not running "bbb-conf --setip your.domain.tld" after an update or some firewall configuration issues.
