### ISSUE TITLE
100% server CPU usage

### ISSUE THREAD

**Issue by yourbestdev** [bigbluebutton/bigbluebutton#9701]
I have a serious problem that is happening on my server, it has been installed for a week and working normally, but a few days ago I started to increase the server CPU usage to 100%.
Does someone pass the same error to you?

Characteristics:
Dedicated Bare-Metal: Intel Core i7 920 2x HDD sata 2. 0 TB Enterprise grade level 48 GB RAM DDR3

**Comment by basisbit** [comment]
Use top / htop to figure out which process is using the CPUs how much.
Also, make sure you use uwf to set up the firewall so that your freeswitch server is not flooded with call redirects / requests.

This issue tracker here is not for support issues. Please instead ask your support questions at the mailing lists / forum at https://groups.google.com/forum/#!forum/bigbluebutton-setup
