### ISSUE TITLE
BigBlueButton Backup

### ISSUE THREAD

**Issue by Magnou17** [bigbluebutton/bigbluebutton#9702]
Hi,
My plateform (BigBlueButtob+Greenlight) is working fine. I am behind a NAT/Firewall and to avoid error 1007 and 1020, i had set all requisites (STUN/TURN, Dummy).
Now i want to backup it to be sure to recover it as is if my server fail.
How can i do?
Rgds
Chris

**Comment by kinimodmeyer** [comment]
the following folders i would backup:

`/root/greenlight/db
/var/bigbluebutton/published
/var/bigbluebutton/recording`

**Comment by basisbit** [comment]
alternatively, consider automatically creating backups of the whole server / VM, thus allowing for quick restore or analyzing the logfiles from a backup. https://lmgtfy.com/?q=backup+linux+server

**Comment by basisbit** [comment]
closing this issue because it is a support question, not something related to BigBlueButton software development or a feature request.
If you still have questions on how to backup your setup, please use the forum / mailing list at https://groups.google.com/forum/#!forum/bigbluebutton-setup .
If you got some spare time and want to suggest improvements of the documentation, pleas do so at https://github.com/bigbluebutton/bigbluebutton.github.io/ . Thank you.

**Comment by Magnou17** [comment]
Hi,
I undestand but when i use https://groups.google.com/forum/#!forum/bigbluebutton-setup, with my Google login, i can't answer or write anything!
It's fine for https://github.com/bigbluebutton/bigbluebutton.github.io/
Rgds
Chris
