### ISSUE TITLE
Play an Synchronized Audio/Video file/link in BigBlueButton

### ISSUE THREAD

**Issue by bigbluebutton-issue-import** [bigbluebutton/bigbluebutton#973]
Originally reported on Google Code with ID 218

```
Hello,

installed bbb this week. Great software and very useful. I have a 
question. Is it possible to play an AVI or an FLV-file in the 
presentation module? Are the other ways to view a flv-movie or AVI- 
movie form within bbb? 
The idea is that I'll first show the students a movie and later 
discuss it. It is for my target audience very important, they do not 
have to leave the bbb-envronment. I dont't want to redirect them to 
other sites and thus let them leave my presentation :) 

There are two options. Uploading a local file or playing a file from, for 
example, youtube. 

```

Reported by `gerard.op.school` on 2009-10-21 20:38:33

**Comment by natkuhn** [comment]
I am willing to work on this as a developer, but I would need a mentor for guidance and perhaps some collaboration.  Who should I talk to?

**Comment by ffdixon** [comment]
Hi Natkuhn, 

That's great.  There are a few things that you need to cover, see

  http://docs.bigbluebutton.org/support/faq.html#contributing-to-bigbluebutton

Post your intent to our developer mailing list at

  https://groups.google.com/forum/#!forum/bigbluebutton-dev

and give a background on yourself and your skill level.  (To calibrate expectations, if your just starting out as a developer, it would be good to demonstrate you've tried to do something already in BigBlueButton to make it easier for others to mentor you).

**Comment by mschipperheyn** [comment]
As a possible work around it might be interesting to be able to push a youtube (or other player types) video to all participants that would open in a video and start playing. That way you wouldn't waste bandwidth (framedrops etc) on distributing the video content. It could just open as a little popup and start playing.

**Comment by ffdixon** [comment]
Another user described using controlling YouTube videos, see

  https://groups.google.com/d/msg/bigbluebutton-dev/2OLdUbi2K_w/i9THyToFBwAJ

Looks like YouTube supports an iFrame embedded API

   https://developers.google.com/youtube/youtube_player_demo

Also found an example of embedded YouTube video in Flash using AS3

   https://www.youtube.com/watch?v=F9GTfBwLz2A

**Comment by mikhailnov** [comment]
Hello.
BBB makes a per-slide conversion of the presentation into swf. I uploaded (on BBB 0.9) a presentation and then changed on of the swfs to the swf with a similar name, but it was actually a video file with sound. The effect was quite interesting. 
When I changed the presentation to that slide which was a video, the video playback started, the sound was on, and the videoplayback looped, it started to play again and again. Then I changed the slide, the image changed but the sound continued to be playing and being looped (so the flash video actually did not stop).

so, what I think can be done is:
1) allow uploading swfs
2) for the beginning, it will be enough not to implement a playback control, but we can upload an swf with already built in player controls, playing autostart (so thateach webinar attendee did not have to turn the video on manually) and no loopback.

Is it possible to do right now? How to allow the permitted to upload file types and make so that the system did not try to convert them into PDFs? I think it will not be that difficult to build such a flash player, maybe even LibreOffice Draw can tdo it, or maybe we can make an ant (or sth like that) template to build the players. Of course, using proprietary software like Adobe's software for flash is the worst thing to do, because a license should be bought and it will not run properly under wine.

**Comment by mikhailnov** [comment]
I also saw a video without any clear explanations, but it seens to be controlling BBB HTML5 client streans via Gstreamer web interface, was it implemented? https://www.youtube.com/watch?v=2TjGAtrjD-w

**Comment by kepstin** [comment]
Uploading a 'swf' file containing a pre-packaged player is an interesting hack, but it's incompatible with our current development efforts towards a native html5 client and support for mobile applications. 

We probably won't consider something for inclusion at this point unless there's a plan on how it could be also supported in clients other than the flash web client.

**Comment by mikhailnov** [comment]
Well, maybe it is possible to disable convertion to pdf of specific filetypes (such as swf) so that the hack could be done via a web-interface? If you can tell me where it can be configured or maybe the place of code to be changed, I could have a look at this (but I do not currently have enough programming skillsm but I can try).

This requires changes to processing of uploaded files, they can also be used to implement the same feature in the HTML5 client. SWF won't work here, but the video above shows that some work was done to play other streams instead of web cams in the HTML5 client.

**Comment by Paradiesgestalter** [comment]
Here is the workaround for streaming videos in BBB that works nicely for me on MS Windows10 : I use SplitCam https://splitcamera.com/ as the video source in BBB sessions so I can switch sources in SplitCam from my webcam to a downloaded video that then gets streamed into BBB instead of the webcam. With picture-in-picture PiP function both can be seen at the same time.

**Comment by german2209** [comment]
Maybe you can take a look in https://meet.jit.si/ , they have the option to play a YouTube video synchronized for all the participants.
Regards,
German

**Comment by aogilvie** [comment]
Looks like the PDF conversion is the blocker?
If one could upload an HTML file with embedded video tag that would sure solve this?
It would make sense that having an HTML5 client should support HTML5 elements.

**Comment by ffdixon** [comment]
The solution with the widest application would be to allow the user to upload a video file (or audio file) and a have control over the playback.  We would do this directly (such as the upload of a presentation).

The ability to control playback in YouTube is also an option we'll be exploring.

**Comment by mikhailnov** [comment]
Just for information, you can try Dumacast https://gitlab.com/mikhailnov/dumacast. It allows to broadcast a video file to a virtual webcam on Linux. Unfortumately, I have not translated it from Russian into English yet.

**Comment by atar3d** [comment]
German you can checkout  https://www.unicko.com/ , they also have nice option to play a YouTube video for all the participants.

**Comment by ffdixon** [comment]
If others can do it -- we should be able to do it as well.  It's been a while since we took a look at YouTube's interface.  We'll take a closer look to see how difficult it would be to add this to the HTML5 client.

**Comment by atar3d** [comment]
from what you guys achieved so far i m sure you will make it better and simpler.
Not sure it's related but i found this project that use  use WebRTC DataChannels API to synchronize YouTube playback
https://github.com/GleasonK/WebRTC-YouTubeTogether

**Comment by ffdixon** [comment]
Thanks for the suggestions -- much appreciated.

**Comment by yvikt** [comment]
Hi.
I had experience whith browsersync. I just made simple page with video player, then serve it with browsersync. Then put the required video file in site folder. And of course don't forget to open ports. In this case, any user can start playing the file. Browsersync will send the event to all connected browsers)))

**Comment by atar3d** [comment]
Hi.
Using youtube saves the need to load files and resources on the server.
Most similar systems use [IFrame Player API](https://developers.google.com/youtube/iframe_api_reference?csw=1)
and the 'onStateChange' event

**Comment by ffdixon** [comment]
We can now share a YouTube video within the HTML5 client:  https://www.youtube.com/watch?v=7A_TOm0Qzvk

You can try this at https://test.bigbluebutton.org/

**Comment by antobinary** [comment]
Implemented (see above)

**Comment by hadifarnoud** [comment]
this is not useful because video is not played to everyone. The usecase would be a promotional content at beginning of the session for example, or the educational content students must see.

**Comment by aogilvie** [comment]
I've only tested with YouTube, but this does show to all participants. You can also pause video for all participants

**Comment by hadifarnoud** [comment]
@aogilvie if the video plays for all and pause for all, that's exactly what I needed

**Comment by vlasov01** [comment]
> 
> 
> I've only tested with YouTube, but this does show to all participants. You can also pause video for all participants

I think it was synchronizing between moderator and students before (I think it was in 2.2 beta, Share YouTube video - https://youtu.be/Q2tG2SS4gXA?t=296 ), but it is not supported in the current release (share external video). I've tested it in Firefox with BBB Client build: 908 (on my BBB server - xenial-220).
Is it possible to get information which version of BBB is supporting this synchronized audio/video feature?

**Comment by markus2330** [comment]
Is it possible to play an audio file which is not external (Copyright issues)? Embedding audio in the presentations does not seem to work.

**Comment by aogilvie** [comment]
@hadifarnoud @vlasov01 
I cannot say for sure, but definitely it was 2.2RC6 or a previous 2.2 version.
