### ISSUE TITLE
Transcribe text passages

### ISSUE THREAD

**Issue by mrkeksi** [bigbluebutton/bigbluebutton#9750]
I just want to start a little discussion about the wording used in two BigBlueButton phrases. I had already started a Theard in the Google Groups, but little attention was paid there. https://groups.google.com/forum/#!topic/bigbluebutton-users/Dt7bcfjQ-Pw

First this is about the viewer rights that can be set under the "Lock viewers" item. In some scenarios these settings are already preset, so the expression "restrict someone" does not fit anymore. Therefore I would be for the text passage the viewer rights to set and not to lock.

Lock viewers ->  Set viewer rights
https://groups.google.com/group/bigbluebutton-users/attach/1c2bb44395a7f/Auto%20Generated%20Inline%20Image%201?part=0.1&view=1&authuser=0

My next request is "logout". Which is true if you use BBB with a simple API. But if the frontend Greenlight or Moodle etc. is used, you just leave the "room". And to make this consistent with "End meeting" I would suggest "leave meeting" here. 

https://groups.google.com/group/bigbluebutton-users/attach/1c2bb44395a7f/Auto%20Generated%20Inline%20Image%202?part=0.2&view=1&authuser=0

What do you say? Especially with the first one many users are confused because sometimes they want to unlock someone and not lock them.

**Comment by antobinary** [comment]
Hi @mrkeksi 
Thanks for your suggestions. I read your original post but restrained myself from commenting. The matter of rephrasing and renaming items goes a bit further. Some people would agree with the renaming, some won't. Luckily everyone is able to override their own deployment (en.json, de.json, etc). But in order to have fuller picture, let's expand on other use of these terms:
1) if "locking" became "restricting rights", what would be good name for 
"Locked" label 
![Screenshot from 2020-06-03 09-02-15](https://user-images.githubusercontent.com/6312397/83639673-03b46000-a579-11ea-8894-7e95ca9a7218.png)
And "Unlock" menu
![Screenshot from 2020-06-03 09-02-35](https://user-images.githubusercontent.com/6312397/83639672-03b46000-a579-11ea-9875-6571c998df75.png)

2) "Logout" becoming "Leave meeting" - this one I find more isolated and simpler to change.

In all cases, I would recommend renaming considerations to be postponed to BigBlueButton 2.3 since we are very far ahead into version 2.2 (2.2.16 preceded by numerous beta's) and updates to user documentation is likely untimely.

**Comment by mrkeksi** [comment]
If you want to stick to a consistent picture for one language. Then we can also make it a "lock setting". But you just don't know who to lock out anymore. 
So how about a dynamic content? Like among the viewers. So that the text stays that way when nothing is set and changes to "Unlock viewer" when a setting is set.

**Comment by matiasilva** [comment]
Would like to add my thoughts here. I think the first suggestion makes sense in some respects, but the current model with "locking users" works well enough. I think the second suggestion is definitely worth pursuing and has resulted in numerous confusions between users of my setup. In any case, the solution to any of these problems and indeed further GH issues would be to localize all the strings.

**Comment by hex-m** [comment]
I agree with the second suggestion (don't have an opinion about the first one). As having multiple "feature requests" in one issue is confusing, I singled out the second suggestion to #9868 

I would suggest to do the same with the first topic or change the topic to only discuss the first point here.
