### ISSUE TITLE
See if a moderator banned a user from a session

### ISSUE THREAD

**Issue by lipsmega** [bigbluebutton/bigbluebutton#9775]
Hi! As a suggest, I cant see if a moderator banned a user from a session. I think it would be great!

**Comment by antobinary** [comment]
Hi @lipsmega 
From what point of view do you want to be able to see this info? From the user's perspective i.e. You have been banned, from the moderator's or from the server admin - i.e. this log says the user was banned, or something else...

**Comment by vlasov01** [comment]
I wish moderator can see banned users and can evaluate if someone was banned by mistake.

**Comment by lipsmega** [comment]
Hi! Thats because in a huge school I worked with, sometimes a user was banned from a session and the parents (or school admin) would like to know why or when.

**Comment by InfoFractal** [comment]
This feature would be very useful, accidental bans do happen.
Meanwhile, were is the ban list stored? To unban users manually.

**Comment by cschmitt-rma** [comment]
> This feature would be very useful, accidental bans do happen.

I can second this, we banned a user accidentally and had no way to get him back into the conference. 

> Meanwhile, where is the ban list stored? To unban users manually.
I have only found the corresponding syslog entries by searching for "UserEjectedFromMeetingEvtMsg" which also listed by whom the ban was executed.

A list per conference accessible to moderators with entries in the form <banned user name> <when the ban happened> <which moderator banned him/her> (so that moderators can double-check amongst each other via private chat if the ban was legitimate or not) and <unban-button> to unban would be very helpful!

**Comment by cschmitt-rma** [comment]
> A list per conference accessible to moderators with entries in the form "user name", "when the ban happened" "which moderator banned him/her" (so that moderators can double-check amongst each other via private chat if the ban was legitimate or not) and an unban-button would be very helpful!

Or alternatively, as this would not add clutter to the UI: Keep banned users in the participant list with a "banned" remark (visible only for moderators and maybe auto-sort them to the bottom of the list), together with a remark about who banned them (and when) and display the "unban" option in the contextual menu when clicking on such a banned user.
