### ISSUE TITLE
Share website

### ISSUE THREAD

**Issue by sh-csg** [bigbluebutton/bigbluebutton#9785]
In conferences many people use external services for moderation / collaboration (e.g. mentimeter, padlet, ...). The participants have to open a URL in a separate tab / window.

I'd suggest a "Share website" mode (like "Share video") which shows the requested URL as an iframe in the main window (instead of presentation). 

Additional feature: Use different URL for moderators / participants (for embedded use of moderation features of these services)

**Comment by Josecarpeniet** [comment]
Hi,
I also want that feature. Cobrowse is a real game-changer!
Imagine sharing your browser directly and both users, presenters, and attendees can collaborate in real projects and doing it in real-time.

When delivering/presenting content in BBB, right now we are just limited to a plain presentation. We could make the system more dynamic.

With co-browse, we would be opening a door to infinite possibilities because you could leverage any website introducing it in your workflow!
Think about using an online application with exercises to follow and the tutor helping the student... or maybe a Codepen where you guide your student while collaborating in a real project, with browser sharing the sky is the limit. This is the closest to be in the same room sharing interactive tools/apps on a computer. It is almost real-time mentoring.

I'm using that feature included on Vectera and it blew my mind from the first moment. It provides the best experience to the attendees. (here you can see an example on their docs https://help.vectera.com/en/articles/3347286-how-do-you-set-up-co-browsing) and we

Cheers!

**Comment by hiroshisuga** [comment]
well, I teach bioinformatics in University, and usually use screen share for that purpose. This works pretty well, although the delay stresses me a bit.
When I teach how to operate an app or website, I would like to show "how I would do", and students will learn from the shared screen and do it in separate window, watching the shared screen. If I understand correctly, this feature enables the students to operate the website by themselves, and they cannot see the teacher's operation in the main window. I am afraid that the teacher will lose the control over the students, which may get confused anyhow. 
Sorry if I misunderstand something.

**Comment by Josecarpeniet** [comment]
@hiroshisuga this feature is for specifically allowing the student to use the mouse and keyboard when required (BigBlueButton allows you to turn on/off when attendees can control or not as "guest presenters").
It's not replacing screen sharing, it's providing an extra powerful feature for making it better.

**Comment by ptandler** [comment]
I really would appreciate to have a "show web page as iframe" feature as well!

It would be cool if you could pass things like the participant's name or user role and room name etc. as URL parameters to be able to show different content depending on the context.

Suggestion:

- No URL parameter: https://pet.teambits.events/app/join.jsp?m=fa80bddb-69c9-4e96-84de-dd04354a1f71
- `%u` to pass user name: https://pet.teambits.events/app/join.jsp?m=fa80bddb-69c9-4e96-84de-dd04354a1f71&login-name=%u
- `%r`to pass role
- `%t` to pass room title / topic

**Comment by ptandler** [comment]
Please leave this open

**Comment by nidico** [comment]
@stale: Please leave this open.

**Comment by antobinary** [comment]
Merging into #15482 where someone has described a possible (temp) approach
