### ISSUE TITLE
Webcams Should Be Able To Float Above Presentation Area 

### ISSUE THREAD

**Issue by jingwenw** [bigbluebutton/bigbluebutton#9817]
**Is your feature request related to a problem? Please describe.**
Currently, when the presentation area maximum-ed, the webcams will be no-show.

**Describe the solution you'd like**
To make the webcams floating above the presentation area, even the presentation area is maximum-ed, that way the webcams will always show up.

**Describe alternatives you've considered**
No alternatives found.

**Additional context**
The video conference system is about video and presentation - those are 2 most important parts. Once users select to share webcams, they should be always showing somewhere, even they have to float above the presentation area.

**Comment by frank-miller9** [comment]
Also for screen sharing it would be helpful.
Sugar would be, when one can disable every element but the camera images, so we can put the videos somewhere on the side and work e.g. in excel, while speaking with the participants and share camera.

**Comment by basisbit** [comment]
> The video conference system is about video and presentation - those are 2 most important parts.

These are only the most important parts for your specific use case.

Anyways, this is a website, so to get full screen view of the presentation and the webcam, just press the F11 key (default for your webbrowser) and then just hide the user list + chat.

When the user presses on the fullscreen button of the presentation area, then only the presentation area should be visible on full-screen, not all the other stuff, too. When the user presses on the fullscreen button of a certain webcam, then only that webcam video should be shown. If you actually want a fullscreen of the whole page button, please create a feature request for that.

**Comment by basisbit** [comment]
Regarding the topic of this issue `Webcams Should Be Able To Float Above Presentation Area`, this is already supported. When in fullscreen (F11 key), just drag + drop the webcam video to where you want it to be. this can also be on top of the presentation area.

**Comment by basisbit** [comment]
Actually, instead of pressing F11 key, you can also press on the ... in the top right corner (or top left corner in rtl layout) and then enable fullscreen view.

**Comment by Piotr-Fr** [comment]
> Also for screen sharing it would be helpful. Sugar would be, when one can disable every element but the camera images, so we can put the videos somewhere on the side and work e.g. in excel, while speaking with the participants and share camera.

Absolutely, yes. This is one of the reasons we are coming back to MS Teams, at least for awhile.

**Comment by Piotr-Fr** [comment]
> Actually, instead of pressing F11 key, you can also press on the ... in the top right corner (or top left corner in rtl layout) and then enable fullscreen view.

Thank you for your instructions, however, this is not a user friendly solution.

We (boutique language school) need:
1. two separate windows to work: one with video (be that BBB or anything else), and the other with the edu platform.
2. A teacher needs to see a student on the camera while a student shares screen and works on the platform, and vice versa, when students do the work while screen sharing they should be able to see a teacher in the corner. Just for better psychological interaction between the two.
3. All of them need to easily switch between two windows, to start chat, whiteboard and so on.
And the last one is pretty much difficult when in fullscreen mode. I use keys, but no chance to teach our clients "how to", plus another complication for them, apart of already non-intuitive BBB interface. This is business clientele, used to use intuitive easy-to-work stuff. They already complain about complexity of BBB, after we moved from MS Teams.

So that would be great if a selected floating webcam would be available anyway, no matter of the screen mode (full or not). Like pin it to top or alike.

**Comment by Piotr-Fr** [comment]
> Actually, instead of pressing F11 key, you can also press on the ... in the top right corner (or top left corner in rtl layout) and then enable fullscreen view.

We have checked, MS Windows, Edge, Chrome, Firefox: neither works, unfortunately, even in this very limited way (floating over the presentation in full screen mode).
