### ISSUE TITLE
Poll feature does not work if no presentation exists - breakout room

### ISSUE THREAD

**Issue by apinos76** [bigbluebutton/bigbluebutton#9861]
**Describe the bug**
If a user deletes the default slides from the breakout room, the poll function no longer works:
![image](https://user-images.githubusercontent.com/30633300/84901416-71808180-b079-11ea-957d-31b656ceafb4.png)

**To Reproduce**
1. Go to breakout room
2. Click on upload presentation
3. Remove(delete) all slides
4. Click confirm
5. Click, Start a Poll
6. See error

**Expected behavior**
Allow polling

**Actual behavior**
Screen showing that no presentation is seleted

**Screenshots**
![image](https://user-images.githubusercontent.com/30633300/84901655-c91eed00-b079-11ea-9808-8235404c7a3a.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 83

**Comment by KDSBrowne** [comment]
I'm not sure this is a bug, the current implementation was designed to display this message as a type of safe guard (it happens in the main meeting as well). When we publish the poll results to the presentation area, crashes occur if there is no active presentation.

@antobinary , maybe polling should still be allowed and display this
message closer to the publish button (if no active presentation)?

**Comment by ffdixon** [comment]
It's almost like when breakout rooms are started, if we named the uploaded presentation (which is the current slide in the main room) `default.pdf`, would the logic to protect the current slide from being deleted in the breakout room kick in?

**Comment by antobinary** [comment]
I think when we implemented this safeguard the only display for published poll was on top of the current slide. And no current presentation -> no current slide -> lost results of the poll...

In 2.3 we have poll results in the chat area. I am tempted to have us address this issue on 2.3+ by allowing polling to be initiated if there is at least one of { public chat, current slide } so we have somewhere to output the results. We should proceed with caution here because in different customizations we disable slides, or chat, etc and we have hit numerous edge cases because of this and the dynamic nature of presentation availability (sometimes takes longer to first become available)
