### ISSUE TITLE
Could we have a counter for each session?

### ISSUE THREAD

**Issue by cod3r0k** [bigbluebutton/bigbluebutton#9879]
Dear All, I want to embed a counter beside the menu (exit menu, for example) to know how much time is going on from the starting time of each session. Could you help me to embed this feature?

**Comment by matiasilva** [comment]
Hi @cod3r0k. You will notice this feature exists if you set a time limitation for the room. For future feature requests, understand that the BigBlueButton community is formed of the core developers and volunteers like myself. Unfortunately, time is limited and we can't just make features when we wish. These things take time. I've already shown you how to set up a development environment for the HTML5 client and you can play around and create there. If you want to discuss development ideas, post to https://groups.google.com/forum/#!forum/bigbluebutton-dev. Otherwise, if you really need a feature you can contact the companies that provide commercial support for BBB: https://bigbluebutton.org/commercial-support/
