### ISSUE TITLE
Show 0-to-unmute tip when already connected

### ISSUE THREAD

**Issue by mrks** [bigbluebutton/bigbluebutton#9884]
#7765 added "Press the '0' key on your phone to mute/unmute yourself" to the screen that you see when you are about to join using your phone. However, if you already joined, the message shown in the chat (version 937) simply says:

```
To join this meeting by phone, dial:
***
Then enter 000000 as the conference PIN number.
```

Especially for auto-mute rooms, this leads to people not knowing how to join the room and unmute themselves.

**Comment by jens-br** [comment]
Hi all,
our team had the same problem recently: The phone connection to a colleague was established based on the connection info in the chat (which did not contain that info), but as that person was not aware of the `0` as the mute key, we had some problems.

My question is: Are there any fundamental problems which would speak against including this addition? If not, could you reopen and implement this issue? It seems to be that it would only be a small addition to the `defaultWelcomeMessage` or the `defaultwelcomemessageFooter` strings. I am aware that this setting can also be adjusted by admins - but since the mute/unmute problem is not so obvious when setting up a BBB instance, I think it would help to have it already contained in the default configuration, so they would not oversee it so easily.

Many thanks in advance - and many thanks also for your work on BBB in general! :+1: :slightly_smiling_face:
