### ISSUE TITLE
Update NGNINX to newer version

### ISSUE THREAD

**Issue by Schmidie64** [bigbluebutton/bigbluebutton#9901]
**Is your feature request related to a problem? Please describe.**
Basically, it is a matter of standard that BBB uses the last nginx version that is available on xenial. Unfortunately, this is not the latest version (xenial: 1.10, current: 1.16). So if there are no errors in BBB, you should add the nginx package source during installation so that the latest NGINX version is always used.

**Describe the solution you'd like**
Add the NGINX developer package source during installation.

What do you think about that? Did anyone of you updated there NGINX version by your own? I don't know if there are software problems which would block this changes.

**Comment by basisbit** [comment]
This is definitely not something desirable. Using the packages that are provided by the package maintainers is the best practice for Debian based distributions. Package maintainers (usually) do a good job at making sure that compatibility is tested properly and also add critical security patched when necessary. Adding nginx from source would risk running old versions (because the typical `apt update` + `apt upgrade` would not update it) and can cause compatibility issues.
