### ISSUE TITLE
Disable Permanent Recording - Enable Recording on request

### ISSUE THREAD

**Issue by Pankevalley** [bigbluebutton/bigbluebutton#9920]
We intent to use BBB within the whole Lufthansa Group as the standard VC application. To get the appoval by the Management and all involved work councils/staff representations we have to fullfill European privacy requirements. One important item of the regulation is, that storage of personal data (=audio/video) must be earmarked. Means, it has to be dedicated to a clearly defined purpose. The standard behavior of BBB (all sessions are recorded by the system) is not in accordance with the European General Data Protection Regulation (resp. German DSGVO), because that purpose is not given in general.

We are aware, that the automatic video recording can be switched OFF generally. But that means, NO recording is possible, even not manually. The point is, that we do need session recording for some courses/ events for authority purpose (Federal Aviation Office/Luftfahrtbundesamt/BMVI) to get the courses licensed and the student grading valid. Also, often the session recording would be very usefull for didactical reasons as well. 

**For the mentioned reasons we would appreciate, if the recording feature is basically deactivated and can solely activated for a certain classroom, by pressing the record button by an BBB Moderator.**

**Comment by matiasilva** [comment]
@basisbit this seems like your expertise :D. In all seriousness, if you are using the Greenlight frontend then you can have a look at this PR (https://github.com/bigbluebutton/greenlight/pull/1296) and see if it solves your problem. I currently have it installed on my setup and so do many others. This wouldn't be something to be implemented on the BBB side, but rather in the frontend you are using. Whichever frontend you have, you can simply set the "record=" parameter when creating the room.

**Comment by basisbit** [comment]
As a shareholder of Lufthansa until recently (still think it is a good company, just a very unfortunate time for airplane based passenger transport), I'll gladly help out here.
@Pankevalley for operating BigBlueButton in accordance to GDPR/DSGVO, you'll want to take a look at the BBB privacy documentation: https://docs.bigbluebutton.org/admin/privacy.html
These contain bunch of configuration settings and suggested changes to adjust logging, storing of private data and so on. This documentation also contains best practices / suggestions for how to disable the storing of that data, which in most cases will be the easiest solution. For other cases, you'll at least have to adjust your data protection agreement.

One of the next major version of Greenlight (a web-frontend where you create and manage rooms + their settings) will probably support enabling or disabling recording in the room settings. That should be exactly what you want: (bigbluebutton/greenlight#1296)
In your use case, I'd guess that Lufthansa Systems operates its own learning platform, and then it would be even easier - because the learning tool integration can just specify the `record` parameter (for enabling or disabling the session recording) which @matiasilva already mentioned.

I'll close this issue for now, because there is nothing left to do regarding the request in the BigBlueButton server software itself. You can still continue using this issue for discussion, it will just not show up as an "open" issue for other developers.

**Comment by Pankevalley** [comment]
Thank you very much for the fast and detailed reply. We already read the "privacy" text you linked above. So we are aware, that we can set the recording systemwide to OFF. This would indeed fullfill all requirements of DSGVO and staff representation panels as well. The point is, that for authority reason, we have to record some sessions. As you mentioned, we use BBB exclusively via our LMS (ILIAS). That brings me to the one question:
Is it feasable to have the overall recording generally deactivated and set the moderator into the position to activate it solely for "his" session just by pressing a record button? This behavior is obviously not intended by the BBB software. Please do not misunderstand me, I am aware, that BBB is an OpenSource project and it's up to the developers to implement a feature or not. I just want to know if this feature can be implemented in the near future, or for some reason not. This information would bring us a step forward in the negotiations within our companys panels.

**Comment by basisbit** [comment]
> This behavior is obviously not intended by the BBB software

As mentioned before, BigBlueButton actually already supports what you want. Please contact your ILIAS support, so they can add a configuration switch for your "classrooms". You are not using "Greenlight", thus BigBlueButton already does all what you need.
