### ISSUE TITLE
Poll options not visible on full screen

### ISSUE THREAD

**Issue by shahidagha** [bigbluebutton/bigbluebutton#9942]
when presenter starts a poll and if the users are on full screen mode then those users are only able to see the poll options by exiting full screen.Poll options are visible if the user is NOT using Fullscreen

**Comment by basisbit** [comment]
Can not confirm the reported problem. When joining a session either as moderator or as non-moderator, the user gets to see the poll options in fullscreen (press the `...` in the top right corner and select fullscreen). The poll configuration options are also visible.

![image](https://user-images.githubusercontent.com/10870269/86300494-47939700-bc03-11ea-802a-70b5923d22d9.png)

Next time you report a bug or feature request, please make use of the issue template. Providing a screenshot, used BigBlueButton version and all the other stuff that is asked for in the issue template probably would have helped.
For support on how to fix your problem, please use the [forum / mailing list](https://groups.google.com/forum/#!forum/bigbluebutton-users). This issue tracker here is only for BBB development related issues.

**Comment by InputMoe** [comment]
I can confirm the problem on Samsung Tab S5e with Chrome 87.0.4280.141 on Android 10 Build QP1A.190711.020

Happens if ca. more than 10 Users with cam mode on are in the conference. You can only see the heading "poll options" in the right lower corner but the buttons to vote are cut off and seem to be "below" the visible screen.

Please help!
