### ISSUE TITLE
Leave the audio to connect the microphone easier to users

### ISSUE THREAD

**Issue by amguirado73** [bigbluebutton/bigbluebutton#9992]
Hello,

### Is your feature request related to a problem?
My users are always frustrated when they have to activate microphone after beeing connected as Listen-Only.
The user must press "leave" the audio to reconnect with the microphone.

### Describe the solution you'd like
What our users are demanding is that even if the users are Listen-only, a microphone icon appears in mute.
When you click on it, transparently to the user, exit the audio and force it to enter with a microphone, 
going to the echo test. 

### Describe alternatives you've considered
Nothing

### **Additional context**
It is not very intuitive for users to leave the audio to connect the microphone.

Thanks
Regards.

**Comment by matiasilva** [comment]
Hi, thanks for the suggestion. I don't quite agree with this but I'd be interested in hearing what others have to say.

**Comment by basisbit** [comment]
@amguirado73 If you want your feature requests to eventually be implemented, please edit your description and make use of the issue template (the one you removed on purpose when creating this issue here).

**Comment by iSamof** [comment]
@amguirado73 makes a lot of sense when he says:

"It is not very intuitive for users to leave the audio to connect the microphone."

Currently, the moderators ask us how do users join with a mic ... and we have to explain the above to them. Then at every single session, the moderators have to tell the attendees "yes, yes, the icon does say leave audio ... ignore the message and click it anyway and then rejoin ..."

The OP's suggestion is a good solution.

**Comment by amguirado73** [comment]
> @amguirado73 If you want your feature requests to eventually be implemented, please edit your description and make use of the issue template (the one you removed on purpose when creating this issue here). The purpose of the issue template is to reduce the amount of time needed to understand your requirements and get you to suggest possible solutions.

Hello,

a have edited my description to do it easier as you ask me.

Thank you very much.
Regards

**Comment by Jossef-767** [comment]
I totally agree with @amguirado73 .
The problem is aggravated when a teacher locks microphones and a student leaves and enters again, accidentally, or because of a poor intranet connection. Then the student returns to "listening only" mode.
In this situation, the student does not understand what to do and why he cannot speak even after the teacher has unlocked the microphone.

This can be improved if the teacher had   another way to prevent unmute,   rather than using lock settings. For example, if the menu command "_Mute all users except presenter_" would not allow unmute.

see also isseu #10011 it is related  in the sense that the option to disconnect from "voice server" should be prevented.
so that there will be only 2 options: 
1) **connected** with mic 
2) **connected** without mic

**Comment by matiasilva** [comment]
@Jossef-767 isn't your issue just a duplicate of this one?

**Comment by Jossef-767** [comment]
@matiasilva isseu #10011 is about preventing  users from beeing disconnected from voice when entering to the room. 
this isseu is about switcing from Listen-Only to Mic without disconneccting.
In both we want to avoid, or skip, the state of disconnection from voice server

**Comment by basisbit** [comment]
*bump*

**Comment by ffdixon** [comment]
We are working on improvements to the audio that should reduce the reconnect times to make this much faster.  Look for these updates in the upcoming BigBlueButton 2.5 (we're working now on finishing 2.4).

**Comment by basisbit** [comment]
*bump*
